- src/cli/commands/create.js
**Summary**
Yarn create fails on Windows, see #3530 
The issue is caused by Yarn trying to run a javascript file as an executable (the !# doesn't work in Windows command)
This PR uses the existing `linkBin` function to create any appropriate shim depending on the system.
**Test plan**
No existing test. Manually tested on Windows 10 and one linux. More tests by other people would be appreciated.
Also any idea to automate a test here is welcomed.
> Fix `yarn create` command on Windows

- src/cli/commands/list.js
- src/package-request.js
**Summary**
Fixes #3859 and #3841.
These both seemed to be related to the virtual manifest that's included when workspaces are enabled, so I took a stab at fixing both places.
**Test plan**
Existing tests should ensure this doesn't break things for people not trying out the experimental workspaces feature.
> Fix list, outdated commands when workspaces enabled

- src/resolvers/exotics/file-resolver.js
**Summary**
`path.isAbsolute()` will always return `false` when the path is prefixed with `file:`
I came across the issue when adding local packages using absolute paths using the `file:` protocol. 
`file:` dependencies of a `file:` dependency will erroneously have their paths modified so yarn tries to locate them relative to the parent instead of using their absolute path.
**Test plan**
Take, for example, 3 packages.
**package-1**
```
{
"name": "package-1",
"description": "Test 1",
"scripts": {
"test": "test"
},
"author": "Test",
"license": "ISC",
"dependencies": {}
}
```
**package-2**
```
{
"name": "package-2",
"description": "Test 1",
"scripts": {
"test": "test"
},
"author": "Test",
"license": "ISC", …
```
> Strip 'file:' from the path before checking with path.isAbsolute()

- __tests__/util/misc.js
- src/cli/commands/publish.js
- src/util/misc.js
**Summary**
```publish``` still uses the old ```has2xxResponse``` method of checking the registry request. This was causing publish to fail.
**Test plan**
```
johnf@kermit:~/dev/npm-test$ ~/dev/small_patches/yarn/bin/yarn publish  --new-version 1.0.5 
yarn publish v0.27.0
[1/4] Bumping version...
info Current version: 1.0.5
[2/4] Logging in...
info npm username: johnf
info npm email: johnf@inodes.org
question npm password: 
success Logged in.
[3/4] Publishing...
success Published.
[4/4] Revoking token...
success Revoked login token.
Done in 18.24s.
```
Was previously returning
```
ohnf@kermit:~/dev/npm-test$ ~/dev/small_patches/yarn/bin/yarn publish --new-version 1.0.3
yarn publish v0.27.0
[1/4] Bumping version...
info Current version: 1.0.2
info New version: 1.0.3
[2/4] Logging in... …
```
> Fix HTTP status check for publish

- package.json
- yarn.lock
**Summary**
Remove `babel-plugin-transform-es2015-typeof-symbol` from package.json because it is not used.
**Test plan**
Everything is working like before
cc @Daniel15 @BYK
> Remove babel-plugin-transform-es2015-typeof-symbol

- package.json
- yarn.lock
**Summary**
This is an experiment: it seems that if we have jest, we don't need to declare babel-jest as our devDependency.
**Test plan**
The same tests.
> Remove babel-jest from package.json

- package.json
- yarn.lock
**Summary**
I reviewed almost all the dependencies of yarn, I upgraded this one, it doesn't seem have breaking changes IMHO
**Test plan**
The same tests
> Upgrade node-emoji to 1.6.1

- __tests__/commands/install/bin-links.js
- __tests__/fixtures/install/install-bin-links-eslint/package.json
- __tests__/fixtures/install/install-bin-links-eslint/yarn.lock
- __tests__/package-hoister.js
- src/package-hoister.js
- src/package-linker.js
**Summary**
This is a fix for https://github.com/yarnpkg/yarn/issues/3801
It seems like there's some history behind this issue, namely
**https://github.com/yarnpkg/yarn/pull/3310**, which 1) looked through all transient dependencies, 2) linked them to node_modules/.bin, then 3) overrode them with any top level dependencies
**https://github.com/yarnpkg/yarn/pull/3545**, removed the last part from above, which I assume was due to it incorrectly detecting what is actually at top level.
So now, the flat tree from `PackageHoister` gives us a list of all the bin paths that are hoisted to top level, but will include same names if their version ranges don't match, since hoisted has a different meaning from being added as an actual top level dependency. The latest implementation before this PR …
> Prioritize bin links at the root level

- package.json
- yarn.lock
**Summary**
Remove `babel-eslint` because we don't use it.
**Test plan**
The same tests
> Remove babel-eslint

- __tests__/commands/cache.js
- __tests__/commands/licenses.js
- src/cli/commands/cache.js
- src/cli/commands/licenses.js
- src/cli/commands/owner.js
- src/cli/commands/tag.js
**Summary**
This pull request deprecates every `yarn <command> ls` in favor of `yarn <command> list`
**Test plan**
I check every command and every test that took these commands
If you like it, do you think we should do the same for `yarn <command> rm`? And delete everything deprecated when we roll out the version 1.0?
> Breaking: Deprecate yarn <command> ls in favor of yarn <command> list

- __tests__/util/git.js
- src/util/git.js
**Summary**
If there are any ENV variables specified for the parent process - use them.
The main reason for this is that our CI uses `GIT_SSH_COMMAND` env to specify ssh keys to use for cloning and not via ssh-agent.
For example for github the user is always `git@` and it is obviously possible to make fake users in ssh config, etc...
But there should be an option to customize `GIT_SSH_COMMAND` directly.
**Test plan**
Before:
```
$ GIT_SSH_COMMAND="ssh -i ~/git.pem -F /dev/null" yarn install
yarn install v0.27.5
error Command failed.
Exit code: 128
Command: git
Arguments: clone git@github.com:monder/test.git /home/monder/.cache/yarn/v1/.tmp/f13ca8a124faac37abd837f21d8375bf
Directory: /tmp/test
Output:
Cloning into …
```
> Prioritize git environment variables from parent process

- __tests__/index.js
- src/cli/index.js
**Summary**
Request from issue https://github.com/yarnpkg/yarn/issues/3818
Shows the version of yarn only when `-v` is the first argument passed to the cli. Also added -v as a shortcut for verbose flag on install and other commands.
**Test plan**
*BEFORE*
*AFTER*
> #3818 Add -v command to show version when specified without other commands

- src/resolvers/exotics/file-resolver.js
**Summary**
Kind of a follow up to #3856. Since `file:` prefix and its length is used in multiple places, this patch moves that into a constant to make the code more maintainable.
**Test plan**
Existing tests should pass.
> Chore: use a constant in file resolver for `file:` prefix

- __tests__/normalize-manifest.js
- src/util/normalize-manifest/index.js
**Summary**
From #3821
When `global` command is used, skip the validation check for manifest, such as missing license or name field listed here https://github.com/yarnpkg/yarn/blob/master/src/util/normalize-manifest/validate.js#L44-L98
**Test plan**
Added a test in `/__tests__/normalize-manifest.js`, refactored out the test function used for non-global commands
*BEFORE*
*AFTER*
> #3821 Remove manifest check for global commands

- src/util/root-user.js
- src/util/user-home-dir.js
Fixes #2536
**Summary**
When packaging software that uses yarn for dependency management, some distributions use fakeroot as a part of their build system (my case, Solus OS). 
What happens is that the uid is set to 0, and because of that yarn tried to use /usr/local/share as the home directory. When yarn tried to create this directory it fails, because the user is not really root and does not have the permissions. 
This added check makes sure that we use the right home directory when running under fakeroot  
**Test plan**
This is what was executed (in the yarn codebase) to prove the difference:
With current yarn:
```
~/tmp/yarn $ fakeroot yarn
/usr/lib64/node_modules/yarn/node_modules/mkdirp/index.js:90
throw err0;
^
Error: EACCES: permission denied, mkdir '/usr/local'
at …
```
> Do not use /usr/local/share as home under fakeroot

- circle.yml
- jenkins_jobs.groovy
- scripts/update-npm.sh
**Summary**
This is a followup to #3866. I originally moved the Yarn npm publish to our external build infra. After thinking about this for a while, I'm going to move this particular step back to publishing directly from CircleCI. The reasons that the other releases are pushed from infra under our own control (eg. signing them with GPG/Authenticode) don't really apply to the npm package as it just doesn't support this functionality. 
We'll have to revisit it if npm add extra security in the future, but it's fine for now.
**Test plan**
This is difficult to test without publishing a new Yarn version. I tested the script locally by commenting out the check for if the specific version already exists on npm, and it worked up until the point of publishing (which obviously threw an error "You …
> Publish npm release of Yarn directly from CircleCI

- src/registries/npm-registry.js
**Summary**
Commands like ```publish``` were asking for a password instead of using the token in ```.npmrc```.
The core code path that was causing the issue is https://github.com/yarnpkg/yarn/blob/master/src/registries/npm-registry.js#L218-L221
``` javascript
// If sending a request to the Yarn registry, we must also send it the auth token for the npm registry
if (baseRegistry === YARN_REGISTRY) {
registries.push(DEFAULT_REGISTRY);
}
```
The problem was ```baseRegistry = "https://registry.yarnpkg.com"``` while ```YARN_REGISTRY = "https://registry.yarnpkg.com/"```. Notice the trailing slash.
I've reverted the code added in https://github.com/yarnpkg/yarn/commit/33820719e2c049ff93e86d29251b96d496f2b6e8#diff-b053bee294c216269844e5874039b6caR172
which solves the problem. Unclear to me why it …
> Fix various commands asking for a password

- __tests__/commands/global.js
- src/cli/commands/create.js
- src/cli/commands/global.js
- src/cli/commands/link.js
- src/cli/commands/unlink.js
- src/constants.js
- src/util/execute-lifecycle-script.js
Previous PR: #3458
Fixes: #2064
> Fix yarn global prefix directory

- resources/winsetup/Yarn.wxs
**Summary**
We're writing the Yarn installation directory to the registry (`HKEY_LOCAL_MACHINE\Software\Yarn\InstallDir`) but aren't reading that on upgrades. derp.
This was pretty much just copypasta from https://www.firegiant.com/wix/tutorial/getting-started/where-to-install/ 😛 
**Test plan**
Now when upgrading, we correctly prefill the path:
On a fresh install, we still default to the Program Files directory:
(as an aside, I'd love to install to `C:\Program Files\` rather than `c:\Program Files (x86)\` given all our code is "AnyCPU" / processor-agnostic, but that actually requires building a 64-bit `.msi` file that doesn't even run on 32-bit machines. It's probably not worth it.)
Closes #3944
> [windows] When upgrading Yarn, install into the previously-used directory

- src/util/fs.js
**Summary**
[`path.relative`](https://nodejs.org/api/path.html#path_path_relative_from_to) returns an empty string for the current directory. This was being passed as the target to `fs.symlink`. Changed it so '.' is passed instead in these cases. Fixes issue #3276.
**Test plan**
The fix is very small and straightforward so haven't added a test. Can do if needed.
> Fix: Ensure valid target passed to fs.symlink (refs #3276)

- bin/yarn
**Summary**
After merging #1180 `yarn` binary executes node commands it these ways:
```bash
node "$basedir/yarn.js" "$@"
nodejs "$basedir/yarn.js" "$@"
```
This leads to the fact, that yarn uses `/bin/sh` for running:
```bash
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         8  0.0  0.0   4340   756 ?        S    08:08   0:00 /bin/sh /usr/local/bin/yarn test:unit
root        19  4.0  3.3 1083008 69008 ?       Sl   08:08   0:00  \_ node /opt/yarn/bin/yarn.js test:unit
root        29 28.6  7.4 1284500 152928 ?      Sl   08:08   0:06      \_ node /app/node_modules/.bin/karma start test/unit/karma.conf.js --single-run
```
It causes problems when Yarn is running in Docker container - it doesn't handle `SIGTERM` or any other signals.
To resolve this issue we …
> Add exec to node commands in the binary

- src/registries/npm-registry.js
- src/registries/yarn-registry.js
This searches for the global RC files at `${PREFIX}/etc/{npm,yarn}rc`, whereas previously it looked in `${PREFIX}/.{npm,yarn}rc`.  By code inspection it looks like the NPM code does the same thing on both windows and posix, but the documentation for windows suggests it might not use the `/etc` path component.  I haven't verified behaviour on windows.
Resolves #1931.
> Global Config at ${PREFIX}/etc/{nmp,yarn}rc

- bin/yarn-bundle-entry.js
- bin/yarn.js
- scripts/build-webpack.js
- src/cli/index.js
- src/reporters/console/console-reporter.js
**Summary**
Refs #3524. We are using `process.exit()` pretty liberally although it is [strongly advised not to use it](https://nodejs.org/api/process.html#process_process_exit_code) since it may cause the `stdout` to get corrupted/terminated before a full flush. This patch changes all possible `process.exit(code)` calls with `process.exitCode = code` statements.
We'd also ideally enable [no-process-exit](http://eslint.org/docs/rules/no-process-exit) rule in ESLint but it requires an upgrade to ESLint v4 which should be handled separately.
**Test plan**
Expect tests to pass and actually finish (not run indefinitely due to `yarn` not exiting at all). Also, the script referenced in #3524 to output something like the following:
```
DATA 18
DATA 8192
DATA 8192
DATA 5392
DATA 15
EXIT 0
```
> Fix: avoid using `process.exit()` when possible

- src/reporters/lang/en.js
Updates color legend:
```
info Color legend :
"<red>"    : Patch Update Backward-compatible bug fixes
"<yellow>" : Minor Update backward-compatibles features
```
to
```
info Color legend :
"<red>"    : Patch Update backward-compatible bug fixes
"<yellow>" : Minor Update backward-compatible features
```
> Fix color legend messages

- src/cli/commands/install.js
- src/integrity-checker.js
- src/lockfile/wrapper.js
**Summary**
Bug: pruneOfflineMirror does not guard against `lockfile[dependency].resolved == undefined` (eg. the dependency is a local file)
This results in the following error when running `yarn install`:
`TypeError: Cannot read property 'split' of undefined`
To reproduce:
- set a `yarn-offline-mirror` path and set `yarn-offline-mirror-pruning` to `true`
- have a `file:` local dependency in `package.json`
- run `yarn install`
Simple fix - set basename only if resolved is valid.
**Test plan**
The fix is obvious - call `resolved.split()` only after making sure `resolved` is not undefined. Nothing changes at the functional level.
Please let me know if I should still create a test case for this scenario.
> Fix: pruneOfflineMirror handle undefined resolved

- src/cli/commands/owner.js
- src/cli/commands/tag.js
- src/cli/commands/team.js
**Summary**
From #3952 - For the sake of consistency and clarity, we need to rename the `rm` command to `remove` and add a deprecation warning for `rm`.
**Test plan**
I have done some rounds of functional manual testing.
Unfortunately, every command with `rm` requires a login. Coincidentally, and if I am not mistaken, none of the commands that implement `rm` has tests ( `owner`,  `tag`, `team`).
I will happily add tests for those but I can't seem to make a mock login to work... I need suggestions/guidance?
Note: I'm working on a windows machine. When I try to run `yarn run test`  I get the following
```
$ yarn lint && yarn test-only
Found 0 errors
C:\code\projects\yarn\node_modules\.bin\jest:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
^^^^^^^
SyntaxError: missing ) after …
```
> Breaking: rename every `yarn <command> rm` to `yarn <command> remove`

- __tests__/util/git.js
- __tests__/util/git/git-ref-resolver.js
- __tests__/util/git/git-spawn.js
- src/resolvers/exotics/hosted-git-resolver.js
- src/util/git.js
- src/util/git/git-ref-resolver.js
- src/util/git/git-spawn.js
**Summary**
For git dependencies, the branch/tag resolution does not always work as expected.
Refactor the code to make the resolution algorithm more explicit and follow discussions in #3720
**Test plan**
New test in `__tests__/util/git-ref-resolver.js`.
Also benefit from the fact that travis-ci ran the test with an older Git version. I don't know if we have a minimum git version requirement, it seems we currently don't test against any specific version.
**Implementation details**
I refactored `parseRefs` to return the full ref name, so we can differentiate branches and tags.
I use `git ls-remote --symref` to get the default branch name. This works only in recent versions of git (thanks travis-ci for reporting the issue), so I fallback to another algorithm if `--symref` is unavailable.
I …
> Refactor branch/tag resolution for git dependencies, fixes #3720

- src/fetchers/git-fetcher.js
- src/fetchers/tarball-fetcher.js
- src/util/fs.js
**Summary**
There's a delay between when we make sure a file in cache exists and when we actually start reading it. Our code wasn't doing any error handling when trying to open the file so if another process removes the file we assume existing we were throwing an unexpected `ENOENT ... open` error.
This patch removes all delayed existence checks and catches the error directly on the `ReadStream` instance directly. Moreover, it automatically falls back for local caches: direct, cache, offline mirror.
This revealed a bug in tarball path resolution which I fixed.
**Test plan**
> Fix: handle potential race conditions when using cache

- src/util/execute-lifecycle-script.js
**Summary**
Fix for #3773
> Yarn run no longer works on windows with executables not mentioned in package.json/scripts
**Test plan**
I think we don't have automated tests for this case, it's OS specific and the fix relies on the `shell` option of `child_process.spawn`, so we cannot use mock to reliably test this issue.
(Any idea welcomed)
I ran manual tests on Windows 10 and a linux VM.
We should get more manual tests from the community before merging.
> Fix `yarn run` on window

- .eslintrc
- bin/yarn.js
- src/cli/index.js
- src/config.js
- src/util/signal-handler.js
**Summary**
A follow up to #3955 to disable further usage of `process.exit()`.
**Test plan**
`yarn lint` should not produce any errors.
> Chore: enable no-process-exit lint rule

- __tests__/registries/npm-registry.js
- src/registries/npm-registry.js
- src/resolvers/registries/npm-resolver.js
**Summary**
Fix scoped packages not adding correct auth headers (#4016)
**Test Plan**
Having set up config for a scoped registry with an auth token. It should be possible to run `yarn cache clean` followed by `yarn install` without having the scoped packages 403
> Scoped packages 403 on yarn install with empty cache

- __tests__/registries/npm-registry.js
- src/registries/npm-registry.js
- src/util/user-home-dir.js
**Summary**
Fix for https://github.com/yarnpkg/yarn/issues/3920.
In this [commit](https://github.com/wtgtybhertgeghgtwtg/yarn/commit/f4fe7431ed992862a1c1d2357e6521c268bad7a7), `userHome` for linux users running as root was changed to `/usr/local/share`, mainly to allow for other users to run globally added bins. However this introduced a bug where npmrc wasn't being looked in the root directory after checking `/user/local/share`. So this change pushes another location to check in case `userHome` is different from native home directory returned by `os.homedir()`
**Test plan**
I've added a test to generally test the `getPossibleConfigLocations` method, but I haven't been able to properly mock out running it as a root user on linux. Suggestions welcome!
> Check for npmrc in home directory for linux root users

- __tests__/commands/version.js
- src/cli/commands/version.js
**Summary**
Refs #3610.
Some versions of `git` doesn't support passing absolute paths to
`git add` causing it to fail. This patch runs
`git rev-parse --show-toplevel` to git root and uses the relative
path of `package.json` to that directory when calling `git add`.
**Test plan**
Manual tests for now.
> Fix: use `git add` with relative path to git root in version command

- __tests__/fixtures/lifecycle-scripts/script-fail/app.js
- __tests__/fixtures/lifecycle-scripts/script-fail/package.json
- __tests__/fixtures/lifecycle-scripts/script-segfault/app.js
- __tests__/fixtures/lifecycle-scripts/script-segfault/package.json
- __tests__/fixtures/lifecycle-scripts/script-segfault/segfault.c
- __tests__/fixtures/lifecycle-scripts/script-success/app.js
- __tests__/fixtures/lifecycle-scripts/script-success/package.json
- __tests__/lifecycle-scripts.js
- src/errors.js
- src/reporters/lang/en.js
- src/util/child.js
- src/util/execute-lifecycle-script.js
**Summary**
Fixes: #3954, Adds error handling for scripts that are failing with a signal such as `SIGBUS`, `SIGSEGV`, etc.
In current behavior, yarn checks the exit code of a script to show errors and fail the process. But certain errors make node child-processes to exit with a signal instead. (e.g. the case in #3954)
This fix adds support for handling exit signals from child processes and shows more informative error messages.
**Note:**  This implementation handles exit signals priorly, assuming exit signals are pointing to more critical low-level issues.
**Test plan**
Added 3 test cases (one for _zero_ exit code, one for _non-zero_ exit code, one for _exit signal_)
> Handle scripts failing with exit signals (fixes: #3954)

- src/cli/index.js
**Summary**
We should call `await reporter.close()` before we know we are done to ensure flushing of stdout contents.
**Test plan**
> Fix: Make sure reporter is closed before exit

- gulpfile.js
Converted two constants to `const` inside `gulpfile.js`
> Convert gulpfile 'var's to 'const's

- __tests__/reporters/__snapshots__/console-reporter.js.snap
- src/cli/index.js
- src/reporters/console/console-reporter.js
- src/reporters/console/progress-bar.js
**Summary**
Fixes #4023. There was nothing preventing the console reporter from
having more than one progress bars, or keep updating and rendering
its progress bar after it was finished or the reporter was "done".
This patch stores the active progress bar, and stops it before
`footer` is printed out. Also makes sure the progress bar itself
ignores any updates once it stops.
**Test plan**
One, weak, existing test with updated snapshot. Manual steps:
- Run `yarn install express`
- Observe that your console is properly cleared after `yarn`
finishes and the last thing you see is the "Done in X.YZs."
message and not a corrupted progress bar.
> Fix: Progress bar continue to update after footer

- __tests__/integration.js
- src/cli/index.js
**Summary**
The current network mutex code relies on the old `process.exit()` to
terminate all existing connections. Since that has been removed now,
when a "master" `yarn` instance gets another one connected to it and
waiting for it to end, it stays in a zombie state due to the TCP
server not terminating with clients on it. This patch makes it shut
the server down properly when everything is done, fixing the deadlock.
**Test plan**
Adds a new integration test which hangs and times out without the fix.
Also can be tested manually, running two `yarn` instances side by side
with the `--mutex=network` option, concurrently.
> Fix: deadlock when using network mutex and concurrent runs

- .travis.yml
- __tests__/integration.js
**Summary**
We normally clean up the test `cwd` after running them but we
don't for integration tests. With the addition of a new test case,
this started causing macOS builds to fail on TravisCI due to exhaustion
of space on ramdisk which we use to run tests on for speed.
**Test plan**
macOS tests should pass on TravisCI.
> Fix: Clean-up cwd after integration tests

- src/cli/index.js
**Summary**
When `:` is not used in the `mutex` argument to provide a specifier,
`mutexType` and `mutexSpecifier` are parsed incorrectly. This patch
fixes that.
**Test plan**
Run `yarn --mutex=network` before the patch, observe the error. Run
the same command after the patch and see it pass.
> Fix: fix unknown single-instance type error

- src/fetchers/workspace-fetcher.js
**Summary**
When resolving workspace packages, we were always using the version `0.0.0` instead of the version defined in that package. This patch fixes it to use the correct version available from the package.json file inside.
**Test plan**
> Fix: invalid versions for workspace package

- src/package-hoister.js
**Summary**
Just fixes a small bug in the hoisting code where it pushed `undefined` to the ancestor list when traversing the-level dependencies.
**Test plan**
N/A
> Fix: prevent hoister from adding an ancestor when there is none

- .flowconfig
- package.json
- yarn.lock
Summary: This upgrades flow, both in the flowconfig and in the flow-bin dependency to ^0.52.0
Test plan: `yarn lint`
*Note*: Should we reconsider using carets for flow versions? While flow is still < 1.0 and shouldn't introduce breaking changes in patch versions, @nmote has told me not to rely on this in the past.
> Upgrade flow to ^0.52.0

- __tests__/reporters/__snapshots__/console-reporter.js.snap
- __tests__/reporters/console-reporter.js
- src/reporters/console/console-reporter.js
**Summary**
We were not stopping any activities in the reporter and were
relying on `process.exit()` to kill them earlier. This patch
fixes that and ensures all activities are stopped when the
reporter is closed.
**Test plan**
Adds a new snapshots test that fails without the fix.
Manual: just try to install a non-existent package and see `yarn`
getting stuck due to an ongoing reporter activity. After the fix,
it shuts down properly.
> Fix: stop all active spinners on reporter.close()

- .flowconfig
- __tests__/commands/install/bin-links.js
- src/lockfile/stringify.js
- src/util/request-manager.js
**Summary**
Enables one of the new lint warnings in Flow. Others are left out because they are too noisy to be useful at the time, without and easy override.
**Test plan**
Lint should pass.
> Chore: Enable untyped-type-import warnings for Flow

- src/cli/commands/install.js
- src/constants.js
- src/integrity-checker.js
- src/reporters/lang/en.js
**Summary**
The integrity file doesn't currently support workspaces, which leads
to #3863 (removing a workspace node_modules folder and running yarn
doesn't do anything, because Yarn incorrectly assumes that everything
is already done).
This PR rewrites a good chunk of the integrity logic to support and
fix this behavior.
**Test plan**
Tests are passing, I still have to write an automated test before
merging this PR.
> Fix: Reimplements part of the integrity check

- __tests__/commands/add.js
- src/cli/commands/add.js
- src/reporters/lang/en.js
**Summary**
This PR prevents using `yarn add <pkg>` from within a workspace root folder, in order to prevent common mistakes where a package is added to the workspace root folder instead of being added to the right workspace (which, because of the node resolution algorithm, would be effectively invisible to the user).
If the user really wants to add a dependency to the workspace root folder, then we suggest them to use `yarn add <pkg> --dev` instead. This should be fine since the workspaces will probably only be used in development mode anyway. An alternative would be to introduce a new flag `--force` that would bypass this check, but I think the current heuristic is fine until we receive complaints.
**Test plan**
Added two tests.
> Enhancement: Prevents "yarn add" from being run from the workspace root directory

- src/reporters/lang/en.js
**Summary**
I noticed that when running `yarn install --offline`, the error message could be a bit cryptical at times when a lockfile entry is missing. This PR helps with this and gives a possible way to fix the error.
**Test plan**
No test plan, since this is purely wording.
> Makes an error message clearer

- __tests__/commands/list.js
- __tests__/fixtures/list/no-args/package.json
- __tests__/fixtures/list/resolutions/package.json
- src/package-resolver.js
**Summary**
Fixes https://github.com/yarnpkg/yarn/issues/4178
`Yarn list` still expects the original requested pattern to be in the resolver, so use the resolved manifest to add the pattern back
**Test plan**
I've added a test in `list.js`.
> Fix #4178: Add original request pattern to fix `yarn list` with resolutions

- __tests__/commands/info.js
**Summary**
This PR fixes #4191. Now that we are using the single-file build with npm, the `scripts` field isn't included into the `package.json` file anymore. It's not clear why the problem only appeared now, but my guess is that this is related to the recent publication of the 0.28.4 release.
**Test plan**
Tests should now pass again.
> Fixes the info tests

- __tests__/fetchers.js
- src/fetchers/git-fetcher.js
There is a problem related to how url.parse and path.basename is used to build the repository name. So the simplest and easiest solution to this, is after the parsing remove ":" when is needed. Looks quick and dirty but understanding that the objective of the function is to transform reference to the packageFilename looks like the correct place to manage exceptional behavior.
> Fix local mirror invalid file name (#4076)

- __tests__/integration.js
- src/cli/commands/cache.js
- src/cli/index.js
- src/config.js
- src/constants.js
- src/reporters/base-reporter.js
- src/reporters/console/console-reporter.js
- src/reporters/lang/en.js
- src/util/fs.js
- src/util/misc.js
**Summary**
Fixes #4141. If `$(yarn cache dir)` isn't writable, Yarn will crash and burn with EACCESS / EPERM. This patch adds a fallback mechanism so that we try different folders until we find one that fits. As a first step, I've added `/tmp/.yarn-cache`.
**Test plan**
Tested with
```
chmod 000 /Users/mael/Library/Caches/Yarn && ~/yarn/bin/yarn
```
> Fallbacks to /tmp if the preferred cache folder isn't writable

- __tests__/fixtures/lifecycle-scripts/lifecycle-scripts/package.json
- __tests__/lifecycle-scripts.js
- src/cli/commands/pack.js
**Summary**
Yarn wouldn't run the `prepack` and `postpack` scripts, as it is expected when `pack` is ran (#4177).
This PR adds those missing calls and updates tests accordingly.
**Test plan**
Added tests.
> Added missing pre/post hooks for `pack` (#4177)

- src/config.js
**Summary**
Since the merging of #, the AppVeyor tests seem to broke randomly on Windows. I suspect this is because Windows is temporarily locking the files after they are created (for inspection?), and that the unlink call is failing because of this. This PR removes the unlink call, which is not required strictly speaking.
This should also make the code more resilient to concurrency issues (there was a slight possibility that two Yarn processes run an `unlink` at the same time, which would cause the second one to fail).
**Test plan**
I'll run the tests multiple times on AppVeyor before merging this PR, to make sure it works as expected.
> Removes the unlink test when selecting the cache folder

- __tests__/index.js
**Summary**
AppVeyor sometimes fail with buggy errors. This PR tries to change that to reject actual errors that Jest will be able to correctly print.
**Test plan**
Nothing particular, since this is only affecting the tests that don't pass.
> Fix: Uses an actual error object in __tests__/index.js

- __tests__/commands/_helpers.js
- __tests__/lockfile.js
- __tests__/package-request.js
- src/cli/commands/import.js
- src/cli/commands/install.js
- src/lockfile/parse.js
- src/lockfile/wrapper.js
**Summary**
Follow up to #3544. Currently, `yarn` happily keeps moving if it
detects merge conflicts and is able to resolve them in the lockfile.
That said it doesn't persist the resolution by saving the lockfile
to disk again. This patch ensures writing the lockfile if it is
"dirty".
This patch also causes `yarn` to throw an error if there are merge
conflicts in the file and `--frozen-lockfile` option is true.
**Test plan**
Existing unit tests. Also try running `yarn install` with the following
files:
`package.json`
```
{
"name": "yarnlock-auto-merge",
"author": "Burak Yigit Kaya <byk@fb.com>",
"left-pad": "^1.1.3",
"right-pad": "^1.0.1"
}
}
```
`yarn.lock`
```
<<<<<<< HEAD
left-pad@^1.1.3:
version "1.1.3" …
```
> Fix: Lockfile should be updated when merge conflcits are resolved

- .gitignore
- packages/lockfile/README.md
- packages/lockfile/package.json
**Summary**
Some tweaks to @wmhilton's work around creating a separate lockfile parser package:
- Rename package to `@yarnpkg/lockfile` as we've discussed
- Add Webpack'd JS file to `.gitignore`
- Capitalize "Yarn" in package description
- Use semicolons in example code
**Test plan**
Eyeballed. No functional changes. Tested locally using `yarn link` to ensure the scoped package name works as expected.
> Tweaks to lockfile package

- __tests__/integration.js
- src/cli/index.js
- src/reporters/lang/en.js
**Summary**
Running the following command doesn't have the expected effect, because the `--no-coverage` option is interpreter by Yarn instead of being forwarded to the script. This patch fix this.
```
$> yarn test-only --no-coverage     # currently bad
$> yarn test-only -- --no-coverage  # currently good
```
This is a breaking change: it will change some edge-case behaviors.
> Fix: Prevents interpreting run options as yarn options

- __tests__/commands/install/integration-hoisting.js
- __tests__/fixtures/install/install-should-prioritise-popular-deep/alice/package.json
- __tests__/fixtures/install/install-should-prioritise-popular-deep/bar/package.json
- __tests__/fixtures/install/install-should-prioritise-popular-deep/baz-1/package.json
- __tests__/fixtures/install/install-should-prioritise-popular-deep/baz-2/package.json
- __tests__/fixtures/install/install-should-prioritise-popular-deep/bob/package.json
- __tests__/fixtures/install/install-should-prioritise-popular-deep/foo/package.json
- __tests__/fixtures/install/install-should-prioritise-popular-deep/foobar-1/package.json
- __tests__/fixtures/install/install-should-prioritise-popular-deep/foobar-2/package.json
- __tests__/fixtures/install/install-should-prioritise-popular-deep/hello/package.json
- __tests__/fixtures/install/install-should-prioritise-popular-deep/package.json
- __tests__/fixtures/install/install-should-prioritise-popular-deep/world/package.json
- src/package-hoister.js
Keep track of side-effects of each visit of package, and replay side-effects rather than re-crawling through the subtree given the same exact pattern
**Summary**
This is a bug fix for #4008. Since Package Hoisting prepass was introduced, the algorithm crawls through the dependency tree regardless of whether the package has been seen before or not. This is okay for small repositories. To scale this to a large repository that has packages numbered in the 50+k, this prepass eats up CPU and hangs for upwards of 15-30minutes. 
The fix is to cache the side-effects of adding occurrences of the packages. This PR preserves the ability for the occurrence to be accounted for as well - it remembers what changed last time the same pattern was encountered and simply reruns the same side-effects …
> Major optimization on hoisting

- src/cli/index.js
**Summary**
The command line flags are missing the `--link-folder` option. Because we always try to create the global and cache folders if they don't exist, if the path is readonly, then Yarn will crash. The new option makes it possible to workaround this issue by manually selecting a different, writable, path.
Followup will be to:
- Make it easier to change all folders at once by selecting a "yarn internal folder" and derivating the others (cache, global, link) from this one.
- Prevent Yarn from automatically creating the global and link folders, unless it really needs to write into them.
> Fix: Add the missing link-folder flag

- __tests__/index.js
- __tests__/integration.js
- src/cli/index.js
- src/constants.js
**Summary**
Fix #2709 - Yarn will now try to move to the closest ancestor directory that contains a `package.json` file if it can. If none is to be found, the current directory will be used as usual. Note that the same behavior if applied to the `--cwd` option, so `--cwd foo/bar` will go to `foo` if `foo/package.json` exists but not `foo/bar/package.json`.
I thought about doing this in the same pass than the rc file selection, but it wouldn't change anything because we're not stat'ing the same files, so we could not factorize the checks.
**Test plan**
Added a test case, and the old one should still pass as expected.
> Better active directory selection

- __tests__/commands/check.js
- __tests__/integration.js
- src/cli/commands/global.js
- src/reporters/lang/en.js
**Summary**
Fixes #4164. Ensures we have the bin folder before trying to link
binaries into it and throws a user-friendly error if it encounters
any permission issues.
**Test plan**
```
rm -rf $(yarn global bin);
yarn create react-app hello-world
```
Make sure it doesn't throw.
> Fix: Ensure bin folder exists before trying to use it

- __tests__/commands/install/integration.js
- __tests__/fixtures/install/install-file-as-default-no-package/package.json
- __tests__/integration.js
- src/package-request.js
- src/reporters/lang/en.js
- src/resolvers/exotics/file-resolver.js
**Summary**
Fixes #4251. Follow up to #4088. Instead of just checking whether the
target is a valid directory, we now check if it contains a
`package.json` file too. This is still different from `npm`'s behavior.
Apparently, `npm` fetches the package info upfront to favor dist-tags
over directories but this comes at a distinct performance penalty and
makes static, deterministic resolution impossible so we are now
deprecating the implicit `file:` protocol in patterns. After a certain
point, we'll remove this code and will require everyone to use `file:`
or at least one of the following path identifiers: `./`, `../`. `/`.
**Test plan**
Updated the existing test for warning check and added a new test for
invalid directories.
> Fix: Deprecate implicit `file:` protocol and only allow package dirs

- __tests__/__snapshots__/fetchers.js.snap
- __tests__/commands/check.js
- __tests__/fetchers.js
- src/fetchers/git-fetcher.js
- src/fetchers/tarball-fetcher.js
- src/reporters/lang/en.js
**Summary**
Fix for https://github.com/yarnpkg/yarn/issues/3697
- Previously, the tarball fetcher always piped the content to offline cache path when the request succeeded (<=400), regardless of whether the received hash matched the requested hash or not. So I moved the write process to the `finish` block of the stream when it checks for the matching hash.
- Improved warning message to include package name and be more user friendly
**Test plan**
Added a test case in fetchers
*BEFORE*
*AFTER*
*note hashes are the same in the screenshots bc I made the code block fail intentionally
> Fix #3697 Improve error handling when tarball fetcher receives bad hash

- __tests__/integration.js
- src/cli/index.js
- src/reporters/lang/en.js
**Summary**
I'm currently debugging a concurrency issue that I noticed when running some internal tests, and the current mutex implementation makes it difficult to know exactly what's happening, because we only know that the process are waiting, with no indication as to *who* they're waiting.
This PR solves this issue by refactoring the mutex to now be an actual webserver (no extra dependency is required, I simply use the `http` native module). When a process fails to create a server, it sends an http request to the one already existing, and print the response (usually the active process `$PWD`) to its standard output as part of the warning message. Once this is done, it opens a new raw socket to the server, and patiently wait for it to be terminated (like in the current workflow).
Note …
> Refactors the network mutex implementation

- __tests__/index.js
- src/cli/index.js
- src/reporters/base-reporter.js
**Summary**
Fix #4276
In some particular cases, the reporters are not correctly closed before Yarn exits. It makes the process hang, because the reporters are expected to periodically check for the RAM usage. This patch does two things:
- First the setInterval loop itself is `unref`, so that it will never prevent the process from exiting.
- More importantly, the reporter is now correctly closed when exiting in the two cases I've noticed.
**Test plan**
I don't think tests are required for this fix, since the reproduction steps are fairly narrow (the bug only occurred when using Yarn in an invalid way) and won't allow us to catch any other bug than this one.
> Fix: Always close the reporter before exiting

- __tests__/fixtures/install/workspaces-install-link-bin/package.json
- src/package-linker.js
**Summary**
When running `yarn install` on some kind of workspaces (I still have to find out the exact criteria that trigger this bug), Yarn crashes with the following error message:
```
ENOENT: No such file or directory, lstat '/some/path/.../node_modules/workspace-aggregator-...'
```
This fix is an hotfix to prevent this error from happening. I still need to investigate to understand what exactly happens, and under what circumstances. This is probably related to #3896.
**Test plan**
Tests will be wrote. Do not merge.
> Fix: Prevents linking binaries from workspaces

- __tests__/integration.js
**Summary**
Follow up to #4286, which accidentally made `getRandomPort()` function obsolete and caused a lint warning.
**Test plan**
Existing integration tests.
> Chore: use the orphaned `getRandomPort` function in tests

- src/errors.js
- src/util/child.js
- src/util/execute-lifecycle-script.js
- src/util/git.js
**Summary**
Fixes #4287. Throws a specific error when `child.spawn` cannot find
the executable and handles this error properly in all `git` invocations.
**Test plan**
> Fix: show better error messages when Git is not found

- __tests__/commands/why.js
- __tests__/fixtures/why/workspace/package.json
- src/cli/commands/why.js
**Summary**
We were not passing the `workspaceLayout` to the resolver, which was breaking the resolution process for workspaces (the resolver was trying to resolve the workspaces on NPM). This PR fix this.
A followup will be to remove (or rather reformat) the aggregator from the display. Given the current time constraints I haven't took time to completely remove it:
**Test plan**
Existing tests should pass + added a new one + manually tested `yarn why` inside a workspace
> Fixes yarn why when using workspaces

- __tests__/commands/info.js
**Summary**
Looks like bumping the version on npm invalidated a cache that
revealed the new API response from npm for yarn. Now the
`scripts` field always exists even if it is empty.
**Test plan**
> Chore: fix info tests

- src/cli/commands/global.js
- src/config.js
- src/constants.js
- src/registries/npm-registry.js
- src/reporters/lang/en.js
- src/util/fs.js
**Summary**
Fixes #4320 and fixes #4323. We were using `fs.access` when selecting
the global prefix folder automatically and expecting only an `EACCES` error.
This caused issues on Heroku where one of our first tries had threw an
`EROFS` error.
This patch also adds `$DESTIR` support back, which was removed in #3721,
probably inadvertently.
**Test plan**
Existing cache folder fallback tests should be enough for now. We should
move the core of those tests for the newly added `fs.getFirstWriteableFolder`
method.
> Fix: More resillient global and cache folder determination

- src/util/execute-lifecycle-script.js
**Summary**
Fixes #4003. 
The motivation behind this PR is to get more parity with npm wrt the `process.env` variables available when running scripts.
**Test plan**
Made these exact changes in my globally installed `yarn`'s node_modules. Using the following `package.json`
```json
{
"name": "foo",
"scripts": {
"test": "env | grep npm_"
}
}
```
I ran `yarn test` to yield:
```
MacBook-Pro:temp adityavohra7$ yarn test
yarn test v0.27.5
warning package.json: No license field
$ env | grep npm_
npm_config_version_git_tag=true
npm_config_init_license=MIT
npm_config_registry=https://registry.yarnpkg.com
npm_execpath=/usr/local/lib/node_modules/yarn/bin/yarn.js
npm_config_argv={"remain":[],"cooked":["test"],"original":["test"]}
npm_lifecycle_event=test
npm_package_name=foo …
```
> Add npm_lifecycle_script to env in makeEnv

- src/resolvers/exotics/file-resolver.js
**Summary**
The exotic `file-resolver` checks for `.` and `..`, but the regex is missing the escape on the `.`, so *any* two characters count as a file. This includes single-character scope names, like `@s/packagename`.
This issue was introduced in https://github.com/yarnpkg/yarn/pull/4257.
**Test plan**
I wasn't sure how packages should be named in `__tests__/fixtures/install/resolutions/exotic-version`, so I have not added add a single-character scoped package reference to test.
I don't know of any single-character scopes in the public registry to use as reference, the way `left-pad-1.1.1.tgz` is mirrored in there. Could I just copy `leftpad-1.1.1.tgz` as `@s/leftpad-1.1.1.tgz` and use that?
> Yarn 1: Fix regex so single-character @scopes can work again

- __tests__/registries/npm-registry.js
- src/registries/npm-registry.js
**Summary**
Fixes #4339. Also fixes handling of upper-case registry names.
**Test plan**
Added unit tests for `NpmRegistry.prototype.getRequestUrl()`.
> Fix: fix support for registry URLs without trailing slash

- __tests__/registries/npm-registry.js
- src/registries/npm-registry.js
**Summary**
Fixes matching protocol-relative registry URLs from config.
Reported here: https://github.com/yarnpkg/yarn/pull/3987#discussion_r137624001
**Test plan**
Added one new test.
> Fix: support protocol-relative registry URLs

- src/fetchers/tarball-fetcher.js
**Summary**
Fixes #3833. Removes `accept` header from tar requests as @arcanis suggested since `application/octet` wasn't ensuring any valid tar file and `npm` client does not send this header anyway.
**Test plan**
Run `yarn add http://prerelease.componentone.com/wijmo5/npm-images/C1Wijmo-Enterprise-Eval-System-5.20172.328.tgz`
It fails without the patch, installs correctly with the patch.
> Fix: remove the `accept` header from tar fetcher requests

- __tests__/index.js
- src/cli/index.js
**Summary**
Fixes #4345. This patch triggers the `help` command with `-h` or
`--help` only when the command name is known to `yarn` and the flag
is set immediately after the command name itself.
**Test plan**
Should add unit tests.
> Fix: only switch to help mode for valid commands

- src/cli/index.js
**Summary**
Currently running `yarn -v` displays the yarn version number but `yarn -h` says otherwise:
```
$ yarn -h
Usage: yarn [command] [flags]
Options:
-h, --help                          output usage information
--version                           output the version number
-v, --verbose                       output verbose messages on internal operations
$ yarn -v
1.0.1
```
this PR fixes `yarn -h` to use `-v` as version number. Output of `yarn -h` with this PR:
```
$ ./bin/yarn -h
Usage: yarn [command] [flags]
Options:
-h, --help                          output usage information
-v, --version                       output the version number
--verbose                           output verbose messages on internal operations
```
> arguement -v is version not verbose

- __tests__/index.js
- src/cli/commands/install.js
**Summary**
Fixes #4344.
**Test plan**
Added new test.
> Fix: don't generate a lockfile when --frozen-lockfile is used

- CONTRIBUTING.md
**Summary**
I got questions about how to run the latest master locally and realized this is not document. This patch documents how to run local yarn builds for potential contributors. 
**Test plan**
Test the suggested change locally and verify it actually works.
> Chore: add instructions about using local builds

- __tests__/commands/install/resolutions.js
- __tests__/fixtures/install/install-nested-resolutions/bar/package.json
- __tests__/fixtures/install/install-nested-resolutions/package.json
- src/package-resolver.js
- src/resolution-map.js
**Summary**
Fix for https://github.com/yarnpkg/yarn/issues/4357.
The issue is that when a dependency (dep A) defined in resolutions (includes dep A, dep B) depends on another resolution (dep B), then it expects to match its own nested dep B to the top level resolution dep B. So the first part of this fix is "don't run resolutions map check when it's in flat mode", which is what threw the invariant warning. Second part of the fix is that we still want that nested dependency (dep B) of a resolution (dep A) to be resolved correctly. `--flat` mode solves this by [collapsing all versions](https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/install.js#L558) after the resolver is done. For resolutions, I'm adding a delay queue for requests with resolutions but no manifests found yet so …
> Fix #4357 - Allow resolver to delay resolutions for nested dependencies

- src/cli/commands/bin.js
**Summary**
Fixes #4371.
**Test plan**
Manual verification: `yarn --silent bin` or `YARN_SILENT=1 yarn bin` should produce output.
> Fix: yarn bin should produce output even when silent

- __tests__/util/git/git-ref-resolver.js
- src/util/git/git-ref-resolver.js
**Summary**
Fixes https://github.com/yarnpkg/yarn/issues/4369, a regression from previous refactor.
Include `pull` requests in ref search and test for it later when it's called by github resolver.
*BEFORE*
*AFTER*
**Test plan**
Added a unit test in `git/git-ref-resolver.js`
> Fix #4369: Include pull requests in git ref search

- __tests__/fixtures/index/run-custom-script-with-arguments/echo.js
- __tests__/fixtures/index/run-custom-script-with-arguments/package.json
- __tests__/index.js
- src/cli/index.js
**Summary**
Fixes #4383. This patch makes argument parsing a bit tidier, and
starts supporting `yarn --silent custom-script` style commands as
initiall intended by #4152.
**Test plan**
Existing unit tests. Should ideally add a few more.
> Fix: fix incorrect argument parsing

- scripts/build-dist.sh
- scripts/release-branch.sh
**Summary**
We've been using `node -p -e` where `-e` is redundant since
it is implied by `-p`: https://nodejs.org/api/cli.html#cli_p_print_script
This patch removes those extra `-e`s.
**Test plan**
All bundles should build on CI without errors.
> Chore: fix misues of -p in node infocations

- __tests__/registries/npm-registry.js
- src/registries/npm-registry.js
> Fix the scope regex, allow / in addition to %2f in the url

- __tests__/index.js
**Summary**
This PR fixes some test flakiness, especially in the
"should add package with frozzen-lockfile option" tests
where we get `ENOENT` errors from cache. This is most
likely because multiple `add` tests are run concurrently
causing cache corruption. This PR makes all `execCommand`
invocations use a separate cache.
**Test plan**
Tests should not be flaky anymore.
> Chore: fix flaky `add` tests by using separate cache

- src/cli/commands/config.js
- src/reporters/console/console-reporter.js
**Summary**
Fixes #3922. Certain commands in yarn should always produce an
output, regardless of the silent status. This makes
`reporter.inspect` for console reporter to always produce an
output. It also forces the output of `yarn config get` to override
silent mode.
**Test plan**
Should add integration tests.
> Fix: always output reporter.inspect values and `config get` result

- __tests__/util/colorize-diff.js
- src/util/colorize-diff.js
**Summary**
Fixes #4395 
This PR fixes a bug that causes `colorizedDiff` to append a period at the end of the return value if the `from`/`to` versions are identical. If they do happen to be identical, then it will simply return the `from` value.
**Test plan**
I am currently testing that, given identical `from`/`to` versions, it returns the `from` (or `to`) version. I've not added unit tests to cover when the versions differ in any way, nor am I testing that the returned string is formatted correctly (e.g., if `from = '1.0.0'` and `to = '1.0.1'`, the result should be `1.0.1` with the trailing one being formatted to green)
> Fix: Diffing identical versions should not include extra period at end (#4395)

- __tests__/__snapshots__/fetchers.js.snap
- src/fetchers/tarball-fetcher.js
**Summary**
This PR fixes the error message for hash mismatches where the actual and expected hashes were swapped in the error message.
**Test plan**
> Fix: actual and expected hashes are swapped

- src/util/root-user.js
I think that fixes #4430
`fakeroot` detection was added in #3924 (7a053e2ca07d19b2e2eebeeb0c27edaacfd67904); it actually tests the exact opposite though. 
For testing this I added the line
```JavaScript
console.log("isFakeRoot", isFakeRoot());
```
I then tried the lines
```
./yarn global add
sudo ./yarn global add
fakeroot ./yarn global add
```
I also tried if `ROOT_USER` is now correct in [user-home-dir.js](https://github.com/yarnpkg/yarn/blob/0ef3bf1f03d128e4793eca3fe3b5f93542451f15/src/util/user-home-dir.js) for these 3 commands. 
```JavaScript
console.log("ROOT_USER", ROOT_USER);
```
> Fix fakeroot detection

- src/reporters/console/console-reporter.js
**Summary**
A combination of changes have caused `yarn upgrade-interactive` to exit with a promise rejection. 
In short, I believe it has always been a problem, but #3995 exposed it to the prompt. 
The child rejection inside of [upgrade-interactive](https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/upgrade-interactive.js#L152) is fine, as it was handled by the `Promise.race` condition; however, rejecting at the parent level inside of [console-reporter](https://github.com/yarnpkg/yarn/blob/master/src/reporters/console/console-reporter.js#L458) causes[ loud-rejection](https://github.com/sindresorhus/loud-rejection) to handle this.
I believe @arcanis 's PR #4283 is what would allow us not to hook into `SIGINT` inside of the console reporter and allow the reporter to cleanly close …
> Fix #4346 yarn upgrade interactive exit

- src/reporters/console/console-reporter.js
**Summary**
Not substantial. It makes it easier to differentiate the items in a list vs the hint. Here is the before:
and the after:
**Test plan**
I ran the tests, and only ones that failed on master failed for me here 🥇
> Bolds the titles in a list

- __tests__/util/root-user.js
This adds a test for `isFakeRoot()` as proposed by @BYK in #4431.
> Add test for isFakeRoot

- package.json
- src/util/request-manager.js
- yarn.lock
**Summary**
Fixes #746. Unfortunately, neither Node, nor many systems come with
built-in DNS caching so the many parallel requests that Yarn makes
sometimes overwhelm the DNS servers, and most of the time, for the
very same domain(s). Even worse, we pay the DNS look up cost for
each request, which is quite sad at best. This patch introduces
the `dnscache` module which intercepts all DNS look ups and answers
them from an in-memory cache when possible. This applies to the
built-in `http` and `https` modules, used by `request`.
**Test plan**
Existing tests should pass, and hopefully be faster. Total number of
DNS look ups should decrease dramatically.
> Update: add DNS caching to request manager

- src/cli/commands/install.js
**Summary**
Fixed incorrect documentation for global add deprecated message
**Test plan**
Run `yarn add -g left-pad` and follow the suggested command on the console. It should work.
> fixes global add error message

- __tests__/commands/install/integration.js
- __tests__/fixtures/install/install-with-null-version/package.json
- src/util/normalize-manifest/fix.js
**Summary**
Fixes #4429. Apparently there's an advice on the internet to use
`null` as the package version to install the latest and even worse,
some people are actually doing this. This patch makes sure the 
version is at least a string (albeit an empty one) when fixing the 
manifest.
**Test plan**
Added new integration test.
> Fix: Handle `null` versions in package.json

- .flowconfig
**Summary**
Right now `yarn lint` produces 27 warnings from flow, all coming from `grpahql` which is not even used (required by `eslint-plugin-relay`). This creates unnecessary noise and makes it hard to see actual flow warnings in Yarn code. This patch adds a directive to `.flowconfig` to ignore erros from graphql.
**Test plan**
Run `yarn lint`. You should see 0 errors and 0 warnings.
> Chore: ignore flow warnings from graphql

- __tests__/commands/add.js
- __tests__/fixtures/add/install-strict-all/.yarnrc
- src/cli/commands/add.js
**Summary**
Fixes #4343. Currently there is no way to remove the package prefix inside `.yarnrc` file, this PR add support for `save-exact` in `.yarnrc` as discussed in #4343. Full credit goes to @jambonrose
```
save-exact true
```
One small thing, should `yarn` be backwards compatible with the old behavior which is `save-prefix ''`? We can just add an extra check here for do this. What do you think @BYK?
```js
} else if (exact || Boolean(this.config.getOption('save-exact')) || Boolean(this.config.getOption('save-prefix'))) {
```
**Test plan**
New unit test.
> Support save-exact true

- .travis.yml
- appveyor.yml
- circle.yml
- src/util/fs.js
**Summary**
Fixes #4331. Supersedes #3290. Uses the newly added `fs.copyFile` 
on Node 8.5 hen available and falls back to the old buffer based 
method otherwise. This patch also refactors the file copy code a 
bit making it more efficient. Here are the durations on my computer 
with [this package.json](https://github.com/sciolist/fcopy/blob/c0ded8b82bbaa3f4cdb0a67e951eb3f8b0f97fb7/perf/project/alottafiles/package.json):
| master | w/o copyFile | w/ copyFile |
| - | - | - |
| ~23s | ~19s | ~14s |
This is with `yarn.lock` in place and w/o `node_modules`.
**Test plan**
> Update: use fs.copyFile when available

- __tests__/index.js
- __tests__/integration.js
- __tests__/lifecycle-scripts.js
FORCE_COLOR environment variable allows to force yarn to use
colors. This makes some of tests fail because of comparing
colorized output with plain strings.
For example, if you run a test in environment where
FORCE_COLOR is set you get this failure:
```
FAIL  __tests__\index.js
● should add package
expect(received).toEqual(expected)
Expected value to equal:
"success Saved lockfile."
Received:
success Saved lockfile."
```
> Free tests from FORCE_COLOR environment variable dependency

- scripts/update-homebrew.sh
**Summary**
Fixes #3415. The old homebrew update script updated the repo
from remote but did not update the local `master` branch, thus
had the potential for conflicts and mismatches. This patch
forces it to use `origin/master` instead and uses the latest
up-to-date version from the source.
**Test plan**
N/A
> Fix: always use origin/master instead of master for homebrew

- __tests__/lockfile.js
- src/cli/index.js
- src/lockfile/parse.js
- src/rc.js
**Summary**
Lockfile parser fails when the lockfile had Windows-style line
endings with an "Invalid token" error. This is default on Windows
and, say when editing the file using vim, it is not obvious or
trivial that the file endings are in Windows-style. This patch
makes the parser tolareate potential "\r" chars before "\n" while
keeping the existing parsing logic the same.
**Test plan**
Added three new unit tests.
> Fix: make lockfile parser tolerant to CRLF

- .travis.yml
- __tests__/__snapshots__/integration.js.snap
- __tests__/integration.js
- src/cli/index.js
- src/rc.js
**Summary**
Fixes #4457, partially handles #4470. `.yarnrc` argument passing logic was not aligned with
how `commander` works. Even more, `commander`'s boolean logic was
also not used correctly. This patch fixes both, allowing use of
boolean type CLI options both ways (enable/disable) both from the
command line and `.yarnrc` file.
**Test plan**
Added new integration test for getting args from `.yarnrc`.
> Fix: fix argument parsing and .yarrc argument passing

- src/cli/index.js
- src/constants.js
- src/reporters/lang/en.js
**Summary**
Fixes #4501, refs #4490, refs #4284. Yarn now warns when it
detects it is running in a Node version that is not fully
supported and warns the user about this. This is different than
the hard Node 4+ check in the entry file since in that case,
Yarn wouldn't run at all due to syntax incompatibilities. This
warning is to signal that users may encounter unexpected errors
but are allowed to use Yarn if they wish. It also adds a new
flag to suppress this warning: `--no-node-version-check`.
**Test plan**
Since we cannot add unsupported Node versions to our CI and
spoof the Node version internally, this has to be tested
manually, which I did.
> Update: warn when used with not supported Node versions

- package.json
- src/reporters/console/console-reporter.js
- yarn.lock
**Summary**
This is a bugfix for the following error which happens on master
```
❯ yarn outdated
yarn outdated v1.0.2
error An unexpected error occurred: "this.format.stripColor is not a function".
info If you think this is a bug, please open a bug report with the information provided in "/Users/danieltschinder/Documents/ResearchGate/PHP/community/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/outdated for documentation about this command.
```
chalk 2.0 removed stripColor see https://github.com/chalk/chalk/releases/tag/v2.0.0 and this wasn't respected in #4482
> Fix stripColor to be available again in console reporter

- __tests__/commands/install/integration.js
- src/package-resolver.js
**Summary**
Fixes #3780, and makes the failing test from #3779 passing.
As a final step of package resolution, for each dependency we check whether any version satisfies all resolved version ranges. 
**Test plan**
Fixes an existing (failing) test: "unbound transitive dependencies should not conflict with top level dependency"
> Fix: 'yarn --flat' unbound transitive deps shouldn't conflict with top level deps

- src/cli/commands/global.js
**Summary**
Fixes #2652. Adds a `yarn global dir` command that prints the output
of the global installation folder that houses the global `node_modules`.
**Test plan**
> Update: add `yarn global dir` command

- src/util/fs.js
**Summary**
Refs #3751. Changes `reporter.warn` to `reporter.verbose` for the message "The case-insensitive file ${dest} shouldn't be copied twice in one bulk copy".
**Test plan**
> Fix: Suppress "revealed multiple traversal of the same folder" warnings

- src/util/fs.js
**Summary**
Follow up to #4486 which reverted the while loop that waits on
potential multiple copies of the same file. This seems to have
some random breakages and needs more investigation for optimizing.
**Test plan**
N/A
> Fix: bring back the aggressive concurrency protection

- __tests__/integration.js
- src/cli/commands/config.js
- src/config.js
**Summary**
Fixes #4557. Also adds `yarn config current` that lists the current
configuration as JSON for testing purposes.
**Test plan**
Added integration tests.
> Fix: always prefer CLI options over env for --prod

- bin/yarn
**Summary**
This addresses some of the windows issues regarding running yarn in gitbash and friends envrionment.
with this fix I keep the behavior introduced 5 months ago in yarnpkg/yarn#3245, but try to do a better job detecting when to use winpty out of the box, in order make `piping` of output work with yarn.
Before this fix:
```shell
$ yarn --version
1.1.0
$ yarn --version | cat
1.1.0
$ yarn init
yarn init v1.1.0
error An unexpected error occurred: "Can't answer a question unless a user TTY".
info If you think this is a bug, please open a bug report with the information provided in "D:\\workspace\\yarn\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/init for documentation about this command.
```
Piping works for simple commands, but interactive commands only work with an …
> fix(windows): Detect when winpty is present and if the current terminal is a TTY

- src/cli/commands/autoclean.js
Hello!
**Summary**
I removed the *.gz from the default .yarnclean generated by the `yarn autoclean --init` command. 
**Test plan**
I tested by hand and launch `yarn test` and didn't find a test case for the autoclean --init option. If needed I could write a test case to check the default .yarnclean file content against the constant DEFAULT_FILTER.
I hope it resolve half the issue #4450 :)
> ref(autoclean): remove *.gz from the default .yarnclean file

- __tests__/commands/cache.js
- src/cli/commands/cache.js
**Summary**
This was proposed in #3200. It adds the ability filter the cache list with multiple filters.
If it matches any of the filters it will add the module to the list. If it doesn't it just skips.
**Test plan**
Added tests for this new feature.
Matching with single filter:
Matching with different filters:
No match in the cache:
> Add ability to filter yarn cache (fixes #3200)

- Dockerfile.dev
The reasoning behind this:
1) As discovered in #4606 not all of the tests are passing on 7.x 
2) Node 7.x is no longer supported anyway
I also removed MAINTAINER field from Dockerfile as it's not required.
> Updated node to 8.x in Dockerfile.dev

- src/package-resolver.js
**Summary**
Fixes #4550. The optimization introduced in #4488 should only
apply to flat installations since even if a single pattern can
satisfy all resolved versions, it is not guaranteed that it is
strict enough for resolving correctly for all patterns under all
circumstances.
**Test plan**
> fix(resolver): Only optimize patterns in flat mode

- __tests__/commands/run.js
- __tests__/integration.js
- package.json
- src/cli/commands/run.js
- src/util/misc.js
- yarn.lock
**Summary**
Extra command-line arguments to scripts were not being escaped correctly. This patch adds robust shell quoting logic for both Windows and Linux/macOS.
**Test plan**
On *nix, create a `package.json` containing `"scripts":{"echo":"echo"}`. Run `yarn run -s echo -- '$X \"blah\"'`. Expect to observe ` \blah\` prior to this patch, and `$X \"blah\"` after it.
Testing on Windows should be similar, but may require fancier escaping to get the arguments into yarn in the first place. (I don't have access to a Windows box to verify the exact procedure to follow, sorry—but I did confirm that my automated tests succeed in AppVeyor.)
> fix(run): improve escaping for script arguments

- src/config.js
- src/util/request-manager.js
**Summary**
Fixes #4546. Previous behavior was that if `.npmrc` or `.yarnrc` contained and `http-proxy` but not an `https-proxy`, HTTPS requests would "fall back" to the `http-proxy`.
This is not always the desired behavior; See #4546 sometimes one protocol needs a proxy and the other does not.
This PR adds the ability to set the `https-proxy` to `false` which will cause Yarn to not use an HTTPS proxy (and not fall-back to the HTTP proxy). This allows the code to treat `undefined` as the setting not being specified (which will fall back to http-proxy) and `false` as the setting being specified, but set to false (which will not use a proxy).
**Test plan**
Tested manually on Windows with Fiddler.
I have no idea how to test this since requests go through the mock http requester when running …
> fix(network): Allow `https-proxy false` to not use a proxy for HTTPS

- src/util/request-manager.js
**Summary**
Sometimes Yarn saturates the network and sometimes the network itself
has issues, especially on CI and Yarn reports this as a warning. This
should be a simple info message unless it actually completely fails.
This also fixes a flaky integration test with react-scripts.
**Test plan**
`react-scripts` integration test should not be flaky anymore.
> fix(request-manager): Flaky network messsage should be info, not warning

- __tests__/commands/list.js
- src/cli/commands/list.js
- src/reporters/lang/en.js
**Summary**
In PR #4571, list was highlighted to be a candidate for adding a pattern option to allow filtering.
This PR adds this option.
Usage:
`yarn list --pattern mypattern`
Still allows:
`yarn list exact-package --pattern mypattern`
but this is now deprecated.
**Test plan**
Updated current tests to use new flag.
> Add ability to filter yarn list with pattern

- __tests__/commands/upgrade.js
- src/cli/commands/upgrade.js
- src/package-request.js
**Summary**
In PR #4571, upgrade was highlighted to be a candidate for adding a pattern option to allow filtering.
This can be used with the current args or by itself.
Usage:
`yarn upgrade --pattern mypattern`
`yarn upgrade diff-package --pattern mypattern`
**Test plan**
Added test that filter with pattern and with the current args together.
> Add ability to upgrade based on pattern

- __tests__/integration.js
The change introduced in 96c215c1ce5944a6fe993ab0d9b13e6edfe65675 caused tests to fail on node 7 as react-scripts is not compatible with it, this skips test on node v7 which is used within yarn's Docker.
I excluded this test for node v7, here's the reasoning behind it:
```
Summary of all failing tests
FAIL  __tests__/integration.js (182.903s)
● yarn add react-scripts@1.0.13
expect(received).not.toMatch(expected)
Expected value not to match:
/^warning /gm
Received:
"warning You are using Node \"7.10.1\" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: \"^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0\""
at __tests__/integration.js:82:1793
at Generator.next (<anonymous>)
at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30) …
```
> chore(tests): Make integration tests passing on Node 7

- __tests__/package-request.js
- src/package-request.js
**Summary**
Bugfix for #4480. Change suggested by @BYK 
**Test plan**
Running yarn on local.
_**Before Changes**_
```bash
warning node-uuid@1.4.8: Use uuid module instead
```
_**After Changes**_
```bash
warning raven > node-uuid@1.4.8: Use uuid module instead
```
> fix(resolver): `parentNames` is missing in package warning breadcrumbs

- __tests__/package-request.js
- src/package-reference.js
**Summary**
This is a follow up to #4484 and #4478 which improves the code
around those areas a bit and removes a now-unnecessary `while`
loop.
**Test plan**
Existing tests should pass.
> chore(resolver): Minor improvements in resolver code and tests

- __tests__/integration.js
- src/registries/base-registry.js
**Summary**
Follow up to #4238. We were always passing the `registry` key in
registry overrides but its value was `undefined` when an override
was not in place. `Object.assign` doesn't care about that though
so we were overriding the registry all the time, mostly with
`undefined`.
**Test plan**
Added new test case.
> fix(config): Don't override registry with `undefined` by default

- src/resolvers/exotics/bitbucket-resolver.js
- src/util/git.js
- src/util/request-manager.js
**Summary**
* fix hasHTTPCapability issue with bitbucket shortcut resolver and private repo (#4393)
*bug with a private repo that used like `"module": "bitbucket:team/repo"`*
* fix setRefRemote issue with exotic shortcut resolvers and branch/tag/commit
*bug with a repo that used like `"module": "bitbucket:team/repo#tag"`*
**Test plan**
If I have a private dependency like `"activities": "bitbucket:openagenda/activities"` in my package.json, and I run `yarn install --verbose` then I have this error:
```
verbose 0.407 Performing "HEAD" request to "https://bitbucket.org/openagenda/es-node".
verbose 0.867 Request "https://bitbucket.org/openagenda/es-node" finished with status code 302.
verbose 0.873 Performing "GET" request to …
```
> fix(git): Fix Bitbucket exotic shortcut resolvers with private repositories

- __tests__/util/git.js
- src/util/git.js
**Summary**
This PR is triggered by https://git.io/vdzI2. It refactors the
code to allow more hosted Git expansions (like GitLab) in a more
flexible way. It also prefers `url.parse` over regular expressions
and removes any hasehs in `GitUrl.repository` results.
**Test plan**
Existing tests should pass along with the hash removal correction.
> fix(git): Refactor Git URL resolution code & remove hash from URL

- README.md
- package.json
- yarn.lock
**Summary**
Adds commitizen and adopts the cz-conventional-changelog adapter for commit logs. Will be followed
up by commit message linters and automatic version number bumping in CI builds.
**Test plan**
Run `yarn install` and then `yarn commit -a` after making some changes to test the new awesomeness. This commit message was also generated via that command.
> chore(repo): Add `yarn commit` for structured commit messages

- __tests__/integration.js
- src/cli/index.js
**Summary**
Follow up to #4204. We forgot to relay the exit code of the
newly spawned yarn instance when using `yarn-path` which is
causing false negatives especially when using `yarn run`. This
patch relays the exit code of the spawned process.
**Test plan**
Added a new test that fails without the fix.
> fix(config): Relay exit code when using yarn-path from yarnrc

- src/cli/index.js
**Summary**
Yarn doesn't correctly forward the exit code if the process is executed via `spawnp`.
**Test plan**
Will write tests in a separate PR, but I'd prefer to merge this one asap.
> Fixes how the exit code was forwarded when using the yarnrc path

- src/reporters/console/util.js
If the output does not support color, then each render of the progress bar is added to a single line, which wraps over multiple lines.
As a fallback, a simple carriage return is used to move to the start of the line, and space characters to clear the line.
**Summary**
This is a minor cosmetic output on the formatting of the progress output.
I came across the issue raised when looking for problems to address for Hacktoberfest.
**Test plan**
I verified by running `yarn check` to provide output with the progress bar under the following conditions:
* Interactive use with color output.
* Interactive use with terminal not supporting color output
* Non-interactive use (output was piped)
The output from the 3 tests can be seen in the following screenshot.
This screenshot shows the non-color test …
> Fixes progress display on non-color tty (#4647)

- __tests__/config.js
- src/config.js
**Summary**
fixes #4695 
Do not convert empty string to cwd directory. This avoids a problem where a `cafile=''` setting was trying to load the directory as the cert file.
**Test plan**
Requests are mocked during tests so request-manager doesn't try to load the `cafile`, so the exact fix is hard to test.
I added a new test file for `config.js` and a couple initial tests.
> Do not convert empty string to cwd path.

- src/cli/commands/autoclean.js
**Summary**
Remove entries to clean `*.yml` and `.*.yml` from the default filter list in `.yarnclean`. Instead, include configuration files from common CI and build tools.
- Travis CI
- CircleCI
- AppVeyor
- Codeship
- Wercker
Fixes #4281, fixes #2276.
**Test plan**
```shell
$ yarn autoclean --init
yarn autoclean v1.2.1
[1/1] Creating ".yarnclean"...
info Created ".yarnclean". Please review the contents of this file then run "yarn autoclean --force" to perform a clean.
✨  Done in 0.15s.
$ grep yml .yarnclean 
appveyor.yml
circle.yml
codeship-services.yml
codeship-steps.yml
wercker.yml
.travis.yml
```
> fix(autoclean): Include only common CI configs in default .yarnclean

- src/package-linker.js
**Summary**
@gaearon called Yarn out for better peer dependency error messages so this is the first step to make
them more useful and informative.
**Test plan**
Use a repo like `https://github.com/edmorley/yarn-unmet-peerdependency-testcase` to have peer dependency
warnings and observe they now show the path for the package missing the peer dependency. This should
allow people to investigate these errors in an easier fashion.
```
warning "neutrino-preset-airbnb-base > eslint-config-airbnb-base@12.0.2" has unmet peer dependency "eslint@^4.8.0".
warning "neutrino-preset-airbnb-base > eslint-plugin-import@2.7.0" has unmet peer dependency "eslint@2.x - 4.x".
```
> docs(linker): Use breadcrumbs in peer dependency warnings

- src/util/request-manager.js
**Summary**
Fixes #4546.
Pass a `proxy` value to `request` to prevent it from falling back to
checking envirnment variables.
Yarn already gets the env var values through it's configuration and may
have overriden them to it's own liking.
See use case in mentioned issue.
If a `proxy` value is not set, then [this logic](https://github.com/request/request/blob/b12a6245d9acdb1e13c6486d427801e123fdafae/request.js#L277) causes it to check the env vars instead, which will fallback to `http_proxy`. This was preventing the `https_proxy false` config setting from working if environment variables were set, because the request library would fallback to using that instead.
**Test plan**
Manually test with and without https_proxy set in config and in
environment variable.
> fix(request): pass a proxy to request even if falsy

- __tests__/commands/install/integration.js
- __tests__/fixtures/install/install-with-comments/package.json
- src/constants.js
- src/util/normalize-manifest/fix.js
Fixes #4774
**Summary**
Previously package.json comments were being ignored for "dependencies",
"devDependencies", "optionalDependencies".
This change adds "resolutions" to the sections that will ignore
comments.
**Test Plan**
Added unit test to make sure warning is not printed for a comment in a
resolution.
> feat(config): Allow JSON "//" comments in package.json resolutions

- src/cli/commands/install.js
- src/integrity-checker.js
**Summary**
Fixes #756. We have multiple versions of our app and each one uses a different version of node. 
Therefore we need to rebuild our `node-sass` module every time we move from one to another. 
This PR addresses that by saving the NODE version those artifacts were built with within the `.yarn-integrity` file and triggers forced scripts install (only if the node version is different ofc).
**Test plan**
```
1. Install Node.js 7.x
2. Add the node-sass dependency to the project via Yarn
3. Update Node.js to 8.x (new NODE_VERSION)
4. Run "yarn install" (you should see yarn downloading fresh scripts/binaries)
```
> fix(install): Rebuild native modules when node version changes

- __tests__/util/git/git-spawn.js
- src/util/git/git-spawn.js
**Summary**
Fixes #4729.
Previous version in #4805.
Manually specify `GIT_SSH_VARIANT` in order to get package download via `git+ssh` with non-standard port when using `plink.exe` working.
Without `GIT_SSH_VARIANT` set properly, Git won't convert `-p` into `-P` and `plink.exe` will throw an error about unknown `-p` parameter.
**Test plan**
Also got `git-spawn.js` test suite updated for testing `GIT_SSH_VARIANT`.
> fix(git-spawn): Set `GIT_SSH_VARIANT` to get `plink` working with custom port

- src/reporters/console/util.js
**Summary**
My recent pull request was to improve the appearance of the progress bar for non-color terminals (PR #4697).
However, @skevy reported a RangeError when running with macOS 10.12, with Node 8.6.  This would have been caused by process.stdout.columns returning a negative number.
In this case, this just assumes a default width of 100 characters (as in spinner-progress.js).
**Test plan**
I have not been able to reproduce the condition where `process.tty.columns` returns a negative number, so have verified the logic by considering key cases, e.g., `undefined > 0`, `-1 > 0`.
> fix(reporters): Handle process.stdout.columns being zero

- __tests__/commands/info.js
- src/cli/commands/info.js
**Summary**
Fixes #3947. By default, package `version` was set by sorting all the versions and getting the highest one. Now it's provided via package `latest` dist-tag.
**Test plan**
```bash
yarn info ui-select | grep version: 
version: '0.20.0',
```
```bash
$ yarn info ui-select | grep version:
version: '0.19.8',
```
I've also added a test case for it in `__tests__/commands/info.js`.
Although, I'm not sure if using a specific package like `ui-select` (from #3947) is a proper way to do it, because it'll break with the new release.
Could we add it to the `__tests__/fixtures/request-cache/`, so the package manifest won't change? Or do you have some other idea how can I write this test better?
> fix(info): Use version from `latest` dist-tag instead of the highest one

- src/cli/commands/run.js
- src/cli/index.js
**Summary**
Fixes #4615. Disabling all Yarn output in nested commands with `YARN_SILENT` is a bit much, we usually want to see the output. This pull request introduces a new environment variable `YARN_WRAP_OUTPUT` that can be set to `0` to disable the header and footer Yarn normally displays.
Disabling the header/footer might also be useful in other situations, like other tools calling Yarn, so the `YARN_WRAP_OUTPUT` variable has general use.
**Test plan**
Existing integration tests.
> feat(cli): Disable only header/footer in nested commands, not all output

- src/constants.js
**Summary**
Update the accepted semver range to not warn on unknown future versions of node.
**Test plan**
N/A since we don't want to add Node 9 into our build matrix just yet.
> fix(cli): Don't warn when running on node 9

- src/cli/index.js
**Summary**
Use `boolifyWithDefault()` to determine if environment variable values are `true` or `false`. This ensures that all environment variables interpret the same values the same way.
This changes the behavior of `YARN_SILENT` and `YARN_IGNORE_PATH` if they have "unexpected" values, all nonempty stings beside `"0"` and `"false"` are now interpreted as `true`. For example `YARN_SILENT=hello` was interpreted as `false` before, now it is `true`. This makes some sense since those values are truthy in Javascript, but generally makes things more predictable if it works like that for all yarn environment variables.
`YARN_SILENT=true` was also interpreted as `false`. This now definitely makes more sense since it will be interpreted as `true`.
See also …
> fix(config): Use boolifyWithDefault() for bools from environment

- __tests__/commands/list.js
- __tests__/constants.js
- src/cli/commands/list.js
- src/constants.js
**Summary**
[config.js](https://github.com/yarnpkg/yarn/blob/389e02979a1ffe803ab95cbea1ad7b6bcdfa42a7/src/config.js#L336) determines if yarn runs in a production environment and sets a `production` config variable accordingly. The list command wants to know if it runs in a production environment and uses `isProduction()` to do so, which does look at environment variables, slightly different than the code in `config.js`, leading to inconsistencies in some corner cases. It should just use `config.production` instead.
`isProduction()` isn't used anywhere else and `config.production` should always be preferred, so I removed the whole function. I planned to adapt the tests of `isProduction()` for `config.production`, but the [existing …
> chore(config): Use config.production instead of isProduction()

- .travis.yml
**Summary**
We have some flakiness on our macOS Node 6 builds with ENOSPC errors so increase the RAMDISK size to
avoid these.
**Test plan**
TravisCI macOS builds should pass.
> ci(travis): Increase RAMDISK size for macOS builds

- .circleci/config.yml
**Summary**
CircleCI is not deploying the build artifacts anymore. This PR tries to fix that by using the `only` field to explicitly say that the deploy should run on master (not sure it will have an effect).
https://circleci.com/docs/2.0/workflows/#branch-level-job-execution
cc #4271
> ci(circle): Run deploy tasks on master branch

- .circleci/config.yml
**Summary**
After Yarn 1.0, the `--` separator to pass arguments to run scripts is no longer necessary. We still
have it in our CircleCI config and this patch removes it since Circle CI now uses Yarn 1.1.0+
**Test plan**
CircleCI builds should pass without any warnings or errors.
> ci(circle): Remove unnecessary `--` from test-ci invocations

- .circleci/config.yml
**Summary**
This PR fixes the deploy job to only run for version tags. It also renames it to "Publish" to convey
the actual task being performed since this job only publishes to NPM. Everything else is handled by
our webhooks.
Source: https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
**Test plan**
Builds on master should be fixed and when something is tagged, it should be deployed to NPM.
> ci(circle): Fix deploy job so it only runs on version tags

- __tests__/registries/npm-registry.js
- src/registries/npm-registry.js
**Summary**
Fixes #4650.
Problem is that Verdaccio (and probably Sinopia2) both are affected as they do not return "repository" nor "homepage" in top level data structure.
**Test plan**
Added new test cases. Also, manually tested with and without https://github.com/verdaccio/verdaccio as registry.
> fix: Use wanted package repository URL and homepage from npm

- README.md
**Summary**
We have stopped building on TravisCI so remove the badge from README.
**Test plan**
Make sure the README is still in a good shape.
> docs(readme): Remove Travis badge

- __tests__/commands/workspaces.js
- src/cli/commands/index.js
- src/cli/commands/workspaces.js
- src/reporters/buffer-reporter.js
**Summary**
Adds a command name `workspaces` that display useful data about the workspaces layout. Can be used for debugging, or for integrating other tools on top of Yarn itself. Currently only expose the two following information, but can be easily expanded if we need to add more fields:
- Workspace name
- Workspace location
**Test plan**
Added an automated test.
> feat(workspaces): Adds a `workspaces` command

- src/cli/commands/access.js
**Summary**
The help and error output for `yarn access` command was confusing and not clear about it not being implemented yet. This PR makes it clearer.
Before:
```
yarn access v1.3.2
error Usage:
error yarn access access public [<package>]
error yarn access access restricted [<package>]
error yarn access access grant <read-only|read-write> <scope:team> [<package>]
error yarn access access revoke <scope:team> [<package>]
error yarn access access ls-packages [<user>|<scope>|<scope:team>]
error yarn access access ls-collaborators [<package> [<user>]]
error yarn access access edit [<package>]
error Invalid subcommand. Try "public, restricted, grant, revoke, ls-packages, ls-collaborators, edit"
info Visit https://yarnpkg.com/en/docs/cli/access for documentation about this command.
```
After: …
> docs(access): Fix the help output for the skeleton `access` command

- src/cli/commands/global.js
**Summary**
Fixes https://github.com/yarnpkg/yarn/issues/4500#issuecomment-342616138.
The global subcommands currently only allow flags from the two places below to be passed from the CLI
https://github.com/yarnpkg/yarn/blob/8918b6cff99e037f3ab56523ebfde96e0c19cdae/src/cli/index.js#L65-L113 and https://github.com/yarnpkg/yarn/blob/8918b6cff99e037f3ab56523ebfde96e0c19cdae/src/cli/commands/global.js#L289
which meant [by the time it gets to upgrade interactive](https://github.com/yarnpkg/yarn/blob/8918b6cff99e037f3ab56523ebfde96e0c19cdae/src/cli/commands/upgrade-interactive.js#L37-L38), commander didn't correctly pass in `latest` as a valid key in the flags object. As a result, whenever `yarn global upgrade-interactive` was called, `--latest` was ignored.
**Test plan**
This is a pretty low …
> Add latest flag to global upgrade interactive

- __tests__/integration.js
**Summary**
We had a test using left-pad without pinning its version and since now there's a new version of
left-pad, the snapshots are failing. This PR fixes the issue by pinning the version of left-pad in
the test.
**Test plan**
Tests should pass.
> test(integration): Fix left-pad version used in a test with snapshots

- src/util/request-manager.js
**Summary**
Fixes #4885. In #4761 I started always passing the proxy to the `request` library to prevent it from falling back to env vars HTTPS_PROXY and HTTP_PROXY. At the time I thought that Yarn would pick up these env vars through its config system and pass them down itself.
It turns out this was not true and caused #4885. Now handling an explicit `false` in the request-manager to allow it to override the `https_proxy` if set. Otherwise, resume allowing request library to pick up the env vars.
**Test plan**
Manually tested. Since the actual requests are proxies under unit test, this is difficult to unit test.
> fix(request) Fix https_proxy env var

- __tests__/commands/pack.js
- __tests__/fixtures/pack/glob-dotfile/a.js
- __tests__/fixtures/pack/glob-dotfile/index.js
- __tests__/fixtures/pack/glob-dotfile/package.json
- src/cli/commands/pack.js
- src/util/filter.js
**Summary**
This makes globs in the files array in package.json and in .*ignore files match dotfiles, consistent with npm's behavior and how git processes .gitignore lines.
**Test plan**
See automated test.
> fix(pack): make globs match dotfiles

- .eslintignore
**Summary**
`build-dist` generates a `packages/lockfile/index.js` file that eslint should ignore.
**Test plan**
Run `yarn build-dist`, then `yarn lint`, and expect not to see a ton of errors.
> chore(eslint): ignore packages dir

- src/cli/index.js
**Summary**
This is to fix https://github.com/yarnpkg/yarn/issues/4983 to prevent the firewall popup on Mac OSX.
**Test plan**
Ran the following tasks
```bash
yarn run test
yarn run lint
```
Also validated that the popup no longer occurs by setting the alias
`alias yarn="node /path/to/my/yarn/lib/cli/index.js"`
and running `yarn install --mutex network`
> fix: connectionOptions passes in localhost as its host to prevent pop up on MacOsx

- src/cli/index.js
fixes #5021
**Summary**
Added a help line to the commander output for the `--json` flag.
I didn't see any mention of `--json` on the website docs (nor are any of the "use anywhere" flags really documented) so I didn't make any changes there.
> Add help comment to --json flag

- __tests__/commands/add.js
- src/cli/commands/add.js
**Summary**
Fixes #4978
Previously, there was logic in add command that [uses user-specified range out of the box](https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/add.js#L71-L72), resulting in the issue above. For example, if the user ran `yarn add left-pad@1.0.0` the pattern parser skipped `--exact` or `--tilde flags`, as well as saved prefix config options.
This change updates it so that if the user specifies a valid numeric version, then these flags still have an effect. These cases don't cover `yarn add left-pad@~1.0.0` or `yarn add left-pad@^1.0.0` since I think the confusion only arises from when the user enters `exact` pattern (just the number).
**Test plan**
Added a test case that fails on master
> fix(add): Make semver flags compatible with versioned requests

- .circleci/config.yml
**Summary**
We had a tiered cache key setup for some reason (probably remnant of the pre-macOS builds config) which was breaking macOS builds when a new dependency was introduced due to common install was done on a Docker machine and cached with a key including the architecture. This patch changes that and ties everything to a single cache key.
**Test plan**
CircleCI builds should pass without issues.
> ci(circle): Fix cache key setup for proper node_modules sharing

- __tests__/integration.js
**Summary**
We don't expect any warnings when installing high-profile and well-tested packages like
react-scripts so we have an integration test that enforces 0 warnings. Unfortunately a package got renamed and started producing a warning about this so the tests started failing. This PR relaxes the test to only fail on peer dependency warnings.
**Test plan**
All builds and tests should pass.
> test(integration): Fix react-scripts test due to unexpected warning

- __tests__/util/git.js
- src/util/git.js
Fixes #5077
**Summary**
Added a regex to filter output lines from `git ls-remote`.
**Test plan**
Modified mock `git ls-remote` output to include an additional line of output 
Ran `yarn run test`
Tested install on local application
> fix(git): Ignores irrelevant output from ls-remote

- bin/yarn
**Summary**
_To be a good citizen of UNIX ecosystem._
One may write a script to add `$(yarn global bin)` to `$PATH`, but one must consider different cases depending on what this command returns in STDOUT. This is not ideal. 
And, of course, error messages such as this naturally belongs to STDERR.
**Test plan**
```sh-session
$ yarn global bin 2>/dev/null
$
```
> fix(cli): Write Node4+ error message to stderr

- __tests__/resolvers/exotics/hosted-git-resolver.js
- src/resolvers/exotics/hosted-git-resolver.js
**Summary**
The GitHub resolver incorrectly removes `.git` from anywhere in the project name. For examplee, the project `linagora.esn.unifiedinbox.github` becomes `linagora.esn.unifiedinboxhub`. The GitHub resolver should only remove `.git` from the end of the name.
Fixes #5117 
**Test plan**
* Run `yarn add lenagora/linagora.esn.unifiedinbox.github`
* Observe that the package is installed and no error is shown
> fix(cli): allow GitHub project names that contain the string .git (#5117)

- __tests__/commands/run.js
- __tests__/fixtures/run/script-shell/package.json
- src/cli/commands/run.js
- src/util/execute-lifecycle-script.js
**Summary**
This fixes issue #4248, based off of [what NPM does](https://github.com/npm/npm/blob/07d2296b10e3d8d6f079eba3a61f0258501d7161/lib/utils/lifecycle.js#L264).
**Test plan**
I'm not actually sure how to write a test suite for this (as testing any alternate shell would involve additional installations), but it passes all of the current tests. Any feedback/advice would be appreciated!
Here's how I am manually confirming that the change works (see the `echo $SHELL` output):
The Windows terminal emulator (which I am using) doesn't support emojis, which causes the weird characters before the Done message. However, MinTTY should.
>  feat(cli): allow running scripts with custom shell (#4248)

- __tests__/util/git/git-ref-resolver.js
- src/util/git/git-ref-resolver.js
**Summary**
NPM supports git URLs with this format: `git+ssh://git@github.com:npm/npm#semver:^5.0` and yarn currently does not. This works in yarn without the word `semver`. This updates yarn to accept either format.
Fixes #5126 
**Test plan**
1. Run `git+ssh://git@github.com:npm/npm#semver:^5.0`
2. Observe that the package is installed and no error is shown
> fix(cli): improve support for semver in git URLs (#5126)

- __tests__/package-resolver.js
**Summary**
OCaml repos has been moved so URLs had to be updated. 
I have also extended timeout from 60 s to 90 s because 2 out of 9 test runs failed with default value on my machine while fetching OCaml. By tweaking this value I have achieved 100% success rate.
> test(package-resolver): fix hash and no ".git" extension tests

- src/config.js
- src/reporters/lang/en.js
**Summary**
Display a helpful error message if `workspaces` in `package.json` is not an array. Currently just displays: `error An unexpected error occurred: "patterns.map is not a function".`
Fixes #5089 
**Test plan**
* Create a `package.json` file with `workspaces: "packages/*"`
* Run `yarn` and observe that this error message is shown: `The workspaces setting in package.json must be an array.`
> fix(cli): check if workspaces setting in package.json is an array (#5089)

- src/reporters/lang/en.js
Remove ambiguity in the warning message, to clarify that answering "yes" to all questions may have security implications, not that all questions which may have security implications will be answered with "yes".
> Add comma to yesWarning text

- src/reporters/lang/en.js
- src/resolvers/exotics/file-resolver.js
**Summary**
Improve the error message when the file resolver can't find the specified file.
**Test plan**
* Create a `package.json` with a dependency that points to a non-existent file (`file://noexist`)
* Run `yarn`
* Observe that the error message says what the problem is and provides a command to resolve the issue
> feat(cli): improve error message when file resolver can't find file (#5134)

- __tests__/commands/__snapshots__/licenses.js.snap
- src/cli/commands/licenses.js
**Summary**
Group packages by license when running `yarn license list` as requested in #5074.
**Test plan**
Run `yarn license list` in an existing package and observe that packages are grouped by license.
> feat(cli): group by license in licenses list (#5074)

- src/cli/commands/licenses.js
- src/types.js
- src/util/normalize-manifest/fix.js
**Summary**
Include NOTICE file (if present) along with LICENSE when running `yarn licenses generate-disclaimer`.
Fixes #5072 
**Test plan**
* Create a package and add `json2array` (or any package with a NOTICE file) as a dependency
* Run `yarn licenses generate-disclaimer` and observe that the NOTICE text is included after the LICENSE text
> feat(cli): include notice with license when generating disclaimer (#5072)

- __tests__/util/guess-name.js
- src/util/guess-name.js
**Summary**
Improve guessing of package names that contain a dot. It was reported that the `scottoffen/jquery.toaster` package from GitHub was being saved as `jquery`. With this change that package is now saved as `jquery.toaster`.
Fixes #5102 
**Test plan**
1. Run `yarn add scottoffen/jquery.toaster`
2. Look in `node_modules` and observe that the package is saved as `jquery.toaster` instead of just `jquery`
> fix(cli): improve guessing of package names that contain a dot (#5102)

- .circleci/config.yml
- src/util/execute-lifecycle-script.js
**Summary**
With this `yarn` will be able to discover and use the `node-gyp` from the homebrew installed `npm` on macOS instead of falling back to globally installing `node-gyp` every time a native addon needs to be compiled from source.
Homebrew installs a clean copy of `npm` inside a `libexec` folder together with `node`. Previously yarn didn't look there when trying to locate `node-gyp` and the `globally install node-gyp`-fallback would be used every time when building native addons with a yarn version from homebrew.
This PR adds the `libexec` path of `node-gyp` from homebrew to the `node-gyp` search paths of yarn, making it possible to compile native addons using the homebrew npm provided `node-gyp` with yarn without relying on this fallback.
**Test plan**
This can't be tested outside …
> fix(install): use node-gyp from homebrew npm

- src/cli/commands/upgrade-interactive.js
**Summary**
`upgrade-interactive` was updating the `package.json` in the current directory (where Yarn was run) instead of where the upgrades were made. The most notable occurrence of this was `global upgrade-interactive`, but it also happened by using the `--cwd` option.
When the location was not a workspace, it resolved to the current directory instead of using the previously configured one. Additionally, `config.cwd` was changed without being cleaned up, so it contained the last processed workspace, which affected anything that used it afterwards (e.g. symlinking binaries).
Fixes #4728 
Fixes #4952 
Fixes #4922 
**Test plan**
Install any package globally, then upgrade it interactively without being in the global directory. (or with `--cwd`). The binary of the package that is being …
> fix(cli): Use correct directory for upgrade-interactive

- __tests__/resolvers/exotics/registry-resolver.js
- src/resolvers/exotics/registry-resolver.js
**Summary**
Yarn already supports aliasing a scoped package with an unscoped package:
```bash
yarn add @goodforonefare/left-pad@npm:left-pad@1.2.0
```
This PR adds support for aliasing any package with a scoped package:
```bash
yarn add left-pad@npm:@goodforonefare/left-pad@1.2.0
```
Note: the only documentation I can find for this feature [is a tweet from Sebastian McKenzie](https://twitter.com/sebmck/status/873958247304232961?lang=en).
**Test plan**
* `cd` to a yarn-managed repo
* Add a scoped alias for `left-pad`:
* `yarn add left-pad@npm:@goodforonefare/left-pad`
* Verify that `left-pad` calls append my username to inputs:
```
$ node -e "console.log(require('left-pad')('test', 20))"`
GoodForOneFare                test
```
> Allow scoped package as alias source

- src/package-request.js
- src/reporters/lang/en.js
**Summary**
When a package is not found during installation, show which package is requiring it (if any) in the
error message. If there is no parent request, throw the same error as before.
Add new localized string 'requiredPackageNotFoundRegistry' which is the same 'packageNotFoundRegistry', but includes the parent package pattern. 
Add isMessageError boolean value to MessageError class to distinguish
between errors thrown by yarn from errors thrown by yarn dependencies.
**Test plan**
Use a workspace with at least 2 packages `foo` and `bar`. `bar` depends on `foo`. If you manually bump the package version of `foo`, running the install command will fail because the npm registry doesn't have the latest `foo` version that was just created. 
**Error shown (Before)**
**Error shown (After)** …
> feat: better error when package is not found

- __tests__/commands/add.js
- src/config.js
- src/reporters/lang/en.js
Add an error when the working directory doesn't exist (most probably when `--cwd` option points to the wrong directory)
As a side effect, this PR detects typo in one of the tests. Path "non-packages" should be "non-package". That test was passing because the yarn was creating target directory.
**Test plan**
`yarn add bluebird --cwd /wrong-path`
current behavior: creates `/wrong-path` directory
expected: Error message
> feat(cli): error on missing workspace directory (#5206)

- bin/yarn.js
Since node 0.10.x doesn't support process.exitCode, use process.exit for terminating when yarn is incompatible.
**Summary**
Fixes https://github.com/yarnpkg/yarn/issues/5258
We have a rule to not use process.exit whenever possible, but since this particular command is specifically for determining node version compatibility (currently we don't support 0.12.x or 0.10.x) we should default back to process.exit.
**Test plan**
run `yarn` on node .10.x then `echo $?`
> fix(CLI): Use process exit instead of exitCode for node < 4

- __tests__/hooks.js
- src/cli/commands/install.js
- src/util/hooks.js
**Disclaimer:** This is NOT a public feature, we reserve the right to change it as we wish, including between patch releases.
---
This PR adds a very basic and undocumented hook system. I plan to use it internally to get better
stats on how Yarn performs, and how much time is spent on the linking step.
**Test plan**
I tested this PR by adding the following code to the beginning of a custom build:
```js
let trace = name => {
return async fn => {
let x = Date.now();
let r = await fn();
console.log(`step ${name}: ${Date.now() - x}`);
return r;
};
};
global.experimentalYarnHooks = {
resolveStep: trace('resolve'),
fetchStep: trace('fetch'),
linkStep: trace('link'),
buildStep: trace('build'),
};
```
More comprehensive tests are on their way.
> feat(install): Implement a very basic hook system

- README.md
**Summary**
The horizontal rule had no empty space between it and the previous paragraph, and as such was rendered as '---' in the markdown, rather than the intended horizontal rule.
This is not a substantial feature pull request.
Motivation: it will look better.
**Test plan**
Not relevant.
> Horizontal rule fixed in README

- __tests__/util/user-dirs.js
- src/constants.js
- src/util/rc.js
- src/util/user-dirs.js
This implements:
* Supporting user-defined environment variables adhering to the [XDG
Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html)
to override yarn's defaults
* Supporting equivalent environment variables on Windows such as
%LOCALAPPDATA%
* More conventional defaults for these locations according to the
operating system.
* Support for the user defined config dir in the `.yarnrc` lookup path
* Storing global modules in a data-oriented location rather than a
config location (seeing this is actually what motivated this PR)
Concerns:
* Existing Windows config locations will break. This probably need to be
addressed with a migration path and/or a breaking change
* A few notes included in comments (will highlight these with inline GH
comments)
* …
> RFC: feat(config): Use more conventional paths for config and data

- __tests__/registries/npm-registry.js
- src/reporters/lang/en.js
- src/resolvers/registries/npm-resolver.js
**Summary**
Running yarn add to install an unpublished version produces an error message suggesting that the response is malformed and the registry may be down. This fix adjusts the error to indicate that no valid versions were found. This also brings the feature more in line with the `npm install` spec.
Fixes #5311 
**Test plan**
Running:
```
$ yarn add x-iterable-tree
```
Produces:
```
yarn add v1.4.1
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
error No valid versions found for "x-iterable-tree". The package may be unpublished.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
> fix(cli): report no valid versions for unpublished packages (#5311)

- src/registries/npm-registry.js
**Summary**
Minor refactor of isRequestToRegistry logic for readability. Pointed out by @arcanis over here: https://github.com/yarnpkg/yarn/pull/5216#discussion_r161489376.
**Test plan**
Nothing functionality changed, relying on existing test suite.
> Minor refactor of isRequestToRegistry logic for readability

- __tests__/commands/version.js
- __tests__/index.js
- src/cli/commands/login.js
- src/cli/commands/publish.js
- src/cli/commands/version.js
- src/reporters/lang/en.js
**Summary**
Running `publish` with `--non-interactive` should not prompt for input and should fail if required args like `--new-version` are not provided.
Fixes #5002 
**Test plan**
* Run `yarn publish --non-interactive` and see error message about not providing `--new-version`
* Delete NPM token, run `yarn publish --non-interactive --new-version=1.0.1` and see error message about not being able to ask for login due to `--non-interactive` flag
> chore(cli): don't ask questions during publish when --non-interactive is specified (#5002)

- __tests__/package-compatibility.js
- src/package-compatibility.js
**Summary**
Addresses #2172 
When trying to run a prerelease version of yarn, packages that specify versions of yarn in their engine requirements in package.json cause installation to fail. When running prerelease versions of yarn, you most likely don't want this engine check to fail because you have already signed up for potentially unexpected behavior by using a prerelease version.
**Test plan**
[rollup-plugin-rebase](https://github.com/sebastian-software/rollup-plugin-rebase/blob/master/package.json) has an engine requirement of `>=1.0.0`
Install nightly build (1.4.1-20180211.2236)
`yarn add rollup-plugin-rebase`  (fails engine check)
alias local copy of yarn (1.4.1-20180208.2355)
`yarn add rollup-plugin-rebase`  (success)
> break semver for engine check by allowing prereleases

- src/resolvers/registries/npm-resolver.js
**Summary**
When prompting the user to select a package version to install sort the options by version number.
Closes #5220
**Test plan**
* Create a package and add `"@types/react": "15.4.0"` (or another non-existent package version) to `package.json`
* Run `yarn` and when prompted to select a package version observe that the list is sorted by version (according to semver rules) in descending order
> feat(cli): sort by version when asking user to select a package version (#5220)

- gulpfile.js
**Summary**
Add `sourceRoot` to sourcemaps config in the gulpfile.js. Fixes: #5319.
Without this a developer who wants to debug the yarn src would have to manually configure a mapping between the lib/**/*.map files and the src/**/*.js files so that the breakpoints get hit. With this fix this manual configuration step is not necessary.
**Test plan**
```shell
yarn run build --sourcemaps
rg -i "sourceRoot" lib/*.map # should get some output from ripgrep listing sourceRoots in .map files.
```
> fix(build): add sourceRoot to sourcemaps

- src/reporters/base-reporter.js
**Summary**
Fixes #4158
This issue would occur, for example; while during a `yarn install` there was a `node-gyp` error - the line breaks would remain literal "\n". Example log of this:
```
/usr/src/app/node_modules/drivelist: Error: Command failed.\nExit code: 1\nCommand: prebuild-install || node-gyp rebuild\nArguments: \nDirectory: /usr/src/app/node_modules/drivelist\nOutput:\nprebuild-install info begin Prebuild-install version 2.5.1\nprebuild-install info looking for local prebuild @ prebuilds/drivelist-v5.2.12-node-v57-linuxmusl-x64.tar.gz\nprebuild-install info npm cache directory missing, creating it... \nprebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/https-github.com-resin-io-modules-drivelist-releases-download-v5.2.12-drivelist-v5.2.12-node-v57-linuxmusl …
```
> Added logic to correctly print stringified linebreak chars

- src/cli/commands/index.js
- src/cli/commands/node.js
- src/cli/index.js
**Summary**
This PR implements a new command called `yarn node`. It is meant to call Node with the correct environment to run the application. The main difference with running Node directly is that Yarn will automatically "cd" to the right directory.
**Test plan**
I manually ran the following commands and checked their outputs:
```
yarn node
yarn node -p 42
yarn node -- -p 42
yarn node script.js
```
I haven't written unit tests for this feature because it is relatively small and self-contained, and because I'm currently designing a new architecture for our tests, which will include tests for this feature. I prefer to spend time on this 🙂
> Implements "yarn node"

- __tests__/commands/add.js
- __tests__/commands/remove.js
**Summary**
Running the tests did, for some test cases, show yarn command output like `[1/4] Resolving packages...`. This pull request captures the command output instead of printing it to the console, the same way as this is done in many other test cases.
Unnecessary command output during testing makes the tests noisy. We are mostly only interested in test success or failure messages, not all the details of all the commands that run internally. Even *if* the command output were interesting, it usually should be captured and tested in the test, not written to console.
**Test plan**
The tests still pass, just with less random console output.
> Remove unnecessary console output when running test cases

- __tests__/commands/workspaces.js
- __tests__/fixtures/workspace/run-basic/packages/workspace-child-2/package.json
- src/cli/commands/workspaces.js
**Summary**
Running `yarn workspaces info` will now yield information to reconstruct the workspace dependency tree. This information can then be feed to other build systems.
**Test plan**
Updated the tests to include the new fields
> Improves "yarn workspaces info"

- __tests__/commands/__snapshots__/info.js.snap
- __tests__/commands/info.js
**Summary**
`yarn info` tests were broken due to some registry changes. This patch updates the tests to use an
older package, left-pad to get master green.
**Test plan**
Fixes tests. All builds should pass.
> test(info): Fix failing `yarn info <package> readme` tests

- scripts/build-chocolatey.ps1
**Summary**
Currently, the Chocolatey build is failing: https://github.com/yarnpkg/yarn/issues/5416
```
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At C:\Jenkins\workspace\yarn-chocolatey\scripts\build-chocolatey.ps1:44 char:1
+ Invoke-WebRequest -Uri $url -OutFile $installer_file
```
Github appears to have started enforcing TLS 1.2 at some point: https://www.ssllabs.com/ssltest/analyze.html?d=github.com
However, PowerShell uses TLS 1.0 by default. This causes an error when loading from GitHub via `Invoke-WebRequest`:
```
PS C:\Users\danlo> Invoke-WebRequest -Uri https://github.com/
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:1
+ Invoke-WebRequest -Uri https://github.com/
+ …
```
> Enforce usage of TLS 1.2 when building Chocolatey package

- __tests__/commands/pack.js
- __tests__/fixtures/pack/include-files-ignored-in-other-directories/a.js
- __tests__/fixtures/pack/include-files-ignored-in-other-directories/ignoring/.gitignore
- __tests__/fixtures/pack/include-files-ignored-in-other-directories/ignoring/file.js
- __tests__/fixtures/pack/include-files-ignored-in-other-directories/index.js
- __tests__/fixtures/pack/include-files-ignored-in-other-directories/package.json
- src/util/filter.js
**Summary**
Fixed the bug from #5407 and #2603.
The function `matchesFilter` returned `true` if the file's relative path or its basename matched the given regular expression. I adjusted this to only test the basename for a match if the `base` option is not set (or set to `.`).
**Test plan**
I added the test `pack should include files only ignored in other directories`.
Two tests were failing on my local build, but they were also failing before making the changes. All other tests were green.
> Restrict .gitignore to their own subdirectories

- src/reporters/lang/en.js
Previously, we are using the word "module" and "package" somewhat interchangeably.
However, [the web page for `yarn link`](https://yarnpkg.com/lang/en/docs/cli/link/) talks about linking a "package" consistently.  The same goes for [`yarn unlink`](https://yarnpkg.com/en/docs/cli/unlink); it doesn't even mention the word module.
I believe we should change these strings in accordance to the naming already in use at the web page; the way it is now is a bit confusing and inconsistent to our users.
> yarn link: Use "package" consistently

- __tests__/commands/check.js
- src/reporters/base-reporter.js
- src/reporters/lang/en.js
**Summary**
As of the current stable version, yarn fails with an internal error when `yarn check --integrity` is run in an environment where the Node version is different from the one listed in the integrity file. This happens because a language key is missing:
```
$ node --version
v9.2.0
$ yarn check --integrity
yarn check v1.3.2
success Folder in sync.
✨  Done in 0.12s.
$ nvm use stable
Now using node v9.6.1 (npm v5.6.0)
$ yarn check --integrity
yarn check v1.3.2
error An unexpected error occurred: "Unknown language key integrityNodeDoesntMatch".
info If you think this is a bug, please open a bug report with the information provided in "/Users/wabain/code/yarn/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```
The …
> Add message for integritySystemParamsDontMatch

- src/cli/commands/publish.js
**Summary**
This is a fix for #2717 
Do not check for content in publish response - 201 and 202 are successful as well - as discussed in the thread.
This should fix support for 3rd party repositiories.
**Test plan**
Publish on VSTS code works correctly after this fix.
[3/4] Publishing...
verbose 0.691 Performing "PUT" request to "https://<mycompany>.pkgs.visualstudio.com/_packaging/<myrepo>/npm/registry/<mypackage>".
verbose 5.55 Request "https://<mycompany>.pkgs.visualstudio.com/_packaging/<myrepo>/npm/registry/<mypackage>" finished with status code 202.
success Published.
Republish which should fail is still failing correctly:
[3/4] Publishing...
verbose 1.06 Performing "PUT" request to "https://<mycompany>.pkgs.visualstudio.com/_packaging/<myrepo>/npm/registry/<mypackage>".
verbose …
> Do not check for content in publish response

- __tests__/commands/__snapshots__/licenses.js.snap
- __tests__/commands/licenses.js
**Summary**
There is [a test][testcase] that attempts to test that license files are show correctly for `yarn licenses generate-disclaimer`. The test currently just prints the license files to the console and doesn't verify what was printed. This pull request modifies the test to not show unwanted output during testing and to actually test that the output is correct.
**Implementation**
The normal method of capturing output isn't sufficient to capture the output of `yarn licenses generate-disclaimer`, since that command [intentionally][1] uses `console.log()` directly. Because of this a special helper function is used that mocks `console.log()` and lets the test verify what was written.
**Test plan**
The `licenses.js.snap`, which is used to verify the commands output, now contains the …
> Fix test for `yarn licenses generate-disclaimer` output

- __tests__/util/conversion.js
- src/cli/index.js
- src/util/conversion.js
**Summary**
This adds tests for `boolify()` and `boolifyWithDefault()`. It also fixes a bug in `boolify()` discovered in the process: the number `0` should evaluate to `false`, not `true`. 
The functions are moved from cli/index.js to util/conversion.js since they can be generally useful.
**Test plan**
Adding tests is the main point.
> test(util): Add tests for boolify() and boolifyWithDefault()

- src/cli/index.js
- src/reporters/base-reporter.js
**Summary**
This PR attempts to fic issue [5067](https://github.com/yarnpkg/yarn/issues/5067)
Currently `questionAffirm` in [base-reporter.js](https://github.com/yarnpkg/yarn/blob/master/src/reporters/base-reporter.js) is not prepared to handle the [`--non-interactive`](https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-non-interactive) flag. 
This PR makes it so that `questionAffirm` should, by default, handle the specification of this term by assuming the answer to be, for instance, yes. This would allow the implementation of user prompts more easily and in a cleaner manner.
**Please mention your node.js, yarn and operating system version.**
Non-applicable
**Test plan**
There are still some tests need, but I would like to get some feedback on the way of accessing …
> default option for report in non-interactive terminals

- .circleci/config.yml
- package.json
- packages/pkg-tests/yarn.test.js
**Summary**
This PR makes CircleCI run a test instance for the pkg-tests testsuite. It's currently only run on a Node 8 instance, but this can be improved later on.
**Test plan**
CircleCI
> Makes CircleCI run the pkg-tests testsuite

- packages/pkg-tests/package.json
**Summary**
Remove this from the output of running the pkg-tests testsuite:
**Test plan**
Manual check + CircleCI
> Disables jest-haste-map for the fixtures

- appveyor.yml
**Summary**
AppVeyor only has one container and runs all different tests sequentially, taking up to 50 minutes
for a full build. Node 4 will become obsolete next month and we don't really want to provide too
much support for Node 6 so this patch removes leaves only Node 8 on AppVeyor builds.
**Test Plan**
> ci(appveyor): Remove old Node builds from AppVeyor

- appveyor.yml
**Summary**
The coverage information in AppVeyor tests is completely useless and distracting so don't generate
it.
**Test plan**
Go look into AppVeyor build and make sure there's no coverage information there.
> ci(appveyor): Don't output coverage on AppVeyor

- __tests__/integration.js
- src/util/execute-lifecycle-script.js
**Summary**
Fixes #5481.
With #5133, we have stopped passing the command/script name to the shell properly. This patch makes
sure the proper escaping is done when not using the `script-shell` option.
This patch may also fix #5479.
**Test plan**
Added a new integration test.
> fix(run): Fix script running in paths with special chars

- __tests__/util/execute-lifecycle-script.js
- src/util/execute-lifecycle-script.js
This is #5409, but on a different branch because I fucked up.
> feature in npm: https://docs.npmjs.com/files/package.json#config
> 
> issue: https://github.com/yarnpkg/yarn/issues/2989
> 
> **Summary**
> 
> The goal of this PR is to allow the same feature as found in npm:
> 
> package.json
> 
> ```json
> "name": "yarn",
> "config": {
>     "whatever": "test"
> }
> ```
> 
> `yarn config set yarn:whatever production`
> 
> should make the environment variable
> 
> `npm_package_config_whatever === 'production'`
> 
> **Test plan**
> 
> Automated tests are incoming. Tested manually with `yarn env`.
> 
> Are these changes too much or is there a better way of accomplishing this?
> feat: allows yarn config set to override package.json config keys

- src/cli/index.js
**Summary**
In my opinion lockfile shouldn't be written at all into the error file (#5443) but this should be a simpler solution to that.
The stack trace is more important than the entire contents of the lock file, so I've moved it above it. As it's rather unnecessary to scroll to the end of the file to see the actual error.
**Test plan**
Run any command that produces an error (e.g. non existing command) to produce an error file.
> Write stacktrace in yarn-error.log sooner

- __tests__/util/semver.js
- src/util/color-for-versions.js
- src/util/semver.js
**Summary**
Fixes #4942.
The yarn CLI uses colors to indicate backwards compatibility for version updates in the `yarn outdated` and `yarn upgrade-interactive` commands. These can be confusing and also misleading for updates to unstable package versions (0.x.y & 0.0.x), as it doesn't match either the semver spec nor how both yarn and npm handle updates to these versions using caret-ranges. 
This change special-cases the diff calculation, along with the color representation, for updates to *unstable* package versions, to more accurately indicate the level of backwards compatibility.
For `0.x.y` versions, increments to the *minor* version number (`y`) will be considered a *major* version change, and increments to the *patch* version number (`x`), will be considered a *minor* version change. …
> fix(cli): adjust colors for unstable version updates

- .circleci/config.yml
**Summary**
Move e2e test to circle-ci,  Closing #4863 
**Test plan**
This pull request is about tests, so we are not testing the tests.
> move e2e test to circle-ci

- scripts/install-latest.sh
- scripts/update-homebrew.sh
- scripts/update-npm.sh
- src/cli/commands/install.js
This will let `curl` automatically to send `Accept-Encoding` header to include the compression methods such like `deflate`, `gzip`, etc, to request compressed data from server, and automatically decompress the data if it's compressed, I believe that this is very like(pretty the same) what commit 0829a745ae5d6948d939d0c181bbb7bb2cd1686a / PR #1083 did, will save the time and bandwidth on transferring data.
The output and other behavior should be the same as `curl` will automatically handle the process to add header and to decompress.
My first PR to this project, let me know if I need to revise/improve anything, thanks a lot!
> Enable curl `--compressed` option to speed up request

- flow-typed/npm/jest_v22.x.x_with_custom_matchers.js
**Summary**
Follow up to #5569.
**Test plan**
`yarn lint` should pass without errors.
> chore(jest): Upgrade Jest flow types

- appveyor.yml
**Summary**
Follow up to #5569. Jest 22.4.x mocks the process object without a proper stub for `process.mainModule`. In our lifecycle code, we try to set `env.npm_execpath` when it is not defined by
using `process.mainModule.filename`. When running tests on AppVeyor, we run Jest directly, thus we
don't have `env.npm_execpath` set, triggering the `process.mainModule` code path which is also not set,
causing tests to fail.
**Test plan**
AppVeyor builds should pass.
> ci(appveyor): Fix AppVeyor tests

- .gitignore
- .vscode/settings.json
**Summary**
looks like a .vscode/settings file has been accidentally checked in a few days ago (#5572). This file is only related to vscode and most vscode dev would probably prefer their own settings ;-). We should not need to keep it in the repo.
- removed settings.json 
- added `.vscode/` to .gitignore to prevent accidental checkin in the future.
**Test plan**
there is no code change.
> remove .vscode settings from repository

- __tests__/commands/install/workspaces-install.js
- __tests__/fixtures/install/workspaces-install-already-exists-deep/package.json
- __tests__/fixtures/install/workspaces-install-already-exists-deep/packages/a/node_modules/lol/package.json
- __tests__/fixtures/install/workspaces-install-already-exists-deep/packages/a/node_modules/lol/x/package.json
- __tests__/fixtures/install/workspaces-install-already-exists-deep/packages/a/package.json
- __tests__/fixtures/install/workspaces-install-already-exists-deep/packages/b/node_modules/lol/package.json
- __tests__/fixtures/install/workspaces-install-already-exists-deep/packages/b/node_modules/lol/x/package.json
- __tests__/fixtures/install/workspaces-install-already-exists-deep/packages/b/package.json
- src/config.js
- src/util/execute-lifecycle-script.js
**Summary**
address #5579 related to #3986/#3996: 
in order to prevent greedy workspaces.packages patterns to match unnecessary packages, #3996 added the `node_modules/*/package.json` pattern to exclude packages under the workspace package's node_modules folder. While sufficient for most use cases, it does not work for "deep" path such as "node_modules/X/Y/package.json". This PR replaced the shallow wildcard with globstar "**" so it will ignore **all** packages under the workspace package's node_modules folder.
- Config.js: replace the shallow ignore pattern with a deep pattern.
- execute-lifecycle-script: address when process.mainModule is undefined
- tests: the rest are all tests.
**Test plan**
both new and old tests should pass
> fix workspace packages ignore-pattern

- src/cli/commands/install.js
**Summary**
When ```experimental-pack-script-packages-in-mirror``` is set in conjunction with ```yarn-offline-mirror-pruning true```, prebuilt packages in /yarn-offline-mirror-dir/prebuilt/* are deleted.
Fixes #5614 from @bestander PR #5314.
**Test plan**
Should pass tests created for #5314 🤓
> Bugfix #5614: When offline pruning, don't unlink prebuilt packages.

- src/cli/commands/run.js
**Summary**
If user's answer contains leading spaces, the command will fail. Like:
```sh
> yarn run
...
question Which command would you like to run?:  start
error An unexpected error occurred: "Command \"\" not found.".
```
This PR add a `trim` operation to remove leading spaces
**Test plan**
> Remove leading spaces of `yarn run`'s answer

- __tests__/commands/workspace.js
- __tests__/fixtures/index/run-workspace/.yarnrc
- __tests__/fixtures/index/run-workspace/package.json
- __tests__/fixtures/index/run-workspace/packages/workspace-child-1/package.json
- __tests__/fixtures/index/run-workspace/packages/workspace-child-2/package.json
- __tests__/index.js
- src/cli/commands/workspace.js
- src/cli/index.js
fixes #5496
**Summary**
Previously, if flags were defined in .yarnrc then they would be inserted into the rawArgs array of
commander.js. The yarn workspace command would then attempt to pass these flags to the child process that it spawns. They were being passed out-of-order and causing the child command to fail to
properly parse it's command line args.
This change prevents those flags from being passed at all.
The yarn child process will read .yarnrc and inject the flags into it's own argument array anyway,
so passing them was just duplicating the flags.
**Test Plan**
No additional tests, existing tests pass.
> fix(config): Don't pass .yarnrc generated flags to workspace child command

- __tests__/commands/link.js
- __tests__/commands/unlink.js
- __tests__/fixtures/link/package-with-bin/package.json
- src/cli/commands/link.js
- src/cli/commands/unlink.js
**Summary**
fix #4772 
**Test plan**
existing and new tests should pass.
> fixed link and unlink cmd on windows (#4772)

- .babelrc
- __tests__/integration.js
- package.json
- yarn.lock
**Summary**
Fix for #5451, #5457.
The test case in the first commit fails for pre-node5 builds, in the way described in the links issues. The problem are classes deriving from `Error`, which are problematic in ES5 ([babel][babel-Error]). Adding `babel-plugin-transform-builtin-extend` fixes the issue in this case.
**Why now?**
The error surfaced because the [current yarn build published on npm][v1.5.1] is a pre-node5 build while for example [v1.3.1][v1.3.1] seems to have been created by the more modern build configuration. This can be seen by checking if code like "class A extends B" got compiled to ES5 or not.
[babel-Error]: https://babeljs.io/docs/usage/caveats/#classes
[v1.3.1]: https://registry.npmjs.org/yarn/-/yarn-1.3.1.tgz
[v1.5.1]: https://registry.npmjs.org/yarn/-/yarn-1.5.1.tgz
> Fix yarn behaviour when scripts are failing

- renovate.json
**Summary**
Renovate constantly nags us about pinning Docker image versions which we intentionally don't want to
(see #5622). This PR disables the whole Docker integration since we want our config to stay in this
very specific way for CI.
**Test plan**
Renovate should keep working but PRs like #5622 should not come back.
> ci(renovate): Disable Renovate Docker support

- jenkins_jobs.groovy
These tests are now being ran directly in CircleCI.
> Remove yarn-e2e from Jenkins

- package.json
- yarn.lock
**Summary**
Updating validate-npm-package-license in order to update its dependencies :
- spdx-correct
- spdx-license-ids
This is allowing us to use newer licences such as EUPL-1.2.
https://github.com/kemitchell/validate-npm-package-license.js/compare/v3.0.1...v3.0.3
https://github.com/jslicense/spdx-correct.js/compare/v1.0.2...v3.0.0
https://github.com/shinnn/spdx-license-ids/compare/v1.2.2...v3.0.0
> chore(deps): update dependency validate-npm-package-license to ^3.0.3

- __tests__/commands/upgrade.js
- __tests__/fixtures/upgrade/multiple-packages/package.json
- __tests__/fixtures/upgrade/multiple-packages/yarn.lock
- src/package-request.js
**Summary**
Fix for #5660
Before it needed to have package argument to enter the block to filter the deps. Now it will do it if either a package is given or a --pattern is given.
**Test plan**
Corrected my incorrectly created tests.
Also `is-negative-zero` would not update as there is no new version which would be found in a caret. So changed that to `array-union` which has a version `1.0.2`
> Fix for pattern not working with upgrade

- __tests__/commands/version.js
- __tests__/fixtures/version/no-args-no-git-hooks/.yarnrc
- __tests__/fixtures/version/no-args-no-git-hooks/package.json
- src/cli/commands/version.js
- src/registries/yarn-registry.js
**Summary**
Last year I contributed the ability to disable commit hooks when versioning with npm (See [this commit](https://github.com/npm/npm/commit/2dec601c6d5a576751d50efbcf76eaef4deff31e#diff-2992be03e25e9f38300b7ce175e4f4e1)). It makes sense to add the same functionality to yarn.
The original motivation for this feature is based on a pre-commit hook that included linting and testing a large code base, taking ~20 seconds to run. When that hook is run on the preceding commits, it's unnecessary and time-taking to do so on versioning. Because of that, it's nice to have the option to disable that git hook.
**Test plan**
Added lower level integration tests.
> feat(version): Ability to disable commit hooks on versioning

- __tests__/util/execute-lifecycle-script.js
- src/util/execute-lifecycle-script.js
**Summary**
`INIT_CWD` environment variable holds the full path you were in when you ran `yarn run`
Motivation: https://twitter.com/housecor/status/983773854530260992
**Test plan**
1. Create a script called `testscript.js`
2. In the file type `console.log(process.env.INIT_CWD);`
3. In `package.json` add a script with a key `testscript` and value `node testscript.js`
4. Build yarn
5. Call `../bin/yarn testscript` from the command line in a subfolder
6. The script should log the folder you're running the script from
Video: https://www.youtube.com/watch?v=XY_w8GVtuCY
**Test plan**
Added a new test.
> feat(run): Set `INIT_CWD` in environment

- __tests__/commands/version.js
- src/cli/commands/version.js
fixes #5670 
**Summary**
Currently, it's possible (although undocumented) to automatically bump the version by running something like `yarn version --loose-semver --new-version minor`. To me, this seems less convenient and less intuitive than something like `yarn version --minor` (closely comparable to `npm version minor`). I've added the ability to automatically increment the version with one of the flags: `--major`, `--minor`, or `--patch`. This will also satisfy feature request #5367.
**Test plan**
I've included Jest test cases for each of the new versioning flags.
> feat(version): Added semver versioning flags for convenience

- __tests__/util/git/git-ref-resolver.js
- src/util/git/git-ref-resolver.js
**Summary**
Fixes #1610. Previously yarn would allow a dependency on a GitHub pull request with "#1/head" where 1 is the PR number. npm allows the format "#pull/1/head" as well. For compatibility, allowing Yarn to fall back to this format.
**Test plan**
Added a test to `git-ref-resolver` to test the case `"pull/10/head"`
> fix(resolution): Allow github dependency refs of type "#pull/1/head"

- __tests__/commands/__snapshots__/init.js.snap
- __tests__/commands/init.js
- __tests__/index.js
**Summary**
We had an integration test relying on a specific version of a package without coding that version
into the test.
We also had some tests using snapshots with `test.concurrent` which are not safe to use per https://github.com/facebook/jest/issues/1630#issue-175391968. These were randomly failing, mostly on AppVeyor.
This PR fixes tests failing on master as of now.
**Test plan**
> test: Fix failing tests on master

- __tests__/commands/__snapshots__/init.js.snap
- __tests__/commands/init.js
**Summary**
Snapshots should not be used with `test.concurrent`. This PR fixes a
flaky test which was doing exactly this.
**Test plan**
> test(init): Fix flaky init test which used snapshots w/ concurrent

- src/registries/npm-registry.js
- src/util/fs.js
**Summary**
Fixes #5477 and #5704.
Remove usager of deprecated `Buffer`constructor to avoid ugly warnings on Node 10.
**Test plan**
Existing test should pass.
> fix: Removes usage of deprecated Buffer constructor. (#5477)

- __tests__/reporters/__snapshots__/console-reporter.js.snap
- __tests__/reporters/_mock.js
- __tests__/reporters/console-reporter.js
- src/reporters/console/console-reporter.js
**Summary**
This PR fixes #5721 where `upgrade` was not being silent when the `--silent`/`-s` flags were provided. It still printed the tree.  🖨🌳  
**Test plan**
Added two new test cases.
Manual CLI tests:
Before:
```
> yarn-local upgrade --silent
└─ left-pad@1.3.0
└─ left-pad@1.3.0
```
After:
```
> yarn-local upgrade --silent
```
> fix(console-reporter): Fix issue where tree logger was ignoring --silent/-s flag

- package.json
- src/cli/commands/install.js
- yarn.lock
**Summary**
In eab88b8 you introduced a new dependency on [deepequal](https://yarnpkg.com/en/package/deepequal). This is an immature module (v0.0.1) with 1.1k downloads in the last 30 days and whose github repo has seen no activity since on 2014-01-31.
I propose to replace that with [deep-equal](https://yarnpkg.com/en/package/deep-equal), which has had 11.6m downloads in the last 30 days.
This is not substantial, the two should be functionally equivalent for what you need.
**Motivation**: In creating a native Debian package for yarn (#1305), each new dependency is a pain because it has to packaged separately. We try to package only Node.js modules which make sense and are not duplicates of modules we already have (and we do have deep-equal, as …
> fix #5729: replace dependency on deepequal with deep-equal

- packages/pkg-tests/pkg-tests-core/sources/utils/fs.js
- packages/pkg-tests/pkg-tests-specs/sources/index.js
- packages/pkg-tests/pkg-tests-specs/sources/script.js
- packages/pkg-tests/yarn.test.js
- src/util/execute-lifecycle-script.js
**Summary**
This diff orders Yarn to run the lifecycle scripts with a PATH configured to offer in priority the same `node` binary used to run Yarn itself. This change makes Yarn more coherent since we were previously doing this for node-gyp.
**Test plan**
Added a test to pkg-tests
> Adds the directory that contains Node to the PATH

- __tests__/commands/bin.js
- src/cli/commands/bin.js
- src/reporters/lang/en.js
**Summary**
This allows to get the path to a binary without making assumptions regarding the layout of the
`node_modules` folder.
**Test plan**
Added a test.
> feat(bin): Implement an optional parameter support to `yarn bin`

- __tests__/commands/__snapshots__/run.js.snap
- __tests__/commands/run.js
- src/cli/commands/run.js
**Summary**
This pr fixes a bug ([#5655](https://github.com/yarnpkg/yarn/issues/5655)) in which `yarn run --non-interactive` prints a `Error: No command specified` message and also suppresses the message `question Which command would you like to run?:` when running non-interactively. 
**Test plan**
```
> yarn-local run --non-interactive
yarn run v1.6.0
info Commands available from binary scripts: acorn, atob, babylon, browserslist, commitizen, detect-libc, errno, escodegen, esgenerate, eslint, esparse, esvalidate, flow, git-cz, git-release-notes, gulp, gunzip-maybe, handlebars, import-local-fixture, jest, jest-runtime, js-yaml, jsesc, jsinspect, json5, loose-envify, miller-rabin, mkdirp, node-pre-gyp, nopt, prettier, rc, regjsparser, rimraf, sane, semver, sha.js, shjs, sshpk-conv, …
```
> fix(run): yarn run should never prompt when non-interactive

- package.json
- yarn.lock
**Summary**
These are a few upgrades of dependencies in order to address issues on node 10 (in relation to: https://github.com/yarnpkg/yarn/issues/5477)
*duplexify* *3.5.0* => *3.5.4* (https://github.com/mafintosh/duplexify/commit/00d08fa3f223e1c7d1c05e0350c236d1c4e32d09)
*v8-compile-cache* *^1.1.0* => *^2.0.0* (https://github.com/zertosh/v8-compile-cache/pull/7)
*natives* *1.1.0* => *1.1.3* (https://github.com/gulpjs/gulp/issues/2162)
The last did not have to do with `new Buffer` but was something I personally encountered when using `gulp` for building in `node 10`. I don't know how common this is, but the fix is easy and within scope, so decided to include it.
**Test plan**
CI should be green.
> chore(deps): update deprecated deps for node 10

- src/cli/commands/publish.js
- src/reporters/lang/en.js
**Summary**
When publishing a package with `yarn publish` fails, yarn catches the error and shows "Couldn't publish package.". That's not very useful to diagnose the problem.
With this change, it additionally shows the message of the caught error, for example for a truncated `.tgz` file:
> error Couldn't publish package: "https://registry.yarnpkg.com/somepackage: unexpected end of file"
**Test plan**
No actual functionality changed, only the error message got expanded. The tests still pass.
> Show error message to user when publishing fails

- src/config.js
**Summary**
This is a fix for #5776 where the `--scripts-prepend-node-path` CLI switch is ignored.  The code to wire this flag up in `src/config.js` was missing.
**Test plan**
Before: 
```
$ yarn run --scripts-prepend-node-path env | egrep 'NODE|PATH'
"NODE": "/usr/local/Cellar/node/8.1.0/bin/node",
"PATH": "/Users/brainfish/code/yarn/node_modules/.bin:...
```
After:
```
$ yarn run --scripts-prepend-node-path env | egrep 'NODE|PATH'
"NODE": "/usr/local/Cellar/node/8.1.0/bin/node",
"PATH": "/usr/local/Cellar/node/8.1.0/bin:/Users/brainfish/code/yarn/node_modules/.bin:...
```
> Fix #5776: CLI switch "--scripts-prepend-node-path" doesn't work

- __tests__/reporters/base-reporter.js
- src/reporters/base-reporter.js
This is my very first PR. So if there's any suggestions or if I'm missing anything, please advise 😀
**Summary**
This is the fix for [#5517](https://github.com/yarnpkg/yarn/issues/5517) where backlashes in the output in Windows are broken if the directory path contains "\n". The **stringifyLangArgs** method has been modified so that "\n" will only be replaced by EOL if it is not preceded by a "\\". 
**Test plan**
The test project path is C:\\Users\\An\\Documents\\Projects\\oss\\name\
Before
```
error An unexpected error occurred: "C:\\Users\\An\\Documents\\Projects\\oss\ 
ame\\package.json: Unexpected token U in JSON at position 139". 
```
After 
```
error An unexpected error occurred: "C:\\Users\\An\\Documents\\Projects\\oss\\name\\package.json: Unexpected token U in JSON at position …
```
> Fix #5517: Backlashes in output fail for escape sequences in Windows

- src/util/execute-lifecycle-script.js
**Summary**
A previous change removed the -c option that was passed to the shell, causing script like "echo foo"
to fail if script-shell was set to bash. This change cleans up the way custom shell is specified,
passing the shell to node's child process spawner instead of trying to make it part of our command
string. Doing it this way seems to account for the previously required -c flag.
fixes #5699 
**Test plan**
No test was added because our tests for the `yarn run` command use a mocked `execute-lifecycle-script`. Plus these tests would get run on windows too, so making a test that specified a config of `script-shell bash` would fail if it was unmocked.
Can be tested manually by creating a `.yarnrc` that contains:
```
script-shell bash
```
and adding a script like:
```
"scripts": { …
```
> fix(run): Fix custom shell execution

- jenkins_jobs.groovy
**Summary**
Homebrew changed how their `brew bump-formula-pr` script works, and it now requires a GitHub access token to be set as an environment variable instead of reusing the access token configured for "Hub" (https://hub.github.com/)
This updates the Jenkins job to pass a credential (the access token) to the script as an environment variable.
Closes #5861
**Test plan**
Make sure we can update formulas on Homebrew after the change.
> ci(brew): Pass access token to Homebrew job

- bin/yarn
**Summary**
Add a case in `bin/yarn` to run `cygpath` on the yarn base dir if the environment is MSYS.
Automatic path translation happens differently, or perhaps conditionally, depending on whether msys detects the target binary is a native Win32 application or not. While bash from Git for Windows seems to treat `winpty` as a Win32 binary, the version of `winpty` which is compatible with MSYS2 does not trigger the path conversion.
**Test plan**
`yarn` executed from within bash within MSYS2 correct executes, instead of failing with a path
related error. `yarn` continues to execute correctly from within Git Bash.
```
// Changes were made to system install to test more easily.
$ which yarn
/c/Program Files (x86)/Yarn/bin/yarn
akrieger@AKRIEGER-701 /c/Users/akrieger
$ yarn
yarn install v1.6.0 …
```
> Support MSYS{2} bash in bin/yarn

- __tests__/commands/install/bin-links.js
- __tests__/fixtures/install/install-link-siblings/bar/package.json
- __tests__/fixtures/install/install-link-siblings/foo/package.json
- src/package-linker.js
**Summary**
Fix #5876 . There was an error in the new bin link calculation logic when the bin folder was a symlink. The code would only look for a target installation of the package to be linked relative to the realpath of the bin folder, when it should also consider targets relative to the symlinked location of the bin folder and choose the closest overall location. Otherwise, it may fail to link.
**Test plan**
Added a new unit test which fails without this change. Based on [this reproduction](https://github.com/spalger/reproduce-issues/tree/master/yarn-reduce-of-empty-array-without-initial-value)
> fix bin links for link: protocol (fixes #5876)

- src/cli/commands/info.js
**Summary**
Right now tests are failing on master. 
The test that's failing: https://github.com/yarnpkg/yarn/blob/643deaa9673bcfe3afb41413572c0df2aa308e03/__tests__/commands/info.js#L135-L140
It fails here: https://github.com/yarnpkg/yarn/blob/643deaa9673bcfe3afb41413572c0df2aa308e03/src/util/request-manager.js#L392-L395
When this is rejected: https://github.com/yarnpkg/yarn/blob/643deaa9673bcfe3afb41413572c0df2aa308e03/src/cli/commands/info.js#L63
Checking out a commit from 1 month ago on master still fails at the same point. 
My guess is that this happens because in the past, the npm registry returned an empty body on 404, and now it returns a JSON with an error. I cannot confirm this however. Since this is a pretty simple fix, I thought there's no need to go deeper.
**Test plan**
CI …
> fix(info): handle 404 with non-empty body

- src/cli/commands/info.js
**Summary**
#5903 added support for exceptions thrown by the npm request, but changed handling of empty responses. They are now an invariant violation instead of an expected error reported as `infoFail`.
But empty responses [can still happen][1]. I assume they should continue to be handled like they were before #5903. This pull request makes this change.
**Test plan**
Tests should still pass and hopefully more reliably than before.
[1]: https://circleci.com/gh/yarnpkg/yarn/16689
> fix(info): report empty npm response with `infoFail` again

- __tests__/commands/add.js
- src/resolvers/registries/npm-resolver.js
This is a rebase of https://github.com/yarnpkg/yarn/pull/4820, which fixes #4818.
cc @arcanis
> Fix offline npm cache resolve for scoped packages (rebased)

- __tests__/fetchers.js
- src/util/fs.js
**Summary**
The error messages caused by TarballFetcher are supposed to contain the name of the offending file. The name is taken from the streams `path` attribute, but since a recent change this attribute is empty.
This PR populates the attribute again and tests that the path is actually mentioned in the TarballFetcher error messages.
**Test plan**
Existing tests have been modified to be stricter than before and test for this problem.
> Make sure TarballFetcher error messages contain names of problematic files

- __tests__/integration.js
- src/registries/yarn-registry.js
**Summary**
Relative cache paths set in the yarnrc file are currently resolved relative to the cwd (even worse - the actual cwd, not the typical `cwd` from our codebase, which equals the project path). They should instead be resolved relative to the `.yarnrc` they originate from, so that they keep a consistent value everytime.
**Test plan**
Added a test.
> Fixes relative cache paths

- __tests__/commands/global.js
- __tests__/commands/install/integration.js
- src/cli/commands/link.js
- src/package-linker.js
**Summary**
This is a fix for #5927 which broke all installs with bin links on
Windows. Fixes #5927, fixes #5971. Also, #5968 was probably about this.
**Test plan**
AppVeyor tests should start passing (instead of timing out).
> fix(install): Fix bin-links and related hung installs on Windows

- src/config.js
**Summary**
It was possible for duplicate registryFolders to be inserted into the array. In code that looped over this array, it could cause additional processing.
fixes #5984
**Test plan**
Put a breakpoint on [this line](https://github.com/yarnpkg/yarn/blob/master/src/config.js#L283) and let the breakpoint hit a few times. It will eventually add duplicates. This fixes that.
> fix(cli): force registryFolders to be unique

- src/reporters/lang/en.js
- src/util/fs.js
**Summary**
npm 6 locks mtime of all files in the published tarball to be October
26th 1985, which means mtime is no longer changed when a package
is published with an npm version above 6.
See: https://npm.community/t/tarball-content-timestamps-locked-to-1985/149
Fixes: #5723
> fix(util/fs): use file content instead of mtime to determine equality

- src/fetchers/git-fetcher.js
- src/fetchers/tarball-fetcher.js
- src/util/fs.js
**Summary**
The `readFirstAvailableStream()` function in `util/fs.js` is unnecessarily complicated. By not passing in a generator of nulls and strings but instead using a simple array of stings (with at most 4 elements), the function can be simplified and one of its two return values becomes unnecessary.
The resulting code should be much easier to understand.
**Test plan**
Tests still pass.
> Simplify readFirstAvailableStream()

- __tests__/util/semver.js
- src/util/semver.js
**Summary**
Fixes a bug where if invalid SemVer versions were present on a registry, Yarn wouldn't be able to update that dependency.
It's (very) rare for invalid SemVer versions to be present on npm registries, but it's possible, particularly for private registries which may or may not have checks present when versions are pushed.
Before this patch, the presence of any such versions would causes a resolution-ending `TypeError: Invalid Version` when determining which version to update that dependency to. After this patch, invalid versions on the registry will be quietly ignored.
**Test plan**
I've added a test which fails if the code change here isn't applied.
> fix(util/semver): handle invalid versions in satisfiesWithPrereleases

- src/package-hoister.js
**Summary**
I'm submitting this PR early so I can get as much feedback as possible. I am not at all familiar with the yarn codebase, so I'm not sure if I'm even making this change in the right place.
I have a rather large monorepo (~150 packages) and when running `yarn install` from yarn>=1.4.0, it just hangs during the "Linking Dependencies" step. For example, today I let it run for 3.5 hours before I finally gave in and killed it. For the past several months I've just used v1.3.2 as a temporary workaround. Today I spent several hours in the yarn code adding `console.log` statements all over the place and I think I've determined that `this.levelQueue` is growing exponentially at [package-hoister.js:247](https://github.com/yarnpkg/yarn/blob/master/src/package-hoister.js#L247). The same …
> [WIP] dedupe hoister levelQueue items for performance gains

- src/reporters/lang/en.js
**Summary**
This PR fixes https://github.com/yarnpkg/yarn/issues/5991.
The message for linkCollision is now:
```
There's already a package called $0 registered. This command has had no effect. If this command was run in another folder with the same name,  the other folder is still linked. Please run yarn unlink in the other folder if you want to register this folder.
```
**Motivation**
As mentioned in the issue, the current warning for `yarn link` is vague and should be more specific.
**Test plan**
When running `yarn link`, it produces this warning now:
```
warning There's already a package called "rimraf" registered. This command has had no effect. If this command was run in another folder with the same name, the other folder is still linked. Please run yarn unlink in the other folder if …
```
> Clarified yarn link Warning

- src/cli/commands/create.js
**Summary**
Fixes #5981 by using the scope as part of the path lookup, if it exists.
**Note:** this does *not* yet work on Windows, and it seems like we'll need to do some explicit platform checking to *make* it work on Windows.
**Test plan**
Output on macOS:
```
yarn create @olo/ember-app
yarn create v1.7.0
success Installed "@olo/create-ember-app@0.1.0" with binaries:
- @olo/create-ember-app
[#######################################################################################] 1007/1008
App name:
```
**Current (broken) output on Windows:**
```
yarn create @olo/ember-app
yarn create v1.6.0
warning @olo/create-ember-app > …
```
> Correctly resolve scoped packages in `yarn create`.

- src/util/filter.js
**Summary**
This fixes `yarn pack` not ignoring `.gitignore` when `.npmignore` is avaialable on Windows. Initial fix was done in https://github.com/yarnpkg/yarn/pull/3538, but it used string concatenation to join paths which make it unfortunately fail for Windows which uses different path separator than other systems. It was reported as not fixed in https://github.com/yarnpkg/yarn/issues/685#issuecomment-329895660 (OS: Windows) in initial issue after issue was closed as fixed.
**Test plan**
First I tested if tarball created by `yarn pack` is correct (so it ignores `.gitignore` when I have `.npmignore`). 
To demonstrate here, I added extra console output here https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/pack.js#L89 logging `dotIgnoreFiles` and here's before / after: …
> fix(pack): higher priority to .npmignore over .gitignore on windows

- src/util/filter.js
**Summary**
This diff fixes the Windows tests that broke due to #5979.
**Test plan**
AppVeyor should pass again.
> Fixes windows filtering

- src/package-compatibility.js
- src/reporters/lang/en.js
**Summary**
This PR extends the incompatible engine message with a "Got" field that references the current engine version.
**Motivation**
When running `yarn add` in remote or cloud environments, it may not be possible to immediately determine the engine version (node / npm etc). This helps identify the current engine version. 
**Test plan**
Not needed.
**Before**
```
error eslint@5.0.1: The engine "node" is incompatible with this module. 
Expected version "^6.14.0 || ^8.10.0 || >=9.10.0".
```
**After**
```
error eslint@5.0.1: The engine "node" is incompatible with this module. 
Expected version "^6.14.0 || ^8.10.0 || >=9.10.0". Got "9.6.0"
```
> Added a got field to incompatible engine message

- src/cli/commands/licenses.js
- src/cli/commands/list.js
- src/reporters/base-reporter.js
- src/reporters/console/console-reporter.js
**Summary**
When running a list command, ensure `--silent` option doesn't suppress the  essential output, only supplementary information like how long it took and which version of yarn was used.
Fixes #6127
**Test plan**
The following commands should both produce output - previously they did not:
```
yarn --silent list
yarn --silent licenses list
```
> fix: Show essential output for list commands when using --silent option

- src/reporters/lang/en.js
Hello maintainers.
**Summary**
This PR is trying to close https://github.com/yarnpkg/yarn/issues/6111.
Although I'm aware of that there are still many the term "manifest" in this repository, changing just the error message which is pointed out in the issue is even worth for users.
**Test plan**
I've run `yarn remove` command on local and checked the error message has changed.
```
$ node ./lib/cli/index.js remove invalid-package-name                                                                                                  reword-manifest-to-package-json
yarn remove v1.10.0-0
(node:83703) ExperimentalWarning: The fs.promises API is experimental
[1/2] 🗑  Removing module invalid-package-name...
error This module isn't specified in a package.json file.
info Visit …
```
> fix(cli): reword manifest

- src/util/execute-lifecycle-script.js
**Summary**
Fixes #5935 
**Test plan**
This one is supposedly going to remain untested:
```diff
commit 3759562d6a4b114723ee7055e7f872153301657b
Author: Yuri Kanivetsky <yuri.kanivetsky@gmail.com>
Date:   Mon Jul 30 12:01:22 2018 +0300
trying to test...
`yarn test` pollutes PATH with another /usr/bin, and even if
the child instance of yarn doesn't do that, there are at least two
/usr/bin's in the PATH
diff --git a/__tests__/fixtures/lifecycle-scripts/usr-bin/package.json b/__tests__/fixtures/lifecycle-scripts/usr-bin/package.json
new file mode 100644
index 00000000..d825e8bd
--- /dev/null
+++ b/__tests__/fixtures/lifecycle-scripts/usr-bin/package.json
@@ -0,0 +1,5 @@
+{
+    "scripts": {
+        "cmd1": "echo $PATH | tr : \\\\n"
+    }
+}
diff --git a/__tests__/lifecycle-scripts.js …
```
> Make yarn not to add /usr/bin to PATH if already there

- __tests__/integration.js
**Summary**
This test was failing on Windows with the following error:
```
'false' is not recognized as an internal or external command,
operable program or batch file.
```
The script used for this test is `false`. This is valid in Bash, but is
not valid in cmd.exe. It has been replaced with `exit 1`, which will
exit with a status of `1` in both Bash and cmd.exe
The reason this test was passing on AppVeyor is that they have Cygwin
installed by default. This includes a binary called `false`.
**Test plan**
N/A
> test: Fix `yarn run <failing script>` test on Windows

- __tests__/integration.js
**Summary**
AppVeyor is constantly timeouting on the tarball fetching test.
**Test plan**
n/a
> Disables a tarball fetching test on windows

- package.json
**Summary**
The test suite displays the following warning message when run:
```
jest-haste-map: @providesModule naming collision:
Duplicate module name: yarn
Paths: <repo directory>\dist\package.json collides with
<repo directory>\package.json
```
This is because the Jest module system finds two copies of Yarn; the
primary package and the build output. This causes ambiguity when loading
`yarn` from a test, or a module that depends upon yarn.
Adding the build directory to `modulePathIgnorePatterns` prevents this
message. This means that if `yarn` is imported from within a test (which
it is not currently), the version found will be the primary package, not
the built version.
This seems acceptable. Currently, components of `yarn` are referenced by
filename rather than by package name, and …
> test(warning): Jest: Ignore build directory modules

- src/package-hoister.js
**Summary**
For big repositories with thousands of packages splicing the queue array can take upwards of 60s to complete. Changing the algorithm to filter the queue only once solves this.
Our monorepo contains more than 2k packages at the top level, with a workspace of more than 200 packages. Yarn got very slow lately, with `install --force` taking more than 4 minutes easily - mostly hanging at "Linking dependencies" with no progress updates.
I profiled yarn with `ndb` and found the culprit to be native `Array.splice`. After this change, it's still the biggest offender but I couldn't find any more obvious call sites to fix.
With the fix we went down from 240s to 50s for `yarn install --force` on Node 10.1.  After upgrading to 10.8 we went down even further to 24s.
**Test plan**
This is a …
> fix(perf): Filter queue in PackageHoister.seed instead of splicing

- bin/yarn.js
`v8-compile-cache` is not loading because `fs.existsSync` is checking for a file that doesn't exist. `fs.existsSync` resolves relative to the cwd, not the current module (like `require`), and `v8CompileCachePath`'s filename is missing `.js`.
Instead of checking for the existence of `v8-compile-cache.js`, just try to `require` it in a `try`/`catch`, using a full path. Also switched the `require` of `cli.js` to use the same pattern for consistency (plus it's a module resolution micro-optimization).
```
$ time ./dist/bin/yarn -v
1.10.0-0
./dist/bin/yarn -v  0.28s user 0.06s system 98% cpu 0.344 total
$ time ./dist/bin/yarn -v
1.10.0-0
./dist/bin/yarn -v  0.16s user 0.05s system 97% cpu 0.213 total
```
> Fix: Correctly load v8-compile-cache

- __tests__/commands/create.js
- src/cli/commands/create.js
This one works as it should:
yarn create @scope/name => @scope/create-name
There were problems when name was omitted:
Before:
yarn create @scope => create-
yarn create @scope/ => @scope/create-
After:
yarn create @scope => @scope/create
yarn create @scope/ => @scope/create
Fixes #6233
**Summary**
it Is not substantial feature request.
Existing behaviour is a bit odd and not aligned with npm. This PR aims to fix it.
**Test plan**
```
~/projects/oss/yarn fix/scoped-create
☯ ./bin/yarn create name
{ packageName: 'create-name',
packageDir: '',
commandName: 'create-name' }
~/projects/oss/yarn fix/scoped-create
☯ ./bin/yarn create @scope/name
{ packageName: '@scope/create-name',
packageDir: '@scope',
commandName: 'create-name' }
~/projects/oss/yarn fix/scoped-create
☯ ./bin/yarn create @scope/ …
```
> fix(cli-create): fix scoped creation

- __tests__/commands/workspaces.js
- src/cli/commands/workspaces.js
**Summary**
Added the ability to run a script on every workspace in a project. 
`yarn workspaces run script`
Motivation was to be able to run build or test across an entire monorepo during a CI process. While it was possible to run a script on a workspace individually by name `yarn workspace workspace-1 script`. This required you to know and list all workspaces. 
**Test plan**
I added more tests that ensure that the commands are being spawned properly. Since most of the code was copied from functioning parts of the project, I felt this was sufficient. 
*Update*
Based on feedback I validated that arguments can be passed. 
Here were the commands I ran. 
- `cd __tests__/fixtures/workspace/run-basic`
- `yarn workspace workspace-1 add jest`
- `yarn workspace workspace-2 add jest`
- `yarn …
> Added ability to run script on all workspaces

- src/cli/commands/create.js
**Summary**
When running yarn create, first the package is installed globally,
however after installing create was attempting to invoke the binary from
within a scope folder that did not exists. The corrects the path
resolution to invoke the binary from the actual place it was installed
to.
fixes #6266
**Test plan**
This basically just removes the change introduced in #5983. I'm happy to add tests if needed but I'm unsure how to accomplish that.
> fix(create): invoke correct path when using scoped package

- package.json
- scripts/build-webpack.js
- yarn.lock
**Summary**
#6208 caused some rx packages to be upgraded, which in turn broke the bundling process (the new release doesn't play well with webpack because of its amd definition). This diff updates the configuration to hack around this issue.
**Test plan**
```
yarn && yarn build-bundle && ./artifacts/yarn-1.10.0-0.js --version
```
> Fixes the bundle build

- bin/yarn.ps1
… #6092
**Summary**
Not a substantial pull request. `cmd` is unmaintained, according to its authors at Microsoft. One of the issues is that the termination behavior (Ctrl C) for `cmd` scripts cannot be modifed, but there are likely other issues with `cmd` being unmaintained. 
**Test plan**
All Windows `yarn` commands still work, with no effect on speed and output.
> Add yarn.ps1, fixes #6092 (bad Ctrl C behavior)

- src/config.js
- src/package-linker.js
- src/util/execute-lifecycle-script.js
**Summary**
Fix #3724 
When running `yarn install` with a customized `--modules-folder`, binaries are still linked under the default `node_modules/.bin`.
This PR fixes that behavior.
From now on:
1. `install` and `add` commands will link binaries under `custom/.bin`.
1. `run` command will prepend the custom folder path to `PATH` env.
1. `remove` command will remove the specified package from the custom folder. The same way `install --force` will prune extraneous from custom folder.
**Test plan**
All the following were tested with local `.yarnrc` too.
**_Add_**
```bash
$ yarn --modules-folder custom add acorn
$ tree -a --noreport custom/.bin/
custom/.bin/
└── acorn -> ../acorn/bin/acorn
```
**_Install_**
```bash
$ cat package.json 
{
"acorn": "^5.7.1"
}
}
$ yarn …
```
> Bugfix #3724

- scripts/build-webpack.js
**Summary**
The Webpack config for the modern build was [adjusted recently to add a loader](https://github.com/yarnpkg/yarn/pull/6274),
which is used as a workaround for a bug introduced by a [recent dependency
update](#6208 ). The legacy config needed the same update.
The Webpack config was also updated in superficial ways to follow
recommendations made for migrating from Webpack v1 to v2 (e.g. using
`module.rules` instead of `module.loaders`). These changes should have no
functional impact, and should make migrating to future versions of Webpack
easier.
fix #6269
**Test plan**
I have tested building and running both the modern and legacy builds. Before this change, the artifact from the modern build worked, but the one from the legacy build did not. Now they both work.
I also compared …
> fix(build): Apply bundle fix to legacy build

- src/util/filter.js
**Summary**
This PR fixes an alert that was found on LGTM: https://lgtm.com/projects/g/yarnpkg/yarn/alerts/?mode=tree&ruleFocus=1506222917439
https://github.com/yarnpkg/yarn/blob/8cbbc6df34d5ff050bed507224f42abd1b104904/src/util/filter.js#L103-L104
This replacement was incomplete, and would only replace the first backslash which is not what was intended.
**Test plan**
Output from node:
```js
> 'fooo\\bar\\baz'.replace('\\', '/')
'fooo/bar\\baz'
> 'fooo\\bar\\baz'.replace(/\\/g, '/')
'fooo/bar/baz'
```
I'm not sure how to otherwise test this part of the code, or introduce a test case that proves that the previous version fails and the fix fixes it.
> chore: fix incomplete sanitization

- __tests__/index.js
- __tests__/integration.js
- __tests__/lifecycle-scripts.js
**Summary**
Previously if `yarn test` was run without first having run `yarn build`, these three test suites would fail with over 1000 lines of unclear console output. Now, later tests are stopped from running to reduce verbosity, and a more contributor-friendly error message displayed instead.
Note: We unfortunately can't handle this case in `beforeAll()`, since even if it throws, later tests in the same file are still run:
https://github.com/facebook/jest/issues/2713
**Test plan**
Output of `yarn test` previously:
<details>
<summary>Click to expand</summary>
```
(node:11068) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
(node:11068) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'addExpectationResult' of undefined …
```
> test: Fail early if the local yarn build is missing

- __tests__/reporters/__snapshots__/console-reporter.js.snap
- src/reporters/console/console-reporter.js
**Summary**
Given the general problem of yarn emitting console color codes at inappropriate times, this PR tackles one particular case that's been annoying me.
Before:
```
jrr@jrrmbp ~> yarn versions |more
yarn versions v1.9.4
{ yarn: ESC[32m'1.9.4'ESC[39m,
http_parser: ESC[32m'2.8.0'ESC[39m,
node: ESC[32m'8.11.3'ESC[39m,
v8: ESC[32m'6.2.414.54'ESC[39m,
uv: ESC[32m'1.19.1'ESC[39m,
zlib: ESC[32m'1.2.11'ESC[39m,
ares: ESC[32m'1.10.1-DEV'ESC[39m,
modules: ESC[32m'57'ESC[39m,
nghttp2: ESC[32m'1.32.0'ESC[39m,
napi: ESC[32m'3'ESC[39m,
openssl: ESC[32m'1.0.2o'ESC[39m,
icu: ESC[32m'60.1'ESC[39m,
unicode: ESC[32m'10.0'ESC[39m,
cldr: ESC[32m'32.0'ESC[39m,
tz: ESC[32m'2017c'ESC[39m }
Done in 0.02s.
```
After:
```
jrr@jrrmbp ~/r/yarn (fix/console-reporter-colors)> ./bin/yarn versions |more
yarn …
```
> ConsoleReporter: do not color if !isTTY

- src/util/fs.js
**Summary**
Cf my comment in #2454 - I'm not certain it fixes anything. I'm not certain there was a problem to begin with 🤔 
**Test plan**
I can make a test if I understand the repro. The existing ones are passing.
> Reverts #2454

- src/util/fs-normalized.js
**Summary**
Fixes #5456.
This flag increases performance and saves disk space on COW filesystems that support this flag (APFS, btrfs). On my machine running High Sierra, this decreases `yarn install --offline` time from 9.24s to 6.89s for a project with a lot of dependencies.
**Test plan**
- `yarn run test` passes
> Use UV_FS_COPYFILE_FICLONE flag in fs.copyFile when available

- __tests__/commands/publish.js
- src/cli/commands/publish.js
**Summary**
Fix https://github.com/yarnpkg/yarn/issues/2430
This PR fix `yarn publish [tarball]` and `yarn publish [folder]` commands: flag `--new-version` should not be required, like when using just `yarn publish`.
Current bugged behavior:
```sh
$ yarn publish build
yarn publish v1.9.4
[1/4] Bumping version...
error Use the "--new-version [version]" flag to create a new version.
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
```
**Test plan**
```sh
yarn publish build
```
or
```sh
yarn publish some-package.tgz
```
> fix(cli/publish): allow to publish directory without `--new-version`

- __tests__/commands/publish.js
- __tests__/fixtures/publish/publish-config-registry/package.json
- src/cli/commands/login.js
- src/cli/commands/publish.js
- src/registries/npm-registry.js
**Summary**
Fix https://github.com/yarnpkg/yarn/issues/6258
While getting login token we should use directly publishConfig.registry instead of trying find suitable repo by package's name/scope. 
**Test plan**
```json
// package.json
"publishConfig": {
"registry": "https://my.registry/"
}
```
```sh
yarn publish
``` 
**Additional thougths**
With this and https://github.com/yarnpkg/yarn/pull/5376 PRs we have a slightly unobvious behavior that `publishConfig.registry` has more priority than flag `--registry`. NPM has the same behavior which reported as bug https://github.com/npm/npm/issues/5522. It has not been fixed yet but I think we could fix that in yarn before npm do it.
> Fix login for `yarn publish` when using publishConfig.registry

- yarn.lock
**Summary**
Running ´yarn install` in repo gives this diff because `validate-npm-package-license` is missing the integrity field.
> Fix missing intregity field for validate-npm-package-license in yarn.lock

- src/util/git.js
**Summary**
Fixes #6256
This change fixes an issue where the cached git repo was not updated with the latest tags.
As a result yarn would exit with the `git archive` command -> `fatal: not a tree object`.
> Fetch tags for cached git repo

- src/cli/commands/help.js
- src/util/misc.js
**Summary**
Fixes #5050. Uses the already defined 'sortAlpha' for the actual sorting.
**Test plan**
Run `yarn help`.
Output,
> sort options using flags; Fix #5050

- __tests__/util/request-manager.js
- src/config.js
- src/fetchers/tarball-fetcher.js
- src/reporters/lang/en.js
- src/util/request-manager.js
**Summary**
Supersedes #6400, #6383
This PR adds a retry mechanism for when the npm registry returns 408 / 500 errors.
**Test plan**
Added a test. Hopefully our own CI will become more stable as well.
> Adds retry-on-error for errors 408/500

- yarn.lock
**Summary**
This PR has done nothing except run `yarn install` using `yarn@1.10.1` and committed the result, which includes integrity hashes. 
**Test plan**
None needed
> Add integrity hashes to project yarn.lock

- packages/pkg-tests/pkg-tests-fixtures/packages/peer-deps-lvl0-1.0.0/index.js
- packages/pkg-tests/pkg-tests-fixtures/packages/peer-deps-lvl0-1.0.0/package.json
- packages/pkg-tests/pkg-tests-fixtures/packages/peer-deps-lvl1-1.0.0/index.js
- packages/pkg-tests/pkg-tests-fixtures/packages/peer-deps-lvl1-1.0.0/package.json
- packages/pkg-tests/pkg-tests-fixtures/packages/peer-deps-lvl2-1.0.0/index.js
- packages/pkg-tests/pkg-tests-fixtures/packages/peer-deps-lvl2-1.0.0/package.json
- packages/pkg-tests/pkg-tests-specs/sources/basic.js
- src/util/generate-pnp-map.js
**Summary**
This PR fixes cases where peer dependency across multiple levels of a dependency tree. A practical case is `webpack-dev-server` which has a dependency on`webpack-dev-middleware` and a peer dependency on `webpack`, and `webpack-dev-middleware` which has a peer dependency on `webpack` as well.
Since peer dependencies weren't registered until after the recursion, nested packages weren't able to leverage them. This was hard to spot because of the fallback: if `webpack` was defined as a top-level dependency (as it usually is), everything was working fine. But in the case of `create-react-app`, `webpack` is a dependency of `react-scripts`, which prevented the fallback from kicking in and triggered the bug.
**Test plan**
Added a test.
> Fixes how peer dependencies are resolved multiple levels deep

- packages/pkg-tests/pkg-tests-specs/sources/workspace.js
- src/cli/commands/run.js
- src/util/execute-lifecycle-script.js
**Summary**
This diff ensures that we are able to run scripts from `yarn run` even when within a workspace. We just find the locator that owns the workspace we're into, and use that to detect the dependencies.
**Test plan**
Added tests.
> Fixes yarn run when used on workspaces + pnp

- src/util/generate-pnp-map-api.tpl.js
**Summary**
The subject has been covered in various other topics (https://github.com/eslint/eslint/issues/10125 and derivates), but basically the way ESLint works doesn't allow `react-scripts` to cleanly provide its own lint plugins. Since it's an important use case I want to support, something has to be done.
This diff makes it so that `react-scripts` becomes a fallback of its own if found in the dependency tree (it still has a lower priority than the top-level fallback). Note that these fallbacks are not considered for files loaded from the top-level package (meaning that an application file doing `require('foo')` without listing `foo` in the top-level `package.json` will throw, even if `react-scripts` depends on `foo`). This ensures people won't accidentally rely on the fallback when …
> PnP ESLint compatibility

- CHANGELOG.md
- src/config.js
- src/reporters/lang/en.js
- src/util/generate-pnp-map-api.tpl.js
- src/util/generate-pnp-map.js
This PR is a start to resolve #6402 _(Plug'n'Play doesn't support Windows paths)_.
> Support Windows paths for pnp.

- __tests__/registries/npm-registry.js
- src/registries/npm-registry.js
- src/resolvers/registries/npm-resolver.js
**Summary**
It's relatively common to see `Received malformed response from registry for undefined` errors, where the `undefined` is coming from the fast that the returned body was totally invalid JSON, and therefore the package name couldn't be parsed from it.
This PR ensures that a package name will always be show in such errors.
**Test plan**
A new test checks that the dependency name is included in the error message for malformed responses, even if it was not returned by the registry.
> Ensure malformedRegistryResponse errors always have a dependency name

- CHANGELOG.md
- packages/pkg-tests/pkg-tests-specs/sources/pnp.js
- src/util/generate-pnp-map-api.tpl.js
**Summary**
This PR injects a `process.versions.pnp` variable in the environment when the PnP hook is setup. This is useful for plugins to detect whether they're operating in a PnP environment (where they can require the `pnpapi` module to access the full API) or not without having to rely on try/catch.
**Test plan**
Added a test
> Injects a "process.versions.pnp" variable

- CHANGELOG.md
- __tests__/commands/add.js
- __tests__/commands/install/integration.js
- __tests__/commands/remove.js
- src/cli/commands/install.js
- src/config.js
**Summary**
While not breaking technically speaking, the automatic migration is causing unexpected behaviors to our users. Such a behavior should only happen when bumping the major version.
To prevent that, the `unsafe-disable-integrity-migration` settings will default to `true` for the duration of the 1.X branch. **It will default to `false` again starting with the 2.0.**
In order to migrate your project now, just add the following line into your project-local yarnrc:
```
unsafe-disable-integrity-migration "false"
```
Note that this only affect the lockfile entries already present in your lockfile. Yarn will continue to create the new entries using the `integrity` field. My guess is that by the time the 2.0 lands, enough projects will have been migrated to use the `integrity` field that …
> Disables by default the migrations

- renovate.json
**Summary**
After enabling this setting, Renovate will:
- Create a "master" issue containing a list of all outdated dependencies
- No longer automatically create Pull Requests once updates are available
- Provide "checkboxes" in the master issue to allow maintainers to selectively approve PRs for creation
Note: existing PRs will remain open and approvals will be needed only for future/subsequent PRs after this merge.
As suggested by @arcanis, example issue dogfooding this issue is here: https://github.com/renovatebot/renovate/issues/2599
**Test plan**
None necessary
> Enable Renovate master issue approval

- CHANGELOG.md
- __tests__/registries/npm-registry.js
- src/registries/npm-registry.js
**Summary**
Builds on top of https://github.com/yarnpkg/yarn/pull/5216.
Adds support for using Basic auth like so:
```
@scope:registry=https://artifactory.example.com/api/npm/registry/
//artifactory.example.com/api/npm/registry/:username=uuuu
//artifactory.example.com/api/npm/registry/:_password=pppp
//artifactory.example.com/api/packages/username=uuuu
//artifactory.example.com/api/packages/:_password=pppp
```
As pointed out in https://github.com/yarnpkg/yarn/pull/5216#issuecomment-357885471.
**Test plan**
Test gen ftw!
> feat(auth): Add basic auth support for pathed registries

- CHANGELOG.md
- src/lockfile/parse.js
Replace all instances of building strings incrementally using += with more efficient methods.
**Summary**
This is motivated by #4929, as one cause of "Invalid string length" is trying to concatenate with too large of a string, and the stack trace there points to a string concatenation operation in this function. It's probably not the root cause of #4929, so I wouldn't say this should close that issue until we understand what in the lockfile was causing runaway string concatenation. But it does address the proximate issue and helps with general code health and probably performance as well, if only in a small way.
**Test plan**
Automated tests should cover regressions. Manually review code to ensure no lingering string concatenation.
> refactor(lockfile): remove string concatenation from parsing code

- CHANGELOG.md
- package.json
- yarn.lock
**Summary**
`cli-table3` no longer supports Node v4 as of v0.5.0. Downgrading to `cli-table3@0.4.0` restores Node v4 support, and should fix the nightly `test-e2e-ubuntu1604` CircleCI test that has been failing
This dependency was introduced in #6409, so this problem is present in v1.12.0
**Test plan**
Using Node.js `v4.8.7` and after running `yarn build-dist`, any command with the resulting artifact will give the following output:
```
C:\Development\git\yarn\artifacts\yarn-legacy-1.13.0-0.js:62791
let code = codeRegex();
^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load …
```
> fix: Restore Node v4 support by downgrading cli-table3

- CHANGELOG.md
- src/cli/commands/install.js
- src/cli/commands/upgrade-interactive.js
**Summary**
Small quality of life improvement. This means that you won't accidentally take your time choosing your dependencies to upgrade and then find out that engines don't match.
> Check package engines before running upgrade-interactive

- __tests__/commands/_helpers.js
**Summary**
The last three tests in `__tests__/commands/publish.js` were regularly timing
out locally, yet they were doing fine on CI. They were apparently running in
interactive mode, and were waiting for user input after `publish` was called
(to set the next version number).
Setting `nonInteractive` to false by default in `__tests__/commands/_helpers`
ensures that all command tests run in non-interactive mode unless otherwise
specified. This prevents this problem from occuring again, at least among the
tests that use this helper.
This change won't improve tests on CI, as this problem never
affected CI. The tests were running in non-interactive mode on CI
already due to an `isCi` check in `config.js`.
**Test plan**
The last three tests in `__tests__/commands/publish.js` would regularly …
> test: Default `nonInteractive` to true in cli tests to prevent timeouts

- CHANGELOG.md
- __tests__/commands/pack.js
- __tests__/fixtures/pack/files-include-from-root/index.js
- __tests__/fixtures/pack/files-include-from-root/package.json
- __tests__/fixtures/pack/files-include-from-root/sub/index.js
- src/cli/commands/pack.js
**Summary**
`npm pack` bases paths in the `files` array from the package’s root.
This updates yarn pack to behave in the same way.
**Test plan**
Let’s consider the following package:
```js
{
"name": "files-include-from-root",
"files": ["index.js"]
}
```
With the following files:
```
$ tree ./files-include-from-root
├── index.js
├── package.json
└── sub
└── index.js
```
`npm pack`’s current behavior:
```
$ npm pack --dry-run ./files-include-from-root
npm notice
npm notice 📦  files-include-from-root@1.0.0
npm notice === Tarball Contents ===
npm notice 107B package.json
npm notice 25B  index.js
npm notice === Tarball Details ===
npm notice name:          files-include-from-root
npm notice version:       1.0.0
npm notice filename: …
```
> Anchor package.json `files` to the package’s root

- CHANGELOG.md
- __tests__/registries/npm-registry.js
- __tests__/util/request-manager.js
- src/cli/commands/login.js
- src/cli/index.js
- src/config.js
- src/errors.js
- src/registries/base-registry.js
- src/registries/npm-registry.js
- src/reporters/lang/en.js
- src/util/request-manager.js
**Summary**
Added support for logging into NPM account with 2FA enabled, based on [`npm-profile`](https://github.com/npm/npm-profile/tree/latest/lib) implementation.
Fixes #4904.
**Test plan**
1. Enable 2FA for your account: https://docs.npmjs.com/getting-started/using-two-factor-authentication
2. Run `yarn publish`:
**Issues**
I've added some basic tests, but don't know where should I put functional test with the whole one-time password prompt flow (like in the screenshot above). Are there any similar high-level tests you could point me to?
I also don't support `--non-interactive`, because AFAIK there's no way to access `Config` nor `flags` (Do we need to check both of them?) from `NpmRegistry.request(...)`, as it's done in the case of `getToken(config, reporter, name, flags, registry)` …
> feat(auth): Support two factor authentication for NPM accounts

- CHANGELOG.md
- packages/pkg-tests/pkg-tests-specs/package.json
- packages/pkg-tests/pkg-tests-specs/sources/pnp.js
- packages/pkg-tests/yarn.lock
- src/util/generate-pnp-map-api.tpl.js
**Summary**
The generated hook currently completely ignores the `paths` option from `require.resolve`. This diff fixes that by trying the resolution one path at a time until we find one that would work (if we don't find any, we simply rethrow the first error).
As an added safety, our implementation will also throw if the user specifies any option that isn't properly understood by the hook. This is better than silently ignoring the options.
**Test plan**
Wrote tests.
> Implements require.resolve's `paths` options

- CHANGELOG.md
- bin/yarn
If the yarn binary is a symlink the `basepath` is not correctly resolved on OSX/Darwin.
For example take the following structure:
```
vendor/yarnpkg/yarn/bin/yarn
vendor/bin/yarn -> ../yarnpkg/yarn/bin/yarn
```
And run yarn:
```
$ yarn
internal/modules/cjs/loader.js:582
throw err;
^
Error: Cannot find module '/Users/yarnpkg/yarn/bin/yarn.js'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
at Function.Module._load (internal/modules/cjs/loader.js:506:25)
at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
at startup (internal/bootstrap/node.js:285:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```
Since the symlink is not resolved the relative path in the symlink leads to the wrong path.
This PR, fixes that issue.
**Summary**
**Test …
> Support Darwin bash in bin/yarn

- CHANGELOG.md
- src/util/generate-pnp-map-api.tpl.js
**Summary**
I accidentally broke the resolve shim in an experiment (I was considering make shim qualifiers regexps, which ended up unnecessary). This diff reverts the boggus change.
**Test plan**
I specifically don't want to test this part of the code, since it's a shim that we shouldn't even have in the first place.
> Fixes the resolve shim for liftoff

- __tests__/commands/install/integration.js
- __tests__/fixtures/install/install-no-bin/package.json
- src/package-linker.js
**Summary**
Fixes #6622
**Test plan**
Added a test
> Stop copying `.bin` folders

- CHANGELOG.md
- package.json
- yarn.lock
There is a potential freeze when running interactive upgrades after selecting the options. (See #6592, #6367, #6198, #5949)
This boiles down to a problem in the `inquirer` library which is used internally to provide the possible options on the CLI. Updating `inquirer` to the latest version fixes the problem.
All tests keep passing also with the new version of inquirer.
> Fixes potential freeze on win+node10 interactive upgrades (#5949)

- scripts/build-webpack.js
**Summary**
Inquirer dropped support for Node 4. We recently upgraded via #6635, which breaks Node 4 compat.
This PR ensures that inquirer is properly transpiled in the legacy build.
**Test plan**
CI; ran `yarn upgrade-interactive` and `yarn add lodash@doesnt-exist`
> Precompiles inquirer for Node 4 compat

- CHANGELOG.md
- packages/pkg-tests/pkg-tests-specs/sources/pnpapi-v1.js
- src/util/generate-pnp-map-api.tpl.js
**Summary**
The hook was only exposing `pnpapi` through the `require` function, not the actual PnP API. In most cases this isn't a problem, but non-Node things that depend on resolving the dependencies for a project (such as the Jest resolver) weren't able to allow their scripts to access the PnP API.
**Test plan**
Added a test to make sure that it was correctly exported.
> Exposes pnpapi through resolveToUnqualified

- packages/pkg-tests/pkg-tests-fixtures/packages/no-deps-scripted-1.0.0/package.json
- packages/pkg-tests/pkg-tests-fixtures/packages/no-deps-scripted-1.0.0/scripts/install.js
- packages/pkg-tests/pkg-tests-fixtures/packages/no-deps-scripted-1.0.0/scripts/postinstall.js
- packages/pkg-tests/pkg-tests-fixtures/packages/no-deps-scripted-1.0.0/scripts/preinstall.js
- packages/pkg-tests/pkg-tests-specs/sources/script.js
@arcanis Is this what you propose? It's working great in Windows, and it should in other OS.
Btw I've replaced 100, 200, 300 by more meaningful values.
> Use node scripts to avoid Windows interoperability issues.

- azure-pipelines.yml
- packages/pkg-tests/yarn.test.js
- scripts/azure-run-tests.yml
Some tests in Windows may randomly take up to 5s, increasing to 10s.
Better name test results with its source job.
@arcanis Can you integrate this in your PR?
Let me know if you see any other blocker.
We're also looking into fastening up these tests,
> Increase Windows timeouts and better name Test results

- CHANGELOG.md
- src/cli/commands/index.js
- src/cli/commands/policies.js
- src/cli/commands/self.js
- src/registries/yarn-registry.js
- src/util/fs.js
**Summary**
This feature implements a new command:
```
$> yarn self set [range]
$> yarn self set nightly
$> yarn self set rc
$> yarn self set ^1.12
$> yarn self set 1.12.3
```
When run, Yarn will download from Github the latest release matching the specified range, will put it inside the `<lockfileFolder>/.yarn/releases` directory, and will update `<lockfileFolder>/.yarnrc` to point to this new binary.
Essentially, this command allows:
- to upgrade Yarn in a single swoop
- to rely on npm much less (which always was a bit funny)
- to enforce a specific Yarn version for a single project
This last point is especially important: we've been recommending people to use the same Yarn release across a team, but they usually had to discover by themselves that the `yarn-path` settings existed …
> Implements "yarn self set"

- CHANGELOG.md
- src/util/execute-lifecycle-script.js
**Summary**
Avoids #6683 in many situations by siginificantly reducing the length that the `PATH` is increased by.
This issue could still raise its head in some situations, if the user already has a `PATH` whose length is close to the Windows character limit.
**Test plan**
- Ran `yarn build && yarn test` - all succeeded
- Tested newly-built yarn against my own repository that was previously exhibiting #6683. Lifecycle scripts now work.
> Check for existence of `.bin` dir in pnp dependencies before adding to `PATH`.

- packages/pkg-tests/pkg-tests-fixtures/packages/one-dep-scripted-1.0.0/index.js
- packages/pkg-tests/pkg-tests-fixtures/packages/one-dep-scripted-1.0.0/package.json
- packages/pkg-tests/pkg-tests-specs/sources/script.js
- src/util/execute-lifecycle-script.js
**Summary**
Fixes https://github.com/yarnpkg/yarn/issues/6709
This diff ensures that scripts have access to the binaries exposed from their dependencies, even when they don't belong to the top-level package.
**Test plan**
Added a test.
> Fixes dependencies using bins from their own dependencies

- src/util/portable-script.js
**Summary**
Since the portable script doesn't use `exec`, signals seem to be trapped.
This diff ensures that we correctly replace the process rather than simply spawning a new one.
**Test plan**
CI
> Fixes how signals are forwarded

- CHANGELOG.md
- __tests__/commands/install/integration.js
- __tests__/fixtures/install/missing-opt-peer-dep/foo/package.json
- __tests__/fixtures/install/missing-opt-peer-dep/package.json
- __tests__/fixtures/install/missing-peer-dep/foo/package.json
- __tests__/fixtures/install/missing-peer-dep/package.json
- src/package-linker.js
- src/types.js
**Summary**
This PR implements https://github.com/yarnpkg/rfcs/pull/105 (Optional Peer Dependencies).
It uses a new `peerDependenciesMeta` field to specify which peer dependency warnings can be safely ignored.
**Test plan**
Added tests.
> Implements optional peer dependencies

- src/cli/commands/install.js
- src/cli/commands/remove.js
Switch from page_with_curl (📃) to hammer (🔨) emoji for this stage.
**Summary**
The hammer symbol is commonly used to indicate building or construction, or work in general:
https://en.wikipedia.org/wiki/Hammer#Symbolic_hammers
Using this as the glyph during the build or rebuild stages communicates more clearly to the user compared to the `page_with_curl` symbol, which would be more associated with composing / writing / authoring (eg during a hypothetical codegen stage of a process).
**Test plan**
Before this change, on my ubuntu:cosmic computer:
After this change:
> Use hammer emoji for install/reinstall stage

- scripts/build-chocolatey.ps1
**Summary**
Updates `build-chocolatey.ps1` to search for an existing Yarn package using the `choco list` command, rather than using OneGet. For some reason I can't get OneGet to work properly on Windows Server 2016
The script now runs:
```
choco list yarn --exact --version $latest_version 
```
and checks if the output contains "0 packages found". This is a bit messy, but the `choco` command doesn't have an API that returns XML or JSON (ref https://github.com/chocolatey/choco/issues/159, https://github.com/chocolatey/choco/issues/1252), and I didn't want to hit their web API directly, so this will do for now.
Fixes #6189
**Test plan**
Manually executed the script
> Check for Chocolatey version using "choco list" instead of OneGet

- src/fetchers/tarball-fetcher.js
**Summary**
My team would like to download tarballs attached to GitLab Releases.
The projects are authenticated, therefore we need to add `PRIVATE-TOKEN` header to the request for the tarball. See https://docs.gitlab.com/ee/api/README.html#personal-access-tokens
I propose the following configuration addition:
`~/.npmrc`:
```
//custom.gitlab.host/:_header:PRIVATE-TOKEN=REDACTED
```
where:
- `//custom.gitlab.host/` is the host which matches the tarball request.
- `:_header:<HEADER-NAME>` indicates a custom header should be added, with `PRIVATE-TOKEN` being the `HEADER-NAME` in this instance. Multiple custom headers could be added in this way.
Then we can run:
```
❯ yarn-local add --dev --verbose https://custom.gitlab.host/OWNER/REPO/uploads/REDACTED/PKG-NAME-v1.0.0.tgz
```
And the request …
> Add custom headers to tarball fetcher

- CHANGELOG.md
- src/util/request-manager.js
**Summary**
This diff makes sure that we properly report the status codes coming from the npm registry when downloading the tarballs.
**Test plan**
Changed a tarball url from a lockfile to something invalid, ran `yarn cache clean`, ran yarn and saw the proper error message.
> Properly reports network errors

- CHANGELOG.md
- packages/pkg-tests/pkg-tests-specs/sources/pnp.js
- src/util/generate-pnp-map-api.tpl.js
**Summary**
This PR adds builtin `resolve` support using the mechanisms described in https://github.com/browserify/resolve/pull/174. I've also added an escape hatch (`forceNodeResolution`) in case something goes awry.
cc @ljharb
**Test plan**
Added an automated test.
> Implements the pnp hook for the `resolve` package

- CHANGELOG.md
- src/package-linker.js
**Summary**
We currently unplug packages by default when they have postinstall scripts, since we can't run them from within the cache. This approach is fine, but we're a bit overzealous and we also do this when the user explicitly disabled the scripts.
This diff ensures that we don't automatically unplug packages anymore when the install scripts are disabled. Of note: packages that have already been unplugged won't be affected by this change (so for example, if you do `yarn install && yarn install --ignore-scripts`, the packages will *still* be unplugged).
**Test plan**
Should be simple enough not to be worth a test?
> Stops unplugging packages when the install scripts are disabled

- CHANGELOG.md
- __tests__/commands/audit.js
- src/cli/commands/audit.js
**Summary**
Resolve https://github.com/yarnpkg/yarn/issues/6748
`yarn audit` currently returns the number of found vulnerabilities. This can lead to an overflow and a false negative. E.g., if the number of vulnerable dependencies is equal to 256, the exit code will be equal 0. Furthermore, it is not very practical, as this number does not indicate the severity level of found vulnerabilities.
This pull request modifies this behavior by returning a number that is a sum of found severities:
* 1 for INFO
* 2 for LOW
* 4 for MODERATE
* 8 for HIGH
* 16 for CRITICAL
That is, if only INFO and MODERATE vulnerabilities were found, then the exit code will be `1+4 = 5`.
With this change it would be possible to check for particular severity levels. E.g., if someone wants to know, if there are HIGH and …
> Return semantic exit code for audit

- .eslintrc.json
- src/util/generate-pnp-map-api.tpl.js
**Summary**
Prior to these changes the generated `.pnp.js` file would use trailing commas for function invocations which is not allowed (and generates a parse error) under Node 6.
**Test plan**
I would like to add _some_ CI testing of the generated `.pnp.js` files to ensure that Node 4 and Node 6 continue to work (and do not regress) until the project officially drops support for them, but I am not quite sure how to go about it.
> Fix generated .pnp.js compatibility with Node 6.

- src/cli/commands/cache.js
**Summary**
Sometimes, `yarn add` will fail unexpectedly, and it leaves the cache in an invalid state. To cause your yarn cache to become corrupted:
```
$ yarn add antd@3.11.6
yarn add v1.12.3
error https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
$ yarn cache list
yarn cache v1.12.3
error An unexpected error occurred: "There should only be one folder in a package cache (got  )".
info If you think this is a bug, please open a bug report with the information provided in …
```
> Show problem path in invariant message

- CHANGELOG.md
- src/config.js
**Summary**
The detection was bogus for workspaces - it was checking the configuration of the workspace instead of the configuration of the root project folder. The reason why it should have checked this file is that the PnP configuration should be project-wide, not workspace-wide. Doing otherwise causes the installs to change depending on the folder where you run `yarn install`.
Fixing this bug has a slight risk of breaking someone's setup, unfortunately 😞 
**Test plan**
Will add a test.
> Fixes PnP detection across workspaces

- CHANGELOG.md
- src/cli/commands/policies.js
**Summary**
When using `yarn policies set-version`, yarn makes an API request to GitHub to fetch a list of yarn releases. This request can be [rate limited](https://developer.github.com/v3/#rate-limiting), but can be bypassed if request is [authenticated](https://developer.github.com/v3/#basic-authentication)
If the environment variable `GITHUB_TOKEN` is defined, append `?access_token=<GITHUB_TOKEN>` when requesting yarn releases from GitHub.
Closes https://github.com/yarnpkg/yarn/issues/6905
**Test plan**
> feat(policies): Use github access token when requesting releases

- CHANGELOG.md
- package.json
- scripts/build-webpack.js
- yarn.lock
**Summary**
When running `yarn pack` with a bundledDependency yarn was throwing
an error: An unexpected error occurred: "Cannot find module \".\"".
This was due to yarn's cli.js being transpiled to on line 110321:
```
var thePackage = !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }());
```
This line comes from https://github.com/stefanpenner/hash-for-dep/blob/e849d3e2f0350810716a0e504c84603362229570/lib/pkg.js#L20
and is a dynamic require. This commit impements a fix for this based on the guidence from https://github.com/webpack/webpack/issues/4175#issuecomment-450746682
This code was originally added with #5966
**Test plan**
Ran `yarn build-bundle` and then ran `./artifacts/yarn-XXX.js pack` inside of a sample …
> Fixing dynamic require missing from webpack

- CHANGELOG.md
- src/util/generate-pnp-map-api.tpl.js
**Summary**
I could not get P'n'P working on a project using `critical`[1] and traced it down to a lookup of a package locator without a trailing slash.
A `require('resolve').sync('fg-loadcss')` from `inline-critical`[2] would fail to resolve as the `locatorsByLocations` lookup in `.pnp.js` would be using a key without a trailing slash, i.e.:
```
"../../.cache/yarn/v4/npm-inline-critical-4.0.7-3ffba6a869f39215c8bb00ed2dd6b872e7f98adc/node_modules/inline-critical"
```
`findPackageLocator` is invoked with `location` parameter (notice no trailing slash):
```
location = "/home/zregvart/.cache/yarn/v4/npm-inline-critical-4.0.7-3ffba6a869f39215c8bb00ed2dd6b872e7f98adc/node_modules/inline-critical"
```
from `resolveToUnqualified` with parameters:
```
request = "fg-loadcss/package.json"
issuer = …
```
> fix(pnp): make sure that the package locator is fetched with a trailing slash

- CHANGELOG.md
- src/cli/commands/node.js
This PR addresses #6941 by ensuring pnp is the first preloaded module.
> fix(pnp): make sure pnp module is the first preloaded module.

- CHANGELOG.md
- src/reporters/lang/en.js
Fixes #937, #1957
**Summary**
After unlinking a package, yarn suggests running `yarn` to re-install the package, but it doesn't actually end up re-installing the package. `yarn install --check-files` or `yarn install --force` is required.
**Test plan**
Not needed
> Fix suggested command after unlinking a package

- src/fetchers/base-fetcher.js
- src/reporters/noop-reporter.js
**Summary**
There are some unused imports which we can remove for a lower technical debt and less unused code.
**Test plan**
> refactor: remove unused imports

- CHANGELOG.md
- src/util/execute-lifecycle-script.js
This fixed the remaining `NODE_OPTIONS` reference missed by #6942.
> fix(pnp): make sure pnp module is again the first preloaded module.

- CHANGELOG.md
- __tests__/package-compatibility.js
- packages/pkg-tests/pkg-tests-specs/sources/basic.js
- src/cli/commands/install.js
- src/package-compatibility.js
**Summary**
This change ensures that the `cpu` and `os` requirements are checked if they are present in the `package.json` even when the package does not specify any `engines` requirements.
Fixes #6948 
**Test plan**
package.json:
```json
{
"cpu": ["i32"],
"os": ["win32"]
}
```
Running the following commands on a mac osx machine:
```bash
../bin/yarn
yarn install v1.15.0-0
warning package.json: No license field
[1/5] 🔍  Validating package.json...
error @: The platform "darwin" is incompatible with this module.
error @: The CPU architecture "x64" is incompatible with this module.
error Found incompatible module
```
```bash
../bin/yarn --ignore-platform
yarn install v1.15.0-0
warning package.json: No license field …
```
> Check os and platform even when engines is not present in package.json

- src/cli/index.js
The `release` signature is incorrect, because its first argument is a callback function that will be called when the release is done. By attaching it to the `run()` promise however, release will be called with the exit code as argument. When the exit code is `1`, the code will crash. 
This is very rare, but we’re seeing this when calling yarn from another node process (and possibly killing it too soon):
```
<redacted>/node_modules/yarn/lib/cli.js:78119
callback();
^
TypeError: callback is not a function
at options.fs.rmdir (<redacted>/node_modules/yarn/lib/cli.js:78119:9)
at FSReqWrap.oncomplete (fs.js:141:20)
```
> Don’t call `release` with an exit code

- CHANGELOG.md
- src/config.js
Fixed potentially mismatching casing of drive letters in win32 pnp check by toLowerCasing both strings.
Fixes #7005
> fix: drive letter casing for win32 pnp

- src/package-hoister.js
**Summary**
Includes the key that we expected to find hoisted in the tree in the invariant message.
**motivation**
I hit this invariant.  I wanted to know what package "caused" it.
**Test plan**
Ran this in "broken" yarn environment
> Include key info for "expected hoisted" invariant

- CHANGELOG.md
- src/cli/commands/version.js
**Summary**
As proposed in #7050. This allows cancelling `yarn version` with ctrl-c or empty version number.
**Test plan**
Run `yarn version`
Press Ctrl-C without entering a new version number
Yarn exits (no longer with an error message)
Run: `yarn version`
Press enter without entering a new version number
Yarn exits (no longer saying error Invalid semver version)
> feat: allow cancelling yarn version with ctrl-c or empty version number

- CHANGELOG.md
- __tests__/commands/config.js
- src/config.js
- src/registries/yarn-registry.js
**Summary**
Close #5637. Allow `global-folder` to be set in `.yarnrc`, and be used if `--global-folder` is not set. Fallback setting remain unchanged.
**Test plan**
> fix(config): allow global-folder to be set in .yarnrc

- CHANGELOG.md
- src/cli/commands/upgrade.js
**Summary**
Fix bug #7079 of `basicSemverOperatorRegex`. It doesn't match the range operator correctly if the dependency range is specified with `>=`. For example, when running `yarn upgrade --latest`, if a dependency is specified with `>=`, the matched result will be `>`, which is not correct. 
This is because the regular expression engine looks for alternations one-by-one. We can fix it by putting `>=` before `>`.
fixes #7079 
**Test plan**
> fix(upgrade) Fix basicSemverOperatorRegex

- CHANGELOG.md
- __tests__/registries/npm-registry.js
- src/registries/base-registry.js
Fixes #4682
**Summary**
Passing `npm_config_` environment variables changed all underscores (`_`) to dashes (`-`) which isn't correct behavior for special config variables (`_auth`, `_authToken`, `_username` and `_password`). An additional check was added to `base-registry.js` to filter out these config keys from this processing.
**Test plan**
`yarn test` - all tests passed except two tests that have nothing with my change - they are integration tests (I assume my environment isn't set up correctly for these to pass? Maybe CI will verify?)
> fix: handle npm prefix config environment variables

- CHANGELOG.md
- src/reporters/console/console-reporter.js
**Summary**
Fixes the link provided in the “More info” row when running `yarn audit`.
The Node Security Platform (nodesecurity.io) [was acquired by npm](https://medium.com/npm-inc/npm-acquires-lift-security-258e257ef639) in April 2018. [nodesecurity.io/advisories](https://nodesecurity.io/advisories) is no longer available nowadays, however, all security advisories are available on [npmjs.com/advisories](https://www.npmjs.com/advisories).
**Test plan**
```console
$ yarn audit
yarn audit v1.15.0-0
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash …
```
> Fix link to security advisory

- CHANGELOG.md
- src/config.js
- src/util/execute-lifecycle-script.js
**Summary**
#6382 makes the previous behavior of prepending the node path obsolete. This PR cleans up the bugs noted in #5935 and partially addressed in #6178. This PR supersedes #6213.
It makes two basic changes:
* remove the now-unused scriptsPrependNodePath config option.
* remove the code that prepends the node exec path in certain situations.
> Clean up node path prepending

- __tests__/commands/install/bin-links.js
**Summary**
#6954 disabled the creation of `.cmd` files, but forgot to update the Windows tests (it went unnoticed because we hard an appveyor issue that temporarily prevent us from receiving updates).
This diff simply updates the expectation to account for the `.cmd` file not being created anymore.
**Test plan**
CI should now pass.
> Fixes the Windows tests

- CHANGELOG.md
- __tests__/commands/audit.js
- src/cli/commands/audit.js
**Summary**
This pull request implements the feature requested in #6668.
It basically adds a `--level` flag to the audit command allowing to filter the audit output by severity greater than or equal to the provided value which can be (info, low, moderate, high or critical).
**Test plan**
Example:
```sh
yarn audit --level high
```
This outputs all advisories ranked `high` and `critical`.
By default without this new flag, the audit command will behave as it always did.
> feat(audit): add filtering by severity level

- CHANGELOG.md
- src/cli/index.js
add Terminus to the list of supported terminal emulators for emoji
Since [Terminus](https://eugeny.github.io/terminus/) is also a xterm.js terminal emulator (same as [Hyper](https://hyper.is/)), and recently [it sets](https://github.com/Eugeny/terminus/commit/e246e22bfd51b1ee5e9e97a391ba6f51230070bb) `TERM_PROGRAM` to `Terminus` (like how Hyper sets it to `Hyper`), it is proper for Yarn to display Emojis also on Terminus.
Notice the `✨` emoji on the last line:
> Allow Terminus to also display emojis

- CHANGELOG.md
- src/cli/commands/create.js
**Summary**
Fixes #5063.
When a user is running a package via `yarn create` or `npx`, the package is unable to determine whether it was yarn that launched the package. This is useful for running additional yarn commands in the repo over npm-based ones.
**Test plan**
> Add environment variables to spawned create process

- CHANGELOG.md
- src/util/request-manager.js
**Summary**
yarn install randomly fails with a ETIMEDOUT error even though we have not reached the user defined timeout. In some cases, ETIMEDOUT error is not due to user defined timeout but to network instabilities, in such cases we should retry connecting (as we already do for ESOCKETTIMEDOUT errors)
**Test plan**
We tested this fork in production for a few days, no new issues or perf regression was observed, and the issue was fixed.
> Retry on connection timeout

- CHANGELOG.md
- __tests__/fetchers.js
- src/fetchers/tarball-fetcher.js
**Summary**
Fixes https://github.com/yarnpkg/yarn/issues/7199
**Test plan**
I added a new test case to `__tests__/fetchers.js` for NPM Enterprise URLs.
> Support NPM Enterprise URLs in offline mirror filename calculation.

- __tests__/lockfile.js
- src/cli/index.js
- src/lockfile/parse.js
**Summary**
In preparation for the v2 (which is yaml-like), I've slightly relaxed the parser so that the following construct wouldn't generate parse errors:
```
yarnPath: .yarn/releases/yarn-1.15.2.js
```
This will make it easier for v2 users to revert back to the v1 if they need to.
**Test plan**
Tested locally.
> Tweaks the yarnrc syntax parser

- CHANGELOG.md
- __tests__/pipe.js
- src/cli/index.js
**Problem:** when yarn outputs to a pipe, it is sensitive to the pipe closing prematurely. If the pipe is closed before output is finished, a noisy error message appears on stderr.
It appears all commands with reporter output are affected. (`yarn help` appears to be unaffected, for example.)
**Expected:** yarn should handle the broken stdout pipe error quietly and complete its work (and exit with whatever status it would have otherwise).
**To reproduce:** trivial examples on node versions 8.x through 11.x, using `head` to truncate output before the last line:
```
$ yarn versions | head -n 16
yarn versions v1.15.2
{ yarn: '1.16.0-0',
http_parser: '2.8.0',
node: '8.15.1',
v8: '6.2.414.75',
uv: '1.23.2',
...
tz: '2017c' }
events.js:183
throw er; // Unhandled 'error' event
^
Error: write …
```
> Handle EPIPE on stdout gracefully

- src/cli/commands/install.js
- src/util/yarn-version.js
Currently, portage is not an enumerated installation method for yarn despite being available through that package manager (ref: https://packages.gentoo.org/packages/sys-apps/yarn). This means that the update notification is wrong for users that install yarn via portage.
To prevent this, I added portage as a installation method and provide a portage-specific update notification.
Note: a patch to the Gentoo ebuild (package build script) for yarn makes this useful: https://github.com/gentoo/gentoo/pull/11395
Test:
I forced an update to be "available" by overwriting the `latestVersion` to be '1.17.0' and removing all of the frequency checks etc to force the message to appear when yarn is run:
```
warning Your current version of Yarn is out of date. The latest version is "1.17.0", while you're …
```
> Add installationMethod for portage (Gentoo Linux)

- CHANGELOG.md
- __tests__/lockfile.js
- package.json
- src/lockfile/parse.js
- src/util/request-manager.js
- yarn.lock
**Summary**
This PR adds support for Yarn to read Yaml files. This is needed because now that we switch to Yaml in Berry we need the Yarn v1 branch to parse the v2 `.yarnrc` files out of the box (in order to make `yarn-path` work).
Note that the Yaml support here is fickle and purely for reading (emitted files are still using the custom format). In particular, defining a lockfile using the Yaml syntax wouldn't work because the keys are not split on commas.
Ref https://github.com/yarnpkg/berry/pull/183
**Test plan**
Added a test.
> Adds support for parsing Yaml files

- __tests__/commands/install/resolutions.js
- __tests__/fixtures/install/resolutions/optional-deps/package.json
- src/cli/commands/check.js
- src/cli/commands/install.js
Fixes #6040
**Summary**
Resolutions are a required for installing when there is a matching pattern in the resolutions map. When the resolver tries to dedupe dependencies and finds an optionalDependency that matches a resolution pattern, they merge into one no-longer optional request. This PR has resolutions inherit `optional` property if the dependency exists in the top level package.json. 
**Test plan**
I've added a test case under resolutions
> fix(install): Inherit optional property for resolutions

- CHANGELOG.md
- __tests__/fixtures/index/run-global-add-offline/package.json
- __tests__/index.js
- src/cli/commands/global.js
**Summary**
Adds support for --offline flag to global add command. 
Previously, this argument was ignored, resulting in issue #4913.
**Test plan**
Observe below how yarn currently goes to network when --offline is set with global add:
```
$ yarn --offline global add packagethatdoesnotexist@1.0.0
yarn global v1.16.0
error An unexpected error occurred: "https://registry.yarnpkg.com/packagethatdoesnotexist: Not found".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\fcrick\\AppData\\Local\\Yarn\\Data\\global\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```
With fix, it now suggests running without `--offline`
```
$ node ./bin/yarn.js --offline global …
```
> fix(config): Adds support for --offline flag to global add command

- src/cli/commands/login.js
**Summary**
Related issue: https://github.com/yarnpkg/yarn/issues/6258, and PR: https://github.com/yarnpkg/yarn/pull/6411.
Config:
```
// .yarnrc 
registry "https://registry.npm.taobao.org"
```
```
// package.json
"publishConfig": {
"registry": "https://registry.yarnpkg.com/"
}
```
`yarn publish --verbose` Log:  
```
verbose 8.619632385 Performing "PUT" request to "https://registry.npm.taobao.org/-/user/org.couchdb.user:nodece".
verbose 9.237536659 Request "https://registry.npm.taobao.org/-/user/org.couchdb.user:nodece" finished with status code 201.
success Logged in.
......
......
verbose 13.892656022 Performing "PUT" request to "https://registry.yarnpkg.com/egg-authz".
verbose 17.747497997 Request "https://registry.yarnpkg.com/egg-authz" finished with status code 401.
......
...... …
```
> Fix login for `yarn publish`

- CHANGELOG.md
- src/cli/commands/add.js
- src/cli/commands/upgrade.js
**Summary**
Looks like the `--audit` flag has never worked for `add` and `upgrade` due to a typo.
**Test plan**
> fix(add, upgrade): fix audit flag

- src/resolvers/exotics/link-resolver.js
**Summary**
The current code tries to read the manifest when possible, and fallback to a dummy object otherwise. This behavior is problematic (we should never read from the local manifest, as that makes the exact behavior change depending on the state of the repository), but we won't be able to change it in the 1.x (it will however behave as I described in the 2.x, thanks to the split between `link:` and `portal:`).
**Test plan**
Tests should still pass.
> Prevents the link: protocol from crashing when no package.json is used

- CHANGELOG.md
- __tests__/commands/version.js
- flow-typed/npm/semver_v5.1.x.js
- src/cli/commands/version.js
**Summary**
This pull request implements the feature requested in https://github.com/yarnpkg/yarn/issues/6059 and https://github.com/yarnpkg/yarn/issues/5367
It adds four new flags (`--premajor|--preminor|--prepatch|--prerelease`) to allow automatic increment of new prereleases.
It also adds a new flag `--preid` to add a custom identifier to the new prerelease
**Test plan**
Example:
```
$ yarn version --premajor --preid beta
info Current version: 1.3.0
info New version: 2.0.0-beta.0
```
I've included Jest test cases for each of the new versioning flags.
This feature only adds new flags and should not modified the previous behaviour of version.
> feat(version): Allow for prereleases flags and prerelease identifiers

- src/rc.js
- src/util/rc.js
**Summary**
Ref: https://github.com/yarnpkg/berry/issues/239
I'm planning to rename `.yarnrc` files into `.yarnrc.yml` in order to avoid problems where configuration for two different syntaxes / documentations would have to be used together. My hope is that it'll help the migration plan become smoother and less unpredictable.
This proposal has one drawback: the `yarn-path` settings. The v1 (which I expect to stay the version in the global path for some time) doesn't know how to read the `.yarnrc.yml` file, and to look for the `yarn-path` settings there. We could make the v2 write the `yarn-path` settings into the old `.yarnrc` file (rather than `.yarnrc.yml`), but that would require to have both `.yarnrc` and `.yarnrc.yml` at the same time when using the v2, which I'd prefer to avoid.
To …
> Adds basic support for .yamlrc.yml (yarnPath only, v2)

- src/cli/commands/login.js
**Summary**
When set `publishConfig.registry` in package.json , revokedToken should use `publishConfig.registry`.
Similar PR: #7312
**Test plan**
Too lazy!
> Add registry paramter to revokedToken request

- CHANGELOG.md
- __tests__/registries/npm-registry.js
- src/registries/npm-registry.js
**Summary**
The npm registry had an outage some time ago and returned `http:` protocols instead of `https:` for various projects. The following diff ensures that we always use https no matter what for both the npm registry and the yarn registry.
**Test plan**
Added unit tests.
> Forces using https for the regular registries

- CHANGELOG.md
- src/util/execute-lifecycle-script.js
**Summary**
Ignores 2 VS Code extension specific `package.json` keys that tend to get large and can cause E2BIG errors. I just moved my vscode extension ([GitLens](https://github.com/eamodio/vscode-gitlens/)) from `npm` to `yarn` hoping this issue (a large `package.json`) wouldn't manifest itself, but sadly it was still an issue.
Here is the original issue I commented on: https://github.com/yarnpkg/yarn/issues/5420#issuecomment-513100428
Fixes #5420 for another instance.
> fix(E2BIG): Ignore potentially large vscode keys

- CHANGELOG.md
- __tests__/commands/version.js
- __tests__/fixtures/version/no-args-no-git-tags/.yarnrc
- __tests__/fixtures/version/no-args-no-git-tags/package.json
- src/cli/commands/version.js
**Summary**
After battling `yarn` for a while, trying to get the `postversion` lifecycle method to run without committing the new version, I found #5358 which indicated that it actually doesn't run when opting out committing the changes. The documentation doesn't indicate that a commit is needed for `postversion` to run so at least I assumed that I wouldn't need to commit in order for `postversion` to run. According to the previously mentioned issue there seems to be some people sharing my confusing around this. My use case for wanting `postversion` to run without committing is that I need to update other files before creating a commit.
**Test plan**
I tested using the following steps:
- Edited the `scripts` section of `package.json` and added `preversion` and `postversion`:
```js
{ …
```
> Always run postversion lifecycle method

- CHANGELOG.md
- __tests__/fetchers.js
- src/fetchers/git-fetcher.js
**Summary**
When installing a git dependency with the `NODE_ENV` environment variable set to `production`, yarn did not run the `prepare` lifecycle script, because `config.production` would default to true, and then `wrapLifecycle` would skip `prepare`:
https://github.com/yarnpkg/yarn/blob/b6569538de69e0ccd201f0a33f1f5b52f2656f5b/src/cli/commands/install.js#L1202-L1207
This is contrary to npm's behavior and the intent of `GitFetcher#fetchFromInstallAndPack`, which is to install the dependency with its devDependencies and run all the relevant lifecycle scripts (excluding `prepublish`), regardless of the configuration or environment settings of the parent install command.
**Test plan**
Added an automated test.
cc @Volune, who added the original feature in #3553. Thanks for the test case …
> Run the prepare script of git dependencies even if NODE_ENV=production

- src/package-compatibility.js
**Summary**
Parcel requires plugins to use engines.parcel to specify the Parcel version the plugin supports.
Currently yarn is throwing warnings for this, this PR adds parcel to the ignore list so this no longer happens.
See: https://github.com/parcel-bundler/parcel/blob/master/PARCEL_2_RFC.md#engines
**Test plan**
> Add Parcel to the engines ignore list

- __tests__/fixtures/index/run-failing-script/package.json
- __tests__/index.js
- __tests__/integration.js
- src/cli/index.js
Fixes #5359
If sub commands called via `yarn run` fail yarn typically logs `error Command failed with exit code 1.` even if `--silent` is requested basically because a failing command throws (or rethrows) itself instead of just returning this failure as valid output. 
This is the simplest patch to suppress this output.
> Do not log `err.message` of `ProcessTermError`s if silent

- CHANGELOG.md
- __tests__/fetchers.js
- src/fetchers/tarball-fetcher.js
Fixes for `tarball` contains `%2f` instead of `/`
Sample: `http://npm.xxxyyyzzz.ru/@types%2fevents/-/events-3.0.0.tgz`
Issue: #7498
> Fixes offline mirror filename calculation for scoped packages URLs in Verdaccio (private npm repository)

- CHANGELOG.md
- src/resolvers/exotics/link-resolver.js
**Summary**
Using `link:.` currently generates an infinite loop (because we load the dependencies from our own folder, then from our own folder, then from our own folder, then ...).
**Test plan**
Added such a pattern to the Yarn repo and checked that it works.
> Fixes link:.

- CHANGELOG.md
- src/cli/commands/create.js
- src/resolvers/exotics/link-resolver.js
Currently, `yarn create` does not respect an existing package linked with `yarn link`, and will instead overwrite the package in development with the latest version from the registry. With this fix, the package will only be installed if it isn't already linked, allowing users to use `yarn create` to develop locally linked packages without removing their global link. This matches the functionality of `npm init` and `npm create` with linked packages.
Package is not installed globally and linked package is used instead
```
$ cd PACKAGE_SOURCE
$ yarn link
yarn global v1.18.0-0
success Registered "PACKAGE".
info You can now run `yarn link "PACKAGE"` in the projects where you want to use this package and it will be used instead.
$ yarn create PACKAGE_SUFFIX --version
yarn create v1.18.0-0 …
```
> Preserve linked packages in create command

- CHANGELOG.md
- src/cli/commands/install.js
- src/reporters/lang/en.js
**Summary**
This PR adds a new info message when people use Plug'n'Play, suggesting to give the Yarn v2 development trunk a try.
This is because most of the recent development happened there, and we want to get early feedback from a subsection of our users before putting it out of beta (which will likely happen before the end of the year).
**Test plan**
> Adds a message when people use PnP

- src/cli/commands/run.js
- src/util/hooks.js
**Summary**
This diff adds a (still undocumented, just like the existing ones) hook that gets triggered each time a `yarn run` command would run. This makes it possible to get basic informations about the scripts that are used the most, etc (note that this is not related to any kind of telemetrics - it's just a callback that you, as users, can set to whatever you want).
> Adds an undocumented run hook

- src/util/normalize-manifest/resolve-relative.js
**Summary**
There was a remaining bug after #7512 where the lockfile would contain an entry for `link:./.` instead of `link:.`. This caused issues with some software expecting the path to match the manifest (Snyk).
> Fixes link self

- __tests__/fixtures/install/install-production/yarn.lock
- __tests__/package-resolver.js
- src/config.js
**Summary**
When installing a package, Yarn used to always store it based on it's old sha1 checksum. To prevent cache injection issues, we started checking that the cache was in a consistent state before installing it. Unfortunately, it means that various errors are reported when packages got installed without integrity fields and later need to be installed with an integrity field.
This diff fixes that by using different folders for those two use cases. It's slightly worse for performances (since some packages will be downloaded twice in this very specific situation), but much better from a UX perspective.
Note that the real fix will come with the v2, since the cache system will be completely different and won't suffer from this kind of problems.
Fix #7584
**Test plan**
Tested locally.
> Use different folders with integrity or without

- src/cli/index.js
**Summary**
Running `yarn` with a specific version of Node would fail to propagate this Node binary to the binary targeted by `yarn-path` when the `yarn-path` setting was used.
This diff changes the execution order so that we first try to execute the process through Node before running it as a regular binary.
> Fixes Node forwarding w/ yarn-path

- .circleci/config.yml
**Summary**
- sets the required xcode version to 11 -> this gets us a more up to date macOS version 
- keeps xcode 9 for node 6 as that isn't available in the homebrew associated with xcode 11 anymore
- removes the `brew update` from the macOS node 10 job
- ✖️no update of the changelog - as merging this PR won't modify yarn's behaviour
As a bonus the CI for node 10 on circleci/ macOS got 15 - 20 minutes faster.
**Why, though?**
The circle ci job for macOS on node 10 currently fails because it takes too long (both PR's #7649 and #7650 don't green because of that). Cause: the job uses a big chunk of time updating homebrew (up to ~20min). Which is necessary because the version of macOS (the one connected to xcode 9 => macOS 10.12) does not contain node 10 by default.
Using a more recent …
> ci(circleci): prevent timeout on circle-ci macos node10 build

- CHANGELOG.md
- src/cli/commands/init.js
- src/cli/commands/policies.js
- src/rc.js
**Summary**
Initializing projects using Yarn v2 is fairly annoying when the v1 is the global binary (which it often is), since you need to first run `yarn init`, then `yarn policies set-version`, then change the `package.json` to match what you'd expect if the v2 was initialising the project.
To streamline the process, the `--install` flag will automatically call `yarn policies set-version` followed by `yarn init`.
**Test plan**
n/a
> Adds support for --install in yarn init

- __tests__/__snapshots__/normalize-manifest.js.snap
- __tests__/fixtures/normalize-manifest/dangerous bin name/actual.json
- __tests__/fixtures/normalize-manifest/dangerous bin name/expected.json
- __tests__/fixtures/normalize-manifest/dangerous bin values/actual.json
- __tests__/fixtures/normalize-manifest/dangerous bin values/expected.json
- __tests__/fixtures/normalize-manifest/empty bin string/expected.json
- src/reporters/lang/en.js
- src/util/normalize-manifest/fix.js
- src/util/normalize-manifest/util.js
**Summary**
In some circumstances Yarn would allow overwriting files on the filesystem with symlinks at install-time. Despite postinstall scripts having the ability to do that anyway this behavior isn't intended as Yarn installs are reputed to control side effects (the cache and temporary folders being the only exception). Bins shouldn't be able to escape the package because of Yarn.
**Test plan**
Adding tests
> Fixes bin overwrites

- __tests__/fixtures/index/run-suggestion/package.json
- __tests__/index.js
- src/cli/commands/run.js
At some point the `scripts` object changes to be a map instead of an array, at which point the suggestions functionality broke. This commit includes the fix and a test to make sure it doesn't break again.
> Fix suggestions for CLI

- CHANGELOG.md
- __tests__/commands/workspace.js
- __tests__/commands/workspaces.js
- __tests__/fixtures/index/run-workspace/packages/workspace-child-1/package.json
- __tests__/fixtures/index/run-workspace/packages/workspace-child-2/package.json
- __tests__/fixtures/request-cache/GET/gitlab.com/leanlabsio/kanban/raw/7f21696fb9d08130dd62abd96c9572f513c05301/package.json.bin
- __tests__/index.js
- src/cli/commands/workspace.js
- src/cli/commands/workspaces.js
- src/cli/index.js
fixes #7776 
**Summary**
Arguments following a `--` when running `yarn workspaces run ...` and `yarn workspace package run ...` were not being forwarded to the scripts.
Removed the `commander.originalArgs` nonsense that I introduced in a previous PR, and changed the `workspace` and `workspaces` commands to use `args` as already passed instead.
The `yarn run` command used `args` so it makes sense for `workspace run` to use `args` too.
I had to modify `src/index.js`'s check for commands that should forward args and add `workspace` and `workspaces` to it. Again this is in-line with what already happened for the normal `yarn run` command.
As an added bonus, the normal `scripts don't require "--"` warning that `yarn run` normally prints, is now printed for `workspace` commands (it was not …
> fix(workspaces): Pass args following "--" when running workspace scripts

- __tests__/__snapshots__/normalize-manifest.js.snap
- __tests__/fixtures/normalize-manifest/dangerous bin name/actual.json
- __tests__/fixtures/normalize-manifest/dangerous bin name/expected.json
- src/util/normalize-manifest/fix.js
**Summary**
Bin regex is too restrictive at the moment. See comments [here](https://github.com/yarnpkg/yarn/pull/7755).
**Test plan**
Use `dangerous bin name` tests.
> Allow dots in bin names

- src/cli/commands/init.js
- src/cli/commands/policies.js
- src/cli/index.js
**Summary**
This command implements the `yarn set version [...]` alias for `yarn policies set-version` without breaking people who already have a `yarn set` script. This will make the transition workflow much smoother since the same commands will work on both versions.
> Implements set version

- src/cli/commands/policies.js
- src/reporters/lang/en.js
- src/util/request-manager.js
**Summary**
Right now `policies set-version` does not handle invalid scenarios where an invalid github token is provided or the request fails.
**Test plan**
Will add a test that mocks a 401 from Github's API and that the reporter correctly logs.
> handle failed policy set-version

- src/fetchers/tarball-fetcher.js
**Summary**
In some circumstances it was possible to write files anywhere on the disk when running `yarn install`. Although it's not that much of an issue considering that most installs are done with postinstall scripts, we don't want that to happen precisely to guarantee some level of safety for people actually using `--ignore-scripts`.
**Test plan**
Will add tests after the release.
> Fixes arbitrary file write on fetch

- src/cli/commands/policies.js
- src/lockfile/parse.js
- src/rc.js
- src/util/rc.js
**Summary**
The `.yarnrc.yml` settings were ignored when the syntax was erroneous, causing it to accidentally run a Yarn 1.x install.
This diff fixes that so that invalid RC files will always throw exceptions. It also fixes the `yarn set version` command to print relative paths rather than absolute.
**Test plan**
Tested locally.
> Makes the CLI 2 forwarding stricter

- src/cli/index.js
**Summary**
Sigint should be ignored when forwarding a process, because otherwise the outermost process (ie the global Yarn) will exit before the innermost process (ie the local Yarn) has finished its work.
**Test plan**
Tested locally.
> Prevents exiting the process on sigint through yarn-path

- CHANGELOG.md
- src/cli/commands/pack.js
**Summary**
Running `yarn pack` on Windows and Unix systems produce different results, since on Unix systems the files are sorted while on Windows they aren't.
Running `yarn pack` on https://github.com/arcanis/babel-plugin-lazy-import produces this output on Windows
```sh
$ tar -ztf babel-plugin-lazy-import-v1.0.0.tgz
package
package/index.js
package/package.json
package/README.md
```
While on Unix it produces
```
$ tar -ztf babel-plugin-lazy-import-v1.0.0.tgz
package
package/README.md
package/index.js
package/package.json
```
This PR fixes this by telling `tar-fs` to sort the files before it packs them. `yarn pack` also included the `.yarnrc.yml` config file so I added it to the `DEFAULT_IGNORE` list.
**Test plan**
Run `yarn pack` in a repository containing multiple files and check that …
> fix(pack): sort files to produce identical output on Windows and Unix

- CHANGELOG.md
- src/cli/commands/policies.js
**Summary**
This improves the experience of working with yarn in workspaces that are marked as `"type": "module"` in the package.json file.
This change has also been applied in yarn 2, see yarnpkg/berry#1354
**Test plan**
Everything continues to work.
Even in node versions that don't explicitly support `.cjs` files, any unrecognised file extension is assumed to be javascript and as such any node version can load yarn as `.cjs` file.
> Store local yarn versions as .cjs files

- src/cli/index.js
**Summary**
Yarn 2 recently switched its local versions from the `.js` extension to the `.cjs` extension to improve support for workspaces marked as `"type": "module"` in the `package.json`. These should also be executed by `process.execPath` instead of falling back to the node version on the PATH.
https://github.com/yarnpkg/berry/pull/1354
This doesn't change anything the user will notice (berry with `.cjs` extension hasn't been released yet) so unsure what to add to changelog, if anything.
**Test plan**
ø
> Spawn local yarn .cjs files also using process.execPath

- scripts/build-dist.sh
- scripts/preinstall.js
- scripts/update-dist-manifest.js
**Summary**
Cf the comment in the preinstall script for more details.
Ref: https://github.com/arcanis/pmm/issues/6
**Test plan**
It's difficult to test in real circumstances given the our test pipelines. Will build the archive and publish it as a different name before landing it.
> Add a preinstall script to bypass npm's ownership check

- package.json
- scripts/build-webpack.js
- src/cli/commands/policies.js
- src/cli/index.js
- src/rc.js
- src/reporters/lang/en.js
- src/util/child.js
- yarn.lock
Fixes #8793 
Fixes #8965
Fixes #9005
- Punycode is now embed within the bundle, as it has been deprecated by Node.js and will be removed in a future version.
- A message will be displayed when Yarn 1.22 notices that the local project has a `package.json` file referencing a non-1.x Yarn release. The message will explain that the project is intended to be used with [Corepack](https://nodejs.org/api/corepack.html).
- I removed the `yarn-error.log` generation. Given that we don't process non-critical 1.x bug reports, they are now mostly an annoyance.
- The `yarn set version x.y.z` command will now install the exact `x.y.z` version (prior to this change it used to first install the latest version, and only in a second step would it downgrade to `x.y.z`; this was causing issues when we bump the …
> Hotfixes for the 1.22.20

- src/cli/index.js
- src/lockfile/index.js
The lockfile hydration code is trying to unify similar lockfile entries:
```
"strip-ansi-cjs@npm:strip-ansi@^6.0.1", strip-ansi@^6.0.0, strip-ansi@^6.0.1:
version "6.0.1"
resolved "https://registry.yarnpkg.com/strip-ansi/-/strip-ansi-6.0.1.tgz#9e26c63d30f53443e9489495b2105d37b67a85d9"
integrity sha512-Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==
dependencies:
ansi-regex "^5.0.1"
```
However, when this file is read, the code was hydrating a single copy of the package, using a single name (others were dropped). This was causing strange behaviours when generating the hoisting, as the wrong package names were used to prevent incompatible version overrides.
> Fixes the lockfile hydration of the `npm:` protocol
