src/lockfile/parse.js

fix typo: self-udpate => self-update

---

src/reporters/lang/en.js

fix typo: enoguh -> enough

---

CONTRIBUTING.md

**Summary**
Adds a link back to the LICENSE file for convienence

add link to LICENSE file

---

scripts/build-dist.sh

Set the correct filename for the npm package

---

src/cli/commands/why.js
src/reporters/lang/en.js

**Summary**
solves #737
**Test plan**
`yarn why`

Add info for `yarn why` command

---

src/constants.js

out dated comment: no more kpm/fbkpm

---

src/fetchers/base-fetcher.js

**Summary**
Clean up and util function utilization
**Test plan**
Change is already tested by existing base-fetcher coverage

fix base-fetcher: use proper util to stringify, clean up imports

---

src/cli/commands/why.js

**Summary**
MessageError was missing from `src/cli/commands/why.js` from PR #741. This will probably cause it to not work as intended. Plus it was causing errors from the linter.
**Test plan**
I don't think any is needed.

Include MessageErrors class

---

README.md

Revert "Add ied as prior art"

---

src/cli/commands/global.js

use console.log instead of reporter.log - fixes #851

---

gulpfile.js

**Summary**
This PR lints the following files:
- `gulpfile.js`: remove unused variables
- `scripts/eslint-rules/index.js`: remove trailing commas

Lint: remove trailing commas and unused vars

---

README.md

**Summary**
The issue #900 mentions the grammatical error in line#20 of `README.md`. This pull request fixes that grammatical error.
**Test plan**
Since it's just an edit to `README`, no test plan is needed.

Fix grammatical error mentioned in #900

---

appveyor.yml

**Summary**
Adds Windows installer build to AppVeyor config
**Test plan**
See successful build on AppVeyor: https://ci.appveyor.com/project/kittens/yarn/build/1.0.65/job/08nf173s9hao0dx1/artifacts

Build installer on AppVeyor

---

__tests__/fixtures/normalize-manifest/throw name non-string/expected.json
src/cli/commands/pack.js
src/cli/index.js
src/config.js
src/errors.js
src/package-fetcher.js
src/package-request.js
src/reporters/lang/en.js
src/util/normalize-manifest/fix.js
src/util/normalize-manifest/validate.js
src/util/request-manager.js

Don't leak stack traces into output, write yarn-error.log on unexpected errors - fixes #948.

Nicer unexpected error handling

---

src/cli/commands/login.js
src/registries/npm-registry.js

**Summary**
According to comments and #745 kpm is an old name for yarn 
**Test plan**
N/A

Remove outdated kpm parts

---

circle.yml

**Summary**
Fixes deploy commands, now that yarn is not a JS file

fix deploy script

---

src/reporters/lang/en.js

**Summary**
Fixing a typo
**Test plan**
No test needed
occured -> occurred

fix a typo

---

src/util/request-manager.js

**Summary**
Fixes a typo so as not to distract others reading the source.
**Test plan**
It's just a comment change, so if the tests still pass, we should be good. 😄

Fix typo in comment "occured" -> "occurred"

---

src/cli/commands/install.js

**Summary**
Issue #1199
**Test plan**
Run yarn => verify yarn.lock only contains one new line

fix #1199 by removing extra newline from cli/install.js

---

src/util/normalize-manifest/fix.js

**Summary**
Packages which containes Readme, Authors or License folders (ex. `sjcl` or `object-merge`) in their main folder cannot be installed with yarn.
This PR fixes this bug(#680) by checking the files to be really a file before readFile.
**Test plan**
Actual:
`yarn add sjcl` or `yarn add object-merge` fails
After this PR:
`yarn add sjcl` or `yarn add object-merge` works

fix #680 check README, LICENSE and AUTHORS are files.

---

src/cli/commands/init.js

Summary
I made use of the existing package name validation and put this inside a loop to enforce valid names, i.e. no spaces.
Fixes #1268

Validate name upon init. Fixes #1268 

---

__tests__/commands/init.js
src/cli/commands/init.js

1. squash 1382 down
2. add test coverage 
3. make the author and email check more explicit for undefined
4. rename config fn getter to be more obvious

Builds on #1382

---

src/cli/index.js

**Summary**
The output of `yarn help` lists these options, but there is no description (making it difficult to understand the proper usage).
**Test plan**
Used summary from https://github.com/yarnpkg/yarn/issues/170 and https://github.com/yarnpkg/yarn/commit/675fc5b187e0377430dc17b6eee5dd0ccd5b09fa to create documentation.

Document `--prefer-offline` and `--offline` flags.

---

README.md

**Summary**
There were very small errors in the `README.md` that I wanted to clean up.
**Test plan**
No code was changed for this PR

Small grammar and spacing fixes

---

src/cli/commands/version.js

**Summary**
Fixes #1228 
**Test plan**
1. Committing without the `--no-git-tag-version` flag does not commit to github
2. Committing with the `--no-git-tag-version` flag commits to github

Add an option to not commit to git. Fixes #1228

---

__tests__/__snapshots__/fetchers.js.snap
__tests__/fetchers.js
src/config.js
src/fetchers/git-fetcher.js
src/fetchers/tarball-fetcher.js
src/reporters/lang/en.js

**Summary**
Continuing with https://github.com/yarnpkg/yarn/issues/1387  now on config and fetchers files
**Test plan**
Added a test for git fetch local not found .. and update snapshot of hash error on tarball test
But not able to test the more complex cases like `fetchErrorCorrupt` or `errorDecompressingTarball`

Use reporter for error messages on fetchers and config

---

src/cli/index.js
src/config.js
src/util/execute-lifecycle-script.js

Set node env to production with --prod install.

---

src/cli/aliases.js

Update aliases.js  (#1621)

---

src/cli/commands/add.js

Fixed a flag hyphen issue which was merged with #1618

Fixed add command flag

---

.github/ISSUE_TEMPLATE.md

**Summary** Stop silly people like me submitting issues in the wrong place: https://github.com/yarnpkg/yarn/issues/1646#event-846382701
**Test plan** Merge, see if people still submit substantial feature requests to this issue tracker

Add helpful nudge to yarnpkg/rfcs on issue template

---

src/util/fs.js

I am very new to contributing to the open source world so please go easy on me :)
**Summary**
Fixes #923.  When identifiying build artifacts to copy to the cache, both directories and their children are potentially passed to copyBulk.  For example, in the case of phantomjs-prebuilt on Windows it passes:
/lib
/lib/phantom
/lib/phantom/bin
/lib/phantom/bin/phantomjs.exe
... (several others)
As copyBulk process those items, for the 3 directories above it also processes all children.  As such it will identify phantomjs.exe 4 times and copy it 4 times (potentially in parallel).  On Windows this appears to create a race condition in certain situations causing an error on the writeStream.
This PR keeps track of all destinations currently being written to and prevents writing to the same …

Prevent parallel writes to the same destination

---

__tests__/commands/add.js

Added a skipped test for issue #1733.
Fix is a bit involved and is coming in a following PR

added a test for #1733

---

circle.yml

fixes #1203.
ghr should be downloaded outside of the project source

moved ghr out of project

---

__tests__/commands/install.js

made test non concurrent + fixed lint

---

__tests__/cli/aliases.js

**Summary**
Tests broke in this commit: https://github.com/yarnpkg/yarn/commit/b6f3aec6b6fb4c2186cbf70e2d3701ac755f04b4
**Test plan**
All tests pass.

Fix cli aliases test

---

scripts/build-dist.ps1
scripts/build-dist.sh
scripts/clean-node-modules.ps1
scripts/clean-node-modules.sh

Remove crappy folders from node_modules in dist tarballs

---

src/cli/commands/global.js

Fix `expected manifest` on global add

---

src/cli/index.js

**Summary**
This PR resolves issue #1857.

Include description for --ignore-optional

---

__tests__/commands/global.js

**Summary**
Add very basic test for `global add` which covers #1840
_I will try to cover the rest as soon as I can._

Add very basic test for global add

---

__tests__/commands/install.js

made test cross platform

---

src/cli/commands/upgrade-interactive.js

Makes it easier to see what exactly was changed: path, minor or major part.
I found no tests for interactive upgrade, so no new test in this PR.
Before:
After:

Only highlight changed part of the version in upgrade-interactive

---

CONTRIBUTING.md

**Summary**
This PR allows potential contributors to get started faster.
**Test plan**
I ran these commands myself to setup a new fork for contributing.

Update CONTRIBUTING.md to reflect the necessary steps

---

__tests__/fixtures/request-cache/GET/localhost/.bin

It is already in .gitignore but needs to be removed from repo.

removed /localhost/.bin from git so that it is not conflicting anymore

---

src/config.js

**Summary**
I got an error when running the 
`yarn licenses ls `
error Couldn't find a package.json file in ...
Trying to understand the code in config.js was quite painful.
So i decided to add some documentaion to these two methods so other developers will understand the 
code better.
**Test plan**

Better documentation for the readMenifest method and  maybeReadManist

---

__tests__/package-compatibility.js
src/cli/commands/run.js

**Summary**
- `__tests__/package-compatibility.js`
- `src/cli/commands/run.js`
^^ those two files still had LICENSE headers, the rest of which were removed by 46e8be5a9b5e692ac9307a79342d0c1e03ffc3da
**Test plan**
n/a

Removes patent/license boilerplate from last two remaining files

---

.gitattributes

**Summary**
I kept on getting `warning: CRLF will be replaced by LF in __tests__/fixtures/add/install-deterministic/mirror-for-offline/mime-db-1.0.3.tgz.` after every single command in the repo.
**Test plan**
N/A

Set tgz files as binary in git

---

package.json
yarn.lock

**Summary**
Bumps `proper-lockfile`.
**Test plan**
Shouldn't be any different.

Bump `proper-lockfile`.

---

package.json

A quick fix to package building

[CI] flow is a dev dependency, removed it from prod dependencies, broken in #2307

---

.travis.yml
appveyor.yml
circle.yml
package.json

Tests on Travis OSX are unstable: too many timeout issues.
I've made OSX builds run in 1 thread mode and others kept in 3 threads

[CI] Configured Travis OSX builds to run in 1 thread for stability

---

src/constants.js

**Summary**
Make comment match up with code below.

constants: Fix file path comment

---

__tests__/package-resolver.js

**Summary**
Enabled most packager-resolver tests.
Npm-ml tests needs to be either replaced by others or fixed.

[CI] enabled package-resolver tests

---

scripts/build-deb.sh

ref https://github.com/yarnpkg/yarn/pull/2441
ping @bestander

remove hack in deb builder script

---

__tests__/fixtures/lifecycle-scripts/dont-expose-internal-configs-to-env/log-configs.js
__tests__/fixtures/lifecycle-scripts/dont-expose-internal-configs-to-env/package.json
__tests__/lifecycle-scripts.js
src/util/execute-lifecycle-script.js

Treat some configs as internal to fix #2286.

---

.gitignore

**Summary**
Just like #2325 .DS_store should be a global gitignore because it's machine specific and nothing to do with yarn or JS.
**Test plan**
N/A

Remove .DS_store this should also be in a global .gitignore

---

src/util/normalize-manifest/util.js

**Summary**
Fixes issue from #2527 
**Test plan**
ran `./bin/yarn init` on a new project with no repos
With origin remote added 
And with repo existing in package.json

Fixes yarn init showing [object Object]

---

package.json
yarn.lock

**Summary**
Bumps `strip-bom` from `^2.0.0` to `^3.0.0`.  Reduces dependency tree (i.e. drops `is-utf8`).
**Test plan**

Bump `strip-bom`.

---

bin/yarn

fix https://github.com/yarnpkg/yarn/issues/2511
ping @bestander

fix readlink usage on mac

---

bin/yarn

@bestander please merge this one too. i made a silly copy & paste mistake. ref https://github.com/yarnpkg/yarn/pull/2560

Fix clause termination

---

package.json
yarn.lock

**Summary**
Bumps `detect-indent` from `^4.0.0` to `^5.0.0`.  `detect-indent@5.0.0` drops the dependency on `repeating`, but this will still be in the dependency graph unless #2569 is approved.  At the very least, it removes an edge from the dependency graph.
**Test plan**

Bump `detect-indent`.

---

package.json
yarn.lock

**Summary**
Removes `eslint-config-kittens`.  It stopped being used with #219, but it's still a devDependency.
**Test plan**

Remove `eslint-config-kittens`.

---

package.json
yarn.lock

**Summary**
Removes `diff`.  It doesn't seem to be used anywhere.
**Test plan**

Remove `diff`.

---

src/cli/commands/install.js

re https://github.com/yarnpkg/yarn/issues/1326#issuecomment-276454732

adds YARN_INSTALL_METHOD for apk (Alpine Linux)

---

.travis.yml

Mac OS fails too often times, adding retries should reduce the noise

CI: added retries to Travis runs

---

__tests__/package-resolver.js

switched git repo for test

---

package.json
scripts/build-webpack.js
yarn.lock

**Summary**
Removes `json-loader`.  `webpack@2` [implicitly understands JSON](https://github.com/webpack-contrib/json-loader#json-loader).
**Test plan**

Remove `json-loader`.

---

__tests__/__snapshots__/fetchers.js.snap
__tests__/reporters/__snapshots__/buffer-reporter.js.snap
__tests__/reporters/__snapshots__/console-reporter.js.snap
__tests__/reporters/__snapshots__/event-reporter.js.snap
__tests__/reporters/__snapshots__/json-reporter.js.snap
package.json
yarn.lock

Unfortunately this doesn't work in node7 but seems to be a bug in jest. It stops execution when testing remove, though returning a 0 exit code.

Update jest to version 19

---

__tests__/commands/add.js
__tests__/fixtures/add/install-git-ssh-mirror/.npmrc
__tests__/fixtures/add/install-git-ssh-mirror/package.json

**Summary**
This PR tries to have a starting point to solve #2333. It reproduces the issue, so it can start a discussion on the solution.
**Test plan**
The test plan should be that this test passes.

Add failing test for issue #2333

---

__tests__/constants.js
__tests__/util/root-user.js
src/constants.js
src/fetchers/tarball-fetcher.js
src/util/root-user.js
src/util/user-home-dir.js

**Summary**
Cherry-pick of PR #2855, in order to include the fix in v0.22.
**Test plan**
Same as #2855.

Move ROOT_USER to a separate file, fixes #2807

---

.flowconfig
package.json
yarn.lock

**Summary**
* Update to the latest flow.
**Test plan**
`flow check`

Upgrade to flow v0.41.0

---

src/cli/commands/install.js

**Summary**
Apologies. I missed this when I rebased for my last pull request.
**Test plan**
N/A

Remove Git conflict markers

---

src/cli/commands/install.js

**Summary**
I don't believe this function is used anywhere.
**Test plan**
Run the existing tests.

Remove unused lockFileInSync function

---

.flowconfig
package.json
yarn.lock

**Summary**
Keeping it fresh. https://github.com/facebook/flow/releases/tag/v0.42.0
**Test plan**
`flow`

Upgrade to flow v0.42.0

---

src/util/git.js

Reverts yarnpkg/yarn#2905
Appveyor got broken https://ci.appveyor.com/project/kittens/yarn/build/1876

Revert "Resolves issues with git+ssh when ssh daemon has banner set."

---

__tests__/index.js

**Summary**/**Test plan**
As described in the title this commit add tests for bin command.

Add test for bin command

---

__tests__/util/request-manager.js
src/util/request-manager.js

As a follow-up to https://github.com/yarnpkg/yarn/pull/2950, this makes `RequestManager ` to accept max number of retries and tests the retry feature (it wasn't tested before) 
@bestander

Test the retry policy of RequestManager

---

__tests__/util/fs.js
src/util/fs.js

**Summary**
Tests for `fs.fileDatesEqual` as requested in the PR introducing it (#2958)
**Test plan**
```
yarn test
```

Add tests to fileDatesEqual function in fs module

---

src/cli/commands/info.js
src/registries/npm-registry.js

fix lints on master

---

src/cli/commands/pack.js

**Summary**
Fix typo: definently -> definitely
**Test plan**
N/A

Fix typo: definently -> definitely

---

__tests__/commands/pack.js
src/cli/commands/pack.js

**Summary**
Fix typo: inlude -> include
**Test plan**
N/A

Fix typo: inlude -> include

---

src/util/fs.js

> There's a bunch of lint warnings on master introduced by this PR, could you open a PR to fix them?
I see only one warning. Will this do @kittens?

Fix lint warning

---

src/util/filter.js

EDIT: oops, `[skip ci]` doesn't work in the PR title >.<
**Summary**
Fix typo: specifally -> specifically
**Test plan**
N/A

Fix typo: specifally -> specifically [skip ci]

---

__tests__/commands/install/integration.js
src/package-install-scripts.js

Fix a couple of lint warnings for unused variables

---

src/config.js
src/registries/base-registry.js
src/registries/npm-registry.js
src/registries/yarn-registry.js
src/reporters/lang/en.js

**Summary**
Adds output of possible and found config files for .npmrc and .yarnrc when running yarn with `--verbose`.
This would've helped troubleshoot #3136 
**Test plan**
```./bin/yarn --verbose                                                                                                               2759ms  10:11
yarn install v0.24.0-0
verbose 0.159 Checking for configuration file "/home/dennis/go/src/github.com/yarnpkg/yarn/.npmrc".
verbose 0.159 Checking for configuration file "/home/dennis/.npmrc".
verbose 0.16 Found configuration file "/home/dennis/.npmrc".
verbose 0.161 Checking for configuration file "/usr/.npmrc".
verbose 0.161 Checking for configuration file "/home/dennis/go/src/github.com/yarnpkg/yarn/.npmrc".
verbose 0.161 Checking for configuration file …
```

Adding verbose output for config file search

---

bin/yarn

Fixes 
```
line 16: [: : integer expression expected
```
introduced in #3245

fixed unary line 16: [: : integer expression expected

---

jenkins_jobs.groovy

**Summary**
- Adds a build job to call the script that was added in https://github.com/yarnpkg/website/pull/472. This job will be executed as part of the build infra whenever a new version is released
- Updates the Chocolatey and Homebrew build jobs to run when this version bump job runs, rather than polling every 15 minutes
**Test plan**
Tested with a fork of the website repo
References https://github.com/yarnpkg/website/issues/471

Add Jenkins job for bumping version on website

---

__tests__/commands/install/lockfiles.js

Fix offline resolution

---

__tests__/commands/install/lockfiles.js
src/fetchers/tarball-fetcher.js

`c:/` is a protocol, apparently 😞

Fixes offline resolution for absolute Windows paths

---

src/cli/commands/create.js
src/cli/commands/index.js
src/reporters/lang/en.js

**Summary**
This PR implements https://github.com/yarnpkg/rfcs/pull/55
**Test plan**
```
$> yarn create react-app
```

Adds yarn create

---

src/cli/commands/create.js

Less fragmentation, make it easier for other package managers to implement this feature :)

Updates the yarn-create prefix

---

__tests__/util/request-manager.js
src/reporters/lang/en.js
src/util/request-manager.js

**Summary**
If something is missing in your offline mirror, it can be really hard to figure out what it is without this message.
**Test plan**
Unit test.

Include requested url in cantRequestOffline error

---

LICENSE

**Summary** This distinguishes the LICENSE from the BSD 3-Clause.

LICENSE: Specify BSD 2-Clause

---

src/cli/commands/cache.js

**Summary**
Display the activity spinner during `cache clean` command.
Fixes #3452 
**Test plan**
No tests added. (Is there a way to test for an activity spinner?)

Display activity spinner during cache clean. #3452

---

src/registries/npm-registry.js

**Summary**
Adding failing test for a regression. See #3441 for more details.
**Test plan**

Fix `yarn outdated` missing values in URL column

---

scripts/prettier.js

**Summary**
This fix will allow to run prettier on windows. Otherwise it will fail with a commandline to long error.
**Test plan**
Try to run prettier on windows with and without this fix. 😄

Fix prettier on windows.

---

src/cli/commands/pack.js

removed unused variable

---

src/package-linker.js

@BYK, does this comment look better?
Feel free to edit

better comment

---

src/package-linker.js

fixed lint error

---

.babelrc
package.json
yarn.lock

**Summary**
Transpiles `Array.prototype.includes` correctly per Issue https://github.com/yarnpkg/yarn/issues/3693
**Test plan**
Ran `yarn run build` and manually checked the lib and lib-legacy files to check that only the latter had transpiled version.

Add new plugin to .babelrc to transpile Array.prototype.includes

---

src/cli/commands/global.js
src/constants.js

Reverts yarnpkg/yarn#3458
See https://github.com/yarnpkg/yarn/pull/3458#issuecomment-310806048

Revert "Change global prefix directory to `/usr/local` on OS X"

---

src/integrity-checker.js

Fixes https://github.com/yarnpkg/yarn/issues/3722.
Will invalidate all integrity checks but no one should notice.
**Test Plan:**
Unit tests.

fixed typo in integrity file

---

src/fetchers/git-fetcher.js
src/reporters/lang/en.js

Fixes #3689. See issue for details.

Add path to remaining fetchBadHash error

---

__tests__/util/git.js

**Summary**
Regression tests for #3742 and follow up to #3743 and #3759.
**Test plan**
Tests shall pass, mocks shall not pass.

Update: add regression tests for Git.spawn env issues

---

__tests__/commands/add.js
__tests__/commands/check.js
__tests__/commands/install/integration.js
__tests__/commands/install/lockfiles.js
__tests__/fetchers.js
package.json
src/cli/commands/upgrade.js
src/fetchers/git-fetcher.js
src/fetchers/tarball-fetcher.js
src/package-request.js
src/reporters/lang/en.js
src/util/user-home-dir.js
yarn.lock

**Summary**
Just upgrade prettier to 1.5.2
**Test plan**
Tests in place

Upgrade prettier to 1.5.2 and run it

---

package.json

Adds back the `prettier` script (cc @voxsim @BYK)

Adds back the prettier script

---

src/cli/commands/install.js
src/config.js
src/resolvers/registries/npm-resolver.js

**Summary**
Our CI (travis enterprise) was stuck because of a change in package.json that was untested with an install.
**Test plan**
I couldn't find a fitting place to add a test. Ideas?

Don't prompt for version on CI

---

__tests__/commands/install/integration.js
src/package-linker.js
src/util/fs.js

**Summary**
Fixes #3810 
**Test plan**
Adds a new test

Fixes link: protocol linking

---

__tests__/integration.js
package.json
src/fetchers/git-fetcher.js
src/registries/npm-registry.js
src/resolvers/exotics/hosted-git-resolver.js
yarn.lock

Fixes my previous PR: #3624
It also adds integration tests to ensure we cover this feature.

Fix allowing to install packages without manifest

---

src/cli/commands/check.js

**Summary**
Fixes https://github.com/yarnpkg/yarn/issues/3776
**Test plan**
```
yarn add google-closure-library
yarn check
````

Sanitize packageJson version

---

.flowconfig
package.json
yarn.lock

**Summary**
Just upgrade flow to 0.49.1
**Test plan**
Run flow and everything works like before.

upgrade flow to 0.49.1

---

src/package-compatibility.js

**Summary**
Resolves #3738
Screenshots:
then : ![screen shot 2017-07-11 at 20 40 03](https://user-images.githubusercontent.com/4020638/28081869-6e615cc4-6679-11e7-8236-4ceca1f50028.png)
now : ![screen shot 2017-07-11 at 20 36 24](https://user-images.githubusercontent.com/4020638/28081875-72b309d0-6679-11e7-80a1-306ea9caeabe.png)
**Test plan**
This part doesn't seem to have tests yet so I didn't make any updates about tests. I'd be happy to add tests for `checkOne` and the other untested functions though.

Lower platform incompatibility warning to info for optional dependencies

---

flow-typed/npm/jest_v20.x.x_with_custom_matchers.js

**Summary**
Updated Jest flow-types to version 20.x.x
**Test plan**
N/A

Update Jest flow-types to v20.x.x

---

src/cli/commands/install.js

**Summary**
Change to correct npm upgrade command. `npm upgrade` -> `npm update`.
**Test plan**
N/A

Correct npm upgrade command

---

__tests__/commands/__snapshots__/init.js.snap
__tests__/commands/init.js

**Summary**
Fixes build.
**Test plan**
Ci should pass.

Fix: Fix broken snapshots

---

package.json
yarn.lock

Fixes #4059, but other problems remain in my test environment.   Subbmitting this as a PR to run on CI machines.

Use cross-env to launch tests (do not merge)

---

package.json

Update: bump version to 1.0.0 for master

---

packages/lockfile/package.json

docs(lockfile): add metadata to package.json

---

__tests__/commands/install/workspaces-install.js
__tests__/fixtures/install/install-workspaces/.yarnrc
__tests__/fixtures/install/simple-worktree/.yarnrc
__tests__/fixtures/install/workspaces-install-already-exists/.yarnrc
__tests__/fixtures/install/workspaces-install-basic/.yarnrc
__tests__/fixtures/install/workspaces-install-conflict/.yarnrc
__tests__/fixtures/install/workspaces-install-duplicate/.yarnrc
__tests__/fixtures/install/workspaces-install-enabled/.yarnrc
__tests__/fixtures/install/workspaces-install-link-bin/.yarnrc
__tests__/fixtures/install/workspaces-install-link-invalid/.yarnrc
__tests__/fixtures/install/workspaces-install-link-root/.yarnrc
__tests__/fixtures/install/workspaces-install-link/.yarnrc
__tests__/fixtures/install/workspaces-install-mandatory-fields/.yarnrc
__tests__/fixtures/install/workspaces-install-names-issue/.yarnrc
__tests__/fixtures/install/workspaces-install-private/.yarnrc
__tests__/fixtures/install/workspaces-install-subdeps-2/.yarnrc
__tests__/fixtures/install/workspaces-install-subdeps-dev/.yarnrc
__tests__/fixtures/install/workspaces-install-subdeps/.yarnrc
__tests__/fixtures/workspace/run-basic/.yarnrc
src/cli/commands/install.js
src/config.js
src/reporters/lang/en.js

**Summary**
Closes #3294 by enabling workspaces by default.
**Test plan**
Existing tests, slightly modified.

Update: Enable Workspaces by default but keep the option to turn off

---

src/cli/commands/upgrade-interactive.js

**Summary**
Fix for issue #4214 by using the first suggested solution from the issue itself. For more info see the issue 😃
Before: 
After:

Fix #4214: Align column headers for upgrade-interactive command

---

src/cli/commands/add.js

**Summary**
Addresses some concerns around readability from PR https://github.com/yarnpkg/yarn/pull/4278
Also moved the flagsToOrigin override inside the conditional so that the check is only performed when running from workspace root.
**Test plan**

Add inline comments to improve readability of PR #4278

---

src/cli/commands/upgrade.js

**Summary**
Fixes #4397.
**Test plan**

Fix: add back -L shortcut for yarn upgrade

---

__tests__/commands/install/integration.js
__tests__/fixtures/install/install-file-no-package/package.json

It turns out that this is probably already the case, but I'm adding regression test anyway :)
#4257

Add test that manifest-less local packages are installable, #4257

---

src/cli/commands/install.js

**Summary**
Fixes #3042.
**Test plan**

Fix: don't suggest `npm upgrade` since it is broken

---

src/util/blocking-queue.js

Fixes #4551
**Summary**
https://github.com/yarnpkg/yarn/issues/4551#issuecomment-332510392
**Test plan**
* Existing tests pass
* Manually tested

Fix performance issue with multiple lifecycle package scripts

---

CONTRIBUTING.md

**Summary**
Add note about which version of Node is needed to develop Yarn.
**Test plan**
N/A

chore(docs): State minimum Node version for development

---

__tests__/integration.js

**Summary**
This is the missing test for #4679 :)

Adds an extra test for the yarn path feature

---

__tests__/commands/__snapshots__/licenses.js.snap
__tests__/commands/licenses.js

**Summary**
Fix a typo in the tests for `yarn licenses generate-disclaimer`.

chore(tests): Fix typo s/genereate/generate

---

src/reporters/lang/en.js

Fix implicitFileDeprecated message

---

src/cli/commands/create.js
src/cli/index.js

**Summary**
Fixes #4670 .
**Test plan**

fix(create): Fix passing parameters for "yarn create"

---

src/reporters/console/console-reporter.js

**Summary**
This PR fixes a wrong condition which cause the color fix  from  #3607  for #2724 to be no working as intended.
**Test plan**
This change should not influence any tests.

Fix wrong condition

---

src/reporters/console/console-reporter.js

**Summary**
Used a single negation instead of double negation. Follow up to #4767.
**Test plan**
Existing tests

style(reporters): Simplify Windows bold fix check condition

---

CONTRIBUTING.md

**Summary**
We have cleaned up our labels a bit and this PR adds some useful links for people to find what needs
attention from the community.
**Test plan**
Read and make sure the links and the text are accurate.

docs(contributing): Add section about what to work on and triaging

---

src/reporters/console/console-reporter.js

**Summary**
Fixes #5098
The progress bar was not being deleted before showing the license tree.
**Test plan**

fix(output) "licenses list"

---

__tests__/commands/cache.js
src/cli/commands/cache.js

This PR fixes https://github.com/yarnpkg/yarn/issues/5273

'Cache clean' with multiple packages at once

---

src/cli/commands/remove.js

**Summary**
Add emoji for steps when running `remove` command.
**Test plan**
Screenshot:

feat(remove): add emoji for steps

---

src/lockfile/index.js

Removed unnecessary nested if statement

---

scripts/build-webpack.js

**Summary**
Fixes #5719.
**Test plan**
1. Run `yarn run build-dist`.
2. Check that `artifacts/yarn-${version}.js` still has a shebang.
3. Check that `packages/lockfile/index.js` has no shebang.

Excluded shebang for lockfile package

---

yarn.lock

**Summary**
These are not supposed to be here yet. Only once this is merged: https://github.com/yarnpkg/yarn/pull/5042
**Test plan**
CI should be green.

fix(lockfile): remove yet-unreleased integrity field

---

src/cli/index.js

**Summary**
Enable emoji on [Hyper](https://github.com/zeit/hyper) terminal by default.
**Test plan**
No.

feat(cli): enable emoji on Hyper terminal

---

README.md

**Summary**
Update npm repository link

update npm link

---

__tests__/__mocks__/request.js

**Summary**
Cf https://github.com/nodejs/node/issues/21907
**Test plan**
CI

Fixes request mock on Node 10.7

---

src/util/fs-normalized.js

**Summary**
Fixes a Node compatibility issue introduced with #6302
**Test plan**
Tests should pass (I failed to see the problem in the previous PR because the tests were crashing for a transient error).

Fixes constants

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

**Summary**
Our changelogs are not awesome. Let's make them awesome.
Two followups:
- CI on PRs to prevent merging without a changelog update (@BYK?)
- Auto-update the changelog.md file when tagging a release (@Daniel15)
**Test plan**
n/a

Changelog workflow 

---

__tests__/registries/npm-registry.js

**Summary**
Introduced by #6454
**Test plan**
CI

Fixes a boggus conflict resolution

---

packages/pkg-tests/pkg-tests-core/sources/utils/fs.js
packages/pkg-tests/pkg-tests-fixtures/packages/no-deps-scripted-1.0.0/package.json
packages/pkg-tests/pkg-tests-specs/sources/script.js
src/fetchers/tarball-fetcher.js

Investigations on top of @arcanis branch to get Acceptance tests running on Azure Pipelines for 3 OS: Linux, MacOS, Windows.
This is demo purpose only, DO NOT MERGE.

Acceptance tests for Azure pipelines Windows run (DO NOT MERGE, review only)

---

CHANGELOG.md

Add 1.14.0 to changelog

---

src/cli/commands/help.js
src/resolvers/exotics/git-resolver.js

**Summary**
There are two checks which are not needed. One check in a condition was added when the Facebook headers were removed and there is no reasons for the `false` check.
**Test plan**

refactor: remove unnecessary checks

---

packages/pkg-tests/pkg-tests-specs/sources/workspace.js

**Summary**
Spotted this mistake in the tests: package A lists that it depends on itself, but it actually depends on B, and vice-versa.
**Test plan**
Existing tests are sufficient.

Fix minor typo in dependencies test

---

src/cli/commands/list.js
src/hoisted-tree-builder.js

**Summary**
I just optimized function for cutting last `#` and tail. In v8(Chrome) it works 10x faster https://jsperf.com/yarn-split-sharp
**Test plan**

Optimize slice last sharp tail
