scripts/install-latest.sh

Using ZSH when the file would add `export $PATH="~/.yarn/bin:$PATH" to my .zshrc file, the quotes were causing the tilde to not be evaluated to $HOME. This diff changes the tilde to be `$HOME` so even in quotes it is evaluated.
Verified this change caused my `which yarn` to be exposed.

Changed Tilde to $HOME

---

src/cli/commands/run.js

**Summary**
If the project is in a path with whitespace (`/Users/bleh/My Stuff/project/`), running binaries (`yarn run eslint`) doesn't work. I quoted `cmd` to solve this issue.
A better way to solve this could be passing cmd and args separately down to `child.js`s `spawn()` and quoting or escaping there, but that would require too much API change.
Comments?
**Test plan**
Reproduce:
```bash
mkdir "some dir"
cd "some dir"
git clone git@github.com:yarnpkg/yarn.git
cd yarn
yarn
yarn run eslint
```

Quote command so paths with whitespace work

---

resources/winsetup/Yarn.wxs

**Summary**
Remove Node.js check from Windows installer for now. It doesn't handle systems such as `nvm` or `nodemon` that install Node.js without updating the registry.
**Test plan**
Built Windows installer (`npm run build-win-installer`), installed it, it worked.
References #626

Remove Node.js check from Windows installer for now

---

src/cli/commands/install.js
src/package-compatibility.js

package.json
```
{
"cosmiconfig": "2.0.1"
}
}
```
`yarn install`
Fails
...
`yarn install --ignore-flags`
works
Fixes #638

Respect ignore engines flag.

---

src/cli/commands/clean.js
src/reporters/lang/en.js

**Summary**
Added "MB" to the cleanSavedSize message, converted it to Number so there aren't quotes around the output.
**Test plan**
Before:
```
<...>
info Saved "15.29"
<...>
```
After:
```
$ yarn clean
yarn clean v0.15.1
[1/2] Creating ".yarnclean"...
[2/2] Cleaning modules...
info Removed 3485 files
info Saved 15.29 MB.
✨  Done in 3.17s.
```
Include 'MB' in cleanSavedSize message.

Show the units to `yarn clean` saved size report

---

src/fetchers/git-fetcher.js
src/util/git.js

**Summary**
Fixes typos in the archive functionality
**Test plan**
Existing tests should catch this already, just variable name changes.

fix typos: git and git-fetcher to use proper archive

---

package.json
yarn.lock

**Summary**
Ref https://github.com/yarnpkg/yarn/pull/669#issuecomment-253009368
```
warning Unmet peer dependency "eslint-plugin-react@^5.2.2".
```
npm run test will fail on eslint because there is a missing plugin dependency in https://github.com/facebook/fbjs/blob/446badb82d7774a9d23df70b51cb04abb97e11bc/packages/eslint-config-fbjs/package.json#L24.
```
Oops! Something went wrong! :(
ESLint couldn't find the plugin "eslint-plugin-react". This can happen for a couple different reasons:
```
**Test plan**
`npm t`

Add back eslint-plugin-react since it is a peerDep of eslint-config-fbjs

---

src/cli/index.js

**Summary**
The docs URL is displayed as `http` which redirects to `https`. Linking directly to the `https` removes the unnecessary redirect.

Use https protocol in docs link

---

CONTRIBUTING.md

Adding setup instructions similar to what we have in babel https://github.com/babel/babel/blob/master/CONTRIBUTING.md#setup

CONTRIBUTING: add setup instructions [skip ci]

---

README.md

**Summary**
This PR fixes the server ID in the discord badge. The server ID in it was pointing another server that was not yarnpkg's. Merging this PR also means going into server settings & enabling the Widget so that it functions properly.
**Test plan**
N/A

Fix Discord server ID in badge

---

src/cli/index.js

**Summary**
- `yarn --help` no longer shows help instructions just for the `install` command
- Fixes #740
**Test plan**
- Run `yarn help`, `yarn -h`, `yarn --help`. All have the same behavior
- `yarn help install`, `yarn --help install`, etc. still show help instructions for install

`yarn --help` now equivalent to `yarn help`

---

src/util/network.js

Yarn works fine on Windows Subsystem for Linux (WSL) apart from a single call
to enumerate network interfaces.  If this call fails on WSL, we instead assume
that the user has an internet connection and continue.
See #753 and #636 for discussion.
With this change, the test suite works better on WSL but it still has multiple failures.  I've run the test suite on Linux and it passes fine.

Support unimplemented call in Windows Subsystem for Linux

---

scripts/install-latest.sh

**Summary**
This PR adds support for handling installation of `yarn` on [fish shell](https://fishshell.com).
fish is a popular shell. Me and many I know use it regularly for its awesome auto-completion features and convenience.
The current problem is that the `yarn` install script only checks for bash and zsh shells. This was causing `~/.yarn/bin` to not be added to the `$PATH` in fish.
With this commit, the `yarn` install script first checks if the user's shell is fish. If so, it adds the following line to `~/.config/fish/config.fish`.
```fish
set -xg PATH ~/.yarn/bin $PATH 
``` 
See [Startup (Where's .bashrc?)](https://fishshell.com/docs/current/tutorial.html#tut_startup) section in official fish documentation for more information.
**Test plan**
When `yarn/scripts/install_latest.sh` is …

Handle installation for 'fish' shell

---

README.md

Per HN comment from @kittens 
> We initially used a method similar to ied when we first started experimenting with internal usage at Facebook.
https://news.ycombinator.com/item?id=12685936

Add ied as prior art

---

__tests__/package-resolver.js
src/util/git.js

**Summary**
Previously, branches with slashes such as `features/feature-branch` would not be recognized by the package resolver. This happened because ref names (e.g. `refs/heads/features/feature-branch`) were not parsed correctly. Instead of looking at everything after the second slash, it only looked at the string after the second slash and before the third. This resulted in `refs/heads/features/feature-branch` being parsed to `features` instead of `features/feature-branch`.
**Test plan**
I have added a test case to `__tests__/package-resolver.js` that tries to parse `https://github.com/babel/babel-loader.git#feature/sourcemaps`. Previously, this caused an error. This has been fixed now.
There is one more failing test though, but I'm sure it's not related to my change. Tests seem to be …

Fix git dependencies with slashes inside branch name

---

.travis.yml
scripts/build-dist.sh
scripts/update-linux-git.sh

**Summary**
This PR improves Travis CI builds in the following ways:
1. Runs on containers, so Linux jobs start faster
1. Cleans up `git`-related tasks
1. Uses `apt` addon to update `git`. Strictly speaking, this may be unnecessary (depending on what version of `git` is available on the image).
1. Skips updating `git` on the Mac. This also appears unnecessary, and adds some time to the build, since Homebrew now runs `brew update` in the background, which can be quite slow on an old package index.
1. Tweak `$TEST_TYPE` values, so that `script` section is easier to understand.
**Test plan**
Not applicable.

Improvements on Travis CI

---

src/cli/index.js

**Summary**
This fixes issue #664, where the yarn cli was display a url for commands that don't actually exist in yarn.
**Test plan**
`yarn what` 
```
yarn what v0.15.1
error Command "what" not found.
```
`yarn why` (display a doc url)
```
yarn why v0.15.1
error Missing package name, folder or path to file to identify why a package has been installed
info Visit https://yarnpkg.com/en/docs/cli/why for documentation about this command.
```
`yarn what what what` (don't display doc url)
```
yarn what v0.15.1
error Command "what" not found.
```
`yarn why why why` (display a doc url)
```
yarn why v0.15.1
error Too many arguments, maximum of 1.
info Visit https://yarnpkg.com/en/docs/cli/why for documentation about this command.
```
`yarn ls no-arguments` (this will always display a doc url …

Don't display a documentation url if actual command does not exist

---

src/cli/commands/install.js
src/util/misc.js

**Summary**
While trying to analyze why security checks fail (due to hash mismatches), I stumbled upon two hash utils with different default hashing strategies. My first thought was that this is why it isn't working. Turns out, that the two versions are used in different parts of the code.
This PR removes the duplicate hashing util function (for less confusion in the future).
**Test plan**
This PR removes one existing function. Tests already cover this path.

Remove duplicate hashing utility

---

.eslintrc
.gitignore
package.json

**Summary**
In this PR I simply extracted the `eslintConfig` out of it and placed it in a more standard way in the `.eslintrc` file.
Why?
1. The `package.json` file already have enough definitions in it and it is a big file, Let's minimize it.
* We're already using `.eslintignore` file, so why having the eslint configuration in the `package.json` file? Seems a little bit inconsistence..
* A lot of IDEs have built in plugins for eslint, having the configurations in a dedicated file for that makes that integration easier.
* Easier to find - when ever I'll need anything regarding eslint, I would just go to that file instead of searching for it in the `.package.json` file. Also, now this file and the `.eslintignore` file are one after the other.
**Test plan**
No need for tests here.. I …

Chore - Created an .eslintrc file for the eslint configurations instead of having it in the package.json file

---

package.json
yarn.lock

eslint-plugin-flow-vars is deprecated and has been merged into eslint-plugin-flowtype.

chore(package,yarn): remove eslint-plugin-flow-vars

---

src/cli/index.js

**Summary**
If the command is misspelled, the help message should point to
the URL with properly spelled command name.
**Test plan**
Commands to reproduce is in https://github.com/yarnpkg/yarn/pull/803#issuecomment-253134849
----
cc @cpojer

cli: fix help for misspelled command

---

src/cli/index.js

**Summary**
Without making `mutex`'s `type` argument a mandatory one, by default,
`true` is assumed and it fails with the following error.
➜  yarn git:(master) ./bin/yarn --mutex
yarn install v0.15.1
error TypeError: mutex.split is not a function
at config.init.then (yarn/lib/cli/index.js:336:25)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
And if just `mutex` is specified, commander treats that as an array and
fails like this
➜  yarn git:(master) ./bin/yarn mutex
yarn mutex v0.15.1
error TypeError: mutex.split is not a function
at config.init.then (yarn/lib/cli/index.js:336:25)
This patch makes the `type` a mandatory parameter. So, now
➜  yarn git:(fix-mutex-cmd-args) ./bin/yarn --mutex
error: option `--mutex <type>[:specifier]' argument …

cli: make mutex's type a mandatory argument

---

src/cli/index.js

**Summary**
This solves #693 by removing the `.allowUnknownOption()` call on `commander`.
**Test plan**
```
❯ yarn --vesrion
yarn install v0.15.1
success Already up-to-date.
✨  Done in 0.16s.
```
```
❯ yarn --vesrion
error: unknown option `--vesrion'
```

Remove commander's `allowUnknownOption` method call

---

src/cli/commands/run.js

**Summary**
The script quoting behaviour introduced in #663 breaks package.json script entries with spaces in them on Unix.
Instead, this quotes `node_modules/.bin` executable paths, which makes sure both package.json script entries, and executables can be called.
**Test plan**
For this package.json;
```json
{
"name": "yarntest_pr809",
"devDependencies": {
"jest": "^16.0.1"
},
"scripts": {
"test": "jest",
"test-help": "jest --help"
}
}
```
with dependencies installed,
1. **In a path with no spaces** (e.g. `~/yarntest_pr809`);
1. `yarn run test -- --help` should print jest’s help message on the current release, and with this patch.
2. `yarn run test-help` will *fail* on the current release, and print jest’s help message with this patch.
3. `yarn run jest -- --help` will …

Fix executing scripts with spaces

---

src/registries/npm-registry.js

**Summary**
Ensures with and without trailing / registry url is correct and resolvable.
Currently if you set a npm registry via config to be:
1. `yarn config set registry https://mycustom.registry.com/dev/registry`
2. `yarn add redux` (not in cache / fresh install)
The `url.resolve` will turn the url to be `https://mycustom.registry.com/dev/redux` (no `registry` as part of the path due to `/` being removed `removeSuffix`.)
**Test plan(s)**
******
1. `yarn config set registry https://mycustom.registry.com/dev/registry`
2. `yarn add react`
******
1. `yarn config set registry https://mycustom.registry.com/dev/registry/`
2. `yarn add redux`
******
1. `yarn config set registry https://registry.npmjs.org/`
2. `yarn add react-router`
There appears to be a flow issue with `url.format` currently: …

Custom Registry url.resolve Issue

---

src/util/request-manager.js

**Summary**
`hostname` is not always available on network `error` objects when checking that object inside `lib/util.js:isPossibleOfflineError()` function this will always `return false;` so **INSTALL BREAKS ON ANY TYPE OF ERROR** and doesn't attempts to retry and recover from that network error.
**UPDATE** PR Re-based  and used a cleaner solution for this problem :)

Hostname check inside isPossibleOfflineError()

---

src/cli/commands/install.js
src/cli/index.js
src/config.js
src/package-compatibility.js

**Summary**
Hi everyone,
I had an issue with some packages with _not quite correct_ platform properties in `package.json`, blocking completely an install process that was working well with _npm_.
So the output was:
```
❯ yarn
yarn install v0.15.1
info No lockfile found.
error babel-plugin-react-require@2.1.0: The platform "darwin" is incompatible with this module.
error babel-plugin-react-require@2.1.0: The CPU architecture "x64" is incompatible with this module.
error Found incompatible module
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
This is caused by packages having the `os` & `cpu` properties set to the empty array value:
```json
{
"name": "foo",
"os": [], …
```

Flag to ignore platform compatibility

---

src/cli/commands/clean.js

**Summary**
Some packages (like 'timepicker') use minified files as the main entrypoint. This makes them incompatible with `yarn clean`.
I want to use a custom `.yarnclean` while still being able to use this package, and it seems there is no way to do this without modifying yarn itself.

Don't remove compiled files in `yarn clean`

---

src/registries/yarn-registry.js

**Summary**
Currently optional dependencies are not installed since the default flag is true, with or with out flag it sets to true
fixes #628

fix(optionalDependency): reset ignore-optional default flag

---

__tests__/commands/_init.js
__tests__/commands/init.js
__tests__/fixtures/init/init-yes/.npmrc
package.json
src/cli/commands/init.js

**Summary**
Added `-y, --yes` flag to `yarn init` to create `package.json` with default values.
Fixes #637.
**Test plan**
```bash
👉  yarn init -y
yarn init v0.15.1
warning The yes flag has been set. This will automatically answer yes to all questions which may have security implications.
success Saved package.json
✨  Done in 0.09s.
```
```bash
👉  cat package.json
{
"name": "test",
"license": "MIT"
}
```

Add --yes flag to yarn init

---

.travis.yml

**Summary**
This PR increases the `git` clone depth, so that builds can proceed when multiple commits are pushed before a build runs.
See, for example, https://travis-ci.org/yarnpkg/yarn/jobs/167023508#L121 for an example of the build failure.
**Test plan**
Not applicable.
---
Since this repository has a lot of commits, cloning with
depth 1 can cause builds to fail erroneously when the commit
to test is not available in the shallow clone.

Increase git clone depth to 10

---

scripts/build-dist.ps1

**Summary**
#729 fixed the .sh build script for the yarnpkg=>yarn rename, but not the powershell script. This fixes that.
**Test plan**
`scripts/build-dist.ps1` now works, assuming a tar install.

fix tgz glob for powershell build (echo #729 fix)

---

__tests__/commands/add.js
__tests__/commands/install.js

**Summary**
Increases the timeouts for the `commands/add.js` and `commands/install.js` tests
#903 
These tests are passing but occasionally timing out on mac os because they take so long to run
**Test plan**
Run the test suite several times on mac os

increase the timeout for long running tests

---

__tests__/commands/install.js
src/cli/commands/install.js

**Summary**
Fixes https://github.com/yarnpkg/yarn/issues/893
The single resolved version was accidentally being pushed to the passed in argument instead of the result. I have tested the case presented in the issue, and it works locally.

Add single resolved version to flattenedPatterns instead of patterns

---

src/cli/commands/link.js

**Summary**
I was getting an error each time I did `yarn link` on a scoped module because the symlink can't create a folder the `@<scope>` folder inside 
```
$ yarn link
yarn link v0.15.1
warning package.json: No license field
info /Users/ofunes/.yarn-config/link/@<scope>/<module_name>
error ENOENT: no such file or directory, symlink '../../../path/to/<module_name>' -> '/Users/ofunes/.yarn-config/link/@<scope>/<module_name>'
at Error (native)
info Visit https://yarnpkg.com/en/docs/cli/link for documentation about this command.
```
**Test plan**
Now when I run `yarn link` it creates the link. 
Since I'm using `mkdirp` available through `utils/fs`, then I (`path.dirname`) parse the `linkLoc` variable and get the `.dir` property which can be either `/Users/ofunes/.yarn-config/link` or …

Add mkdirp to create a @<scope> folder before doing symlink so that yarn link works

---

package.json

**Summary**
Babel plugin was in `dependencies` rather than `devDependencies`.
**Test plan**

Move `babel-plugin-transform-inline-imports-commonjs` to devDependencies

---

scripts/build-dist.ps1
src/cli/commands/install.js

**Summary**
Adds calls to the following named scripts: `preinstall`, `install`, `postinstall` and wraps `prepublish` in an `if !prod`, as it is in `npm install` Should resolve #783 Happy to discuss.
**Test plan**
Given the following package.json:
```
{
"name": "junk",
"scripts": {
"preinstall": "echo 'preinstall'",
"install": "echo 'install'",
"postinstall": "echo 'postinstall'",
"prepublish": "echo 'prepublish'"
}
}
```
`npm install` outputs the following:
```
PS C:\git\junk> npm i
> junk@1.0.0 preinstall C:\git\junk
> echo 'preinstall'
'preinstall'
> junk@1.0.0 install C:\git\junk
> echo 'install'
'install'
> junk@1.0.0 postinstall C:\git\junk
> echo 'postinstall'
'postinstall'
> junk@1.0.0 prepublish C:\git\junk
> echo …
```

Add pre and post install script calls

---

src/cli/commands/config.js

**Summary**
I noticed that `yarn help config` showed the following usage:
```console
$ yarn help config
Usage: yarn access [set|get|delete|list] [flags]
Options:
-h, --help                  output usage information
-V, --version               output the version number
--offline                   
--prefer-offline            
--strict-semver             
--json                      
--global-folder <path>      
--modules-folder <path>     rather than installing modules into the node_modules folder relative to the cwd, output them here
--cache-folder <path>       specify a custom folder to store the yarn cache
--mutex <type>[:specifier]  use a mutex to ensure only one yarn instance is executing
Visit https://yarnpkg.com/en/docs/cli/config for documentation about this command.
```
Notice …

fix(config): show proper command for `yarn help config`

---

src/cli/commands/cache.js

**Summary**
After PR #881 was merged, 'yarn cache dir' stopped working (was returning undefined). This PR was renaming config.packagesRoot to config.cacheFolder, but left out the dir method for the cache command.
This PR just changes the old config.packagesRoot to the new name config.cacheFolder in the cache dir method. 
**Test plan**
Output before -> undefined
Output after -> /Users/myuser/.yarn-cache
Also flow check was failing before, now it's passing.

Fix 'yarn cache dir' by using config.cacheFolder

---

src/cli/commands/install.js

**Summary**
Documents `install/add --force`, which does what #858 asks for.
**Test plan**
Run `yarn add --help` or `yarn install --help` and `--force` should be documented as `refetch all packages`

Document --force

---

src/reporters/console/util.js

**Summary**
Similar to my PR for the progress bar (#526), this improves the display of the "spinners". Previously, we were clearing the line then immediately writing to it, resulting in a lot of flashing text. I've changed it to write the new text on top of the old text, and then just clear to the right of the cursor (in case the new text is shorter than the old text)
Before:
After:
The cursor still jumps around a lot, I'm not sure if we can solve that though :(
**Test plan**
Run `yarn install` on a `package.json` that uses native modules:
```
{
"name": "lolyarn",
"bcrypt": "^0.8.7",
"leveldown": "^1.5.0"
}
}
```

When rendering spinners, only clear to the right of the cursor instead of the whole line

---

src/package-linker.js

**Summary**
When installing a scoped package that has a `bin` entry in its package.json, the symlink will fail because the dest dir cannot be found. 
This was fixed for the `yarn link` command in https://github.com/yarnpkg/yarn/pull/910, but not for `yarn install`. 
**Test plan**
_before_
_after_
--- 
I would've liked to add some tests for this, but my Jest-juju isn't up to speed so I decided against setting up a fresh test suite for the `PackageLinker`. I can give it a whirl, but for now I have to get back to my day-to-day's.
Ref issues: https://github.com/yarnpkg/yarn/issues/950, https://github.com/yarnpkg/yarn/issues/759

fix(packageLinker): ensure dir before symlinking bin

---

scripts/build-webpack.js

**Summary**
Adds `#!/usr/bin/env node` at the top of single JS builds so they can be run directly if execute permissions are set. Fixes #888 
**Test plan**
`npm run test` has no changes.

Add node shebang to single JS builds

---

__tests__/commands/init.js

**Summary**
Fixed test to use default values from config.
**Test plan**
```bash
👉  jest --verbose __tests__/commands/init.js
PASS  __tests__/commands/init.js
✓ init --yes should create package.json with defaults (162ms)
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.102s, estimated 5s
Ran all test suites matching "__tests__/commands/init.js".
```
cc @bestander

Fix test for `yarn init --yes`

---

src/package-compatibility.js

Older versions of lodash, among other packages, list `'rhino'` as an engine.
Printing a warning here doesn't accomplish much - best to suppress it.
Fixes #1003

fix(engines): Suppress 'rhino' as invalid engine.

---

src/cli/commands/why.js
src/util/fs.js

**Summary**
Added calculating `size on disk` for dependencies and counting the size of real packages from `node_modules` instead of packages from cache (see #578). I'm new to this stuff so feel free to suggest some improvements to this.
**Test plan**
The same scenario as in #578:
```
mkdir test && cd test
yarn init -y && yarn add jest
du -sh node_modules
42M	node_modules
yarn why jest
yarn why v0.15.1
[1/4] 🤔  Why do we have the module "jest"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
info Has been hoisted to "jest"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "36kB"
info Disk size with unique dependencies: "252kB"
info Disk size with transitive dependencies: …
```

Make `yarn why` more accurate

---

scripts/install-latest.sh

**Summary**
I think it's bad idea to exit 1 in this case - because this script can't be used in pipeline or in ansible. Throwing exception breaks next movements. If Yarn already installed this script - it will warn and normally exited with exit code 0.
What do you think?

install sh script: Do not "exit 1" if yarn already installed

---

resources/debian/control.in

**Summary**
A "Recommends" relation preserves the out-of-the-box experience for most people, as recommended packages are installed by default on modern Debian / Ubuntu distros. But it allows people who install Node.js using a different method to opt out of the nodejs DEB package.
**Test plan**
`$ bash scripts/build-deb.sh`
...
`$ sudo dpkg -i artifacts/yarn_0.15.1_all.deb`
^ the above commands execute successfully.
```
$ which yarn 
/usr/bin/yarn
```
```
$ yarn version
yarn version v0.15.1
info Current version: 0.15.1
```

Change DEB nodejs relation from Depends to Recommends

---

src/registries/npm-registry.js

**Summary**
Gzip compression wasn't enabled causing yarn to download twice the data npm does. Fixes #945 .
**Test plan**
`yarn add yo`
Before - 9.9MB
After - 5.3MB

Enable gzip compression

---

scripts/build-deb.sh
scripts/build-dist.sh

**Summary**
CircleCI has a default umask of `0002`, which results in files having their mode set to `0664` and directories having their mode set to `0775`. These should really be `0644` and `0755` respectively, which is accomplished by using the umask of `0022` (which is the default on most systems anyways). Lintian in particular complains about the file permissions being incorrect when the `.deb` package ls linted.
**Test plan**
Built my branch on CircleCI: https://circleci.com/gh/yarnpkg/yarn/1361

Set umask to 0022 when building dist, so file permissions are correct

---

src/cli/commands/upgrade.js

**Summary**
This solves #598. This doesn't affect the ability to run `yarn upgrade` to upgrade all packages.
**Test plan**
```sh
❯ yarn outdated
yarn outdated v0.15.1
Package   Current Wanted Latest
react-dom 15.1.0  15.3.2 15.3.2
react     15.1.0  15.3.2 15.3.2
✨  Done in 0.37s.
```
```sh
❯ yarn upgrade react
yarn upgrade v0.15.1
error This command doesn't require any arguments.
info Visit http://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
```
```sh
❯ yarn upgrade react
yarn upgrade v0.15.1
success Saved lockfile.
success Saved 2 new dependencies.
├─ fbjs@0.8.5
└─ react@15.3.2
✨  Done in 0.79s.
```
```sh
❯ yarn ls
yarn ls v0.15.1
├─ …
```

Enable ability to run `yarn upgrade [package]`

---

src/cli/commands/team.js

**Summary**
This fixes #1018. Previous would throw an ugly stack trace trying to split a string that doesn't exist. This fix will bail early when no arguments are given and show the command usage.
**Test plan**
```sh
❯ yarn team ls
yarn team v0.15.1
error TypeError: Cannot read property 'split' of undefined
at explodeScopeTeam (/Users/neil/Projects/external/yarn/lib/cli/commands/team.js:41:23)
at /Users/neil/Projects/external/yarn/lib/cli/commands/team.js:68:21
at next (native)
at step (/Users/neil/Projects/external/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
at /Users/neil/Projects/external/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
at Promise.F (/Users/neil/Projects/external/yarn/node_modules/core-js/library/modules/_export.js:35:28)
at …
```

Ensure arguments to `yarn team <cmd>` before going further

---

src/cli/commands/team.js

**Summary**
When running the `yarn team` command without arguments, the display would output each command with "team" duplicated, which shows an invalid command. See test plan below for comparison.
**Test plan**
```sh
❯ yarn team
yarn team v0.15.1
error Usage:
error yarn team team create <scope:team>
error yarn team team destroy <scope:team>
error yarn team team add <scope:team> <user>
error yarn team team rm <scope:team> <user>
error yarn team team ls <scope>|<scope:team>
error Invalid subcommand. Try "create, destroy, add, rm, ls"
info Visit http://yarnpkg.com/en/docs/cli/team for documentation about this command.
```
```sh
❯ yarn team
yarn team v0.15.1
error Usage:
error yarn team create <scope:team>
error yarn team destroy <scope:team>
error yarn team add <scope:team> <user>
error …
```

Remove duplicate team display

---

src/cli/commands/login.js
src/cli/commands/owner.js
src/cli/commands/publish.js
src/cli/commands/tag.js
src/config.js
src/fetchers/tarball-fetcher.js
src/registries/base-registry.js
src/registries/index.js
src/registries/npm-registry.js
src/registries/yarn-registry.js
src/reporters/lang/en.js
src/util/misc.js

**Summary**
This implements support for private registries configured in `.npmrc` files. It extracts the registry to use and the auth token info. Supports bearer tokens and basic auth, scoped registries, and the `always-auth` option. Should fix #606.
My flow experience is minimal, so if I messed something up or did something silly please let me know. 😀
**Test plan**
I tested with several npm configs against real live Sonatype Nexus, and Artifactory instances. Here are some cases:
```
//registry.npmjs.org/:_authToken=TOKEN
registry=https://my-registry.com/
_auth=TOKEN
email=test@example.com
always-auth=true
@coralui:registry=https://my-registry.com/
//my-registry.com/:_password=PASSWORD
//my-registry.com/:username=USERNAME
//my-registry.com/:email=test@example.com …
```

Support npmrc for private registries and auth

---

src/reporters/console/util.js

**Summary**
This solves #728 which is to make yarn a nice unix citizen by not emitting escape sequences outside TTYs.
**Test plan**
The only thing I noticed was that flow doesn't seem to support `process.stdout.isTTY`, see https://github.com/facebook/flow/issues/1825. And since I don't really use flow, so I'm not sure how to fix this.

Only write escape sequences to a TTY

---

__tests__/package-resolver.js
src/resolvers/exotics/git-resolver.js

**Summary**
Fixes git-resolver so it takes the proper code path for git+https, etc packages.
This is the last bit that's required for me to use yarn at work.
**Test plan**
Added a test to __tests__/package-resolver.js

Fix git resolver so isVersion matches git+https and the like

---

.travis.yml
appveyor.yml
circle.yml
scripts/bootstrap-env-ubuntu.sh
scripts/build-dist.ps1
scripts/build-dist.sh

**Summary**
On Linux:
- Install Yarn from Ubuntu package rather than `npm`
- Moved installation of Yarn to `bootstrap-env-ubuntu.sh` script. The more of the environment configuration we have in here, the better (as it'll make it easier to have Docker/Vagrant images for Yarn dev/build in the future)
- Use Travis and CircleCI's built-in method to choose Node.js v6 rather than nvm
On Windows (AppVeyor):
- Install Yarn from Chocolatey package
**Test plan**
Will check on Travis/AppVeyor/CircleCI once PR is submitted and the build is kicked off

Use Yarn package/installer on Travis/AppVeyor/CircleCI rather than npm

---

resources/win-chocolatey/yarn.nuspec
scripts/build-chocolatey.ps1

**Summary**
Previously, we required both the Windows installer and the Chocolatey package to be built on the same machine. I've updated the Chocolatey build script to be entirely standalone, similar to how we handle the Debian/Ubuntu/CentOS package repository. 
The Chocolatey build script hits https://yarnpkg.com/latest-version to get the latest version number, and also hits Chocolatey to get the latest version number on Chocolatey. If the latest version as returned by `latest-version` is newer than the latest version in Chocolatey, it downloads the latest Windows installer, hashes it, builds the Chocolatey package, then pushes it to Chocolatey. This means we can schedule it as  a cronjob or post-commit hook and new releases will be pushed to Chocolatey automatically.
Fixes #802
**Test …

Decouple Chocolatey build from Windows Installer build

---

resources/winsetup/Yarn.wxs

**Summary**
Updates the Windows installer to add `%LocalAppData\Yarn\.bin` to the `PATH`, so that we can remove the "path setup" section that was added in the docs (https://yarnpkg.com/en/docs/install)
**Test plan**
Ran installer on my computer, ensured the PATH was updated correctly:
Uninstalled Yarn, ensured both PATH additions were removed.

Add %LocalAppData%\Yarn\.bin to PATH as part of installation

---

src/registries/npm-registry.js
src/resolvers/registries/npm-resolver.js

**Summary**
Sends the auth token for scoped packages, which may be private. Fixes #1134 and #521.
**Test plan**
Tested installing a private package on the public registry without `always-auth` in .npmrc.

Support auth for private npm packages

---

src/reporters/lang/en.js

**Summary**
In #1069, @Daniel15 pointed out a `[TODO]` in the [shrinkwrap warning message](https://github.com/yarnpkg/yarn/blob/22d0ac99bc2dc070ef109ea02b6d29ebcb4dc5df/src/reporters/lang/en.js#L61):
> shrinkwrapWarning: 'npm-shrinkwrap.json found. This will not be updated or respected. See [TODO] for more information.
I suggested inserting a link to https://yarnpkg.com/en/docs/migrating-from-npm, which includes this paragraph:
> If you are using an npm-shrinkwrap.json file right now, be aware that you may end up with a different set of dependencies. Yarn does not support npm shrinkwrap files as they don’t have enough information in them to power Yarn’s more deterministic algorithm. If you are using a shrinkwrap file it may be easier to convert everyone working on the project to use Yarn …

Add docs link to npm-shrinkwrap.json warning

---

__tests__/commands/self-update.js
bin/yarn.js
package.json
src/cli/commands/self-update.js
src/constants.js
src/reporters/lang/en.js
yarn.lock

This fixes self-update by doing:
* enable the tests
* use npm run build in the test instad of make build
* invalidated roadrunner cache, so that the symlink to `current` gets reevaluated
* do not do the request to github for the assets as they are already included in the release response
* pick the correct asset from the asset list by doing a name-check (content-type is sometimes set to octet-stream for the tar file, so we can't use that)
The roadrunner change is necessary as the tests need to invalidate the path cache so that the next test can reevaluate the symlinks. Same for the actual self-update command which also changes the symlink. This depends on kittens/roadrunner#1
Fixes #612 
Docs: https://github.com/yarnpkg/website/pull/173

Fix self-update

---

src/cli/commands/clean.js

**Summary**
The file `.yarnclean`should not be created if it exists. Otherwise filter rules are not usable.
Related issues:
- [1008](https://github.com/yarnpkg/yarn/issues/1008)
- [1051](https://github.com/yarnpkg/yarn/issues/1051)
**Test plan**
Tests and linting passed.

Don't create .yarnclean if it already exists

---

src/cli/commands/upgrade.js

**Summary**
The `upgrade` command was updated to provide similar "usage" docs to most other subcommand, which include the name of the subcommand in the output.
**Test plan**
Before: Usage: [command] [flags]
After:  Usage: upgrade [flags]
* Tested that `./bin/yarn help upgrade` has changed output as expected
* Tested that `./bin/yarn upgrade` still works as expected and isn't broken.

Improve 'Usage' docs for upgrade command.

---

__tests__/package-resolver.js
src/resolvers/exotics/git-resolver.js

**Summary**
The Git resolver did not understand usernames in URLs, e.g. `git+ssh://git@github.com/...` due to it treating any pattern containing `@` as being "un-exploded". See https://github.com/yarnpkg/yarn/commit/411205015b7d4f4af3c344062c1f85c64a32365c, #513.
For me it was falling through, and calling the npm resolver instead. The package wasn't published on the registry, so it was erroring there. For others, it would error due to version mismatches if it was on the registry.
Instead, it's now simply treating any `pattern` with no protocol as being invalid. [There's no valid npm git URL without a protocol.](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies)
Example failing pattern from before:
```
eslint-config-radweb@git+https://git@github.com/radweb/eslint-config-rad …
```

Add support for usernames in git resolver (Take 2)

---

bin/yarn
scripts/build-deb.sh
scripts/build-dist.sh

**Summary**
Converted `yarn` to be a shell script that checks for both `node` or `nodejs`. If neither is found, shows an error stating that Node.js needs to be installed.
**Test plan**
Tested in the following environments:
- Ubuntu 16.04, Node.js v6.7.0 installed from NodeSource repo
- Debian Testing, Node.js v4.3.1 installed from Debian repo
- Cygwin on Windows 10
- WSL (Bash on Ubuntu on Windows) on Windows 10
Built Debian package with `./scripts/build-deb.sh` and tested it on Ubuntu.
**Background**
Yarn always executes `node` (due to the shebang of `#!/usr/bin/env node`), and always executes `nodejs` on Debian/Ubuntu (we `sed` the shebang when building the package: https://github.com/yarnpkg/yarn/blob/master/scripts/build-deb.sh#L74).
The tricky/unfortunate thing with Node.js on Debian …

Convert "yarn" executable to a shell script that runs either "node" or "nodejs"

---

circle.yml

Removes this hack from the `circle.yml` file now that the executable supports both `node` and `nodejs`.

Remove hack for #1142

---

__tests__/util/parse-package-name.js
src/util/parse-package-name.js

**Summary**
Fixes https://github.com/yarnpkg/yarn/issues/1219
`yarn info $PACKAGE` failed when $PACKAGE is a single character. This is due to an overly restrictive regex in `parse-package-name.js`.
**Test plan**
I've included a test for `parsePackageName`, which failed before the regex change and passes after.
`bin/yarn info q` now works:
```
└> bin/yarn info q | head
yarn info v0.16.0
{ name: 'q',
description: 'A library for promises (CommonJS/Promises/A,B,D)',
'dist-tags':
{ latest: '1.4.1',
future: '2.0.3' },
versions:
[ '0.0.0',
'0.0.1',
'0.0.2',
```

Fix `yarn info` failing on single character packages (#1219)

---

appveyor.yml

May fix #1232 as per the discussion in http://help.appveyor.com/discussions/problems/5425-nodejs-690-seems-broken. Node.js is already installed via MSI so we don't need to install it again via Chocolatey.

Don't install Node.js via Chocolatey on AppVeyor

---

circle.yml
scripts/build-deb.sh
scripts/build-dist.sh
scripts/build-webpack.js

Builds the tarball and standalone JS files into the `artifacts` directory rather than the `dist` directory. The Debian package, RPM package and Windows installer are all already built into `artifacts`. This keeps the `dist` directory clean (see #548 for motivation)
Confirmed that all the artifacts appear correctly in CircleCI:
Closes #548

Build tarball and standalone JS files into artifacts directory

---

__tests__/util/git.js
src/util/git.js

**Summary**
This pull request adds tests for util/git.js. It improves the coverage to ~67% and also fixes a bug where Git.assertUrl was not checking correctly for git:// urls (because it was expecting the protocol to be `git` but it is actually `git:`.
**Test plan**
`npm run test` now outputs ~67% statements covered and 78% functions for `util/git.js`

improve Git coverage

---

src/cli/commands/upgrade.js

**Summary**
This fixes #1362. Also, there is a `TODO` in here to support "some" flags from the install command. I can update this PR with what "some" flags should be so we don't add one flag at a time. I just need to know which other ones should be moved over. :)
**Test plan**
```sh
$ yarn upgrade hawk@0.10
error hawk@0.10.2: The engine "node" is incompatible with this module. Expected version "0.8.x".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
```
```sh
$ yarn upgrade hawk@0.10 --ignore-engines
success Saved lockfile. …
```

Add --ignore-engines flag to `yarn upgrade` command

---

__tests__/resolvers/github-resolver.js
src/resolvers/exotics/github-resolver.js

building on #1372 .. add added some tests :)

honor github commit hash re pr/1372

---

src/cli/commands/outdated.js

**Summary**
This fixes #1254. The `yarn outdated` command will output where the dependency is located in the `package.json` file.
**Test plan**
Displays whether the package is a `dependency` or `devDependency`.
```sh
$ yarn outdated
Package   Current Wanted Latest
is-object 1.0.0   1.0.0  1.0.1
left-pad  1.1.0   1.1.0  1.1.3
✨  Done in 0.63s.
```
```sh
$ yarn outdated
Package   Current Wanted Latest Package Type
is-object 1.0.0   1.0.0  1.0.1  devDependencies
left-pad  1.1.0   1.1.0  1.1.3  dependencies
✨  Done in 0.35s.
```

Add package type output to `yarn outdated` command

---

__tests__/fixtures/request-cache/GET/localhost/.bin
src/reporters/lang/en.js
src/resolvers/registries/npm-resolver.js

**Summary**
When the yarn DNS failed to resolve today, a malformed response from the registry caused a cryptic error (see #1348) rather than a meaningful message. 
Sorry for no test plan; this is a simple commit, but I wouldn't know how to reproduce it. `npm test` still works, so it doesn't break anything. =)

Meaningful error message on malformed registry response

---

src/cli/commands/remove.js

This Fix for #1408 will change `yarn remove [package]` (where package is not in package.json) to error on invalid package name:
```
[1/2] Removing module fassdfsdf...
error This module isn't specified in a manifest.
```

Fixes #1408

---

src/registries/npm-registry.js

**Summary**
This PR is aimed at solving problems with `@types` (And I guess other public scopes) that can be seen in #825 and #1260 where even with the latest version yarn fails to restore packages where npm succeed. The case is specific to enterprise caches as the yarn or npm default repositories aren't affected.
In my case I had the problem and tested the resolution on ProGet ( http://inedo.com/proget ) configured with an NPM connector..
The issue is that `always-auth` is assumed for scoped packages, and `always-auth` forces the creation of an `authorization:` http header, even when no authentication can be found. The header is created empty in this case. As ProGet is an ASP.Net application and this platform consider an empty authorization header to be something that can never be met, …

Don't let the authorization header be empty

---

src/cli/commands/pack.js

**Summary**
changes the filename parameter from optional to mandatory for yarn pack -f
without this change the pack -f script fails if no filename is provided
**Test plan**
before this change:
```
[tkloht@Tobias-MacBook-Air ~/Code/yarntest2:master*] ../yarn-forked/bin/yarn pack -f
yarn pack v0.16.2
error An unexpected error occurred, please open a bug report with the information provided in "/Users/tkloht/Code/yarntest2/yarn-error.log".
```
in yarn error.log:
```
Trace:
TypeError: path must be a string or Buffer
at TypeError (native)
at Object.fs.open (fs.js:625:11)
at WriteStream.open (fs.js:1874:6)
at new WriteStream (fs.js:1860:10)
at Object.fs.createWriteStream (fs.js:1815:10)
at /Users/tkloht/Code/yarn-forked/lib/cli/commands/pack.js:133:23
at Object.<anonymous> …
```

set filename parameter to mandatory in pack -f

---

src/resolvers/registries/npm-resolver.js

**Summary**
When trying to add a unexistant version of a package, yarn warn user and list available version, separated by a comma and a space : 
```
error Couldn't find any versions for typescript that matches 2.1.0. Possible versions: 0.8.0, 0.8.1, 0.8.1-1, 0.8.2, 0.8.3, 0.9.0, 0.9.0-1, 0.9.1, 0.9.1-1, 0.9.5, 0.9.7, 1.0.0, 1.0.1, 1.1.0-1, 1.3.0, 1.4.1, 1.5.0-alpha, 1.5.0-beta, 1.5.3, 1.6.0-dev.20150722.1, 1.6.0-dev.20150723, 1.6.0-dev.20150724, 1.6.0-dev.20150725, 1.6.0-dev.20150726, 1.6.0-dev.20150727, 1.6.0-dev.20150728, 1.6.0-dev.20150729, 1.6.0-dev.20150730, 1.6.0-dev.20150731, 1.6.0-dev.20150801, 1.6.0-dev.20150802 [...]
```
The output can be really hard to read on packages with numerous versions.
This PR proposes to use new lines as separator when there …

Join available versions with newline if more than 20

---

__tests__/util/request-manager.js
src/package-request.js
src/reporters/lang/en.js
src/resolvers/registries/npm-resolver.js
src/util/request-manager.js

**Summary**
This is related to the issue https://github.com/yarnpkg/yarn/issues/1387
Replace MessageError string on `package-request.js`, `npm-resolver.js` and `request-manager.js`.
Sometime Im not sure how to get the reporter so I was wondering if its not worth it that Message Error have access to a reporter and you send only the lang message?
**Test plan**
I was able to create some test for `request-manager.js` since there was a test already in place (sry first time using Jest let me know if I should do the tests in another way)
But for the others 2 files I was not able to identify how to reach the code to test it .. so if someone could give some ideas how to test them it would be appreciated

Replace some MessageErrors string for lang  codes

---

src/reporters/lang/en.js

**Summary**
This adds a period to the end of the `savedNewDependency` message. This doesn't really solve a problem, but does make the output of running `yarn` more consistent. Most messages, including the very similar `savedNewDependencies`, end in a period. 
**Test plan**
I haven't actually tested this locally since it is just a change to a locale file and seems low risk. I suspect it can be tested by simply running commands such as `yarn add` or `yarn upgrade`.

Add period to `savedNewDependency` message for consistency

---

__tests__/cli/aliases.js

**Summary**
Add test coverage for existing aliased commands in `src/cli/aliases.js`
**Test plan**
`npm run lint && npm run test-only`
Adds the following test output:

Add test coverage for alias commands

---

src/cli/commands/add.js

**Summary**
yarn add --exact and yarn add --tilde had no CLI docs when running `yarn help add`.
I added this documentation.
**Test plan**
Tested manually with ./bin/yarn help add
Descriptions were based on official docs:
https://yarnpkg.com/en/docs/cli/add

Add CLI docs for yarn add --exact and yarn add --tilde

---

src/cli/commands/info.js

fixes #1347 
test plan
run yarn info . inside of a folder with a package.json before and after this is applied.

Handle using local module info when running info .

---

__tests__/commands/install.js
src/package-request.js
src/package-resolver.js

**Summary**
Smarter/looser dep version number resolving -- by range instead of exact version. ([comment and code disagree](https://github.com/yarnpkg/yarn/blob/master/src/package-request.js#L218-L220))
`package-request` will resolve a package to the **highest** available version, and check if that package version has already been resolved with `package-resolver`'s **exact version match** `getExactVersionMatch`. 
Instead of matching the exact highest version: match satisfying resolved ranges of the requested package, and pick the highest available one, *if* possible. *If not* possible, continue and resolve to the highest possible version as before.
https://github.com/yarnpkg/yarn/issues/112 originally says and tests the opposite of this. The concerns in this issue have been tested as-well …

fix-1158: resolve dep verions by ranges, not exact versions (#1158) (#1272) (#1404)

---

src/resolvers/exotics/hosted-git-resolver.js

**Summary**
Let the dependencies be: 
``` 
dependencies: {
"lens": "github:blahah/lens-1#patch-10"
}
```
Without this change, parsing package.json from this github repository results in:
```
TypeError: factory is not a function
at /Users/juretriglav/src/yarn/lib/config.js:527:22
at next (native)
at step (/Users/juretriglav/src/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
at /Users/juretriglav/src/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
at Promise.F (/Users/juretriglav/src/yarn/node_modules/core-js/library/modules/_export.js:35:28)
at /Users/juretriglav/src/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
at Config.readJson (/Users/juretriglav/src/yarn/lib/config.js:536:7)
at …
```

Factory needs to be a function.

---

src/cli/commands/init.js

**Summary**
https://github.com/npm/normalize-package-data is a tool used by the npm registry and the npm client to clean up package data. One of the things is does is:
> If repository field is a string, it will become an object with `url` set to the original string value, and type set to "git".
This means that the `package.json` file can have a simple string URL value for `repository`. This style leads to a cleaner `package.json` file and is easier for humans to read.
This PR updates the `yarn init` command to set `repository` as a string, rather than an object with `url` and `type` values.
**Example Usage**
```
$ cd example
$ git init                  
Initialized empty Git repository in /Users/zeke/Desktop/example/.git/
$ git remote add origin https://github.com/zeke/example
$ …
```

init package.json repository as a string instead of an object

---

__tests__/resolvers/exotics/hosted-git-resolver.js
src/resolvers/exotics/hosted-git-resolver.js

**Summary**
Given a dependency:
```
dependencies: {
"substance": "jure/substance#fix-lens-#96"
}
```
Yarn raises an error: 
```
error Invalid hosted git fragment "jure/substance#fix-lens-#96".
```
This is because the current code https://github.com/yarnpkg/yarn/blob/0f1db96846badbbe3b43c470c05196eb29437fb4/src/resolvers/exotics/hosted-git-resolver.js#L29 bails if there is more than one hash in the repo part.
**Test plan**
Added two tests, one for a branch with hashes and one for a `feature/fix-issue` (no hash) branch.

Git branches can have hashes as part of their name

---

circle.yml

**Summary**
Archives builds from CircleCI into our directory for nightly builds. I'm using the phrase "nightly" but I really mean "unstable" as it's archived after every build, not once per night.
**Test plan**
¯\\\_(ツ)\_/¯
This probably needs more testing - The script it's calling intentionally ignores all requests that aren't for the master branch of yarnpkg/yarn repo as we don't want to archive random stuff from other repos or branches, but that means that I can't actually test it in my fork at the moment 😛 I might just create a copy of the archiving script and play with it some more in my fork.

Add webhook for archiving CircleCI build artifacts

---

src/constants.js

**Summary**
Fixing `yarn global add` being installed in root folder described in [issue #1029](https://github.com/yarnpkg/yarn/issues/1029)
.
Users can't access `/root/.yarn-*` .
Using `/usr/local/lib`instead like npm modules (`/usr/local/lib/node_modules`)
eg:
```
yarn global add react-native-cli
/usr/local/bin/react-native -> ../lib/.yarn-config/global/node_modules/.bin/react-native*
```
**Reference**
- [Issue #1029](https://github.com/yarnpkg/yarn/issues/1029)

Fixing global add in linux root folder #1029

---

src/cli/index.js
src/config.js

This PR adds two CLI arguments to set the http and https proxies.
A proxy set through the CLI takes precedence over any proxy set inside the .yarnrc/.npmrc files.
Fixes #655.

Add CLI arguments to set the proxies

---

scripts/install-latest.sh

**Summary**
The syntax the install script uses for colour coding works in some shells (including Bash, zsh and Fish), but does **not** work in dash. Debian and Ubuntu use Dash as the default implementation of `/bin/sh` (see https://wiki.ubuntu.com/DashAsBinSh), so Debian and Ubuntu users will see broken colours in the installation script if they use it (as its shebang specifies `/bin/sh`)
**Test plan**
Before:
After:
In `bash`, output should be identical.

Fix colour codes in install script

---

scripts/install-latest.sh

**Summary**
Adds a `--nightly` flag to the installation script. When provided, the script will download the latest nightly build of Yarn, rather than the stable released version
**Test plan**
`./install-latest.sh` gets latest release version (0.16.1), `./install-latest.sh --nightly` gets latest nightly build (0.16.2-20161030.0336 right now)

Add `--nightly` flag to install script

---

src/resolvers/exotics/hosted-git-resolver.js
src/util/request-manager.js

**Summary**
For hosted git resolver, e.g. for BitBucket, the HEAD https://bitbucket.org/someuser/private.git inside the `hasHTTPCapability` gives 302 redirecting user to sign in. However, in such condition we need to fallback to `git+ssh`.
**Test plan**
Create a private git repo on bitbucket, e.g. https://bitbucket.org/someuser/private.git then do:
```
$ yarn add bitbucket:someuser/private
```
Currently, it gives:
```
error An unexpected error occurred, please open a bug report with the information provided in "/Users/diorahman/Experiments/misc/ev/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
After this patch and if this one (https://github.com/yarnpkg/yarn/pull/1081) merged. It will give successful result.

Do not follow redirect for HostedGitResolver#hasHTTPCapability

---

__tests__/resolvers/exotics/bitbucket-resolver.js
__tests__/resolvers/exotics/gitlab-resolver.js
src/resolvers/exotics/bitbucket-resolver.js
src/resolvers/exotics/github-resolver.js
src/resolvers/exotics/gitlab-resolver.js

**Summary**
At this line https://github.com/diorahman/yarn/blob/master/src/fetchers/git-fetcher.js#L20 the `GitFetcher._fetch` should have a resolved URL (from hosted, private repo) that has protocol. If not the actual fetching always falls through to `fetchFromLocal`.
**Test plan**
Create a private repo on github. E.g. For my test I have https://github.com/HOOQTV/inbox and it has several releases, one of them: `v0.1.0`.
Then try to `yarn add github:hooqtv/inbox#v0.1.0`.
Before this PR: 
``` bash
▲ ev: yarn add github:hooqtv/inbox#v0.1.0
yarn add v0.1.0
error git@github.com:hooqtv/inbox.git: Tarball is not in network and can not be located in cache (/Users/diorahman/Experiments/hooq/src/misc/ev/git@github.com:hooqtv/inbox.git) …
```

Return SSH URL format for getGitSSHUrl

---

src/cli/commands/version.js
src/config.js

**Summary**
There were 2 lint warnings: a `no-extra-boolean-cast` on `src/cli/commands/version.js` and a `no-unused-vars` on `src/config.js`.
**Test plan**
All tests are passing.

Fix lint warnings

---

__tests__/resolvers/exotics/hosted-git-resolver.js
src/resolvers/exotics/hosted-git-resolver.js

**Summary**
Fixes #1287
When a github URL is used in a `package.json` file which has a `.git`
suffix attached to its repository name, resolution fails with an error:
```
TypeError: Cannot read property 'split' of undefined
at Function.parseRefs (/usr/local/Cellar/yarn/0.16.0/libexec/lib/node_modules/yarn/lib/util/git.js:439:20)
at /usr/local/Cellar/yarn/0.16.0/libexec/lib/node_modules/yarn/lib/resolvers/exotics/hosted-git-resolver.js:138:50
...
```
for e.g. `https://github.com/gulpjs/gulp.git`.
This was caused by an extraneous `.git` suffix appended to the URL by
the resolver.
**Test plan**
Added a unit test which checks a github URL with and w/o .git suffix.

Make `.git` suffix optional for hosted git

---

src/cli/commands/add.js

Allow save-prefix to be blank
If running
```
yarn config set save-prefix ""
```
Yarn add will prefix undefined to `package.json`
This PR fixes that.

allow blank prefix

---

__tests__/util/git.js
src/fetchers/git-fetcher.js
src/resolvers/exotics/git-resolver.js
src/resolvers/exotics/hosted-git-resolver.js
src/util/git.js

https://github.com/yarnpkg/yarn/pull/1365/files introduced a fix to enforce secure protocols. This unfortunately broke a lot of packages we have which depend on 'git' protocol (e.g., 'npm show @opam-alpha/core').
Instead of refusing to work when a unsecure protocol is provided, maybe a better way here is to automatically upgrade to a secure url.

[git] Upgrade to secure url

---

scripts/install-latest.sh

**Summary**
Terminals are terrible. Literally the worst. `tput` fails if the terminal is `vt100`. I'm reverting my change and instead making the script execute Bash directly.
**Test plan**
Ensure output still has colours:
Reverts #1553 
Fixes #1574

Revert #1553 and instead just use Bash explicitly

---

end_to_end_tests/README.md
end_to_end_tests/data/run-ubuntu.sh
end_to_end_tests/data/run-yarn-test.sh
end_to_end_tests/data/start-ubuntu.sh
end_to_end_tests/test-ubuntu-12.04.sh
end_to_end_tests/test-ubuntu-14.04.sh
end_to_end_tests/test-ubuntu-16.04.sh

**Summary**
Adds some scripts for end-to-end testing of Yarn. The test script does the following:
1. Spin up a fresh Docker container
2. Install Yarn through the Debian/Ubuntu package repository
3. Run `yarn add react` in a test directory
I'm going to run these nightly. The tests will be more useful once I add a package repo for nightly builds, as it'll let us catch any regressions in the full end-to-end process.
**Test plan**
``` sh
cd end_to_end_tests
./test-ubuntu-16.04.sh # or test-ubuntu-14.04.sh or test-ubuntu-12.04.sh
```
Testing on Windows works fine if you have [Docker for Windows](https://docs.docker.com/docker-for-windows/) installed, and run the Docker command directly rather than using the shell script:
```
docker run -t -v c:/src/yarn/end_to_end_tests/data:/data -w=/data …
```

Add end-to-end tests for Ubuntu 12.04, 14.04 and 16.04 using Docker

---

src/reporters/lang/en.js
src/util/normalize-manifest/validate.js

**Summary**
Renamed `manifestPotentialType` in `en.js` to clearer `manifestPotentialTypo`.
**Test plan**
No tests needed I think.

Rename 'manifestPotentialType' to 'manifestPotentialTypo'

---

__tests__/fixtures/lifecycle-scripts/npm_config_argv_env_vars/log-command.js
__tests__/fixtures/lifecycle-scripts/npm_config_argv_env_vars/package.json
__tests__/lifecycle-scripts.js
src/cli/index.js
src/config.js
src/util/execute-lifecycle-script.js

**Summary**
npm `prepublish` script is [broken by design](https://blog.greenkeeper.io/what-is-npm-s-prepublish-and-why-is-it-so-confusing-a948373e6be1#.j9lcz8whd). yarn `prepublish` script is broken the same way for back compatibility 😆 Developers use packages like [in-publish](https://github.com/iarna/in-publish) to workaround this problem. `in-publish` relies on `npm_config_argv` environment variable to determine the actual command that is running. We can't provide exact same results as npm here, because yarn uses other command line parser, but we emulate it's output with precision that is enough to render this workaround usable.
**Test plan**
Tests are included.

Emulate `npm_config_argv` environment variable for lifecycle scripts (closes #684)

---

scripts/bootstrap-env-ubuntu.sh

**Summary**
Loads GPG key from a URL we host, rather than a keyserver. This will hopefully make builds less flaky (they won't fail when the keyserver has issues)
I tried `https` but it didn't work:
> gpgkeys: protocol 'https' not supported
> gpg: no handler for keyserver scheme 'https'
> gpg: WARNING: unable to fetch URI https://dl.yarnpkg.com/debian/pubkey.gpg: keyserver error
**Test plan**
Tested the command locally. Will check CircleCI build.

Load GPG key from URL rather than keyserver

---

appveyor.yml

**Summary**
https://www.appveyor.com/updates/2016/11/01/ mentions that Yarn is preinstalled now (thanks @FeodorFitsner!), so we shouldn't need to install it manually.
**Test plan**
It works! https://ci.appveyor.com/project/kittens/yarn/build/1.0.577

AppVeyor now has Yarn preinstalled, don't install it manually

---

src/cli/index.js
src/reporters/lang/en.js

Implements #1456.
When an unexpected error occurres it now shows the error message in console. I also renamed the old unexpectedError string to bugReport and gave it an info flag. 
**Test plan**
I tested this by setting the permissions of my package.json to read-only and then attempt to install a new package using `yarn add left-pad`. 
Instead of outputting:
```
error An unexpected error occurred, please open a bug report with the information provided in "/home/jeffrey/Documents/Projects/yarn-testing/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
It now outputs:
```
error An unexpected error occurred: "Error: EACCES: permission denied, open '/home/jeffrey/Documents/Projects/yarn-testing/package.json'\n    at Error (native)".
info …
```

Show error message in stdout.

---

src/cli/commands/global.js

**Summary**
Needed to upgrade global packages. Fixes #776 .
**Test plan**
```
$ yarn global ls|grep how-to
warning fsevents@1.0.14: The platform "linux" is incompatible with this module.
info how-to-npm@2.0.0 has binaries:
- how-to-npm
$ yarn global add how-to-npm@1.2.0
yarn global v0.16.1
warning fsevents@1.0.14: The platform "linux" is incompatible with this module.
info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed how-to-npm@1.2.0 with binaries:
- how-to-npm
Done in 7.25s.
$ Workspace/yarn/bin/yarn global upgrade how-to-npm
yarn global …
```

Adding 'yarn global upgrade'(Issue #776)

---

__tests__/util/git.js

**Summary**
Bumping the timeout seemed to do the trick for me here: https://circleci.com/gh/yarnpkg/yarn/1906
**Test plan**
Circle CI builds are green again.

Attempt to fix failing Circle CI builds

---

appveyor.yml

**Summary**
Basically the same as #1473 except for AppVeyor (ie. the Windows installers) instead of CircleCI.
Archives master builds from AppVeyor into our directory for nightly builds. I'm using the phrase "nightly" but I really mean "unstable" as it's archived after every build, not once per night.
**Test plan**
Tested on my fork, will also check results in AppVeyor and on the nightly site once merged.
References #1474

Add webhook for archive AppVeyor build artifacts

---

__tests__/commands/why.js
__tests__/fixtures/why/basic/package.json

Unit tests for basic functionality of `yarn why`.
And possibly later from #1524:

Unit tests for the command `yarn why`.

---

src/cli/commands/add.js

Added short-flags support in `yarn add` command.
Eg. Instead of `yarn add gulp --dev`, you can use `yarn add gulp -D`.
Similarly, `--peer`, `--optional`, `--exact`, `--tilde` can be used by simply adding `-P`, `-O`, `-E`, `-T` flag with `yarn add `.
P.S. I'm a neophyte. Please guide if something is wrong.

Added short-flags for yarn add

---

__tests__/commands/_install.js
__tests__/commands/add.js
__tests__/commands/install.js
src/cli/commands/global.js

**Summary**
There were some flow errors and test broken introduced with https://github.com/yarnpkg/yarn/commit/96fbeea6afb144652a5a05c0ee8571057d78c4b6 and this should fix them up. It also adds a test for the `--no-bin-links` flag that was introduced with that commit.
**Test plan**
Tests and lint checks pass.

Fix flow types and install test

---

package.json
scripts/release-branch.sh

For example, you are on version 0.16 and call `scripts/release-branch.sh` it will:
- change package.json version to 0.17.0 and tag change with v0.17.0
- make new branch 0.17-stable and push it to origin
- switch back to master
- change package.json version to preminor 0.18.0-0 and tag change with v0.18.0-0
- push master to origin
This way when people report bugs from master branch it will not be confused with released versions of Yarn
cc @Daniel15 
Test Plan:
(locally with commit commands suppressed)
```
bestander-mbp:yarn bestander$ ./scripts/release-branch.sh
+ yarn version --new-version minor
yarn version v0.16.1
info Current version: 0.19.0
info New version: 0.20.0
✨  Done in 0.14s.
++ node -p -e 'require('\''./package.json'\'').version'
+ VERSION=0.20.0
++ echo 0.20.0
++ IFS=.
++ …
```

Mark master branch as "prerelease"

---

__tests__/commands/add.js
__tests__/commands/upgrade.js
__tests__/fixtures/add/latest-version-in-lockfile/package.json
__tests__/fixtures/upgrade/fixed-to-latest/package.json
src/cli/commands/add.js

**Summary**
This fixes #1685. The command would not store the latest version in the lockfile and would drop the version altogether. This change will resave the lockfile when it formats the patterns for the manifest.
**Test plan**
```js
{
"lodash": "4.15.0"
}
}
```
```sh
$ yarn upgrade lodash
```
```
lodash:
version "4.16.6"
resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.16.6.tgz#d22c9ac660288f3843e16ba7d2b5d06cca27d777"
````
```
lodash@^4.16.6:
version "4.16.6"
resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.16.6.tgz#d22c9ac660288f3843e16ba7d2b5d06cca27d777"
```

Fix `yarn upgrade <package>` command to store version in lockfile

---

src/cli/commands/add.js

**Summary**
This fixes #1700. The shorthand/alias commands should come before the long command name in the `commander.option` function. The last one defined in the list is the name of the flag that is set. So, previously when passing `--dev` and we look for `flags.dev`, it wouldn't be set, but `flags.D` would be set to `true`.
**Test plan**
All tests pass and flags are respected.

Fix flags for `yarn add` command

---

__tests__/reporters/__snapshots__/console-reporter.js.snap
src/reporters/console/console-reporter.js

**Summary**
This change fixes #1699. 
**Test plan**
Two ConsoleReporter snapshot tests failed when running the test suite. I assume that should be expected since the purpose of this change is to fix the console coloring for console reporter commands. However, let me know if I'm misunderstanding.*
In comparison with the screenshots in #1699, here is the npm-linked fix working with the correct console coloring:
**Update: I realized I needed to update the `jest` snapshot for the ConsoleReporter tests.*

Change all console format grey to dim

---

__tests__/commands/ls.js
src/cli/commands/add.js
src/cli/commands/ls.js
src/reporters/base-reporter.js
src/reporters/console/console-reporter.js
src/reporters/console/helpers/tree-helper.js

**Summary**
Per #726, filtering the depth of children displayed should be supported.
**Test plan**
Added support for: `yarn ls depth [LEVEL]` where the first level is 1.
**Examples**:
`yarn ls depth 1`
`yarn ls depth 2`
`

add depth specification to ls. Fixes #726

---

src/cli/index.js
src/reporters/lang/en.js

Fixes --mutex, which currently doesn't pass the file specifier into repeated calls, and so multiple parallel calls don't correctly exclude one another.
**Test plan**
Tested via running:
```
for i in `seq 1 5`; do
~/git/yarn/dist/bin/yarn install --pure-lockfile --mutex file:/tmp/yarn & 
done
```
For packages with a reasonable number of dependencies, this fails pretty reliably on master with various errors from `~/.cache/yarn`. After this change there are many messages about waiting for the other yarns to finish, and all then complete successfully.

Fix --mutex

---

end_to_end_tests/data/run-ubuntu.sh

**Summary**
Updates the end-to-end test script to use the nightly repo rather than the release repo.
**Test plan**
Tested on my build server using Jenkins + Docker.
Full build output:
```
Started by user Daniel Lo Nigro
Building in workspace /var/lib/jenkins/workspace/yarn/ubuntu-16.04
> git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
> git config remote.origin.url git://github.com/yarnpkg/yarn # timeout=10
Fetching upstream changes from git://github.com/yarnpkg/yarn
> git --version # timeout=10
> git fetch --tags --progress git://github.com/yarnpkg/yarn +refs/heads/*:refs/remotes/origin/*
> git rev-parse refs/remotes/origin/master^{commit} # timeout=10
> git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out …
```

Update end-to-end tests to use nightly repo

---

end_to_end_tests/data/run-ubuntu.sh
end_to_end_tests/data/run-yarn-test.sh
end_to_end_tests/data/start-ubuntu.sh

**Summary**
Latest released version of Yarn handles `yarn add` in directories that don't yet have a `package.json` file, whereas the latest master version fails. I updated the end-to-end test to create a blank package.json to work around this change. See #1747 for more details.
Also other miscellaneous improvements:
- Set `DEBIAN_FRONTEND=noninteractive` so apt-get doesn't complain about not having a tty
- Grab GPG key via HTTP instead of keyserver to avoid flaky keyservers
**Test plan**
Tested on my computer:
```
docker run -t -v c:/src/yarn/end_to_end_tests/data:/data -w=/data -e DEBIAN_FRONTEND=noninteractive ubuntu:16.04 /data/run-ubuntu.sh
```

Create blank package.json during end-to-end tests to work around #1747

---

__tests__/util/misc.js
src/util/misc.js

**Summary**
The previous sort function used `localeCompare` which is dependent on the user's locale configuration (and I think node support). This resulted in non-deterministic lock files. This new approach uses unicode point code as the rank, which is consistent for everyone.
**Test plan**
Added a test.
cc: @bestander @Daniel15

Use deterministic sort (fixes #1308)

---

__tests__/commands/add.js
src/cli/commands/add.js
src/cli/commands/install.js
src/package-resolver.js

Fixes #1733
**Summary**
`add` command now generates integrity hash and has correct package.js and yarn.lock 
**Test plan**
```
bestander@DESKTOP-9BB67ID:/mnt/c/Users/besta/work/temp$ ../yarn/bin/yarn add left-pad
yarn add v0.17.0-0
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ left-pad@1.1.3
Done in 0.52s.
bestander@DESKTOP-9BB67ID:/mnt/c/Users/besta/work/temp$ ../yarn/bin/yarn install
yarn install v0.17.0-0
success Already up-to-date.
Done in 0.14s.
```

Add integrity refactor

---

end_to_end_tests/data/run-ubuntu.sh

**Summary**
Old approach had a few issues:
- It required cURL to be installed, when it's otherwise unnecessary
- Packages can't be cached (eg. by [apt-cacher-ng](https://www.unix-ag.uni-kl.de/~bloch/acng/)) as they're being loaded over HTTPS. I'm caching the packages to speed up the test runs.
Directly adding their repo (rather than using their shell script) seems like a better idea.
**Test plan**
Tested on my computer:
```
docker run -t -v c:/src/yarn/end_to_end_tests/data:/data -w=/data -e DEBIAN_FRONTEND=noninteractive ubuntu:12.04 /data/run-ubuntu.sh
```

Directly add NodeSource repo in end-to-end tests, rather than using their shell script

---

src/package-request.js

**Summary**
Right now visibility is set before the dependencies are added to the package reference. This means that no visibility information propagates for other requests for the same package. Example:
1. `is-glob@^2.0.0` is encountered. Visibility for the request is "env hidden"
2. Dependencies of `is-glob@^2.0.0` are walked and inherit the visibility from their parent
3. `is-glob@^2.0.1` is encountered. Visibility for the request is "used"
4. Because there's already something compatible in flight, it's merged into the existing ref
5. `addVisibility` is called - but at this point the dependencies are not yet resolved
6. The dependencies are added - but none of them will ever learn that (one of) their parent was "used"
**Test plan**
I couldn't figure out a good unit test for this. What I …

Delay visibility propagation until deps are known

---

__tests__/fixtures/normalize-manifest/readme/README/somefile
src/util/normalize-manifest/fix.js

**Summary**
some repos have a README folder that breaks the current heuristic, e.g.:
https://github.com/bitwiseshiftleft/sjcl
**Test plan**
added breaking test and fix (favor filenames with extensions). A more thorough but more expensive fix would be to check try to readFile all readme filename candidates

fix readme detection

---

__tests__/cli/aliases.js
package.json
src/cli/aliases.js
src/cli/commands/index.js
src/cli/commands/update.js
src/reporters/lang/en.js
yarn.lock

This is similar to `npm-check` interactive update mode. It provides an easy way to update outdated packages.
I used the `update` command as par @cpojer's recommendation.
```
$ yarn update
```
> Currently, there is no test with this PR. But, If someone can guide me with some scenarios, I will write them, Thanks.

Feature: Interactive update

---

__tests__/cli/aliases.js
src/cli/aliases.js
src/cli/commands/upgrade-interactive.js

**Summary**
Incorporate changes form #1696 to #1444 
> It would display that you weren't on latest even when your version was higher than what was determined to be latest. I also added another test in regards to dependency types here since I had to make a change that could have affected those.
Also, reverted alias back to original since we are not calling it `update`.

Update outdated condition in upgrade-interactive

---

src/cli/commands/link.js

link is already registered
**Summary**
Fixes #1723 by making yarn link warn instead of throw an error if a link is already registered.
Error is thrown instead of a warning when link is registered
**Test plan**
```
../yarn/bin/yarnpkg link
yarn link v0.17.0-0
warning There's already a module called "yarn-gh-issue-1723" registered.
✨  Done in 0.09s.
```
Some of the tests fail and I'm not really sure why. They seem unrelated and fail inconsistently. Running `npm run test` multiple times gave me different results. The test was running for nearly 10 mins too. 
Looks like the tests only failed locally.

making link command warn instead of throw an error if

---

__tests__/util/request-manager.js
src/config.js
src/util/request-manager.js

**Summary**
npm supports specifying CA contents directly in the `.npmrc` file, using `ca` option.
yarn does not currently support this, as mentioned in several comments, e.g.:
* https://github.com/yarnpkg/website/issues/128#issue-182372920
* https://github.com/yarnpkg/yarn/issues/606#issuecomment-252977248
**Test plan**
Localhost is running Sinopia with cert signed by self-signed root CA.
Below is `.npmrc` file contents (root CA cert is removed for brevity):
registry=https://localhost:4873
ca[]="-----BEGIN CERTIFICATE----- ... -----END CERTIFICATE-----"
npm output:
$ npm install leftpad
leftpad@0.0.0 node_modules/leftpad
yarn output:
$ yarn add leftpad
yarn add v0.16.1
error An unexpected error occured, please open a bug report with the information provided in …

Add support for 'ca' config file option

---

src/cli/commands/ls.js

**Summary**
It was reported in https://github.com/yarnpkg/yarn/pull/1792#issuecomment-260364519 that this code did not work on Node v4.
**Test plan**
All tests still pass. Confirmed working on Node v4 here: https://github.com/yarnpkg/yarn/pull/1792#issuecomment-260369372

Replace `.includes` with `.indexOf` for older Node 4 versions

---

__tests__/fixtures/request-cache/GET/localhost/.bin
package.json

CI systems sometimes don't report number of available cores correctly.
Jest is trying to use all JS cores and this may cause too much memory to be allocated which causes a build to fail. (see tests running in ~16 threads https://2093-49970642-gh.circle-artifacts.com/0/tmp/memory-usage.txt)
**Test plan**
Locally test runtime is not slowed down any significant way
```
Test Suites: 2 skipped, 34 passed, 34 of 36 total
Tests:       19 skipped, 265 passed, 284 total
Snapshots:   50 passed, 50 total
Time:        66.623s, estimated 68s
```

limited number of cores to be used in test runner

---

src/cli/commands/install.js

**Summary**
`yarn install` is broken for the latest nightly, v0.18.0 - introduced by a typo from #1429
There is a typo in `install.js` in the latest nightly where the `version` key for yarn is spelled as **verison**.
```js
const {verison: YARN_VERSION, installationMethod: YARN_INSTALL_METHOD} = require('../../../package.json');
```
This results in `YARN_VERSION` being `undefined` and causing errors down the script. Such as: 
```js
Trace:
TypeError: Cannot read property 'indexOf' of undefined
at Install.checkUpdate (/usr/share/yarn/lib/cli/commands/install.js:906:21)
at /usr/share/yarn/lib/cli/commands/install.js:466:14
at next (native)
at step (/usr/share/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
at /usr/share/yarn/node_modules/babel-runtime/helpers/asyncToGenerato …
```

Fix version key typo on install.js

---

__tests__/commands/install.js
src/package-linker.js

Fixes #1823.
Looks like nested dependencies binaries can conflict with each other and I reverted #1210 for now.
In a fix we need to expect tests that prevent duplicate bins overwriting

reverted Nested executables #1210 to fix #1823

---

__tests__/constants.js
src/constants.js
src/fetchers/tarball-fetcher.js

**Summary**
Fixes #1750 
`TarballFetcher` uses [`tar`](https://github.com/npm/node-tar) to untar tarballs. `tar` in turn constructs a [`Writer`](https://github.com/npm/fstream/blob/24fabdec32e334dd3b130d77b38c010e3119b102/lib/writer.js#L26) object per entry in the tarball, preserving the original UID and GID in the tarball.
If `Writer` detects that the UID of the user is 0 (i.e. root user), it will attempt to [`chown`](https://github.com/npm/fstream/blob/24fabdec32e334dd3b130d77b38c010e3119b102/lib/writer.js#L195) the extracted file to the UID. 
Usually, this is not a problem. However, as in #1750 and other issues, if the _`root`_ user is not really root but inside a [user namespace](http://man7.org/linux/man-pages/man7/user_namespaces.7.html), and the UID is outside the …

Set UID and GID of untared files to zero if user is root

---

__tests__/commands/global.js
src/cli/commands/global.js

**Summary**
`~/.config/yarn/global/node_modules/.bin` was not creating.
Fixes #1886

Fix global add linking issue

---

.travis.yml

**Summary**
Removes the NodeSource repo from the TravisCI build - I don't think we need it any more
**Test plan**
Will check Travis on the PR

Remove NodeSource repo from Travis build

---

src/reporters/lang/en.js
src/util/normalize-manifest/validate.js

**Summary**
The reason for this is that Yarn is useful in many JS environments such as browsers and React Native, which don't provide the Node built-ins. Depending on polyfills is the right thing to do in that scenario and the reality is that people intentionally publish these polyfills under the same name as the Node built-ins (e.g. url and buffer).
Fixes #917
**Test plan**
`npm test`

Remove warning about depending on packages with the same name as Node built-ins

---

bin/yarn.js
end_to_end_tests/data/run-yarn-test.sh

**Summary**
This solves #1724. Ensures that we always have the cache directory created so roadrunner can work successfully.
**Test plan**
Not sure what kind of tests to add for this. @Daniel15, anything you can think of that could be added to e2e tests for this?
I was able to reduce the error with:
```sh
$ rm -rf ~/Library/Caches/Yarn
$ yarn --version
```

Ensure cache diretory exists before using roadrunner

---

bin/yarn.js

**Summary**
Fixes #1898
**Test plan**
I couldn't find a good way to test this. I doubt that it's worth the effort of installing an old, unsupported node version only to expect that it quits gracefully.

Gracefully quit when using unsupported node version

---

src/reporters/lang/en.js
src/util/normalize-manifest/fix.js
src/util/normalize-manifest/index.js

**Summary**
Fixes situation where the bin or man directory is specified in the package.json but does not really exist.  This change is to address issues like #739
**Test plan**
yarn add newman@3.2.0 succeeds to install.  Previously when installing dependency postman-collection@0.5.5 yarn would crash with an ENOENT trying to read the bin directory that doesn't exist.

Warn when man or bin directory not found but don't crash

---

scripts/install-latest.sh

**Summary**
Adds a --version flag to the installation script, expanding on the nightly flag added in https://github.com/yarnpkg/yarn/pull/1554. When provided, the script will download the specified build of Yarn, rather than the stable released version. It grabs them from the downloads directory as specified in https://github.com/yarnpkg/yarn/issues/1724#issuecomment-260568698 and updates the version check to reflect if the user has installed the same version (regardless of flags provided) in the user's home directory. The speed of this script is ~1 minute faster compared to using `npm` and provides an alternative to switching versions to help with https://github.com/yarnpkg/yarn/issues/1724 as well.
**Test plan**
`./install-latest.sh` gets latest release version (`0.16.1`), …

Add `--version` flag to install script

---

__tests__/commands/install.js
__tests__/fixtures/install/artifacts-finds-and-saves/dummy/install.js
__tests__/fixtures/install/artifacts-finds-and-saves/dummy/package.json
__tests__/fixtures/install/artifacts-finds-and-saves/package.json
src/config.js
src/fetchers/base-fetcher.js
src/package-fetcher.js
src/package-install-scripts.js
src/package-linker.js
src/package-reference.js
src/util/fs.js

**Summary**
This PR removes the build artifact copying to our cache and instead saves a list of the build artifact files so we ignore them when considering files extraneous inside modules. We need to save this list to distinguish build artifacts (which we should keep) and other extraneous files.
If we consider build artifacts to be extraneous then it'd require running all install scripts, even if they weren't touched, on every single install which is excessively expensive.
**Test plan**
Tests were added. `$ jest`.

When saving build artifacts, rather than copying, save list of files to ignore

---

__tests__/package-hoister.js
src/package-hoister.js
src/util/fs.js

**Summary**
Resolves #1861.
The above issue is Windows-specific. It's caused by the step that unlinks extraneous packages. This compares a Set `possibleExtraneous` against a Set of paths `files` resolved during bulk copy.
The problem is how paths are added to the `files` Set. yarn attempts to add all path segments to `files` by splitting the destination path on `path.sep`. This works as expected on Posix systems, where the path separator is the same as the scoped package name delimiter:
`project/node_modules/@scoped/dep/node_modules/subdep`
But on Windows, the destination path is constructed naively from the package name:
`project\\node_modules\\@scoped/dep\\node_modules\\subdep`
`possibleExtraneous`, having been resolved from reading directories on disk rather than from the …

Resolve scoped package paths during linking on Windows

---

src/reporters/lang/en.js
src/resolvers/exotics/hosted-git-resolver.js

**Summary**
When a hosted git url cannot be resolved, currently "TODO" is returned to the user. Reference #1921 
** Motivation ** 
Better error message.

fix todo message when url not found on hosted git

---

README.md

**Summary**
Upon looking for basic usage commands I discovered that there is no mention of this in the official README.md, just an indirect link in the form of a link to the installation guide in the official documentation (where you can navigate to the usage documentation, if you know to look for it from here). I therefore propose to add a separate usage section, and/or a documentation section with url to the official documentation for further reading.
**Test plan**
N/A.

Add usage section to README.me with link to docs

---

bin/yarn.js
src/constants.js

**Summary**
Based on the current version to prevent dependency shifting. Fixes #1960.
**Test plan**
Manually tested, unsure how to reliably unit test.

Add a cache breaker to roadrunner cache

---

src/resolvers/exotics/tarball-resolver.js

Closes #1973 
"tar.gz" actually [is a node module itself](https://www.npmjs.com/package/tar.gz)
Any real .tar.gz will have the preceding dot in the file extension.
**Test plan**
I searched for existing tests for the resolvers but couldn't find any. The tarball resolver apparently has no test at all. I think a coverage service would help to make that visible (see https://github.com/yarnpkg/yarn/issues/510). This way, people can easily start to contribute to yarn by adding tests for untested branches. I'd set this up but I'm not a member of the organisation. Can some member do it? @wyze, @torifat @kittens ?

Fix .tar.gz pattern matching

---

circle.yml
scripts/install-latest.sh

**Summary**
When installing Yarn via the install script, check the integrity of the tarball.
I'm using the same GPG key we use to sign the Debian repo, and have already signed the existing releases. The GPG signature sits alongside the tarball in the GitHub release, as an `.asc` file.
**Test plan**
Tested locally with various flags:
```
./install-latest.sh
./install-latest.sh --nightly
./install-latest.sh --version 0.17.6
```
```
daniel@Daniel-PC:/mnt/c/src/yarn/scripts$ ./install-latest.sh --nightly
Installing Yarn!
> Downloading tarball...
[1/2]: https://nightly.yarnpkg.com/latest.tar.gz --> /tmp/tmp.ghxlavTdks
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- …
```

Verify GPG signature in installation script

---

src/cli/index.js

Fixes #1927. 
**Summary**
Original implementation #1190 used `commander.noProgress` but as per the documentation of commanderjs the flag `--no-progress` sets the value of `commander.progress`, not of `commander.noProgress`. This caused `undefined` to be passed around which would always bypass the check to see if noProgress was set.

Fix --no-progress flag.

---

src/cli/commands/licenses.js

**Summary**
There is code currently that explicitly adds a `--production` flag option to the `licenses` command. This is unneeded and results in duplicate output of the flag when running `yarn help licenses`
**Test plan**
Running `bin\yarn.cmd licenses ls` and `bin\yarn.cmd licenses ls --production` result in the same results using the latest yarn. There currently are no tests around `licenses.js` and removing code seems like the wrong time to add them.

Remove duplicate --production flag from licenses

---

appveyor.yml
resources/winsetup/YarnSetup.wixproj

**Summary**
This automates signing the Windows installer and attaching it to the releases. Windows installers built via AppVeyor will now have an `-unsigned` suffix in their filenames, and the code that signs the installer will remove the suffix after signing it. This signing code is running on the same server that's handling hosting the nightly builds.
This might need a bit of hand-holding / monitoring for the very next release we do, to ensure that everything works as expected. cc @bestander 
Once we ensure this is working, we can automate bumping the `latest_release` config field on the website, and the release process will be fully automated! 🎉 
**Test plan**
Played around with it in my fork, manually called the webhook with a valid AppVeyor payload and ensured it worked …

Automate release of Windows installer.

---

src/reporters/lang/en.js
src/resolvers/registries/npm-resolver.js

**Summary**
When an object downloaded from the registry doesn't have a "dist-tags" property, an error is displayed. However, it doesn't include the name of the object that caused the error, which makes it difficult to debug.
**Test plan**
No additional tests; just a text change.

Log the artifact that caused the error when a malformed request is found

---

src/cli/index.js

This reduces some CLI noise when using the `--json` flag.

Don't output header and footer when json flag is passed

---

scripts/install-latest.sh

**Summary**
Fixes two issues with the install script:
- Old versions of Mac OS (10.10 and below) require the `-t` option for `mktemp`
- The check for GPG wasn't returning correctly, and tried to run GPG even when not available
**Test plan**
`mv /usr/bin/gpg /usr/bin/gpg-old` and run install script. Ensure output looks like:
```
> WARNING: GPG is not installed, integrity can not be verified!
> Extracting to ~/.yarn...
> Adding to $PATH...
```
Move `/usr/bin/gpg-old` back to `/usr/bin/gpg`, ensure GPG is ran:
```
> Verifying integrity...
gpg: Signature made Mon 21 Nov 2016 10:18:40 PM STD using RSA key ID FD2497F5
gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature …
```

Fix mktemp usage on Mac OS, and handling of environments where GPG is not available

---

__tests__/commands/run.js
src/cli/commands/run.js

**Summary**
This PR solves https://github.com/yarnpkg/yarn/issues/1991.
**Test plan**
I've modified `__tests__/commands/run.js` to reflect the fixed behavior.
Also, I ran all test suites:
```
Test Suites: 1 skipped, 36 passed, 36 of 37 total
Tests:       18 skipped, 279 passed, 297 total
Snapshots:   50 passed, 50 total
Time:        28.826s
Ran all test suites.
```

Fix duplication of available bin commands (#1991)

---

scripts/build-chocolatey.ps1

**Summary**
Updates the `build-chocolatey.ps1` package so that it can be run from any directory and not only from the root directory.
**Test plan**
Ran `build-chocolatey.ps1` from root and scripts directory

Update build script so that it can be run from any directory

---

.github/ISSUE_TEMPLATE.md

Instead of copying snippets and creating files locally, I want to only clone a provided repository when looking into an issue.
This advice will hopefully be followed by some people and thus simplify reproducing issues.
@torifat: Can we work on a small base repository with a `Dockerfile` and a `package.json` so that people could simply fork it? I saw your comment in https://github.com/yarnpkg/yarn/issues/1903 Maybe we can chat on Discord?

Add public repository hint for issue creators

---

__tests__/commands/pack.js
__tests__/fixtures/pack/files-exclude-dotdir/.dotdir/a.js
__tests__/fixtures/pack/files-exclude-dotdir/index.js
__tests__/fixtures/pack/files-exclude-dotdir/package.json
__tests__/fixtures/pack/files-exclude-dotfile/a.js
__tests__/fixtures/pack/files-exclude-dotfile/b.js
__tests__/fixtures/pack/files-exclude-dotfile/c.js
__tests__/fixtures/pack/files-exclude-dotfile/index.js
__tests__/fixtures/pack/files-exclude-dotfile/package.json
__tests__/fixtures/pack/files-exclude/a.js
__tests__/fixtures/pack/files-exclude/b.js
__tests__/fixtures/pack/files-exclude/c.js
__tests__/fixtures/pack/files-exclude/index.js
__tests__/fixtures/pack/files-exclude/package.json
__tests__/fixtures/pack/files-include-mandatory/index.js
__tests__/fixtures/pack/files-include-mandatory/package.json
__tests__/fixtures/pack/files-include/a.js
__tests__/fixtures/pack/files-include/b.js
__tests__/fixtures/pack/files-include/c.js
__tests__/fixtures/pack/files-include/index.js
__tests__/fixtures/pack/files-include/package.json
__tests__/fixtures/pack/minimal/index.js
__tests__/fixtures/pack/minimal/package.json
src/cli/commands/pack.js

**Summary**
Contains two fixes for yarn pack if "files" is used in package.json:
- some files (package.json, readme, license, changelog) should always be included, even if not listed in the files field. This was not the case, fixed by 13e7b420
- all other files should be excluded, but the exclude filter did not match files starting with a dot (this is the default behaviour of minimatch it seems). fixed by 8851acba
Please note that this only partly fixes #755 .
As far as I can see what happens in #755 is the following:
- some files which should be included we not included, in my example it was package.json
- some files which should be excluded were included, in my example .gitignore and others.
While working on this I was wondering why a missing file would create a corrupt archive, but it …

Bugfixes to yarn pack, partly fixes #755

---

gulpfile.js
package.json
yarn.lock

**Summary**
running gulp --sourcemaps generates sourcemaps in ./lib
can also run gulp watch --sourcemaps, etc.
motivation: sourcemaps enable interactive debugging of original source
**Test plan**
delete ./lib
run gulp --sourcemaps
*.map files generated in ./lib
gen'd *.js files in ./lib have trailing //# sourceMappingURL
delete ./lib
run gulp
no *.map files
no //# sourceMappingURL in gen'd *.js

add build option to generate sourcemaps

---

resources/win-chocolatey/yarn.nuspec

**Summary**
Update the `PackageSource` for the Chocolatey package to link directly to the Chocolatey Package inside the repository. Since `ProjectSource` already links to the Repo direct linking to the nuspec is more helpful for users on Chocolatey.
**Test plan**
Run `build-chocolatey.ps1` and tested on local Chocolatey feed.

Update package sourc to link to Chocolatey package

---

__tests__/commands/pack.js
__tests__/fixtures/pack/files-exclude-dotdir/.dotdir/a.js
__tests__/fixtures/pack/files-exclude-dotdir/index.js
__tests__/fixtures/pack/files-exclude-dotdir/package.json
__tests__/fixtures/pack/files-exclude-dotfile/a.js
__tests__/fixtures/pack/files-exclude-dotfile/b.js
__tests__/fixtures/pack/files-exclude-dotfile/c.js
__tests__/fixtures/pack/files-exclude-dotfile/index.js
__tests__/fixtures/pack/files-exclude-dotfile/package.json
__tests__/fixtures/pack/files-exclude/a.js
__tests__/fixtures/pack/files-exclude/b.js
__tests__/fixtures/pack/files-exclude/c.js
__tests__/fixtures/pack/files-exclude/index.js
__tests__/fixtures/pack/files-exclude/package.json
__tests__/fixtures/pack/files-include-mandatory/index.js
__tests__/fixtures/pack/files-include-mandatory/package.json
__tests__/fixtures/pack/files-include/a.js
__tests__/fixtures/pack/files-include/b.js
__tests__/fixtures/pack/files-include/c.js
__tests__/fixtures/pack/files-include/index.js
__tests__/fixtures/pack/files-include/package.json
__tests__/fixtures/pack/minimal/index.js
__tests__/fixtures/pack/minimal/package.json
src/cli/commands/pack.js

This is an updated version of #1464 which had to be reverted because of ci errors.
The errors were caused by changes in the yarn code after the PR was created (util/fs.copy() has an additional parameter).
This is fixed in this PR.
@bestander you asked me to ping you when this is done.
below is the original message of #1464:
**Summary**
Contains two fixes for yarn pack if "files" is used in package.json:
- some files (package.json, readme, license, changelog) should always be included, even if not listed in the files field. This was not the case, fixed by 13e7b420
- all other files should be excluded, but the exclude filter did not match files starting with a dot (this is the default behaviour of minimatch it seems). fixed by 8851acba
Please note that this only partly fixes #755 .
As far …

bugfixes to yarn pack, retry of #1464

---

__tests__/commands/install.js
src/cli/commands/check.js

**Summary**
There's a mismatch between what `yarn install` does for integrity checking and what `yarn check` does. `yarn check` [flattens the patterns](https://github.com/yarnpkg/yarn/blob/099e76dc075763427605a6a63906127402370bb2/src/cli/commands/install.js#L342), while `yarn check` doesn't, as it just uses Install.hydrate (which doesn't return the patterns flattened)
We ran into some issues where `yarn install` would say everything was file while `yarn check --integrity` would say there's a mismatch. This patch fixes it

Fix yarn check --integrity behavior not aligning with yarn install's integrity checking

---

scripts/install-latest.sh

**Summary**
This PR fixes #2061. Since the `if` construct by design [tests the exit value of commands](http://mywiki.wooledge.org/BashPitfalls?highlight=%28is+a+command%29#if_.5Bgrep_foo_myfile.5D), it’s better to test the `which yarn` command directly.
**Test plan**
```
rm -rf ~/.yarn
mkdir ~/.yarn
./scripts/install-latest.sh
```

Fix `which` check during yarn install (#2061)

---

src/cli/index.js

**Summary**
Fixes a race condition we observed in production, to easily reproduce it, I changed the code in `onServerEnd` to wait any amount of time before resolving:
```js
const onServerEnd = (): Promise<void> => {
clients.forEach((client) => {
client.write('closing. kthanx, bye.');
});
return new Promise(ok => {
setTimeout( () => {
server.close();
ok();
}, 20);
}
};
```
This change makes it easier to spot the issue
**Test plan**
run:
```
./bin/yarn install --mutex network& ./bin/yarn install --mutex network&./bin/yarn install --mutex network&
```
IIRC The original code was written like that because I observed some issue in relying on the `close` event on my original implementation that was using a unix socket.
Since then I changed the strategy and we use the network.
I cannot recreate …

Fixes race condition on yarn install mutex network

---

resources/win-chocolatey/tools/chocolateyinstall.ps1.in

**Summary**
Updates the build script of the Chocolatey package to just use a regular expression to update the installation method in `package.json`, rather than using `ConvertFrom-Json`. We were encountering odd issues with the JSON parsing, and it's not available in older PowerShell versions.
**Test plan**
Pushed an updated Yarn package, it passed verification: https://chocolatey.org/packages/yarn
Closes #2065

Use regex rather than Convert[To|From]-Json to update installation method

---

appveyor.yml

**Summary**
Fixes the AppVeyor deployment webhook. AppVeyor wasn't actually building the tags, it was just building the stable branch. This meant that the deployment script wasn't actually running, as `appveyor_repo_tag` was never `true`.
We don't want to deploy **every** individual commit to the stable branch, we only want to deploy tags. I've switched the branch list to only build master and tags (instead of master and stable branches), and updated the deployment webhook to be called for tags.
**Test plan**
Tested something similar on my fork: https://ci.appveyor.com/project/Daniel15/yarn/build/job/dpyvcc0p88ss9se6

Fix AppVeyor deployment webhook

---

README.md

**Summary**
Makes the badge for CircleCI in the readme look more like the other badges next to it.
This improves the consistency and polish of Yarn's developer-facing documentation.
**Test plan**
No functional changes, only aesthetics.
Before: 
After:

Match CircleCI badge visually to the other badges

---

src/cli/commands/upgrade.js

**Summary**
Remove engine option from upgrade help as it's supported globally.
Fixes #2139

Duplicate upgrade-engines fix. Fixes #2139

---

__tests__/commands/cache.js

**Summary**
The tests from #2046 modify the config in ~/.yarnrc which results in cache folders being created in weird places after having run the tests.
**Test plan**

Fix an issue with cache config tests modifying actual config

---

src/cli/commands/upgrade-interactive.js

**Summary**
The way `upgrade-interactive` works, it already support both `--exact` & `--tilde`. So, I have just enabled them.
**Test Plan**
```
$ cat package.json
{
"react": "15.3.0"
}
}
$ yarn upgrade-interactive --exact
```
**After**
```
$ cat package.json
{
"react": "15.3.2"
}
}
```
---

Add support for --exact & --tilde in upgrade-interactive

---

src/cli/index.js
src/config.js
src/util/request-manager.js

**Summary**
In my organization we are consuming many private dependencies as GitHub private repositories through ssh (i.e. `git+ssh://git@github.com/org/name.git`), which results that when the number of these dependencies exceeds some limit (around 10), the number of concurrent requests to GitHub from the same IP will result in a `Connection reset by peer error` which is a DoS protection from GitHub. 
Fixes https://github.com/yarnpkg/yarn/issues/1307
Since yarn will cache all successful fetches, it really does not matter that the first fetch of dependencies is a bit slow.
Let me know if `concurrency` is also the proper name, I'm thinking if I should use `network-concurrency` instead?
**Test plan**
Running `yarn install --concurrency 1` on https://github.com/albertfdp/yarn-github-repos …

Add support to max network concurrent requests

---

__tests__/commands/_helpers.js

This is a hot fix for #2144 which fully resolved the issue of cache folder been created in current directory every time running tests.
It's related to #2046 and #2140 as well.
@mvestergaard , @bestander

make sure the cache folder would been created in temp 'cwd ' folder during the tests

---

__tests__/commands/install/integration.js
__tests__/fixtures/install/install-from-authed-private-registry-no-slash/.npmrc
__tests__/fixtures/install/install-from-authed-private-registry-no-slash/package.json
src/registries/npm-registry.js

This PR was triggered by new discussion on #1666.
I'm not 100% sold on this yet, I'll try to read through the `npm` source code to see what they do.
Which one of these cases are valid (cause this PR would break some of these):
```sh
@scoped:registry=https://foo.com/
//foo.com/:_authToken=xyz
@scoped:registry=https://foo.com
//foo.com/:_authToken=xyz
@scoped:registry=https://foo.com
//foo.com:_authToken=xyz
@scoped:registry=https://foo.com/custom/path
//foo.com/custom/path:_authToken=xyz
@scoped:registry=https://foo.com/custom/path/
//foo.com/custom/path/:_authToken=xyz
@scoped:registry=https://foo.com/custom/path
//foo.com/custom/path/:_authToken=xyz
```

Fix authentication when @scope:registry does not specify trailing slash

---

src/constants.js

**Summary**
Use the function `isRootUser` to set the `userHome` variable if root is the effective user in Linux platform. The $USER environment variable doesn't match the effective user of the process in some cases.
Related to #2123 
**Test plan**
As root, run yarn as an unpriviledged user using sudo command:
```
[root@fedora nodejs-project]# sudo -u vagrant yarn install
yarn install v0.18.0-20161202.0739
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 7.77s.
```
* Use isRootUser function instead USER environment variable
* Fix #2123

Use effective uid to set the userHome variable

---

src/cli/commands/cache.js
src/cli/commands/config.js
src/cli/commands/global.js

`yarn cache dir` command should not output header and footer, but only the cache directory path.
Resolves issue #2158.
<code>$ yarn cache dir</code>
Expected output should look like:
<code>/root/.cache/yarn</code>

Do not output wrapper for cache dir command (#2158)

---

src/cli/index.js
src/config.js
src/package-fetcher.js

**Summary**
This is a follow-up from https://github.com/yarnpkg/yarn/pull/2129 where the network concurrency was not being passed down to the package fetcher, so the problem was not fixed in that scenario.
**Test plan**
Running `yarn install --concurrency 1` on https://github.com/albertfdp/yarn-github-repos should not raise a Connection reset by peer error.

Apply the network-concurrency option to the package fetchers

---

__tests__/commands/install/integration.js
__tests__/fixtures/install/install-should-respect-npm_config_production/package.json
src/config.js

This fixes #1975.
The motivation is to fix the compatibility issue so that Yarn can be used in place of npm on Heroku ([related buildpack issue](https://github.com/heroku/heroku-buildpack-nodejs/issues/337)). In this case, when you need to install devDependencies, [as documented here](https://devcenter.heroku.com/articles/nodejs-support#devdependencies).
**Test plan**
A test is included.
(I also tested locally on my setup and observed that the devDependencies were indeed installed to `node_modules` when both `NODE_ENV=production` and `NPM_CONFIG_PRODUCTION=false` were set.)

Allow 'production' ENV to take precedence over NODE_ENV

---

__tests__/commands/outdated.js
src/cli/commands/outdated.js
src/cli/commands/upgrade-interactive.js
src/package-request.js
src/registries/base-registry.js
src/registries/npm-registry.js
src/types.js

**Summary**
When viewing outdated dependencies via `yarn outdated` or `yarn upgrade-interactive`, it is often desirable to look at what has changed in the dependent package.  While we don’t have easy access to each dependency’s CHANGELOG, we do have access to its homepage or repository URL.
This PR adds a new column to the output of `yarn outdated` and `yarn upgrade-interactive` to show a URL for each dependency.  Some terminal programs, such as iTerm, allow clicking on URLs to open them in a browser, making this very convenient.  Other terminals only allow copy and paste, but that’s still more convenient than manually attempting to find the package’s homepage.
This feature was inspired by a similar feature of [npm-check](https://github.com/dylang/npm-check).
**Test plan**
Run `yarn …

Show homepage of outdated dependencies

---

__tests__/commands/run.js
src/cli/commands/run.js
src/reporters/base-reporter.js
src/reporters/console/console-reporter.js
src/reporters/json-reporter.js

**Summary**
Closes #2194.
This pull request improves `yarn run` by adding the project commands that would be run when used by `yarn run`.
Essentially, this makes `yarn run` with no arguments show the same thing as `npm run` with no arguments.
**Test plan**
Here's what I have now: http://i.imgur.com/6MKIPya.png
(Ignore the `vundefined` version—I fixed that after the screenshot).
**WIP**
I am vastly unfamiliar with Flow and types in general so this PR is far from finished. Here are things I could use help with:
* The linting error about `pkg.scripts` being undefined
* `run` uses `log` from `ConsoleReporter`, which takes an `Array<string>`. The new scripts array is an array of objects of `{script: command}`[1] structure. I'm not sure how to get both working at the same time without breaking …

Add project commands `yarn run` could run

---

bin/yarn

**Summary**
I would like to be able to call a soft-linked version of the `yarn` shell script. Effectively, Yarn is installed in one location, and I would like to add a soft-link to a `bin` directory already in my `PATH`.
This is useful for manual installations (as outlined under Manual Installation via tarball on the [installation page](https://yarnpkg.com/en/docs/install#alternatives-tab)) or when Yarn is being installed by other package managers (such as Macports, [where we are currently patching this change](https://github.com/macports/macports-ports/pull/48)). 
The use of `readlink` without flags should work on both Linux and BSD variants. Introducing flags like `-f` and `-e` will limit the functionality to GNU's `readlink` (not default on BSDs or macOS), which is why the code forgoes …

Fix #1941 - Allow yarn script to be linked

---

bin/yarn

The problem is caused by mintty, and it manifests weirdly because in most circumstances you can get interactive node programs to work because of a hack introduced via aliasing/wrapping commands in the bash profile:
```
bkc@DESKTOP-NNSLT74 ~/workspace/yarn-test $ type node
node is aliased to `winpty node.exe'
```
After a bit of digging I found the culprit in `/etc/profile.d/aliases.sh`
```bash
case "$TERM" in
xterm*)
for name in node ipython php php5 psql python2.7
do
case "$(type -p "$name".exe 2>/dev/null)" in
''|/usr/bin/*) continue;;
esac
alias $name="winpty $name.exe"
done
;;
esac
```
Git bash wraps `node`, `ipython`, `php`, `php5`, `psql`, `python2.7` in a program called `winpty`
which means when yarn invokes node, this hack is not invoked as well.
Related to issue #743 
**Test …

Make yarn interactive commands run in Git Bash/MSYS environment

---

__tests__/commands/info.js
src/cli/commands/info.js

I'm working on some code, and rather than including all my commits in one PR, I'd like to separate a few of the smaller, non-related fixes into their own PR's (for easier review).
**Summary**
This is a very small change to get the code coverage of the `info` command up to 100%.  The currently included versions of `jest` and `babel-jest` still have slightly incorrect coverage reports, but updating them gives `100%` on this file.  I would like to upgrade all the modules in this repo, but it might make more sense for that to be in a different PR? (I didn't include `package.json` or `yarn.lock` updates in this PR)
**Test plan**
1. Run `yarn test`
2. Confirm `__tests__/commands/info.js` has no errors
3. `open ./coverage/lcov-report/index.html`
3. Confirm that the coverage for …

Add "Too many arguments" message to `info` and improve code coverage

---

src/cli/aliases.js

I'm working on some code, and rather than including all my commits in one PR, I'd like to separate a few of the smaller, non-related fixes into their own PR's (for easier review).
**Summary**
Locally, I've upgraded my eslint versions, and the current `aliases` file throws lint errors due to the `sort-keys` rule.  This commit fixes the errors by sorting all our keys.  I kept the `shorthands` vs `affordances` separation by using 2 variables and the object spread syntax in the exported value.
**Test plan**
1. I made my changes then ran `yarn build`
2. I ran `./bin/yarn ls` and a few other of the alias commands.
3. Confirmed that the behavior is the same before and after my changes.
4. Run `yarn test`
5. Confirm `__tests__/cli/aliases.js` has no errors
6. open …

Small aliases refactor.

---

__tests__/normalize-manifest.js
src/cli/commands/init.js
src/util/normalize-manifest/util.js

**Summary**
Fix for #2179, and a similar issue. The interactive prompt of `yarn init` can't display the nested sub-question for the questions when there are no default values of the repository and the fields have Object values in `package.json`. This error also happens for the author field as well since the field is allowed to be used Object in package.json.
See also
+ [author in package.json](https://docs.npmjs.com/files/package.json#people-fields-author-contributors)
+ [repository in package.json](https://docs.npmjs.com/files/package.json#repository)
**Test plan**
I've added a test into `__test__`.

Normalize the author and the repository fields

---

bin/yarn.js
src/constants.js

**Summary**
The GLOBAL_INSTALL_DIRECTORY (`~/.yarn`) is created by Yarn, but appears to have been replaced by `~/.config/yarn` in #1679, and is therefore unused. This PR removes the constant and the command that creates the directory.
For clarity: the `~/.config/yarn` consists of `CONFIG_DIRECTORY` and `GLOBAL_MODULE_DIRECTORY`, as built by the `getDirectory()` function in `src/constants.js`.
You may find #2177 helpful.
**Test plan**
I have run both the linter and the test suite. Note that I had to run the test suite manually and that there was a single error due to permissions on my system.
```shell
$ yarn run lint
yarn run v0.18.0
$ eslint . && flow check 
Found 0 errors
✨  Done in 14.54s.
```
```shell
$ yarn run test
yarn run v0.18.0
npm run lint && npm run test-only 
sh: npm: command …
```

Fix #2177 - Remove GLOBAL_INSTALL_DIRECTORY const

---

src/package-linker.js
src/reporters/lang/en.js

fixes #1556
before:
`warning Unmet peer dependency "somedep@0.x.x".`
after:
`warning "somepackage@0.2.4" has unmet peer dependency "somedep@0.x.x".`

fix #1556: add package name to unmet/incorrect peer dependency warning

---

__tests__/commands/version.js
__tests__/fixtures/version/no-args/package.json
__tests__/fixtures/version/pre-post/package.json
src/cli/commands/version.js

**Summary**
Like npm having the option to perform commands during version publishing is important.
This new lifecycle step `version` should add npm compatibility to the version cli command.
**Test plan**
I cannot find any tests to the version command. Is this a pr that should be tested? Can you give me some guidance on how to do some testing here?
Related to #2105

Add version lifecycle step to the version cli command

---

__tests__/util/fix-cmd-win-slashes.js
src/cli/commands/run.js
src/util/fix-cmd-win-slashes.js

**Summary**
This address the issue https://github.com/yarnpkg/yarn/issues/1729 which as about that on windows yarn fails to execute scripts that contain commands with unix-style slashes, for example this will fail on windows:
```json
"scripts": {
"compile": "../node_modules/.bin/tsc"
}
```
So to run such script on windows machine successfully we need to replace slashes from `/` to `\`, 
```json
"compile": "..\\node_modules\\.bin\\tsc"
```
For we need to find all the executable commands in the script line, so we assume that exec commands that need to be fixed:
- Are located in the beginning of the line
- Or located after symbols: `&&` or `&` or `||` or `|`
- `&&` or `&` or `||` or `|` symbols after which command go may not be inside the quotes. In opposite case this will mean that it is …

Fix scripts cmd slashes for windows

---

bin/yarn

**Summary**
Test for both `MSYS*` and `MINGW*` when determine to wrap
the node process in winpty.
I made this previous pull request #2230 for supporting interactive commands in
Git bash for windows.
It turns out that I only made it work for some really old git bash.
Along the way Git bash has changed its default terminal emulator, which means it
went from using a terminal that, resolved to `MSYS*` when invoking the `uname` command,
to a newer one that resolves `MINGW*`
This fix make it work with newer configurations and keeping support to the old version.
Github: #743
**Test plan**
Before this change
```bash
bkc@DESKTOP-NNSLT74 ~/workspace/yarn-test (master) $ uname
MSYS_NT-10.0
bkc@DESKTOP-NNSLT74 ~/workspace/yarn-test (master) $ ./bin/yarn init
yarn init v0.19.0-0
question name (yarn): …
```

Support interactive commands in standard MINGW as well

---

__tests__/commands/_helpers.js
__tests__/commands/run.js
src/cli/commands/run.js

**Summary**
Extended regex to match only Windows. Previous regex was matching Darwin in addition to Windows.
yarn run test > all tests pass.
#2261

Increased specificity of Windows platform check

---

__tests__/commands/install/integration.js
__tests__/fixtures/install/install-without-dependencies/package.json
src/cli/commands/install.js

**Summary**
No lockfile is written with empty dependencies, which causes check to fail. Act the same with manifest & lockfile, so write an empty file as-well when no dependencies are going to be installed `dependencies: {}`. 
This will solve: https://github.com/yarnpkg/yarn/issues/679
**Test plan**
```
$ yarn init
$ yarn install
$ yarn check
$ yarn check --integrity
$ npm run test
```

fix-679: empty lockfiles with no dependencies

---

__tests__/commands/install/integration.js
__tests__/fixtures/install/install-should-respect-production_flag_over_node-env/package.json
src/cli/index.js
src/config.js

**Summary**
Add ability to pass `production=false` when running `yarn install`, which will take precedence over the environment variable `NODE_ENV=production`.
This will allow you to have your NODE_ENV set as production while still installing dev dependencies, e.g. when running a script such `yarn install && yarn run build` to build your code in production mode while installing dev dependencies required for the build.
Closes #2167 
**Test plan**
A passing test is included.
I've also tested locally.
Currently it will accept `production=false`, `production=0`, `prod=false`, `prod=0`. Any other value will be considered true, including empty.

Allow production=false flag to override production ENV

---

__tests__/commands/install/integration.js
__tests__/fixtures/install/should-install-failing-optional-deps/optional-failing/install.js
__tests__/fixtures/install/should-install-failing-optional-deps/optional-failing/package.json
__tests__/fixtures/install/should-install-failing-optional-deps/package.json
__tests__/fixtures/install/should-install-failing-optional-sub-deps/optional-failing/install.js
__tests__/fixtures/install/should-install-failing-optional-sub-deps/optional-failing/package.json
__tests__/fixtures/install/should-install-failing-optional-sub-deps/package.json
__tests__/fixtures/install/should-install-failing-optional-sub-deps/sub-dep/install.js
__tests__/fixtures/install/should-install-failing-optional-sub-deps/sub-dep/package.json
__tests__/package-hoister.js
src/package-hoister.js

**Summary**
Fixes #2142, transitive dependencies now inherit "ignored" state from parent dynamically 
**Test plan**
Test has been added before and now is enabled

Fixed #1242 - missing transitive dependencies

---

__tests__/fixtures/index/run-add-lockfile/package.json
__tests__/fixtures/index/run-add-option-in-front/package.json
__tests__/fixtures/index/run-add-option/package.json
__tests__/fixtures/index/run-add-progress-globally/package.json
__tests__/fixtures/index/run-add/package.json
__tests__/fixtures/index/run-custom-script/package.json
__tests__/index.js
src/cli/index.js

Fixes issue when yarn cannot add/remove package which name is equal to one of the CLI options (e.g. **lockfile**, **progress**).
Fixes issue #2112.
The source of the error is this bug from commander.js: https://github.com/tj/commander.js/issues/346
when the first argument after the first two **process.agrv**s (i.e. **node yarn**) cannot have the same name as options defined with commander.
The solution is to parse args along with the command name and the remove command name from the args.
`$ yarn add lockfile`
should work correctly
I added basic integration tests, but IMO would probably be nicer to extract the whole arguments parsing to a separate module and unit test it more intensively, but I found it pretty hard with the current implementation. This might be done later on a separate …

Fix adding package with name like one of the options

---

resources/win-chocolatey/yarn.nuspec

**Summary**
Added releaseNotes to base nuspec file.
**Test plan**
I had to modify the chocolatley build script locally to get around a machine issue, but verified that the nuspec file was properly transformed by the build process.
**Nuspec input:**
**Embedded nuspec inside chocolately build output:**

(2301) Release notes in Chocolatey package

---

__tests__/commands/_helpers.js
__tests__/commands/run.js

**Summary**
This test is too complicated and does not thoroughly test the run command's handling of win32 vs. posix script command mangling.
It is not possible to test win32 and posix from one platform because the path module employed in the test alters its export based on process.platform in Node bootstrap, well before one can mock it. i.e. the test assertion will always be looking for the local platform's path delimiters etc.
One could hardcode path information, but it still feels risky to be changing the process.platform from within one test, for one test.
**Test plan**
The original test asserted that window cmd line formatting is properly applied or not applied, for only the target platform the tests are executed on - that will have to be good enough.
Tests pass.

Reverted test due to inability to mock process.platform (#2262)

---

__tests__/commands/_helpers.js
__tests__/commands/cache.js
__tests__/commands/global.js
__tests__/commands/install/integration.js
src/cli/commands/remove.js
src/util/fs.js

**Summary**
I am working on Ubuntu on Windows and had to fix a few issues with tests that were broken.
- cache tests were slowed down because all of them were copying root folder to a temp location
- if node is installed globally with root then `global` tests were failing for non root users
- fixed a weird Ubuntu on Windows issue (going to report this over there)

Tests stability improvements

---

.gitignore

**Summary**
Vscode uses a .vscode folder to hold local configuration, such as launch.json for debugging.
Would prefer to exclude this folder.
**Test plan**
1. Modify launch.json file for vscode.
2. Git shows modified launch.json in working tree.
3. Add ".vscode" to .gitignore, save.
4. Git updates to not show launch.json in working tree.

add .vscode IDE config folder to gitignore

---

.travis.yml
__tests__/commands/add.js
__tests__/commands/install/integration-deduping.js
appveyor.yml

**Summary**
- Travis was not running tests in Node 4 (see `node --version` output in https://travis-ci.org/yarnpkg/yarn/jobs/188493526)
- Added `node --version` to appveyor builds logs
- Added OSX Node 6 builds to Travis builds
- increased timeouts for the longest running tests

[CI] enabled node 4 in Travis builds + more CI fixes

---

__tests__/resolvers/exotics/bitbucket-resolver.js
src/resolvers/exotics/git-resolver.js
src/resolvers/exotics/hosted-git-resolver.js
src/util/request-manager.js

**Summary**
Intended to solve #573 . This is a re-application of the changes in #1816 but with a fix for the tests in 3c55f6ba63aa87a87f7429f5e8e081004fc8664b. All work is credited to @f-sign . Only attempting to re-run tests and clean up the PR so it doesn't have duplicate commits from master.
**Test plan**
Tests pass. Left it up to author of #1816 .
**Background**
This originated from investigating https://github.com/yarnpkg/yarn/pull/1816#issuecomment-270288503 .

Reroll #1816 into a new PR + fix for test failures

---

src/package-install-scripts.js

**Summary**
The error output of failing optional dependencies can be very intimidating since most of the time yarn will display a huge stack trace (see below).
This PR changes the log level from `error` to `warn` to make the output less intimidating for users.
**Test plan**
Here is the output of a failed install of `canvas` as a optional dependency:
[1/1] ⢀ canvas: ERR! configure error
[-/1] ⢀ waiting...
[-/1] ⢀ waiting...
[-/1] ⢀ waiting...
warning Error running install script for optional dependency: "/Users/lukasgeiger/code/nteract/node_modules/canvas: Command failed.\nExit code: 1\nCommand: sh\nArguments: -c node-gyp rebuild\nDirectory: /Users/lukasgeiger/code/nteract/node_modules/canvas\nOutput:\ngyp info it worked …

Change log level of optional deps to warn

---

src/config.js

**Summary**
`this.rootModuleFolders` has duplicated entries since it is already initialized [here](https://github.com/yarnpkg/yarn/blob/master/src/config.js#L275).
Discovered this while working on #2375 
**Test plan**
It's very unlikely that this change introduces a regression that is not already covered by the test suite.

Don't push duplicated elements to config.rootModuleFolders

---

__tests__/util/git.js
src/cli/commands/check.js
src/cli/commands/global.js
src/package-fetcher.js
src/reporters/lang/en.js
src/util/git.js

**Summary**
Continuing with #1387 now most of the files are cover .. 
Some missing are:
https://github.com/yarnpkg/yarn/blob/master/src/lockfile/parse.js#L178 that dont have access to a reporter 
https://github.com/yarnpkg/yarn/blob/master/src/cli/index.js it would be nice to translate the commander options .. but the definition of the options needs to be moved to after the reporter creation 
And if there is any other translation missing let me know 
**Test plan**
Just ran `yarn run test`  and hope for the best

Add use of reporter lang method

---

.travis.yml

**Summary**
Now that [Travis officially supports yarn](https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn), we no longer need to install it via homebrew/apt-get.

[CI] travis: Use the built-in yarn support

---

circle.yml

**Summary**
yarn is [now cached in ~/.cache/yarn](https://github.com/yarnpkg/yarn/blob/a1192e596b85acb2f63daa1cbf30e662c2125310/src/constants.js#L41), not ~/.yarn-cache.

[CI] circle: Fix the yarn cache directory

---

src/cli/commands/pack.js

Similar to
https://github.com/npm/npm/blob/6f34aa2d366fc9f90ae0d500ef980dd6c4ce505c/lib/pack.js#L54-L55
Verified by creating `package.json` with name `@some/scope` and running `yarn pack`. This command didn't seem to have any tests yet :-"

Fix yarn pack command for scoped packages, fixes #1714

---

circle.yml

See https://github.com/yarnpkg/website/pull/338 for the improved workflow that allows people to get unstable releases.

[CI] supported non stable releases by default

---

__tests__/fixtures/lifecycle-scripts/dont-expose-internal-configs-to-env/log-configs.js
__tests__/fixtures/lifecycle-scripts/dont-expose-internal-configs-to-env/package.json
__tests__/lifecycle-scripts.js
src/util/execute-lifecycle-script.js

**Summary**
Ignore some configs when making env.
**Test plan**
Before change:
```
env['npm_config_lastUpdateCheck'] != undefined
env['npm_config_registry'] != undefined
```
After change:
```
env['npm_config_lastUpdateCheck'] == undefined
env['npm_config_registry'] != undefined
```

Treat some configs as internal to fix #2286.

---

__tests__/commands/config.js
src/cli/commands/config.js
src/registries/yarn-registry.js

* Fixes #2434
`yarn config set [option] [false|true]` 
should set the option value to false/true respectively. 
Currently it's set to string value "false"/"true".
*Test Plan*
* `yarn config set strict-ssl false`
* $HOME/.yarnrc should contain the line:
strict-ssl false

Set boolean config values correctly

---

__tests__/util/git.js
src/reporters/lang/en.js
src/util/git.js

(whoops branch should've been issue-2117-http-url-not-working...)
**Summary**
0. This PR will resolve issue #2117.
1. It will upgrade an HTTP URL to HTTPS and see if that works then fallback to using HTTP if it fails.
2. It will test an HTTPS URL too and verify that the git repos exists
3. Fix and rewrite the broken tests
**Test plan**
The cause of the bug was having a project dependency which itself depended on an HTTP repos.
```
{
"name": "yarn-test",
"pm2": "^1.1.3"
}
}
```
Running a yarn install on the above would trigger this error
```
error Refusing to download the git repo http://ikt.pm2.io/ikt.git over HTTP without a commit hash
```
HTTPS is not valid for that domain since they have an `Invalid certificate …

Fix bug for #2117 - http url not working

---

scripts/build-webpack.js

Bundled builds were not being built correctly..
Example: https://github.com/yarnpkg/yarn/releases/download/v0.19.0/yarn-0.19.0.js
Issue: https://github.com/yarnpkg/yarn/issues/2410
Just add `-loader` suffix to loaders in to scripts/build-webpack.js. ezpz
Previously, packages named with `-loader` suffix could be specified as loaders within Webpack without requiring the suffix to be named explicitly. Webpack 2.1.0-beta.26 no longer looks for `-loader` suffix automatically, and packages have to therefore be named explicitly or `-loader` can be added to `resolveLoader.moduleExtensions`.
See: https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.26
This PR explicitly adds `-loader` suffix, and now bundles are correctly built.
```sh
~/yarn-0.19.0  (yarn@0.19.0)
λ node …
```

Add `-loader` suffix in webpack, closes #2410

---

bin/yarn

**Summary**
https://github.com/yarnpkg/yarn/issues/1941 is great, but it doesn't support relative symlinks.
Given the following symlink `yarn -> ../share/yarn/bin/yarn` you get `Error: Cannot find module '/share/yarn/bin/yarn.js'`.
**Test plan**
Just link the `yarn` script with `ln -rs`. Then run it. With this patch it's going to work. I think this is 0.19 material. Basically a bugfix.

support relative symlinks in yarn script

---

__tests__/package-resolver.js
src/config.js

**Summary**
Currently, only packages resolved to NPM registry have their hash appended to cache directory name. Other packages, such as those with GitHub URL, get cached by their `name` + `version` rather than actual content. This leads to a bug where even if you update the GitHub url in `package.json` (e.g. different GitHub commit hash), it is never updated on `yarn install` unless you clean the cached folders for the package along with `node_modules`. This is a huge pain for teams that depend on GitHub urls in dependencies.
Should address #1171, #1893, #1087, #1280, #1278, #1017 #1573 #2280. I'm not sure it fully fixes all the mentioned issues, so it's a work in progress in need of a discussion and thorough testing, but it should be a step in the right direction.
**Test plan**
This is …

Add hash to cache path for non-NPM packages

---

__tests__/commands/install/integration-deduping.js

Out of 10 most recent CI fails on Travis this test was the reason.
Probably because it requires rather large number of modules to be downloaded and Travis OSX machines are underpowered.
This test still runs on Circle and Travis Linux

[CI] disabled 'install should dedupe dependencies avoiding conflicts 8' test in Travis OSX'

---

__tests__/commands/add.js
__tests__/fixtures/add/latest-version-in-package/package.json
src/cli/commands/add.js

**Summary**
Hi,
this should fix #1306 and I sincerely hope that in some way it resolves #2225.
Please let me know if you like it and I don't forget anything.
**Test plan**
I add a test case in `__tests__/commands/add.js`
cheers,
Simon

Install a package with latest tag, it looks for the latest dist-tag

---

src/util/fs.js

**Summary**
This makes `yarn link` work when `$HOME/.config/yarn/link/` is itself a symlink.
---
The following commit forces symlinks to be relative: https://github.com/yarnpkg/yarn/commit/36d73cc3bb0e3c4afcea4f25b06cc76b7b5531fa
This isn't ideal, although it enables some portability it breaks others. For example, it is not uncommon for `$HOME/.config` itself to be be a symlink: `$HOME/.config` -> `$HOME/src/stefanpenner/dotfiles`. 
Now when running `yarn link` inside `$HOME/src/ember-cli/ember-cli` we end up with:
```js
path.relative('/Users/spenner/.config/yarn/link/ember-cli', '/Users/spenner/src/ember-cli/ember-cli');
=> '../../../src/ember-cli/ember-cli'
```
Which results in the link located at: `/Users/spenner/.config/yarn/link/ember-cli` pointing to …

[FIXES #2096] fix relative symlinks of symlinks

---

__tests__/package-resolver.js
src/resolvers/registries/npm-resolver.js

**Summary**
Addresses #2453. Scoped packages are located in `CACHEFOLDER/REGISTRY-@SCOPE/NAME` opposite to 'regular ones' stored in `CACHEFOLDER/REGISTRY-NAME`. 
**Test plan**
Added unit test that covers offline resolution of scoped package

Handling scoped packages offline

---

__tests__/commands/install/integration.js
__tests__/package-hoister.js
src/package-hoister.js

**Summary**
When installing only production packages using `yarn install --production`, the packagehoister sometimes ignores packages that are actually used. This can happen when an ignored package is deduped with another ignored package. If so, the isIgnored function won't pick up when the parent of the second package becomes non-ignored due to a dependency that is processed later. This is the cause of bug #2468 and bug #2263 (and probably #2421 too, though I haven't tested that one)
This happens with roughly this dependency tree:
dev A -> B (1)
dev A -> C -> B (2)
normal D -> E -> F -> C (3)
1. B is hoisted to the root, with isIgnored calling parent A.
2. B(2) is deduped to B(1). But, because C is also ignored at this point, the isIgnored function of B isn't changed.
3. A non-ignored …

Fix install --production not installing used packages, fixes #2468, #2263 

---

__tests__/commands/run.js
src/cli/commands/run.js

**Summary**
Consider the instance where you're using optional arguments with `yarn run`, and one of these arguments is a string that contains spaces. At the moment, using the raw `process.argv` to obtain these arguments strips the individual arguments of any string separators. Since these arguments are then used in another command, their original intent is lost.
Examples of this problem, as run on the yarn repo itself:
```
bin/yarn run build -- --module "run | init"
#=> gulp build --module run | init
#=> sh: init: command not found
```
In the above, the command defined in `build` interprets `| init` as a bash command. This is not the intent. `"run | init"` should be maintained as a single argument.
**Test plan**
To fix this, this PR sanitizes the optional arguments used in `execCommand` …

Retain string characters if add'l argument has spaces

---

__tests__/commands/add.js
src/package-constraint-resolver.js

**Summary**
The package constraint resolver had some issue with latest tag and if you try to specify --offline or --prefer-offline it throws exception because it does not retrieve the latest cached version :)
**Test plan**
I added two test cases and expanded the test for latest tag.
Let me know if it's ok!
cheers,
Simon

make add command working with latest tag if offline or preferOffline is setted

---

src/reporters/lang/en.js

**Summary**
Remove `$` to allow easier copy/paste
**Test plan**
- Run `yarn outdated` with an outdated lockfile.

Remove `lockfileOutdated` description `$` to allow easier copy/paste

---

package.json
yarn.lock

**Summary**
Removes `babel-preset-es2015` from `devDependencies`.  It looks like it stopped being used with https://github.com/yarnpkg/yarn/commit/862d20b9b3bdc87b7fb3fde22ccea8383bef4e06, which replaces it with `babel-preset-es2015-node4`, but was left as a devDependency.
**Test plan**

Remove `babel-preset-es2015`.

---

__tests__/registries/is-request-to-registry.js
src/registries/is-request-to-registry.js
src/registries/npm-registry.js

**Summary**
I use a private NPM registry hosted via Artifactory.  When using Yarn, I'm unable to install my modules when it gets to the "Fetching packages" phase, but it gets through the resolving packages phase using the private registry just fine.  I traced it back to the `npm-registry.js` doing a comparison to see if the request string `requestUrl.startsWith(registry)` this comparison fails on my server because the request url looks like 
`https://my.server:443/path/to/registry/-/something/somefile.tgz`
and the registry url looks like:
`https://my.server/path/to/registry/`
These are clearly requests to the same url repo, but a string.startsWith doesn't understand that.  As a result, the requests are made without auth info and fail with a Not authorized error.  Similar errors would …

Fix registry auth comparison for explicit port numbers

---

__tests__/commands/_helpers.js
__tests__/commands/info.js
__tests__/commands/install/unit.js
__tests__/commands/pack.js
__tests__/commands/why.js
__tests__/fetchers.js
__tests__/normalize-manifest.js
__tests__/package-resolver.js
__tests__/util/request-manager.js
src/config.js
src/reporters/index.js
src/reporters/noop-reporter.js

These are the first steps to achieve some better understading of yarn internalities :)
First of all, I created a named constructor of the Config because I noticed that every time there was this pattern
```
const config = new Config(reporter);
await config.init({...});
```
now we have something like this
```
const config = await Config.create({...}, reporter); // if reporter is not NoopReporter
const config = await Config.create({...}, reporter); // otherwise we can do this
```
Pros:
- Removes many useless imports
- Better encapsulation
- Hides the temporal coupling between config constructor and init
Cons:
- I do not touch the initialization part in src/config.js because it hides too much complexity, maybe before it is useful add some unit testing ;)
Secondly, I created a real noop …

add Named Constructor for Config and create a real NoopReporter

---

src/cli/index.js

There was a conflict when commander attempts to parse the incoming args between the command executed and the options since the name `version` was shared. In other words, executing the command `yarn version` would yield the same output as `yarn --version`. This fixes #2491. This also seems to relate to PR #2268.
Let me know what you think. And sorry for the issue reference spam! Thanks!

Fix `yarn version` which yields same output as `yarn --version` (#2491)

---

__tests__/resolvers/exotics/git-resolver.js
src/resolvers/exotics/git-resolver.js
src/util/normalize-manifest/fix.js

People were still experiencing issues with private urls using colons as separator even after the fix introduced in #2384.
This fix basically replace the initial pathname part of the parsed url in the git resolver, and reformat exploded parts onto the equivalent url, removing the colon culprit.
Unsure about why the require onto the `url` module is done the old way, I've decided to follow consistency, but can refactor if needed. Related issues referenced in commit.
:wave: @chrisirhc @lxe

Fix private urls using colon separator

---

package.json

**Summary**
add a description field to the package.json which is used on [npmjs.com](https://npmjs.com), [yarnpkg.com/search](https://yarnpkg.com/search) and more places, right now the description will be read out of the first part of the readme, which isn't that useful:
```
description: '<p align="center">   <a href="https://yarnpkg.com/">     <img alt="Yarn" src="https://github.com/yarnpkg/assets/blob/master/yarn-kitten-full.png?raw=true" width="546">   </a> </p>',
```
The npm site renders this as html, while yarnpkg.com/search renders it as escaped text, so plain text is the best choice for this case.
I picked the description from on github to replicate here.
**Test plan**
There's not really code change here

add a description field to the package.json

---

src/cli/index.js
src/reporters/console/console-reporter.js

**Summary**
When debugging issues with verbose logs it is quite useful to know the timings of all operations.
**Test plan**
```
verbose 0.242 current time: 2017-02-08T02:47:26.486Z
...
verbose 0.445 Creating directory "/Users/bestander/work/temp/chek/node_modules/abbrev".
verbose 0.445 Creating directory "/Users/bestander/work/temp/chek/node_modules/buffer-equal".
verbose 0.445 Creating directory "/Users/bestander/work/temp/chek/node_modules/bunker".
verbose 0.445 Creating directory "/Users/bestander/work/temp/chek/node_modules/burrito".
```
Where 0.445 is in seconds since Yarn process was created.
I found full date/time stamps make the logs harder to read and not very useful repeated thousands of times.

Added timestamps to verbose logs

---

package.json
src/constants.js
src/registries/npm-registry.js
src/registries/yarn-registry.js
src/util/user-home-dir.js
yarn.lock

**Summary**
Replaces `user-home` with `os.homedir`.  Proposed to close #2596.
**Test plan**
Refactors internals.  Nothing should change.

Replace `user-home` with `os.homedir`.

---

src/cli/commands/install.js

**Summary**
Fixes #2538.
If `--frozen-lockfile` is used while doing a `yarn install`, and it finds that the lockfile needs to be updated, it simply bails out with an error message. The return code is 0 in this case. We really should return a non-zero return code.
This switch was added for CI purposes. It's kind of silly it returns 0 on failure.
**Test plan**
Go to any directory with a `package.json` and `yarn.lock`, delete `yarn.lock`, and do:
```
$ yarn install --frozen-lockfile
yarn install v0.21.0-0
info No lockfile found.
warning browser-sync > localtunnel > request > node-uuid@1.4.7: use uuid module instead
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for …
```

Throw error on `--frozen-lockfile` failing check instead of simply bailing out

---

src/cli/commands/install.js
src/cli/index.js
src/constants.js

**Summary**
Generic URLs and Links like `https://yarnpkg.com/install.sh` where spread through-out different files, while other related constants like `https://registry.yarnpkg.com` were properly placed in `constants.js` and imported in relevant files.
**Solves**
This PR cleans up the code by centralizing all such links in the proper `constants.js` files as expected.

[Refactoring] [Cleanup] URLs and links now aggregated in constants file

---

.dockerignore
Dockerfile

**Summary**
Adds a Dockerfile for building Yarn. This is mainly for usage with CircleCI 2.0, however it could be used for development too. Inspired by @ryanwohara's version (https://github.com/yarnpkg/yarn/compare/master...ryanwohara:circleci-2.0), however I didn't use anything from his Dockerfile.
Closes #1903
**Test plan**
Ran `docker build -t yarn-dev .` to build an image, then `docker run -it -v c:\src\yarn:/yarn yarn-dev` to run it and mount `c:\src\yarn` to `/yarn`. Built Yarn and the build process mostly seemed to work. I still need to do a bit more testing though.

Add Dockerfile for building Yarn

---

src/cli/commands/run.js
src/util/execute-lifecycle-script.js

**Summary**
Enable the `fixCmdWinSlashes` class for the lifecycle scripts to clean up the
Windows run scripts starting with a relative path.
**Fixes**
- #1729
**Test plan**
Passes existing `fixCmdWinSlashes` class tests.

Windows: can not run scripts starting with relative path #1729

---

bin/yarn.js

**Summary**
Updates `bin/yarn.js` to remove the logic that looks for an updated version of Yarn in `updates/current`. This will stop Yarn from loading older versions that were installed using `self-update`.
**Test plan**
Tried both `.\bin\yarn --version` and `node .\bin\yarn.js --version`, both still work as expected

Remove logic for loading self-update versions

---

__tests__/index.js
__tests__/lifecycle-scripts.js

**Summary**
If the path location for Yarn contains spaces, the test suite would fail on a command. The corresponding upstream issue on Node is https://github.com/nodejs/node/issues/6803. This [specific comment](https://github.com/nodejs/node/issues/6803#issuecomment-219756302) noted that the path should be escaped with double quotes.
**Test plan**
1.  The path location to Yarn needs to contain spaces. 
2.  Run `yarn run test`.
3.  Observe a command fail with a corrupted path location.

Fix tests when path location of yarn contains spaces

---

src/cli/commands/global.js

**Summary**
Introduce `upgrade-interactive` as a subcommand of `global`.
This closes #2021.
**Test plan**
This PR mimics the way the other subcommands of `global` works: the `upgrade-interactive` command is added as a subcommand of `global`. So it is very similar to how `upgrade` is implemented, nothing fancy.
`upgrade-interactive` already has tests, this commit is only about wiring stuffs together within `global`, I didn't see the need to introduce extra tests.

Add global upgrade-interactive command (#2021)

---

scripts/build-chocolatey.ps1

Add `UseBasicParsing` to Invoke-WebRequest so it works in environments without the MSIE engine available. I'm trying to automate the build process for Chocolatey packages (currently I need to run this script manually after every release), and this change should make the script work in Windows Server 2012 R2 environments.
Previously, I was hitting this error on Server 2012 R2:
```
Invoke-WebRequest : The response content cannot be parsed because the Internet 
Explorer engine is not available, or Internet Explorer's first-launch 
configuration is not complete. Specify the UseBasicParsing parameter and try 
again. 
At C:\Jenkins\workspace\yarn-chocolatey\scripts\build-chocolatey.ps1:10 char:28
+ ...  = [String](Invoke-WebRequest -Uri https://yarnpkg.com/latest-version ...
+ …
```

Add `UseBasicParsing` to Invoke-WebRequest in build-chocolatey.ps1

---

__tests__/fixtures/import/missing-dev/package.json
__tests__/fixtures/import/missing-dev/yarn.lock.import
__tests__/fixtures/import/missing-opt/package.json
__tests__/fixtures/import/missing-opt/yarn.lock.import

Import tests would grab latest version from npm for the lockfile.
This change should make the test pass.

fixed import version for not installed dependencies

---

__tests__/fixtures/index/run-custom-script-with-arguments/package.json
__tests__/fixtures/index/run-version/package.json
__tests__/index.js
src/cli/commands/help.js
src/cli/commands/index.js
src/cli/index.js

I almost cover with tests every case in src/cli/index.js and after I extracted an help command.
This simplify the file and maybe it enables some other refactorings.
cheers :D 
voxsim
EDIT:
Test Plan, I think I covered almost every case in the cli, in detail:
1. run help/--help/-h command
2. run a command with --help/-h option
3. run help/--help/-h with a command name as argument
4. run version/--version command
5. Run install command with no args are provided
6. Run install command if first arg looks like a flag
7. Interpolate aliases properly
8. Yarn should use a flag if provided before --
9. The custom script should use a flag if provided after --

Refactoring cli index

---

__tests__/reporters/base-reporter.js
src/reporters/base-reporter.js

Ping @bestander 
**Summary**
This PR fixes #2439 by automatically unescaping the ESC character (`\u001b`) from the stringified version of the arguments passed to `reporter.lang`.
I'm a bit concerned about potential security breaks that could occur should a third-party-providen string contain a literal ESC (let's say a package named "\u001bhello"), which is why this regex [is a bit more complex](https://regex101.com/r/mSWp0d/1) than it could be: it checks that the `\u001b` character isn't escaped before unescaping it. So:
```
'\\u001bhello' => '\u001bhello'
'\\\\u001bhello' => '\\\u001bhello'
```
This way, even if a package name (or anything else) contains "\u001b" somewhere in the argument, it won't be interpreted provided that the string has been escaped beforehand (ideally before adding …

Unescapes ESC character, fixing #2439

---

__tests__/commands/outdated.js
src/package-request.js

**Summary**
When calling `yarn outdated` the packages are not ordered by name. `npm outdated` orders by name and so does `yarn` when merging this PR.
**Test plan**
See https://github.com/yarnpkg/yarn/issues/2513

Sort outdated packages by name, fixes #2513

---

bin/yarn.js
package.json
yarn.lock

**Summary**
This change makes it so that `yarn` can take advantage of V8's compile cache, and improve startup times. From https://raw.githubusercontent.com/zertosh/v8-compile-cache/v1.0.0/README.md:
> `v8-compile-cache` attaches a `require` hook to use [V8's code cache](https://v8project.blogspot.com/2015/07/code-caching.html) to speed up instantiation time. The "code cache" is the work of parsing and compiling done by V8.
> The ability to tap into V8 to produce/consume this cache was introduced in [Node v5.7.0](https://nodejs.org/en/blog/release/v5.7.0/).
`time`time ./bin/yarn.js config list` goes from 0.22s to 0.18s. config list` goes from 0.22s to 0.18s.
**Test plan**
`./bin/yarn.js`, `./bin/yarn.js add underscore` and `./bin/yarn.js config list`. All work.

Add v8-compile-cache

---

src/lockfile/parse.js
src/lockfile/wrapper.js
src/registries/yarn-registry.js

**Summary**
When running yarn with an invalid lockfile, the errors do not direct you to look at your lockfile. An example of one of these "vague" errors is `error An unexpected error occurred: "Invalid value type 2:0".`
In order to better point people towards the actual issue, this PR adds the filepath output after the error location so that people can find and fix the lockfile issue. After this PR, that same output would instead be `error An unexpected error occurred: "Invalid value type 2:0 in /Users/dawsonbotsford/.yarnrc".`
**Test plan**
This should only be a change in the error message. Are error messages included in the test coverage of yarn?

Add filename output to parse errors

---

bin/yarnpkg.cmd

References: #2534, facebookincubator/create-react-app#1555, facebookincubator/create-react-app#1365
**Summary**
Calling yarnpkg on Windows previously did not call Yarn
```
'yarnpkg' is not recognized as an internal or external command,
operable program or batch file.
```
`yarnpkg` command is used by create-react-app instead of `yarn` to prevent collision with other programs by that name in a user's PATH (See facebookincubator/create-react-app#1365). However on Windows, running `create-react-app` falls back to installation via npm because no `yarnpkg` command is found. This PR restores the expected functionality where Yarn is used to install packages for create-react-app if it is installed.
**Test plan**
Tested on Windows 10 x64. Words identically to existing `yarn.cmd`.

Added yarnpkg.cmd batch shim for backwards-compatibility on Windows (#2534)

---

src/cli/index.js
src/config.js
src/resolvers/registries/npm-resolver.js

**Summary**
If yarn is used within an automated process (in a CI system, for example), interactive prompts are not desirable.  This adds a commandline flag to remove them.
This resolves https://github.com/yarnpkg/yarn/issues/2625.
**Test plan**
I intentionally misconfigured a package.json with an invalid version of async:
"async": "^111.5.0",
1) Run 'yarn'.  Output is an interactive menu letting me select a valid version of async to install.
2) Run 'yarn --non-interactive'.  Output is:
yarn install v0.22.0-0
error Couldn't find any versions for "async" that matches "^111.5.0"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
**Pending Issues**
* I wasn't sure how to build an effective test for this option.  If you think …

Add —non-interactive flag for automated processes

---

package.json
src/registries/npm-registry.js
src/registries/yarn-registry.js
yarn.lock

**Summary**
Drops the `defaults` package and uses `Object.assign`.  While
```
this.config = Object.assign({}, DEFAULTS, this.config);
```
is a little less obvious than
```
defaults(this.config, DEFAULTS);
```
I thought it might be worth making a PR.
**Test plan**
Since it's an internal, no tests have been added that strictly test this.

Use `Object.assign` over `defaults`.

---

src/util/fs.js

**Summary**
#2454 introduced a regression as during install symlink sources wouldn't always exist at the time of symlink creation so as `fs.realpathSync` checks if the path actually exist the `ENOENT` error might be thrown here.
This PR makes sure we have more defensive approach by checking that symlink source exists before trying to derive absolute symlink path which might throw. So if source doesn't exist we would stick to more conservative relative symlinks otherwise where symlink source itself is not a requirement at least until the symlink is used.
Fixes https://github.com/yarnpkg/yarn/issues/2714

fix errors thrown if symlink source does not exist

---

__tests__/package-hoister.js
flow-typed/npm/jest_v14.0.x.js

**Summary**
Add a series of unit tests for `PackageHoister`.
Previously there was only 1 unit test (not including integration tests).
With this PR, there are now enough unit testa to bump coverage of the `package-hoister.js` file to ~93% (correction, after I rebased from current master it dropped to ~88%. I guess more code was added recently).  I really wanted to get as close to 100% coverage as possible, but I've been starting at this one file for a couple days and not sure what scenarios would hit some branches in the code.
The real motivation was to understand how PackageHoister works in hopes of trying to look more into issue #2673 and I figured, how better to figure out how it works than to write tests for it!
**Test plan**
```
$ npm run test-only __tests__/package-hoister.js …
```

added unit tests for package-hoister

---

src/package-linker.js
src/util/mutex.js

Fixes https://github.com/yarnpkg/yarn/issues/828 and https://github.com/yarnpkg/yarn/issues/2356
**Summary**
`cmd-shim` (used to generate executables on the `.bin` dir on Windows) is not an atomic operation. So, a race condition can happen where 2 packages that produce the same CLI executable will produce an unusable `cmd` file.
Additional context: https://github.com/yarnpkg/yarn/issues/828#issuecomment-270035847
Examples of packages which produce the same CLI:
* `karma` and `karma-cli` produce the shortcut `karma`.
* `gulp` and `gulp-cli` produce the shortcut `gulp`.
* `grunt` and `grunt-cli` produce the shortcut `grunt`.
To solve this, I've implemented a Mutex (loosely based on [await-mutex](https://github.com/mgtitimoli/await-mutex)) around the usage of `cmd-shim`. It's not the most …

Implemented mutex system to make bin links be generated consistently in Windows

---

__tests__/commands/add.js
src/package-linker.js

**Summary**
When installing multiple packages at the same time eg. `yarn add react react-dom`, `peerDependencies` were incorrectly resolved and triggered warnings.
Related: https://github.com/yarnpkg/yarn/issues/2132
**Test plan**
```
λ: yarn add request request-promise-native
yarn add v0.21.3
warning "request-promise-core@1.1.1" has unmet peer dependency "request@^2.34".
warning "request-promise-native@1.0.3" has unmet peer dependency "request@^2.34".
success Saved 2 new dependencies.
├─ request-promise-native@1.0.3
└─ request@2.79.0
✨  Done in 6.05s.
λ: yarn add react react-dom
yarn add v0.21.3 …
```

Correctly resolve peerDependencies for concurrent installs

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

**Summary**
Currently the rfcs repo is not easily discoverable, the only place it appears to be mentioned is in the new issue template. Linking to the repo in more places improves discoverability of yarnpkg/rfcs.

Improve discoverability of yarnpkg/rfcs

---

src/constants.js

**Summary**
Mitigation for https://github.com/yarnpkg/yarn/issues/2629.
With less tarballs being exploded concurrently we get less IO errors.
**Test plan**
I've tested React Native and there is not difference in fetching time between concurrency 4 and 15 (~21 seconds on MBPro 13").
Same results shown here https://github.com/yarnpkg/yarn/issues/2629#issuecomment-283691556.

set default network concurrency to 8

---

.flowconfig
package.json
src/cli/commands/cache.js
src/package-install-scripts.js
src/reporters/console/progress-bar.js
src/util/normalize-manifest/fix.js
yarn.lock

**Summary**
There were several packages reported as outdated by `yarn outdated`. I upgraded `camelcase` to `4.0.0` which [dropped support for Node 4](https://github.com/sindresorhus/camelcase/commit/2296030d560d4620eb1773219686822eb9c322e3). I also upgraded `flow-bin` to `0.40.0` which brought some stricter type checking. Most notably the [tuple changes introduced in 0.38.0](https://github.com/facebook/flow/releases/tag/v0.38.0) required some changes.
Also I saw that the `package.json` did not specify the supported Node engines. I added this and set to Node 4, since AppVeyor and Travis still build on Node 4.
**Test plan**
I ran `yarn upgrade` to update packages which were still in valid semver range. Then I ran `yarn` after updating the two packages listed above. I ran `yarn run build && …

Upgrade camelcase + flow and specify supported engines

---

jenkins-jobs.groovy

**Summary**
I've got some Jenkins build jobs for Yarn (to run the end-to-end tests, and to update the Chocolatey package). Originally I configured them through the Jenkins UI, but I've swiched to configuring them through the [job-dsl plugin](https://plugins.jenkins.io/job-dsl) so I can commit the job definitions to source control, similar to how we have the CircleCI, TravisCI and AppVeyor configs in source control.
**Test plan**
https://build.dan.cx/view/Yarn/

Add Jenkins jobs to repo

---

src/reporters/base-reporter.js

**Summary**
Several users of Visual Studio 2015 & 2017's NPM Task Runner extension have reported problems on Windows 7 with regard to running Yarn commands inside the IDE's Task Runner Explorer window. Interestingly enough, this doesn't appear to be an issue on Windows 10.
A fix for this problem was attempted [here](https://github.com/yarnpkg/yarn/pull/1000). The Angular CLI project also encountered the same problem, and it was fixed [here](https://github.com/angular/angular-cli/pull/4871).
This PR takes a very similar approach as that taken by the Angular CLI team. The PR also doesn't specifically test for the "win32" platform, as who knows what other platforms are really impacted by this.
**Test plan**
I ran the following commands to ensure that my changes didn't introduce any problems: …

gracefully handle process.stdin exceptions

---

__tests__/constants.js
__tests__/util/root-user.js
src/constants.js
src/fetchers/tarball-fetcher.js
src/util/root-user.js
src/util/user-home-dir.js

**Summary**
This fixes the circular dependency that caused #2807.
**Test plan**
Packages installed with `sudo yarn global add` should now go to `/usr/local/share/yarn` instead of `/root/.config/yarn`.

Move ROOT_USER to a separate file, fixes #2807

---

__tests__/commands/install/integration.js
__tests__/commands/install/unit.js
src/cli/commands/check.js
src/cli/commands/install.js
src/cli/index.js
src/integrity-checker.js
src/reporters/lang/en.js

**Summary**
I plan to improve integrity check code so that it could also verify node_modules structure.
This PR moves most of the integrity checking and saving code into a separate class, no actual changes to the logic.
**Test plan**
All tests should pass (integrity checks are covered with integration tests)
Pending things to do:
- a bit of cleanup

Refactored integrity generation and check

---

__tests__/commands/pack.js
__tests__/package-resolver.js
package.json
src/constants.js
src/fetchers/git-fetcher.js
src/fetchers/tarball-fetcher.js
src/util/git.js
yarn.lock

**Summary**
A mitigation for https://github.com/yarnpkg/yarn/issues/2629
Also fixes #961
Based on a few ad-hoc tests (//gitlab.com/linagora/petals-cockpit.git#075bac4c54fee466568c000c7ffe8025f593e212) tar-fs seems to make less IO thus is more stable and a bit faster.
I noticed that we never tested git repos that support archive.
Did they ever work?
----
Test data:
1. Using offline-mirror (no download), on my MBPro 13", clean cache and using `node-tar` to unzip files.
Concurrency 12 - fails
Concurrency 8 - 18 seconds
Concurrency 4 - 18 seconds
Concurrency 2 - 21 seconds
2. Using offline-mirror (no download), on my MBPro 13", clean cache and using `tar-fs` to unzip files.
Concurrency 12 - 15 seconds
Concurrency 8 - 15 seconds
Concurrency 4 - 17 seconds
Concurrency 2 - 18 seconds
3. …

switched to tar-fs from node-tar to unpack tars

---

src/util/execute-lifecycle-script.js

**Summary**
Docker is using a bundled version of yarn, and the `yarn.js` is moved to `/usr/local/bin/yarn`.
However yarn always generates `npm_execpath` by the following code: 
```
env.npm_execpath = path.join(__dirname, '..', '..', 'bin', 'yarn.js');
```
Then the generated `npm_execpath` with docker pre-installed yarn will be `/bin/yarn.js` which does not exist.
**Test plan**
Run: 
```
docker run --rm -it node:7.7 /bin/bash -c 'echo "{\"scripts\": {\"test\": \"echo \$npm_execpath\"}}" > package.json && yarn test'
```
Output:
```
/usr/local/bin/yarn
```
```
docker run --rm -it node:7.7 /bin/bash -c 'curl -o- -L https://yarnpkg.com/install.sh | bash && echo "{\"scripts\": {\"test\": \"echo \$npm_execpath\"}}" > package.json && yarn test'
```
Output:
``` …
```

Fix npm_execpath for bundled release

---

circle.yml

**Summary**
Currently, our CircleCI build script publishes the GitHub release using [ghr](https://github.com/tcnksm/ghr), whereas AppVeyor publishes the GitHub release using a custom script. To maintain consistency between the two, I've changed the CircleCI build to publish GitHub releases in a way similar to how it's done for AppVeyor builds.
I would have loved to do the release in the `deployment` section of `circle.yml` like we do for `ghr`, but unfortunately this runs too early (before the build log has been saved and artifacts have been archived) so we can't hit the CircleCI API at that point. Running it as a webhook ensures that it runs once the build has fully completed, and the release script can hit the CircleCI API to verify that it's a legitimate build.
Doing release this way …

Use release infra rather than ghr to create GitHub releases

---

src/reporters/base-reporter.js

**Summary**
Per @Daniel15's suggestion, this PR adds a `console.warn` statement to the `catch` block introduced in PR https://github.com/yarnpkg/yarn/pull/2837.
**Test plan**
I ran the following commands to ensure that my changes didn't introduce any problems:
`yarn run build`
`yarn run lint`
`yarn run test`

Add console.warn to process.stdin catch block

---

package.json

**Summary**
The coverage tool of Jest did not generate the coverage for files that were not covered at all. E.g. files that are completely untested. The bad news: A lot of commands are left untested and the total coverage is significantly lower than before. The good news: after this change, you can actually see which commands require more tests which others might be able to contribute!
To trigger coverage for all files, the option `collectCoverageFrom` can be used per https://github.com/facebook/jest/issues/1211#issuecomment-240266448
**Test plan**
Run `yarn test` and open `coverage/lcov-report/index.html` in a browser of your preference. Observe that a lot of commands are now showing 0% coverage. The previous coverage report did not include these empty coverage files.

Generate coverage for uncovered source files

---

src/cli/commands/global.js
src/reporters/lang/en.js

**Summary**
Built upon this original [PR](https://github.com/yarnpkg/yarn/pull/2577/files) from [mnsn](https://github.com/mnsn)
Add a warning when a user is installing Yarn globally with Yarn, see the [issue](https://github.com/yarnpkg/yarn/issues/2495) for more details 
**Test plan**
Do we need tests for this warning?
I've build yarn locally and used that binary to install yarn globally and I get the warning. Should we add tests for this warning? wdwt

issue 2495: warn users when install yarn globally with yarn

---

src/registries/base-registry.js

**Summary**
To ignore the case of environment variable keys, eg use of `NPM_CONFIG_REGISTRY` instead of `npm_config_registry`
As exists, yarn only uses environment variables with lowercased keys
For npm, [environment variables are case insensitive](https://docs.npmjs.com/misc/config#environment-variables)
**Test plan**
Before:
```
> export NPM_CONFIG_REGISTRY=https://custom.npm.registry
> yarn install
yarn install v0.16.0
info No lockfile found.
error Couldn't find package "privately-hosted-package" on the "npm" registry.
> export npm_config_registry=https://custom.npm.registry
> yarn install
...
success Saved lockfile.
```
After:
```
> export NPM_CONFIG_REGISTRY=https://custom.npm.registry
> yarn install
yarn install v0.16.0
info No lockfile found.
[1/4] 🔍 …
```

Make registry environment variables case agnostic

---

src/cli/commands/install.js
src/cli/commands/licenses.js

**Summary**
fix: https://github.com/yarnpkg/yarn/issues/2567
`yarn licenses` command generate dependencies tree.
If is enable to production option is ignore only direct devDependencies.
So, has remain dependencies of devDependencies.
I'll try to remove devDependencies from dependencies tree.
How do you think it?
**Test plan**
confirm to exclude devDepensencies packages from license command output when enable to --prod option.
example paclage.json
```
{
"name": "try-yarn",
"devDependencies": {
"babel-core": "^6.24.0"
},
"react": "^15.4.2"
}
}
```
```
$ ./node_modules/.bin/yarn licenses ls
yarn licenses v0.23.0-0
├─ ansi-regex@2.1.1
│  ├─ License: MIT
│  └─ URL: https://github.com/chalk/ansi-regex.git
├─ …
```

ignore devDependencies on licenses command if is enable to --prod option

---

src/util/git.js

Currently with yarn when using git+ssh yarn fails to download and install the module if your ssh connection first includes a banner.  This change silences the banner by using the -q option on ssh to not show the banner during the connection negotiation along with specifying git cli to reference ssh with the -q option.

Resolves issues with git+ssh when ssh daemon has banner set.

---

src/package-install-scripts.js

**Summary**
Outputs build log when using `--verbose` flag as discussed in #2204.
**Test plan**
None! =) I couldn't find a single test for `PackageInstallScripts`, so this change is untested. If that's a deal breaker or an oversight on my part I'll update this PR.

Add verbose build log

---

src/cli/commands/global.js

**Summary**
Today we installed a package which apparently didn't have any binary.
The console message however was: `warning undefined has no binaries`.
This happens because [`packageHasNoBinaries`](https://github.com/yarnpkg/yarn/blob/6e9a9a6596ca8f177f68f6672a1ef4ff16705336/src/reporters/lang/en.js#L252) has 1 argument, which this call to the reporter does not serve.
Therefore the package name will be undefined.
**Test plan**
Given that the warning is not working properly (recursion, anyone? :smile: ), we suspect that the package was `generator-polymer-init-custom-build`.
Running `yarn global add generator-polymer-init-custom-build` shows the following output:
```
yarn global v0.21.3
[3/4] Linking …
```

Fix undefined error when package has no binaries

---

package.json
yarn.lock

**Summary**
This version fixes a cache permissions issue. See https://github.com/zertosh/v8-compile-cache/issues/2.
**Test plan**
Tested yarn on a shared Linux box as multiple users.
cc: @Kovensky

Update to v8-compile-cache@^1.1.0

---

__tests__/fixtures/lifecycle-scripts/lifecycle-scripts/package.json
__tests__/lifecycle-scripts.js
src/cli/commands/install.js
src/cli/commands/publish.js

**Summary**
This PR is a followup to #1499. We wish to add support for both `prepare` and `prepublishOnly` but aren't yet sure about the versioning we'd like Yarn to follow, so we preferred to remove the warning for the time being.
**Test plan**
I've added some tests on `yarn install` to check that the lifecycle hooks are correctly called, by I'm not sure it will be possible on `yarn publish`.

Adds prepare & prepublishOnly lifecycle hooks

---

package.json
yarn.lock

**Summary**
A small followup to #2995. The bump to 1.2.2 removes a spread operator which caused some folks trouble in node 4.
Fixes #2996 
**Test plan**
Same as #2995, but with node 4. ;)

Bump request-capture-har to 1.2.2

---

__tests__/commands/add.js
__tests__/commands/check.js
__tests__/commands/global.js
__tests__/commands/init.js
__tests__/commands/install/integration-deduping.js
__tests__/commands/install/integration-hoisting.js
__tests__/commands/install/integration.js
__tests__/commands/install/unit.js
__tests__/commands/pack.js
__tests__/commands/remove.js
__tests__/commands/upgrade.js
__tests__/commands/why.js
__tests__/lifecycle-scripts.js
__tests__/util/env-replace.js
src/fetchers/git-fetcher.js

Fix #3006 - Replace `assert` invocations by `expect()...` matchers.

Replaces assert w/ expect

---

__tests__/commands/add.js
__tests__/commands/install/integration.js
__tests__/commands/outdated.js
__tests__/normalize-manifest.js
__tests__/reporters/console-reporter.js

**Summary**
While on something else I noticed some matchers weren't being executed (i.e. just `expect(...)` with no assertion), I've fixed them.
**Test plan**
Existing tests pass.

fix uncalled matchers

---

src/util/fs.js

**Summary**
Motivation: Yarn is slow on one of my windows machines (but not others) with **Linking dependencies...** that can take minutes, so I tried to find the cause.
Turns out that Yarn was sometimes always copying every file because it's hiting this node bug: https://github.com/nodejs/node/issues/2069 that is windows specific.
In `fs.js`, `fs.utimes` is used after the file copy in `copyBulk` to set the `mtime` and checked to avoid extra copies in `buildActionsForCopy` but due to the bug the dates won't match even for files that were just copied by Yarn.
The bug is subtle because it doesn't reproduce on a clean system as Yarn would have downloaded the packages and copied the extracted version to the cache. In this case it would use the same buggy `utimes` version and will set the …

Make "Linking dependencies" faster on Windows (in some cases)

---

src/cli/commands/install.js

**Summary**
Allow disabling of the self-update check with a `disable-self-update-check` option.
t16181086
**Test plan**
Forced the outdated prompt to appear, and verified that adding `disable-self-update-check true` to a `.yarnrc` file prevented it from appearing.
There's currently no tests for the self-update checks.
// cc @bestander

Add option to disable the self-update check

---

__tests__/commands/check.js
__tests__/commands/install/integration.js
__tests__/fixtures/install/install-should-respect-node_env/package.json
__tests__/fixtures/install/install-should-respect-npm_config_production/package.json
__tests__/fixtures/install/install-should-respect-production_flag_over_node-env/package.json

Fixed flakiness of `--verify-tree should check dev dependencies` test.
We had a few tests that verify that Yarn supports setting config.production via environment variable.
Jest does not allow us to execute a test in complete isolation, if they are in different test suites.
So those few tests that changed environment variable could affect any other test running in parallel with it.
The code that handles env variables is quite straight forward so I don't expect us to break it unintentionally.
And removing the tests that affect global state of Jest sounds like a better alternative to me vs running all tests in sequence by default.

fix --verify-tree test stability

---

__tests__/util/request-manager.js
src/cli/index.js
src/config.js
src/constants.js
src/util/request-manager.js

It's been an old and annoying issue: yarn doesn't specify `fetch` timeout when downloading packages, causing `yarn install` to hang forever on network issues.
Steps to reproduce:
1) Install toxiproxy (proxy to simulate network latency [[1]](http://madebymunsters.com/blog/posts/simulating-poor-network-conditions-with-toxiproxy/), [[2]](https://github.com/Shopify/toxiproxy))
2. Configure toxiproxy to simulate the latency:
```
~/.bin/toxiproxy-cli create yarnpkg --listen localhost:8888 -u registry.yarnpkg.com:443
~/.bin/toxiproxy-cli toxic add yarnpkg -t latency -a latency=9000 -a jitter=50
```
3. Point `yarn.lock` to use `localhost:8888` as a host for package registry
4. Run `yarn install` and see the process hanging
***
The issue has been reported multiple times and it's a very easy fix; …

Specify TCP timeout when downloading packages

---

src/cli/index.js
src/reporters/base-reporter.js
src/reporters/console/console-reporter.js

**Summary**
This PR implements a `--silent` flag (`-s` for short) to Yarn's CLI in order to allow raw script output. [This feature is available on npm](https://github.com/rafaelrinaldi/til/blob/master/npm/npm-run-silently.md) and is very useful for when you want to pipe the output of a script as an input of another script.
**Test plan**
Add a `foo` script to your `package.json` that prints a simple message:
```json
{
"scripts": {
"foo": "echo 'it works'"
}
}
```
The default behavior will give you the script output followed by a header and a footer added by Yarn:
```sh
$ yarn run foo
yarn run v0.20.0-0
$ echo 'it works' 
it works
✨  Done in 0.14s.
```
However, if you want only the raw script output you can append the `--silent` flag:
```sh
$ yarn run foo --silent # or simply `-s`
it works …
```

Add silent flag to allow raw output

---

.flowconfig
package.json
src/integrity-checker.js
yarn.lock

**Summary**
Routine update. https://github.com/facebook/flow/releases/tag/v0.43.0
Not sure how that extra "flow" dep snuck in #2970. I tried v0.21.2 and master, and both yarn's remove that "flow" dep.
**Test plan**
`flow`.

Update to flow 0.43.0

---

src/reporters/lang/en.js
src/resolvers/registries/npm-resolver.js

**Summary**
I don't use mouses much so the behavior of the list prompt made me confused in the first place. After some rounds of scrolling through the list using arrows, I didn't know which package the version mismatch came from until I scroll my mouse.
The position of `chooseVersionFromList` message is fixed on the top line so I think `Please choose a version of $0 from this list:` would be more obvious to users than `Please choose a version from this list:`
**Test plan**
https://gfycat.com/ThornySplendidAndeancondor#?speed=2

Add package name to chooseVersionFromList message

---

__tests__/resolvers/exotics/bitbucket-resolver.js
__tests__/resolvers/exotics/github-resolver.js
__tests__/resolvers/exotics/gitlab-resolver.js
src/resolvers/exotics/bitbucket-resolver.js
src/resolvers/exotics/github-resolver.js
src/resolvers/exotics/gitlab-resolver.js
src/resolvers/exotics/hosted-git-resolver.js

**Summary**
When using the shortened git syntax such as `github:thedumbterminal/grunt-gemnasium#vx`, yarn tests for HTTP access using a generated URL ending in `.git` this will always return a `301` status even if the user does not have permission to access the repo (private repos would require auth first).
This change now uses a full git URL which does not end in `.git` this means that private repos will fail with `404` so then SSH auth is attempted instead, as long as the correct SSH keys are setup in the users terminal access to the private repo will succeed.
Addresses existing issue: https://github.com/yarnpkg/yarn/issues/2774
**Test plan**
Added new unit tests for the new `getGitHTTPBaseUrl` method.
This can be manually tested in the following way:
1. Create a new nam project with: …

Supports public and private git repos when using shorted repo syntax

---

src/config.js
src/constants.js
src/package-install-scripts.js

**Summary**
Building native node modules parallely on windows is causing linker errors as iojs.lib/node.lib files could get locked as explained in #2429 
**Test plan**
Set CHILD_CONCURRENCY to 1 and ran yarn install with the package.json having multiple native node modules. Builds ran sequentially.

Providing override for CHILD_CONCURRENCY via ENV

---

circle.yml

**Summary**
This PR adds a small script to make sure that the generated artifacts (the two most recently modified files) are working properly after `build-webpack.js` has been called.

Checks that the webpack builds are working properly

---

__tests__/commands/install/integration.js

fixing lint

---

__tests__/lifecycle-scripts.js
package.json
scripts/build-webpack.js
src/rc.js
src/util/rc.js
yarn.lock

**Summary**
We now ship our own logic to search for the Yarnrc file (initially, this change is prompted because the `rc` module doesn't support webpack, but it also allows us to resolve relative paths relatively to the yarnrc file in which they are found).
**Test plan**
Tests should all pass, a skipped test has been enabled.

Remove the dependency on the "rc" module

---

src/cli/commands/login.js

I think this is a typo? I noticed it when trying to login:

Make it log "email" instead of "username"

---

.gitignore
.npmignore
bin/yarn.js
package.json
src/constants.js
yarn.lock

**Summary**
Now that we're including the bundled .js file in the tarball, we don't really need Roadrunner. @bestander suggested removing it in #3030:
> What do you think of getting rid of roadrunner as well? The extra cache layer for people who run from master branch does not make much impact.
**Test plan**
`./bin/yarn install`, it worked as expected.
Closes #3075, #3037, #2959

Remove Roadrunner

---

__tests__/commands/cache.js

**Summary**/**Test plan**
As described in the title this commit add tests for cache commands.

Add tests for cache commands

---

__tests__/index.js
__tests__/lifecycle-scripts.js
src/cli/commands/help.js
src/cli/index.js
src/rc.js

After working some time on https://github.com/yarnpkg/yarn/pull/2810 I thought that maybe I was trying to reduce the complexity of src/cli/index.js from the wrong point of view.
In this pull request I:
- Cherry picked some commits from https://github.com/yarnpkg/yarn/pull/2810
- Reduce a lot of if statements
- Move all the logic of help in help command
Test plan, add test:
- for not camelised command
- for not alphabetic command
- for not unknown command
- extract npm_config_argv_env_vars correctly if you use 'yarn run test' instead of 'yarn test'
- display the documentation link correctly if we use an alias
- display the documentation link correctly if we use a normal command
- do not display the documentation link correctly if we use have an unknown command
Everything else seems tested …

Reduce complexity of src/cli/index.js

---

src/package-fetcher.js
src/reporters/lang/en.js

**Summary**
This is a mitigation for issue #2629.
In some cases two different packages could end up unpacking into the same cache folder.
Example https://github.com/yarnpkg/yarn/issues/2629#issuecomment-282745896, package typescript is downloaded twice because yarn.lock has inconsistent entries.
This change prevents more than one package to be unpacked into the same cache folder.
This is not a final fix for #2629, there is a more specific bug in resolver that causes this internal inconsistency but I think fetcher should check that every package will be extracted in a unique folder anyway.
**Test plan**
- I'll add a unit test in the next PR when I'll be fixing the reason for the same package having 2 downloads
- Manual test plan
1. Check out …

Fixed concurrnet unpacks into the same folder

---

__tests__/commands/check.js
src/integrity-checker.js

**Summary**
--ignore-scripts affects the underlying node_modules and should be factored in integrity check
**Test plan**
- added test
- manual
```
bestander-mbp:left-pad bestander$ yarn install --ignore-scripts
yarn install v0.24.0-0
warning Integrity check: Flags don't match
warning Ignored scripts due to flag.
✨  Done in 0.55s.
bestander-mbp:left-pad bestander$ yarn check --integrity
yarn check v0.24.0-0
warning Integrity check: Flags don't match
error Integrity check failed
error Found 1 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
bestander-mbp:left-pad …
```

Added --ignore-scripts flag to integrity check

---

jenkins_jobs.groovy
scripts/update-homebrew.sh

**Summary**
Adds a script to update Homebrew using their `brew-formula-pr` command. This runs fine on Linuxbrew. Also adds a Jenkins job for it.
**Test plan**
Manually tested the script with the origin set to a test repo: https://github.com/Daniel15/homebrew-core/pull/2
cc @SimenB 
Closes #2841

Automatically update Homebrew package when new versions are released

---

__tests__/commands/config.js
src/cli/commands/config.js

* Fixes regression introduced in PR #2440
* Related to #2434
**Summary**
Currently `$ yarn config set <config_key> ""` sets the respective config value to true. It should be possible to set config values to an empty string.
Omitting config value should still default to **true**, e.g.
`$ yarn config set  strict-ssl`
should set **strict-ssl** config value to **true**.
**Test plan**
`$ yarn config set version-tag-prefix ""`
should set **version-tag-prefix** config value to an empty string.

Fix bug when cannot set a config value to empty string

---

__tests__/util/git.js
src/util/git.js

Fixes #3146 (related to #1796)
In npm "git+ssh://foo:bar" is an SCP URL (where "bar" is a path), but "git+ssh://foo:123" is an SSH URL (where "123" is a port).

Better match npm's SCP vs SSH URL heuristic

---

package.json
src/fetchers/tarball-fetcher.js
src/util/stream.js
yarn.lock

**Summary**
Following the PR to use `tar-fs` (#2826), I was looking at ways to solve #2629, and noticed that yarn had its own ad-hoc implementation of gunzipping the archives while there exists an available implementation already, by the same person who made `tar-fs`.
Even though it does not improve the situation for #2629 (of course), I thought it would make sense to use an existing library instead of an adhoc implementation.
**Test plan**
I ran `yarn` in a project with lots of dependencies, no `node_modules` and an empty cache.
I used the default network concurrency of 8.
Everything worked as expected.

Use gunzip-maybe instead of reimplementing

---

.gitignore
__tests__/index.js
__tests__/reporters/__snapshots__/json-reporter.js.snap
__tests__/reporters/json-reporter.js
src/reporters/json-reporter.js

**Summary**
Addresses #3155 by applying the same logic used in the `ConsoleReporter` to hide activity and progress output for the `JSONReporter` when using `--no-progress`.
Originally wanted to be able to generate a list of licenses used in JSON format using `yarn licenses ls --json --no-progress`, but extra output from activity/progress was shown. Discovered that the `JSONReporter` does not contain the same logic to hide activity/progress output as other reporters.
**Test plan**
Automated: `yarn test`
Manual: `yarn [cmd] --json --no-progress`
**Before:**
**After:**

Hide Activity/Progress Output in JSONReporter with --no-progress Flag

---

src/cli/commands/clean.js
src/cli/commands/remove.js

@arcanis sorry I totally forgot to inform you that clean and remove command miss a hasWrapper function.
This should fix both commands after https://github.com/yarnpkg/yarn/pull/3105
Let mw know,
cheers,
Simon

Add hasWrapper function in clean and remove command

---

src/util/fs.js

**Summary**
Makes linking faster by reducing the number of file system calls in the `buildActionsForCopy` routine which synchronizes existing `node_modules` tree with the ideal one.
In my test runs (on `yarn` itself, and on [another big project](http://github.com/mapbox/mapbox-gl-js)), it saves about 400ms when running `yarn` without a lock file (or during upgrade).
- Remove redundant `fs.exists` (in favor of `lstat` which is called later anyway)
- Remove unnecessary `fs.access` (which does nothing — it's a placeholder in the code, so should be commented)
- Remove deeper directory traversal for `possibleExtraneous` since it should be populated with the same values later in the queue anyway.
- Avoid calling `mkdirp` if we know the destination folder already exists.
cc @bestander 
**Test …

Optimize buildActionsForCopy routine

---

__tests__/commands/pack.js
__tests__/fixtures/pack/files-include-mandatory/package.json
src/cli/commands/pack.js
src/types.js

**Summary**
This is for compatibility with npm, which [specifies] that:
> Certain files are always included, regardless of settings:
> * package.json
> * README
> * CHANGES / CHANGELOG / HISTORY
> * LICENSE / LICENCE
> * NOTICE
> * The file in the "main" field
[specifies]: https://docs.npmjs.com/files/package.json#files
**Test plan**
I changed the `files-include-mandatory` test to exclude "index.js" from
`files`, and ensure that it still gets included, since it is the `main`
file.

Fix `yarn pack` to always include the file in the "main" field

---

scripts/clean-mirror.sh

**Summary**
This PR adds the script we've used to clear our offline mirror to the Yarn repository. I've improved it a bit in the process, making it more generic (paths are extracted from the arguments), and adding two options: `-d` (dry-run) and `-s` (stats).
**Test plan**
I've only tested this script on OSX, I still need to run it on Linux to make sure everything is ok.

Adds clean-mirror.sh to scripts

---

__tests__/commands/version.js
__tests__/fixtures/version/no-args-same-version/package.json
src/cli/commands/version.js
src/reporters/lang/en.js

See issue 3011 for details. Leave it to npm registry to validate the version number.
Motivation is to make it work with the way how I deploy my videomail-client library at
https://github.com/binarykitchen/videomail-client/blob/develop/bin/release.sh
There I am already bumping to the new version in package.json before publishing it with yarn to npm.
**Test plan**
1. Manually increment version in a random package.json
2. Run `yarn publish --new-version with that new version`
3. Yarn won't complain anymore that the new version is the same.
4. It will be up to the npm registry whether to accept that version or not.

Do not test new version with pkg.version

---

src/util/fs.js

Adds back a few lines that were removed in #2657 that apparently caused the `command add` test to fail. cc @bestander @arcanis

Partially revert #2657 to fix add command test

---

__tests__/reporters/base-reporter.js
src/cli/commands/upgrade-interactive.js
src/reporters/base-reporter.js
src/reporters/console/console-reporter.js
src/reporters/noop-reporter.js
src/reporters/types.js

This is a long time due.
When I first wrote it I had no idea about the rest of the yarn codebase. Later I realized it would be a better idea to move this inside the reporter. Then we can easily use this in other parts of our codebase.
**Future Wok**
* Update Inquirer flow type.
* ~~Fix *press double `ctrl+c` to get out of interactive mode*~~ (done)

Move inquirer code to console reporter

---

__tests__/commands/install/integration.js
src/cli/commands/install.js
src/integrity-checker.js
src/package-install-scripts.js
src/package-linker.js

**Summary**
This moves build artifact tracking away from the cache metadata and into the integrity file.
I suspect this should fix #1981 as the cause seems to be that they restore `node_modules` and not Yarn's internal cache.
**Test plan**

Put build artifact tracking in integrity file

---

__tests__/util/fs.js
src/util/fs.js

There's an issue in node (https://github.com/nodejs/node/pull/12607) with submillisecond truncation of file mtimes on Windows, which makes yarns fileDatesEqual test fail on any file that's affected by the bug. This causes many identical files to appear changed causing unneeded re-copying on every yarn command.
You can run this to reproduce the issue:
```js
var fs = require('fs');
var targetMTime = new Date('2017-04-08T17:59:38.008Z');
fs.writeFileSync("./file1", "");
fs.utimesSync("./file1", targetMTime, targetMTime);
var actualMTime = fs.statSync("./file1").mtime;
console.log(actualMTime); // 2017-04-08T17:59:38.007Z
console.log(actualMTime.getTime() === targetMTime.getTime()); // false
```
In my test projects this issue affects in the area of 10% of files, so in a project with 50000 …

accept 1ms difference in filedates as equal on windows

---

bin/node-gyp-bin/node-gyp
bin/node-gyp-bin/node-gyp.cmd
package.json
scripts/build-dist.sh
src/reporters/lang/en.js
src/util/execute-lifecycle-script.js
yarn.lock

**Summary**
Some Node.js packages depend on `node-gyp` but do **not** declare the dependency in their `package.json`, instead relying on node-gyp to already be globally installed. For packages like this, we used to bundle node-gyp with Yarn itself. However, this does not work for the standalone JS build (which is used by the tarball now too)
The ideal fix is for packages to explicitly specify that they require node-gyp, as relying on the global version is dangerous (eg. if there's breaking changes between releases).
The changes I've made are as follows:
1. Include node-gyp version from npm in the PATH for lifecycle scripts. This means that Yarn should behave the same way as npm, as long as the user has npm installed (not every Node.js user uses npm - Many distributions of Node.js require …

Use npm's node-gyp if available, otherwise automatically install node-gyp

---

src/cli/commands/licenses.js

In https://github.com/yarnpkg/yarn/pull/3238 I noticed that we changed the skipIntegrity flag in skipIntegrityCheck (this is the commit https://github.com/yarnpkg/yarn/commit/bd8e326668aa1deac07b53bb9b9d93daf172c070)
**Test plan**
I have no idea how to test it; right now I don't have time to see this part. Let's park here for now.

Use skipIntegrityCheck instead of skipIntegrity in licenses command

---

resources/winsetup/Yarn.wxs
src/cli/commands/global.js

**Summary**
Node.js is almost always installed in `C:\Program Files\Yarn`, which regular users can't write to. However, Yarn defaults to installing the executables for global modules in the Node directory. This means that the out-of-the-box experience for people installing global modules on Windows is totally broken.
It should instead place them in a directory that the user can write to. I'm going with `%LocalAppData\Yarn\bin` (eg. `C:\Users\Daniel\AppData\Local\Yarn\bin`) as it makes the most sense given all the config and cache is already in that directory. I also updated the path in the installer, as the path the installer was using didn't actually exist (`.bin` instead of `bin`).
**Test plan**
Tested `bin\yarn global add webpack`, it placed the files in the right directory:
Closes …

Fix global module executable path on Windows

---

__tests__/commands/cache.js
__tests__/commands/install/integration.js
package.json
src/cli/commands/import.js
src/resolvers/exotics/file-resolver.js
yarn.lock

**Summary**
When using a `file:` resolution for dependencies, the dependency is always being pulled from yarn's cache; the first time being the exception, which puts it into the cache.  
Currently the cached package will only have the name and version, like the following:
```sh
ls `yarn cache dir` | grep npm-foo
```
This change ensures that the compared dependency always generates a new hashed name which will invalidate the cache.  The new hash name looks like:
```js
`npm-${package.name}-${package.version}-${uuid.v4()}-${(new Date()).getTime()}`
```
I've found two small caveats which are worth noting.
1. Once a dependency is installed to the `node_modules` directory, the hash comparison doesn't have any effect when running `yarn install` is called again.  Only package.json `version` …

Ref #2165 - file-resolver should invalidate cache with a new hash

---

src/cli/commands/install.js

**Summary**
We only take unused dependencies into consideration to get deterministic hoisting.
Since flat mode doesn't care about hoisting and everything is top level and specified then we can safely leave these out. Fixes #2781.
**Test plan**
Not sure how to test this, don't have much time to spend on it.

When in flat mode don't add unused dependencies - fixes #2781

---

__tests__/registries/is-request-to-registry.js
src/registries/is-request-to-registry.js
src/registries/npm-registry.js

**Summary**
This will help solving #521 
I use a private NPM registry hosted via Artifactory v4.14.1 and I was having some issues.
The first one is that apparently this version of Artifactory still does not support the `application/vnd.npm.install-v1+json` header implemented on #3112. To fix that, I noted by reading [npm docs](https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md) that we can add a fallback to `application/json`.
This allowed yarn to correctly download metadata from artifactory. Then, I had another problem, with the `isRequestToRegistry` function implemented on #2598. The problem was that although I do specify `https://myartifactory` for my registy, some dependencies gets the `https` replaced with `http` by yarn, preventing it from sending the …

Fixies for running with artifactory 4.14.1

---

bin/yarn

**Summary**
There used to be issues with Yarn on Windows that required the use of winpty:
- https://github.com/yarnpkg/yarn/issues/743
That fix caused issues down the line when some part of the Windows/Git/Bash toolchain was updated:
- https://github.com/yarnpkg/yarn/issues/2591
- https://github.com/yarnpkg/yarn/issues/2998
This change removes the troublesome auto detection of whether or not winpty is needed and relegates it to the environment variable `YARN_FORCE_WINPTY`
**Test plan**
Simple change of already existing logic. I'm not sure if there are any tests for it, but:
- https://github.com/yarnpkg/yarn/issues/2998#issuecomment-292597818 Working screenshots
- https://github.com/yarnpkg/yarn/issues/2998#issuecomment-291076842 Confirmation that removing the old logic works

Change `use_winpty` logic in bin/yarn

---

__tests__/fixtures/lifecycle-scripts/yarnrc-env/.yarnrc
__tests__/fixtures/lifecycle-scripts/yarnrc-env/log-command.js
__tests__/fixtures/lifecycle-scripts/yarnrc-env/nested/.yarnrc
__tests__/fixtures/lifecycle-scripts/yarnrc-env/nested/log-command.js
__tests__/fixtures/lifecycle-scripts/yarnrc-env/nested/package.json
__tests__/fixtures/lifecycle-scripts/yarnrc-env/package.json
__tests__/lifecycle-scripts.js
src/registries/yarn-registry.js
src/util/execute-lifecycle-script.js

**Summary**
This PR adds an option called `env` to `.yarnrc`. It allows you to specify environment variables that will be exposed to lifecycle scripts.
For example:
**.yarnrc**
```
env:
FOO "BAR"
```
**package.json**
```
{
"scripts": "node install.js"
}
```
**install.js**
```
console.log(process.env.FOO === "bar");
```
**Test plan**
Added a test.

Add .yarnrc env config option

---

src/util/fs.js

Currently performance of yarn on Windows with Windows Defender is not great, especially for large projects. One of the causes of this is fs.copyBulk invoking fs.utimes prior to closing the file being copied.
Windows updates a files mtime when its handle closes, so if yarns utime call completes before the os has had time to actually close the file, yarns times will be overwritten. Windows Defender makes this issue far more noticeable since it runs its scan before the handle is closed causing nearly every file to lose yarns mtime. The end result is that most files in node_modules will be recopied on every single yarn command if Windows Defender is enabled. (If WD is disabled the issue remains, but it does stabilize as yarn gets lucky and updates mtimes after windows.)
By using the close …

use close instead of finish event for file copy completion

---

__tests__/commands/_helpers.js
__tests__/commands/check.js
src/cli/commands/check.js
src/cli/commands/install.js
src/integrity-checker.js
src/reporters/lang/en.js

**Summary**
Integrity-checker should not have side effects and we should reporting warning only in the check command.
**Todo list**
**Test plan**
See above.

extract the reporter out of integrity checker

---

jenkins_jobs.groovy
scripts/build-chocolatey.ps1
scripts/update-homebrew.sh

**Summary**
Instead of always grabbing the Yarn version number from yarnpkg.com/latest-version, allow it to be passed in as command line argument. This allows the Homebrew and Chocolatey packages to be rebuilt with the correct version numbers, after the Github release has been performed but before Netlify pushes the site.
**Test plan**
Tested manually in Jenkins by forking the `jenkins_jobs.groovy` into a test project.

Pass version number to build-chocolatey and update-homebrew

---

__tests__/commands/pack.js

**Summary**
In this file we had a run function very similar to the function present in https://github.com/yarnpkg/yarn/blob/master/__tests__/commands/_helpers.js#L54
**Test plan**
We have a lot of tests for the pack command. Everything seems ok.
cc @bestander @arcanis

remove duplication in __tests__/commands/pack.js

---

src/resolvers/exotics/hosted-git-resolver.js

**Summary**
When running yarn offline, Git dependencies get trapped in `hasHTTPCapability` even though `resolveOverHTTP` defaults to returning the tarball. This change allows us to bypass that step altogether if the tarball already exists.
Resolves #1925.
**Test plan**
Create a `package.json` with a Git dependency, like:
```
"nomnom": "douglasduteil/nomnom#next"
```
Then:
```
yarn
rm -r node_modules
yarn --offline
```
This should fail prior to this commit, but succeed after.
This change was first proposed in #2705, but @chrisgavin closed the PR and hasn't had a chance to revisit. I'm happy to add unit tests if/as needed, but may need some guidance on mocking offline functionality.

Resolve Git dependencies offline if tarball is available.

---

jenkins_jobs.groovy
scripts/build-chocolatey.ps1
scripts/update-homebrew.sh

**Summary**
Updates the Chocolatey and Homebrew builds scripts to quit early if an RC is being built.
**Test plan**
Tested scripts on my computer, and tested Jenkins changes using a test job

Only update Chocolatey and Homebrew for non-RC releases

---

src/reporters/lang/en.js

**Summary**
Just a small wording tidy up,
Original:
> Amount of shared dependencies: $0
Update:
> Number of shared dependencies: $0
**Test plan**
```
yarn why [PACKAGE_NAME]
...
info Number of shared dependencies: 11
...
```

Better use of English in `why` output

---

src/cli/commands/install.js
src/cli/commands/versions.js
src/cli/index.js
src/package-compatibility.js
src/registries/yarn-registry.js
src/util/yarn-version.js

**Summary**
We do `require('package.json')` in a few places to get the version number and installation method of Yarn. In the Webpack build, this is embedded within the JS file itself. While this works fine for the version number (as that's constant), the installation methods can be different even with an identical build of Yarn. For example, Homebrew takes our tarball and then patches the `installationMethod` in `package.json` so we can tell that Yarn was installed via Homebrew. Using `require('package.json')` in this case won't reflect the update as it's only seeing package.json at the time of build (rather than at runtime).
Instead, we need to actually read the `package.json` file to check for the installationMethod at runtime. This looks in the parent directory (`../package.json`) due …

Correctly handle installationMethod when using bundled build

---

src/fetchers/tarball-fetcher.js

**Summary**
It looks like there should be an error handler that reports English for the `fetchErrorCorrupt` string, but instead an error from tar-stream is being returned without the filename.
This makes it quite difficult to figure out which module is causing the error so that the bad tarball can be deleted.
**Test plan**
Running `yarn upgrade <list_of_modules>` with this code yielded the following results:
```
error An unexpected error occurred: "Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped? (/Users/rsandler/Code/zendesk/zendesk_console/npm-packages-offline-cache/detect-browser-1.7.0.tgz)".
```
Where previously the section in brackets was not there.
The cause appears to be yarn caching the npm registry's 404 response (which is HTML) to a file. Why it does …

Add a more useful error message when we cache a broken tarball

---

package.json
yarn.lock

I just upgrade babel-core.
I think we should adopt something like https://greenkeeper.io/ to update our dependencies automatically. I saw zeit using it for their projects: the bot just opens a pull request every time there is a possible upgrade.
what do you think? @bestander @arcanis @Daniel15

upgrade babel-core

---

bin/yarn

**Summary**
#3260 PR broke the `bin/yarn` shell script (see issue #3321)
#3338 tried to fix it in a improper way
This way should work.
**Test plan**
I modify my `/usr/bin/yarn` file on my Debian (testing branch) and it fix the error message describe in #3321.
Could be great if someone test this on another platform, but it should be a generic solution.
To test this :
- Install yarn `0.24.x`
- Modify your yarn bin script (location should depends on your distribution) as this PR does.
- Run `yarn -V`. It should work without any error/warning messages from your shell.

Fix yarn "entrypoint" shell script

---

.travis.yml

**Summary**
Travis tests on OSX seems to failed **A LOT**
because of this :
```
<--- Last few GCs --->
1207511 ms: Mark-sweep 1362.1 (1435.5) -> 1362.1 (1435.5) MB, 2697.2 / 0.0 ms [allocation failure] [GC in old space requested].
1210266 ms: Mark-sweep 1362.1 (1435.5) -> 1362.1 (1435.5) MB, 2754.3 / 0.1 ms [allocation failure] [GC in old space requested].
1213441 ms: Mark-sweep 1362.1 (1435.5) -> 1385.1 (1411.5) MB, 3175.0 / 0.1 ms [last resort gc].
1217347 ms: Mark-sweep 1385.1 (1411.5) -> 1408.1 (1411.5) MB, 3905.5 / 0.1 ms [last resort gc].
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0x5f7e3bcfb39 <JS Object>
2: _tickCallback [internal/process/next_tick.js:~93] [pc=0x109f829ab8e3] (this=0x1c51837a7319 <a process with map …
```

Fix Travis OSX tests

---

__tests__/util/git.js
src/util/git.js

**Summary**
Fixes #3325 
Modified the parsing of Git ref lines to check it against a regexp before assuming the input line is a reference.
Since I was now using a regexp, I also use capture groups to extract the tag name and sha hash, insted of hte old implementation that was using string splits.
**Test plan**
Added unit tests for `Git.parseRefs()` to `__tests__/util/git.js`

modify git ref parsing to not error on non-matching lines

---

__tests__/util/semver.js
src/package-linker.js
src/util/semver.js

**Summary**
Uses lower-level APIs in node-semver to allow prerelease versions when checking peer deps. This honors the intent of library authors e.g. when they write a React component that asks for `"react": ">=15.0.0"` they're saying OK to `react@16.0.0` (partly because the React team specifically has said that if you don't have any warnings in version N, then version N+1 should work for you). By extension and modulo bugs, `react@16.0.0-alpha` works too if the user explicitly installs it.
Fixes #2760
**Test plan**
Added unit tests for the new semver utility.
Tested in a real project that uses React 16.0.0-alpha.11 and verified I didn't get any peer dep warnings that usually appear from libraries that ask for `"react": ">=15.0.0"`. Downgraded React to 0.14.0 (too low) and saw peer dep …

Allow prerelease versions when checking peer deps

---

src/cli/index.js

**Summary**
Installing with `--mutex file:` option spams the output with warnings of:
```
warning Waiting for the other yarn instance to finish
```
It should only display once.  Fixes #2938.
**Test plan**
Not sure this is necessary.

Ref #2938 - Remove warning spam during install with file mutex

---

__tests__/commands/global.js
src/cli/commands/global.js

This involved moving the list function out of the buildSubCommands so it could be called from ls & list.
Calling global ls will display a warning that global ls is deprecated and to use global list.
**Summary**
Changed the `yarn global ls` command to `yarn global list` to be inline with the non-global command, as per #3003.
**Test plan**
Tests were updated to ensure that the output of `yarn global ls` and `yarn global list` produced the same results. Running `yarn run test` verified the new test passed.

Added a list sub-command for the yarn global command. Added unit test.

---

circle.yml

Until #610 is fixed we have to use npm publish on CI

yarn publish not ready for CI

---

__tests__/fixtures/install/install-from-authed-private-registry-no-slash/.npmrc
__tests__/fixtures/install/install-from-authed-private-registry/.npmrc
__tests__/registries/is-request-to-registry.js
src/fetchers/base-fetcher.js
src/fetchers/tarball-fetcher.js
src/registries/is-request-to-registry.js
src/registries/npm-registry.js
src/resolvers/registries/npm-resolver.js
src/types.js

This is a continuation of #2507 where the progress has recently stalled. Fixes #2505.
[Visual Studio Team Services](https://www.visualstudio.com/team-services/) (VSTS) unfortunately produces package feed URLs that look like `https://account.pkgs.visualstudio.com/_packaging/feed-name/npm/registry` but the URLs to fetch the actual tars then point to `https://account.pkgs.visualstudio.com/_packaging/a917cf10-dfe4-4781-b0d1-105df772da02/npm/registry/@scope/package-name/-/package-name-0.0.1.tgz`.
This Pull Request aims to fix this by picking up a suggestion from #2507 by @bestander and introduces a new `.yarnrc` option called `custom-host-suffix`. That options allows to skip a check in the form of `requestPath.startsWith(registryPath)` if the request's URL contains the value of …

[Replace #2507] Support VSTS and other custom registries with unusual feeds

---

src/cli/index.js

The previous behaviour had a default of enabling emojis for Macs, and
allowed explicitly disabling them.
This PR keeps that default but allows `--emoji` to enable for other
platforms if the user wants to.  `--no-emoji` still works as before, but
due to the way that commander processes "--no-" flags (forcing the
default to true and overwriting the default value given in the `.option`
definition) it was necessary to switch the flag definition from
`--no-emoji` to `--emoji`.
**Summary**
Allows users to enable emojis on non-darwin platforms.
Emojis are a nice feature but are explicitly disabled on non-darwin platforms.  There appears to be some interest in having them on other plaforms (see #960) and this allows that by making `--emoji` work as you'd expect (`--no-emoji` and `--emoji` are …

Allow emojis to be force enabled with `--emoji`.

---

src/fetchers/git-fetcher.js

Because `this.hash` is equal to the commit hash inside the git fetcher, we have nothing against which compare the tarball hash. Fixing this will require fixing the lockfile structure (discussion [here](https://github.com/yarnpkg/rfcs/pull/64)), so in the meantime it's better to just disable this check.
Note that it wasn't a problem before 0.23, because until we merged #51 the offline `resolved` entry only contained the tarball name, which conveniently didn't included the hash. Since there was no hash, no check was made.

Disables the hash check for git repositories

---

__tests__/util/git.js
src/util/git.js

**Summary**
After recent work on fixing the private shortened git URL formats I've noticed there are still some that do not work.
For example this URL format works:
github:thedumbterminal/test-private-node-module
But this format does not:
github:thedumbterminal/test-private-node-module.git
This work fixes this.
**Test plan**
Create a new directory with the following `package.json`:
```json
{
"name": "1",
"description": "",
"scripts": {
"test": "echo \"Error: no test specified\" && exit 1"
},
"author": "",
"license": "ISC",
"grunt-gemnasium": "github:thedumbterminal/grunt-gemnasium.git"
}
}
```
Without this fix you will get the following error:
```
ssh: Could not resolve hostname github: nodename nor servname provided, or not known …
```

Added support for more git URL formats

---

__tests__/package-request.js
src/package-request.js

> Description based on https://github.com/yarnpkg/yarn/issues/573#issuecomment-301674068
https://github.com/yarnpkg/yarn/pull/2992 added support for private git repos when using shorted repo syntax (this landed on v0.24.0).
The generation for the first time of a `yarn.lock` file works well, but then with a yarn.lock file if you try `rm -rf node_modules && yarn` fails with this error:
```sh
error An unexpected error occurred: "Invalid protocol: git+ssh:".
```
That error comes from https://github.com/request/request/blob/b12a6245d9acdb1e13c6486d427801e123fdafae/request.js#L455  and I think it's because yarn tries to use the tarball fetcher instead of the git fetcher.
The offline feature/fix added recently makes the git resolver defaults to the tarball to avoid http calls …

Fix support for private git repos when using shorted repo syntax and lock file exists

---

.eslintrc
__tests__/commands/global.js
src/cli/commands/run.js
src/cli/commands/upgrade-interactive.js
src/cli/commands/version.js
src/config.js
src/fetchers/tarball-fetcher.js
src/package-fetcher.js
src/package-request.js
src/resolvers/exotics/hosted-git-resolver.js
src/resolvers/registries/npm-resolver.js
src/util/git.js

* Add lint rule `no-return-await`
* Replace redundant `return await` calls with `return`
* Convert async functions which no longer have `await` calls to normal functions
Similar to #352

Optimize async functions

---

__tests__/commands/install/integration.js
src/cli/commands/install.js

**Summary**
This PR is a bug fix from https://github.com/yarnpkg/yarn/issues/3435
The issue was that files that weren't tarballs (.git, for example) were also removed since they weren't present in the lockfile.
**Test plan**
I've stepped through the STRs from the original bug report
1) Set `yarn config set yarn-offline-mirror ./npm-packages-offline-cache` and `yarn config set yarn-offline-mirror-pruning true`
2) Create a git repo inside of packages-cache
3) Run `yarn remove` on an installed dependency
4) Check that the git repo still exists, unlike previous behavior

Add explicit check for tarball files in mirror files directory

---

__tests__/commands/check.js
__tests__/commands/install/integration.js
__tests__/package-request.js
__tests__/package-resolver.js
package.json
src/cli/commands/check.js
src/cli/commands/import.js
src/cli/commands/install.js
src/fetchers/git-fetcher.js
src/package-compatibility.js
src/package-fetcher.js
src/package-request.js
src/package-resolver.js
src/types.js

**Summary**
Make package-compatibility and package-fetcher stateless and indipendent from package-resolver.
I made some ugly choices, but imho the road towards https://github.com/yarnpkg/yarn/issues/2918 is open :D (I hope this merge it will not close that issue).
I think it is important to be incremental as possible because I am touching the core O.o
Big Pro: now we can time every part and maybe introduce some unit tests :)
**Test plan**
Tests are green, before made every change I carefully check if every line were covered indirectly from tests.

Make package-compatibility and package-fetcher stateless

---

.eslintrc
package.json
yarn.lock

[`no-async-without-await` plugin by @zertosh](https://github.com/zertosh/eslint-plugin-no-async-without-await) is no longer needed since a rule with the same functionality was merged into ESLint core (https://github.com/eslint/eslint/pull/7435) a month after his plugin was published.

Replace `no-async-without-await` plugin with in-built rule

---

__tests__/fixtures/normalize-manifest/dedupe all trivial dependencies/actual.json
__tests__/fixtures/normalize-manifest/dedupe all trivial dependencies/expected.json
__tests__/fixtures/normalize-manifest/dedupe all trivial dependencies/warnings.json
__tests__/fixtures/normalize-manifest/dedupe single trivial dependency/actual.json
__tests__/fixtures/normalize-manifest/dedupe single trivial dependency/expected.json
__tests__/fixtures/normalize-manifest/dedupe single trivial dependency/warnings.json
src/util/normalize-manifest/validate.js

**Summary**
This PR fixes #2660.
When installing `"connect-mincer": "~1.1.0"`, its dependency `underscore` is not installed. This is caused by the manifest normalization functions.
The manifest of `connect-mincer` lists underscore twice:
```
"mincer": "^1.3.0",
"underscore": "1.4.x"
},
"devDependencies": {
"async": "*",
"chai": "*",
"cheerio": "*",
"coffee-script": "1.4.x",
"connect": "*",
"csso": "*",
"ejs": "*",
"express": "^4.13.3",
"less": "*",
"mocha": "1.8.x",
"nib": "*",
"should": "*",
"sinon": "1.6.x",
"stylus": "*",
"supertest": "*",
"uglify-js": "*",
"underscore": "*",
"wrench": "*"
},
```
The cleanDependencies function currently keeps the last dependency with version '*' in the order `[ 'optionalDependencies', 'dependencies', 'devDependencies' ]`. In this …

Fix manifest trivial dependency normalization, fixes #2660

---

src/cli/commands/outdated.js
src/cli/index.js

**Summary**
Fixes #3483 
**Test plan**

Exit process with code 1 when outdated dependencies are found

---

src/reporters/lang/en.js

**Summary**
Fixes typo in 'incorrectLockfileEntry' reporter message.
Fixes  #3496
**Test plan**
No tests needed

Fix typo in reporter message

---

bin/yarn.js
gulpfile.js

* Running `bin/yarn.js` failed if `lib-legacy` wasn't built. Most developers run node v4+ and don't need/want to build the legacy files while developing for yarn. This PR also adds a gulp command `watch-modern`.
* Requiring files from the `lib-legacy` directory in node v4+ environments resulted in loading some modules from disk twice, once from `lib-legacy` and once from `lib`.
For example, previously, `constants.js` was loaded from the `lib-legacy` directory when `require('../lib-legacy/constants')` was called and later again from the `lib` directory when `require(path)` was called. Any module that was required by `constants.js` directly or indirectly, were all loaded twice.

Refactor and optimize `bin/yarn.js`

---

__tests__/commands/cache.js
src/cli/commands/cache.js
src/reporters/lang/en.js

**Summary**
This minor feature is described in #3324 . It introduce an optional argument to existing `yarn cache clean` command.
The usage become : `yarn cache clean [package_name]`
For example, `yarn cache clean yargs` will remove all versions of `yargs` from cache (_if exists in cache folder, otherwise will display a warning message_)
**Motivations**
Default behaviour is to clean all the cache. But for some reasons, you may need to only clean a single package from cache.
**Test plan**
I added a test in `__tests__/commands/cache.js`.

Allow to clean named package from cache

---

src/cli/commands/run.js
src/cli/index.js

**Summary**
This changes `yarn run` commands causing all child yarn processes to go into silent mode. This is useful as when you have a lot of nested scripts it can lead to a lot of stdout thrash with the yarn header CLI header and footer.
**Before**
```
yarn foo v0.26.0-0
$ echo foo && yarn bar
foo
yarn bar v0.24.3
$ echo bar
bar
✨  Done in 0.09s.
Done in 0.56s.
```
**After**
```
yarn foo v0.26.0-0
$ echo foo && yarn bar
foo
bar
Done in 0.56s.
```
**Test plan**
With a `package.json` of:
```
{
"name": "yarn-silent-implicit",
"scripts": {
"foo": "echo foo && yarn bar",
"bar": "echo bar"
}
}
```
produces the output of:
```
$ yarn foo
yarn foo v0.26.0-0
$ echo foo && yarn bar
foo
bar
Done in 0.56s.
```
Note that the the `yarn bar` …

Put yarn into silent mode when calling nested `yarn run` commands

---

src/util/fs.js

**Summary**
This patch boosts cache extraction by ~2x+ by letting node
do more parallelization work. This makes nearly all of the file copy
stuff be done by the C++ code with minimal boundary-crossing (at least
compared to node streams).
Streams in node.js are ~3x slower, specially for small files,
than just doing fs.writeFile/readFile, because of this boundary. This
is something Yarn might want to take into account in other places.
The reason this is OK is because pretty much any files this would
handle would fit neatly into memory (any npm packages MUST fit
into memory by definition, because of the way npm@<5 does extracts).
If you really want to make doubleplus sure to minimize memory usage,
you could do an fs.stat to find the file size and then do heuristics
to only use streams for …

fs: do bulk file reads to optimize cache extraction

---

__tests__/util/path.js
src/cli/commands/config.js
src/config.js
src/util/path.js

**Summary**
Tildes (`~`) were not correctly processed by Yarn when setting up the cache directory. Instead of expanding it to the home folder, it was creating a folder called `~` on the current directory where the command was executed.
The fix included proxying all `fs` calls through our custom module (`src/util/fs.js`), and expand each and every path we get through it. In places where this was not possible (e.g. external modules which accept paths, like `tar-fs`, an extra method called `fs.expandPath` is used just before calling them. Path expansion does not happen on Windows platforms.
Overridding the native `fs` module seemed way too risky and could lead to confusion.
**Test plan**
* Change your cache folder to point to something that includes the tilde; for example `~/foo`. Be sure to …

Allow tilde to be used in config paths, expanding it to $HOME

---

src/fetchers/git-fetcher.js

Found on 0.25.3
Following up #3449
expectHash is used beforehand to generate the cache destination, but actualHash is returned. This causes future cache destination path generation to use the wrong hash, resulting in EOENT errors.
@bestander 
Full story:
PackageFetcher generates `dest` parameter using Config.generateHardModulePath before fetching using expectHash i.e. the commit hash
GitFetcher returns actualHash (i.e. tarball hash) as result of fetch
Some time later updateManifest is called with the fetch result hash (actualHash)
This pollutes the resolved patterns cache (PackageResolver.patterns) with the wrong hash (actualHash)
Future Config.generateHardModulePath calls getResolvedPattern and gets actualHash, (as opposed to expectHash. This causes it to look for the cached package in …

Fix GitFetcher.fetchFromLocal using wrong hash

---

src/cli/commands/install.js

**Summary**
When checking lockfile patterns and resolved patterns, we were using `.filter(!expr).length === 0` pattern, I guess due to Node < 4 support in the past. Since we have `.every(expr)` now, this patch uses that and comes with a slight performance boost due to the short-circuiting nature of `every()` on top of readability.
**Test plan**

Use `.every` instead of `.filter().length === 0` pattern

---

src/cli/commands/check.js

**Summary**
Bug fix. Remove use of `.includes` for node 4 compatibility.
**Test plan**
`yarn check` no longer fails.
Fixes https://github.com/yarnpkg/yarn/issues/3591

Remove .includes for node 4 compatibility

---

__tests__/commands/run.js
src/cli/commands/run.js

**Summary**
Per feature request in https://github.com/yarnpkg/yarn/issues/3566, add a script command that prints env variables. The current implementation can also be extended to other shell commands.
**Test plan**
Added unit tests to `run` file

Add `yarn run env` script

---

__tests__/commands/install/integration.js
__tests__/package-resolver.js

**Summary**
Follow up to 7515772eabc91b741244a4f19aa34dce0a5dc5f4.
After refactoring #3604 I forgot to remove these empty objects
so now I'm doing it with this diff :)
**Test plan**

Chore: Remove unnecessary empty objects from resolver.init calls

---

__tests__/commands/run.js
src/cli/commands/run.js

**Summary**
Fixes #3595.
We were naively adding quotes around arguments that contain spaces but not doing any additional bash/shell escaping. Additionally, we were not compensating for `node` not giving access to raw arguments and were passing parsed arguments to any scripts without reescaping them. This patch tries to fix the madness by replicating `npm`s escaping.
**Test plan**
Existing `run` tests and one additional test.

Fix: Properly escape additional script args

---

src/util/execute-lifecycle-script.js

**Summary**
This patch does two minor optimizations:
1. Do not even have a handler for data updates if we don't have a
spinner. This avoids noop calls to a handler that just returns
if we don't have a spinner.
2. Optimize getting the last available line from the buffer.
Instead of using `.split()` and `.pop()` it uses `.lastIndexOf()`
and `.substr()` to locate and extract the last line.
**Test plan**
Existing tests, behavior should not change.

Enhancement: slightly optimize how we update status from running scripts

---

src/util/git.js

**Summary**
Fixes #764.
Turns out when fetching packages from remote sources via Git,
it may ask for a username or password and get stuck there since
we run it in the background. This patch passes the following env
variables to disable any prompts:
1. `$GIT_ASKPASS=""`
This is the command Git runs to get username and pass. Setting
it to an empty string disables it and git exits with an error.
2. `$GIT_TERMINAL_PROMPT=0`
This is new in Git 2.3 and it prevents git from even trying to
ask for a password. Surpasses `$GIT_ASKPASS` above.
3. `$GIT_SSH_COMMAND="ssh -oBatchMode=yes"`
This is also new in Git 2.3 and it makes git make the call to
ssh via this command. `BatchMode=yes` option tells ssh to not
do anything interactive (because batch/script mode) like
password prompts in case publickey …

Fix: prevent Git from showing a password prompt

---

src/cli/commands/upgrade-interactive.js
src/reporters/lang/en.js

**Summary**
As mentionned in #3454, this PR explains the color legend when using the `upgrade-interactive` command. 
**Test plan**
```
cd-charles@CDCHARLESW764 MINGW64 ~/Documents/workspace/angular2-test (master)
$ yarn upgrade-interactive
yarn upgrade-interactive v0.26.0-0
info Color legend :
"<red>"    : Patch Update Backward-compatible bug fixes
"<yellow>" : Minor Update backward-compatibles features
? Choose which packages to update. (Press <space> to select, <a> to toggle all, <i> to inverse selection)
```

Add legend colors 3454

---

src/resolvers/registries/npm-resolver.js

**Summary**
In the process for figuring out why --prefer-offline is causing a `Couldn't find package "expose-loader" on the "npm" registry.` for us in some cases I noticed a missing await which is probably causing the null check below to be useless.
**Test plan**

Add missing await in npm-resolver.js

---

src/util/execute-lifecycle-script.js

**Summary**
If the global path is present already, prepending it should not be necessary
and might change the order of path entries. This can break
applications that rely on the correct order of path entries, like
rbenv.
fixes #3636
**Test plan**
Should not be needed here, really small code change.

Make `yarn run` only add global path to env if it is not present already

---

src/cli/index.js
src/config.js
src/util/execute-lifecycle-script.js

**Summary**
We package up the `node` interpreter and `yarn` into a distributable application and obscure the fact that we use `node` under the hood.  This leads to problems when trying to build binary packages because `node` is not in the path which causes `node-gyp` to fail.
Previously we were using npm and when we switched from 3 to 4 we had to add `--scripts-prepend-node-path=true` in order to have `node` added to the `PATH` variable.  We could not find a suitable flag for yarn so we hack in `node` into the `PATH` before utilizing `yarn`, but it would be nice if this were available as part of `yarn` itself.
Could you review this PR and let me know what changes are necessary.  One thing I would like feedback on is that the [npm config](https://docs.npmjs.com/misc/config) takes a Type: …

Add scripts-prepend-node-path flag

---

__tests__/util/filter.js
src/cli/commands/pack.js
src/util/filter.js

Here is a solution for #685. I found that the source of the problem is that yarn gives the same priority to `.npmignore` and `.gitignore` while npm does not. According to [npm's developer guide](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package):
> Use a .npmignore file to keep stuff out of your package. If there's no .npmignore file, but there is a .gitignore file, then npm will ignore the stuff matched by the .gitignore file. If you want to include something that is excluded by your .gitignore file, you can create an empty .npmignore file to override it. Like git, npm looks for .npmignore and .gitignore files in all subdirectories of your package, not only the root directory.
In this patch, If `.npmignore` or `.yarnignore` are present in a directory that also …

Give higher priority to .npmignore over .gitignore

---

src/util/execute-lifecycle-script.js

**Summary**
A recent patch introduced `.includes()` which is not supported on Node 4. This patch replaces that with `.indexOf() === -1`
**Test plan**
Make sure TravisCI Node 4 builds pass.

Fix: Fix Node 4 by not using `.includes()`

---

__tests__/commands/install/workspaces-install.js
__tests__/fixtures/install/workspaces-install-names-issue/.yarnrc
__tests__/fixtures/install/workspaces-install-names-issue/package.json
__tests__/fixtures/install/workspaces-install-names-issue/packages/jest-cli/package.json
__tests__/fixtures/install/workspaces-install-names-issue/packages/jest/package.json
src/package-linker.js

**Summary**
Fixes #3598 
Fixed a very naive condition that matched workspaces `jest-cli` as a subpath of workspace `jest`.
**Test plan**
Added test + tested that workspaces install correctly for jest.

Fixes 3598

---

src/package-request.js

**Summary**
This is a fix for https://github.com/yarnpkg/yarn/issues/3506
The root cause of the issue was that after an initial installation method that didn't generate a lockfile, e.g.`--pure-lockfile` or `--no-lockfile`, the second install skipped packages w/pre and post install scripts because [this line](https://github.com/yarnpkg/yarn/blob/master/src/package-install-scripts.js#L137-L139) returned false, even though fresh was being correctly passed [here](https://github.com/yarnpkg/yarn/blob/master/src/package-resolver.js#L455). It turns out `fresh` attribute wasn't being hydrated correctly, so this diff fixes that.
**Test plan**
Existing tests, and tested that the pre and post-install scripts get executed correctly after `yarn --pure-lockfile` command. Not sure how else to test, …

Fix for #3506 - Use setFresh method for determining fresh install 

---

__tests__/fetchers.js
src/cli/commands/install.js
src/cli/commands/pack.js
src/config.js
src/fetchers/git-fetcher.js

Implement a new behaviour in `GitFetcher` to fix #2875 and match the new behaviour of npm 5 regarding git dependencies:
- If the git repository's package.json does not contain a _prepare_ script, no change of behaviour
- If the git repository's package.json contains a _prepare_ script:
- clone the repository in a new temporary folder
- run `install` command in that folder, excluding the _prepublish_ script
- run `pack` command and use the content of the generated tarball as result of GitFetcher
- remove the temporary folder
(@zkat please let me know if you think it differs from npm)
----
At the moment, I open the PR mostly for review and comments. The PR still lacks documentation of the new behaviour.
Some implementation details:
- There is a new boolean `config.gitDependency` to disable …

Run install and pack when fetching git dependencies with a prepare script

---

src/cli/commands/upgrade-interactive.js

**Summary**
Tilde in semver refers to patched version, not minor version. The behavior of command is still correct, this only changes the wording of the help option.
**Test plan**
checked the help menu in CLI with `yarn upgrade-interactive -h`

Rename upgrade-interactive help option

---

src/util/execute-lifecycle-script.js

**Summary** - Bug Fix
This PR fixes #3562 
The code replaces all the invalid characters in the variable names by underscores to match the env variable names introduced by npm. This will eventually allow scripts to be cross-compatible between npm and yarn.
I have tested it using the following:
Node v8.1.2
macOS Sierra 10.12.5

Removes invalid chars in evn var names

---

src/package-request.js
src/package-resolver.js

Should fix #3023 for sure, possibly #3364, #3490, and #3489 as well.
Two notes:
- I thought this would make perfs worse by a large factor, but actually it barely had any impact at all, **even when running without lockfile**. On a project requiring react-native, react, react-dom and webpack, over a hundred tries, it went from Avg:11s to Avg:12s overall.
- I tried to write an integration test, but unfortunately couldn't automatically reproduce from inside the test environment #3023 - for some reason I always ended up getting 2.7.5 instead of the bogus 2.8.0 :( However, I was able to systematically reproduce it manually, so I'm confident that this PR should fix this issue.

Fixes resolution concurrency problem

---

__tests__/package-resolver.js
__tests__/util/guess-name.js
src/resolvers/exotics/git-resolver.js
src/resolvers/exotics/hosted-git-resolver.js
src/resolvers/exotics/tarball-resolver.js
src/util/guess-name.js

This improves over #3624 by:
- Better guessing package names (added a test)
- Adding Support for hosted git, like github or gitlab (including shorthand notation)
- Adding Support for .tar.gz archives (both local and remote)

Improve handling of packages without manifest

---

src/cli/commands/install.js
src/package-linker.js
src/reporters/lang/en.js

**Summary**
Add support for enforcing engine versions (especially yarn) at the project level (as opposed to the [sub]dependencies).
This is especially important on large projects to prevent `yarn.lock` churn.
**Test plan**
`yarn test`. Manual verification by setting various versions in `"engines"`.
**TODO**
Needs language translation, and possibly a better log message.

Include top-level package.json in engines check

---

src/cli/commands/global.js
src/constants.js

When node is installed from Homebrew, node exists at `/usr/local/Cellar/node/7.10.0/bin/node`
So yarn's global bin directory (`yarn global bin`) becomes: `/usr/local/Cellar/node/7.10.0/bin`
```
$ node -e 'console.log(process.execPath)'
/usr/local/Cellar/node/7.10.0/bin/node
$ yarn global bin
/usr/local/Cellar/node/7.10.0/bin
```
This creates two problems:
1. `/usr/local/Cellar/node/(version)/bin` is not present in `PATH` by default. Users have to modify their profile to extend `PATH` with `yarn global bin`.
2. When node is upgraded, all linked global binaries become inaccessible since `yarn global bin` automatically gets changed to `/usr/local/Cellar/node/(latest-version)` from `/usr/local/Cellar/node/(old-version)`. The global bin directory should remain constant on upgrades.
The fix is …

Change global prefix directory to `/usr/local` on OS X

---

yarn.lock

just updated lockfile that selfupdates after install

lockfile optimized

---

src/util/fs.js

**Summary**
If the same file is copied twice during a bulk copy then we have a problem in out recursive logic.
Added an invariant to make sure we don't make extra IO operation.
**Test plan**
all tests pass

add a check that same file is not copied twice

---

src/util/git.js

**Summary**
Fixes #3742.
With #3633 we started overriding the default `env` map that was passed
to `git` calls. It defaulted to `process.env` and since the option is
a whitelist, now it is only the ones we wanted to add, instead of
`process.env` + the additions. This patch fixes the problem by spreading
`process.env` before the new values.
Relevant part from Node docs:
https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options
>Use env to specify environment variables that will be visible to the new process, the default is process.env.
**Test plan**
Manual verification for t19705486. We should have automated tests for this
so I'll start working on them. Just want the fix our first.

Fix: inherit env variables from process when calling Git

---

__tests__/resolvers/index.js
src/cli/commands/add.js
src/cli/commands/import.js
src/cli/commands/install.js
src/cli/commands/upgrade.js
src/package-request.js
src/package-resolver.js
src/resolvers/base-resolver.js
src/resolvers/exotics/git-resolver.js
src/resolvers/index.js

**Summary**
Fixing #3677
> `yarn add git+file:///path/to/git/repo#branch` is not supported, it'll try to find the package in npm registry.
> It does work in NPM (5.0.3).
>
> Expected behavior: file:///path/to/git/repo#branch should be treated as a git remote repository, the same way as if it was accessed by SSH or HTTPS.
**Test plan**
Adding some tests on `getExoticResolver` to ensure the Git resolver is used for `git+file:///` dependencies.
**Implementation notes**
I moved `getExoticResolver` to `src/resolvers/index.js`, I think it's more suitable than `src/package-request.js`, and more convenient to write the tests. I also refactored at little to make the returned type more specific.
I made the Git resolver handle any protocol prefixed with `git+`, not only `git+file`. That way, yarn …

Allow `git+***://` dependencies

---

__tests__/fetchers.js
src/fetchers/git-fetcher.js

**Summary**
Fix installation issue reported by @sammarks in yarnpkg/yarn#3553
> - I have `package-a` that depends on `package-b` (through a git URL as package-b is not published to a registry).
> - `package-a` and `package-b` both use Babel (listed in devDependencies in both).
> - `package-b`'s prepare script is: `babel --optional runtime src -d dist`
> 
> When installing the dependencies of package-a, I get an error message: `babel: command not found`
**Test plan**
Improved test in `__test__/fetchers.js` (Updated test dependency Volune/test-js-git-repo@1958040dbfb461f32f43ac5a6f319880b9c448ea and Volune/test-js-git-repo@c455e0cb000917f4362ee4c792e8a4636a291f89)

Fix ".bin" not linked when preparing a git dependency

---

.travis.yml
__tests__/commands/_helpers.js
__tests__/commands/unlink.js
__tests__/reporters/console-reporter.js
__tests__/util/blocking-queue.js
__tests__/util/promise.js
__tests__/util/request-manager.js
appveyor.yml
package.json

**Summary**
macOS tests on Travis CI keep timing out and they run very slowly. This patch attempts to solve this by doing the following:
- Use ramfs for `__tests__` folder and for `$TMPDIR` for faster file system
- Remove unnecessary `brew update` and `brew install yarn` commands
- Remove unnecessary `--max-workers` argument since all CI VMs have only 2 cores
- Clean up tmp folders per test after they are done
- Fix `link/unlink` test's race condition and previous test case reliance
- Fix `request-manager` timeout tests to be more reliable and finish in under our normal timeout
- Use real timers by default and add necessary `useFakeTimers` calls
- Increase heap size for Linux and OS X to 4 GB since OS X builds were crashing due to limited heap space
- Removes retries from Travis CI
**Test …

Update: Make tests great again on Travis CI macOS

---

__tests__/commands/add.js
__tests__/fixtures/install/simple-worktree/non-package/package-c/README.md
__tests__/fixtures/install/simple-worktree/non-package/package-c/package.json
src/config.js

This fixes an issue that if you run a Yarn command from any folder that is a subfolder of a workspace it will automatically change CWD to the root.
Before changing CWD the code now checks that workspaces glob matches the original CWD.
**Test plan**
Added test

Yarn workspaces: running commands from subfolders that don't match glob

---

__tests__/util/git.js
src/util/__mocks__/child.js

**Summary**
Regression tests for #3742 and follow up to #3743.
**Test plan**
Tests shall pass.

Update: add regression tests for Git.spawn env issues

---

__tests__/registries/npm-registry.js
__tests__/util/path.js
src/registries/npm-registry.js
src/util/path.js

**Summary**
This fixes the handling of path that are present in npm configuration (#2930). What's now handled :
* Paths starting with `~/` (Also `~\` on windows) get expanded
* Path that aren't rooted are considered relative to the current directory
* All path are fully resolved
All of this is from npm ( https://github.com/npm/npm/blob/latest/lib/config/core.js#L394 ).
I'm not sure that I like the fact that relative paths are relative to cwd instead of the configuration file where they are found but it's what's npm is doing 😉 
**Motivation**
My original motivation was to stop having errors when i'm installing `node-sass` on node 8. As versions of `node-sass` that aren't the latest don't include pre-built binaries for node 8 the installer try to use `node-gyp` to build a fresh copy.
This …

Support for ~ (home dir) in path configurations

---

src/cli/index.js

**Summary**
Fixes #3764. Follow up to #3126. Adds the missing `[bool]` type
descriptor to `commander` definitions.
**Test plan**
Run `yarn` on macOS and enjoy your emojis responsibly.

Fix: emoji should default to true on darwin platforms

---

__tests__/util/git.js
src/util/__mocks__/child.js

Reverts yarnpkg/yarn#3759, see comments for reasons
- mock leaks into source code when built
- jest complains about seeing the mock twice

Revert "Update: add regression tests for Git.spawn env issues"

---

__tests__/commands/unlink.js

**Summary**
Follow up to #3667. Uses `async`/`await` instead of `.then()` in
`unlink` tests.
**Test plan**
Tests should pass as usual.

Chore: prefer async/await to `then`

---

__tests__/commands/add.js
__tests__/commands/install/workspaces-install.js
__tests__/commands/upgrade.js
package.json
src/cli/commands/check.js
src/package-request.js
src/util/filter.js
yarn.lock

**Summary**
Fixes #3757. Jest 20 is the latest version with many improvements,
most importantly for us, not automatically polyfilling `Array.includes`.
**Test plan**
CI should pass without issues.

Update: Upgrade Jest to version 20

---

__tests__/index.js
__tests__/lifecycle-scripts.js

**Summary**
Fixes #3536. Explicitly and programmatically passes `YARN_SILENT=0`
to test runs that checks yarn's output.
**Test plan**
All CI tests and local test runs with yarn 0.27.3 should pass.

Fix: fix e2e yarn output tests after #3536

---

src/cli/commands/help.js

**Summary** - Bug Fix
This PR fixes #3559 
The code removes unsupported aliases from the output list of help command and also prints out the supported alias (if there is any) for the command in the same row. For clarification, please have a look at the command `generate-lock-entry` and `upgrade-interactive` in the output below, you should be able to see the alias of the commands in the same line.
**Output with this fix**
```
Usage: yarn [command] [flags]
Options:
-h, --help                          output usage information
-V, --version                       output the version number
--verbose                           output verbose messages on internal operations
--offline                           trigger an error if any required dependencies are not available in local cache …
```

Bugfix help command

---

__tests__/commands/install/lockfiles.js
__tests__/index.js
src/cli/commands/install.js
src/cli/index.js
src/reporters/lang/en.js

**Summary**
Before, we run `yarn -V` or `yarn --version` to display version number of Yarn. But we are used to using `-v` to display it, like running `node -v` and `npm -v`.
Maybe caused by [commander.js](https://github.com/tj/commander.js), flags of command for displaying version number cannot be `'-v, -V, --version'`. In other word, we cannot run `yarn -V` to display version number any more.
**Test plan**
Just run `yarn -v`. Note that do **NOT** use `yarn -V` any more.
```
$ yarn -v
0.25.0-0
$ yarn --version
0.25.0-0
```

Use "-v" to display version number instead of "-V"

---

.travis.yml

**Summary**
Refs #3769. Simplifies the Travis builds by removing a few workarounds for old issues, adds yarn caching and uses the checkout yarn to kick off the tests scripts (yarnception).
**Test plan**
Travis CI builds should pass.

Chore: simpler Travis CI builds with yarnception

---

__tests__/util/child.js
__tests__/util/signal-handler.js
src/cli/index.js
src/util/child.js
src/util/signal-handler.js

**Summary**
If yarn receives a SIGTERM signal, it forwards it to all the child processes that it has spawned. This fixes #3424.
module `src/util/child.js` now keeps a reference to every spawned child process until the child exits. it also exports a new function `forwardSignalToSpawnedProcesses()` which sends a signal to all currently held child processes.
new module `src/util/signal-handler.js` exports a single function `handleSignals()` which attaches a SIGTERM listener to the global `process` object that calls `forwardSignalToSpawnedProcesses()`
Currently the `handleSignals()` function is called in `src/cli/index.js`, please let me know if there is a better place for this.
**Test Plan**
Write a script with a long running operation and a SIGTERM handler:
```javascript
//longOperation.js …
```

forward SIGTERM to spawned child processes

---

__tests__/commands/install/integration.js
__tests__/fixtures/install/install-conflicts/b/package.json
__tests__/fixtures/install/install-conflicts/package.json

**Summary**
This is a failing test to highlight the issue the issue here https://github.com/yarnpkg/yarn/issues/3780 https://github.com/mxmul/yarn_flat_regression
tl;dr:
```
a => b => left-pad@>=0.0.1
a => left-pad@1.0.0
```
yarn fails when doing `--flat` with the following:
```
info Unable to find a suitable version for "left-pad", please choose one by typing one of the numbers below:
1) "left-pad@>=0.0.1" which resolved to "1.1.3"
2) "left-pad@1.0.0" which resolved to "1.0.0"
```
(yarn version: 0.27.1)
(this seems to be a regression introduced in 0.27.0, this worked in 0.26.1)
**Test plan**
This is a test only change.
---
This test is currently failing because it's prompting for a resolution, with the following stacktrace
```
(node:23637) PromiseRejectionHandledWarning: Promise …
```

Add a failing test for version conflicts

---

src/util/fs.js

Turns out https://github.com/yarnpkg/yarn/issues/3751 revealed a bug in fs.copy.
Instead of breaking install it now displays a warning.
The underlying issue needs to be fixed anyway though

tone down error for double copies #3751

---

src/cli/commands/add.js

**Summary**
Fixes #3817. Fixes how the version to be saved being determined
when adding packages with different patterns.
**Test plan**

Fix: honor selected version when saving deps

---

src/registries/npm-registry.js

This commit should fix #3765. I'm not completely satisfied with hardcoding our registry, maybe that could extended at a later point with an option to "inherit" the auth token from npm. Not sure it would be useful, tho.

Fixes npm auth

---

__tests__/commands/_helpers.js
__tests__/commands/add.js
__tests__/commands/install/integration.js
__tests__/lockfile.js
src/lockfile/parse.js
src/lockfile/wrapper.js
src/rc.js
src/registries/npm-registry.js
src/registries/yarn-registry.js
src/reporters/lang/en.js

**Summary**
Git merge conflicts are common with `yarn.lock`. This PR allows you to run `yarn` to automatically merge the two versions of `yarn.lock` which will run Yarn and regenerate a new lockfile.
**Test plan**
Added tests.

Auto detect and merge lockfile conflicts

---

src/errors.js
src/fetchers/tarball-fetcher.js
src/reporters/lang/en.js
src/util/misc.js

This is not a very elegant solution but it will do the job for now.
During fetching tarball for any **5xx** errors, it will show `warning There appears to be trouble with our server. Retrying...` and try again after `3000ms`. If it fails again then it will show the error like before.
**Future Work**
Refactor `RequestManager` to add support for retry.
I spent some time trying to refactor `RequestManager`, but it will take some time and effort to finish it.  And, since `RequestManager` is a very important part of **Yarn**. So, it is important that it doesn't degrade the speed after refactor.

Add retry on 5xx errors. Fixes #2849
